### ISSUE TITLE
TextFields do not scale on HTML5 target

### ISSUE THREAD

**Issue by sruloart** [HaxeFlixel/flixel#1024]
#729 Let's readdress this issue with Bitfive. It looks like scaling is again the main problem. here in the next example, when we add a simple text to a playstate, there's a textfield, 80px/~10px in size (rough estimate), and the text is being scaled inside of it while the textfield does not scale at all. That's pretty much the issue with regular text on HTML5. What would cause this quite specific behavior? Also, the fonts are different, but I guess this is not really a bug...

```hxe
I'm using this line just to demostrate what happens when you add text on HTML5 (the text is being scaled from the same point in the upper left corner, game size is 640/480):
1. var text = new FlxText(200, 200, 0, "1234567890", 10); = All numbers are showing correctly. 
2. var text = new FlxText(200, 200, 0, "1234567890", 15); = All numbers are showing correctly.
3. var text = new FlxText(200, 200, 0, "1234567890", 16); = All numbers are showing correctly.
4. var text = new FlxText(200, 200, 0, "1234567890", 17); = We've lost most of "0".
5. var text = new FlxText(200, 200, 0, "1234567890", 18); = We've lost "0" and now beginning to lose lower vertical ends of all numbers.
6. var text = new FlxText(200, 200, 0, "1234567890", 19); = We've lost "0" and half on 9, and continue to lose lower vertical ends of all numbers.
7. Trend continues.
```

**Comment by Gama11** [comment]
Texts are working pretty well with the openfl backend (which is the default now).
