### ISSUE TITLE
FlxCamera offset is weird. No way to offset target.

### ISSUE THREAD

**Issue by JoeCreates** [HaxeFlixel/flixel#1056]
The offset point you can provide in FlxCamera seems rather weird. I can't at all think why it exists, as it seems only to affect the size of the deadzone.

In my ludum dare game, I needed to be able to offset the actual target position of a sprite, so for example, the target position would be somewhere above the target sprite. I couldn't find any way of doing this, so I added a targetOffset point to the class which is added to the target x and y when updating the following.

I would make this change a PR, however I wanted to check what the existing purpose of the offset point is. Is this a badly implemented attempt at offsetting the target, or does it have a legitimate purpose?

**Comment by Gama11** [comment]
I'm fine with removing the parameter now that we have `targetOffset`.
