### ISSUE TITLE
Expanding FlxRandom

### ISSUE THREAD

**Issue by steverichey** [HaxeFlixel/flixel#1094]
I've had a few ideas for more `FlxRandom` functions, particularly ones that I've wanted to have a few times already. I'd like to add:
- Perlin noise generation
- Generating an array of highly differentiated colors; similar to the "harmony" functions of `FlxColorUtil`, would return an array of any length from 1 to 360 with colors spaced evenly around the color wheel, so you could use random colors in your game without worrying about two colors being nearly identical

If these are beyond the scope, or you have any other ideas, let me know. Thanks!
##

**Comment by MSGhero** [comment]
I have perlin/simplex noise written already, although the parameters are slightly different than `BitmapData`'s. `FlxRandom` or `addons`?

I really don't want to do this work

**Comment by nightblade9** [comment]
Was this ever resolved? #1146 and #1148 don't seem to introduce any new methods related to generating perlin noise. Or, if a new method is not needed, how can I generate perlin noise?

**Comment by 01010111** [comment]
@nightblade9 You could always try this library https://github.com/whuop/hxNoise

I've used noisehx in the past as well with a haxeflixel project

**Comment by MSGhero** [comment]
I have a simplex noise PR in addons, but I’m not sure I want to merge it. It seems way too specific

**Comment by nightblade9** [comment]
@01010111 thanks, that looks promising. I'll check it out. It looks a bit abandoned though (I opened a PR for a README change and it's still not merged after a couple of days).

@MSGhero perlin/simplex noise is used quite a lot in procedural generation. If you can merge it (even if it becomes a flixel addon), I think that would be really useful to a lot of people (like myself).
