### ISSUE TITLE
FlxTilemap.ray() causes a crash on Windows target

### ISSUE THREAD

**Issue by Ohmnivore** [HaxeFlixel/flixel#1098]
I'm trying to use the following code on a loaded tilemap.
Reg.state.collidemap.ray(new FlxPoint(0, 0), new FlxPoint(50, 50));

The version I have of FlxTilemap is https://github.com/HaxeFlixel/flixel/blob/0f20b3913f3336df548c0fe90487d8b11b6ed732/flixel/tile/FlxTilemap.hx

Unfortunately it just crashes.

**Comment by tanis2000** [comment]
It looks like this is still happening in 3.3.6 even though I do not have any negative number in my tilemap
