### ISSUE TITLE
Console is messing up key input after it's called

### ISSUE THREAD

**Issue by Ohmnivore** [HaxeFlixel/flixel#1112]
It happens on Windows target. When I open the debugger and type something in the console, then hit enter, all keyboard input stops being registered, I can only type in the console. The mouse still works though, and the debugger buttons still bring up the debugger.

**Comment by Mixerman123** [comment]
Any news with this? It seems to still happen, and is a pretty big issue. I mean, generally you use the console to edit the gamestate, and then go back to the game to see results. Having no keyboard input when you resume is a pretty big issue, at least in my opinion. If it is out of Haxeflixel's hands, then that is a shame.

**Comment by Beeblerox** [comment]
Wow! This issue is over 1 year old!
Hope my dirty hack fixed it

**Comment by ml497** [comment]
Had this problem with html5 target.  The issue resolved itself after removing the -debug flag on build.
