### ISSUE TITLE
FlxGamepad controller IDs not reliable

### ISSUE THREAD

**Issue by MintPaw** [HaxeFlixel/flixel#1128]
When unplugging and plugging back in a controller it is assigned a new ID, the old ID is not removed, and no sign of the controller is removed. This is tested in cpp and Neko targets.

Expected:
1. A controller is plugged in.
2. Using FlxG.gamepads.getByID(0) you get the first gamepad.
3. The controller unplugged and no input is received. (Hopefully some "controller unplugged" flag is set also)
4. The controller is plugged back in.
5. Using the above method you get controller 0 and play resumes. (Use getByID every frame or if there is a "controller unplugged" flag, check every frame while the flag is set)

Actual:
1. A controller is plugged in.
2. Using FlxG.gamepads.getByID(0) you get the first gamepad.
3. The controller unplugged and no input is received. No flag is set.
4. The controller is plugged back in.
5. The controller is no longer in ID 0, it is now in ID 1.
6. If only one controller is meant to be used then use lastActive to find it.
7. If the game is to support multiple controllers then you're out of luck, you must have the player go to some menu using the keyboard and have each player confirm their controller.

How to fix it:
JoystickEvent.DEVICE_ADDED and JoystickEvent.DEVICE_REMOVED
These events do work in cpp and Neko. They should be used to make an array of plugged in controller IDs.

Edit: Spelling and grammar

**Comment by Waynetron** [comment]
I'm still seeing this issue on Mac. Tested with Neko, C++ and Flash targets.
Works fine in Windows on the same machine through Parallels.

**Comment by Gama11** [comment]
@Waynetron what flixel version?

**Comment by Waynetron** [comment]
I'm on the dev branch.

**Comment by Waynetron** [comment]
Should I open an issue for this?

**Comment by larsiusprime** [comment]
It's probably a result of us not having the correct IDs for Mac, I've mostly just tested the ID's on windows.

**Comment by Waynetron** [comment]
I'm not sure what you mean by not having the correct IDs. If you explain, I can look into it on my Mac and get the numbers for you. 
If I plug in 4 controllers they will be listed as 0,1,2 and 3. It's just removing one controller (say ID 0) and plugging it back in will leave ID 0 as null and then add another to the stack with ID 4, rather than taking up ID 0 again (as it does in Windows).

**Comment by larsiusprime** [comment]
Sure, what I mean is that there is a numerical value associated with each button press and this is often different on each controller model, and different even on the same controller if the OS is different. This number is associated with the lime and/or openfl gamepad events for controller button presses and axis movements.

This is different than the id of the controllers themselves. 

So in many cases I've set up the controllers to work on windows and then having no further information, copy & pasting those same button ID's over for mac and linux, etc. Obviously this does not work in all cases, so if you can provide corrections for what button id's we should be looking for, I can make the change.

**Comment by Waynetron** [comment]
Ok I understand. In that case the button IDs for the Xbox 360 controllers I'm using seem to be correct. So that's not the problem I'm having here.

If you like though, I could modify the existing controller demo to display button ID information. And perhaps have it work with / display multiple controllers. And I've got some 3rd party controllers I can check out on Mac / Windows.

**Comment by larsiusprime** [comment]
That would be swell!

On Mon, Oct 5, 2015 at 6:24 PM, Waynetron <notifications@github.com> wrote:

> Ok I understand. In that case the button IDs for the Xbox 360 controllers
> I'm using seem to be correct. So that's not the problem I'm having here.
>
> If you like though, I could modify the existing controller demo to display
> button ID information. And perhaps have it work with / display multiple
> controllers. And I've got some 3rd party controllers I can check out on Mac
> / Windows.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HaxeFlixel/flixel/issues/1128#issuecomment-145696911>.
>



-- 
www.fortressofdoors.com -- Games, Art, Design
