### ISSUE TITLE
FlxGradient chunkSize incorrect on cpp

### ISSUE THREAD

**Issue by JoeCreates** [HaxeFlixel/flixel#1214]
FlxGradients are not  correctly drawn on cpp targets. In the following example the top and bottom chunks should both be of height 4, but on cpp the top is clearly much bigger.

`FlxGradient.createGradientFlxSprite(100, 8, [0xffaa4444, 0xffff7777], 4);`
##

**Comment by Gama11** [comment]
I thought OpenFL 8 might fix this, but I can't even reproduce the issue with OpenFL 3.6.1 anymore:

![](https://i.imgur.com/tJM6ijk.png)
