### ISSUE TITLE
AssetPaths chokes on hidden .DS_Store files

### ISSUE THREAD

**Issue by ivodopiviz** [HaxeFlixel/flixel#1280]
OSX has a terrible tendency to clutter its own directories with hidden files that try to solve the obvious shortcomings of its obsolete file system. One such type of files are called .DS_Store and AssetPaths.hx seems to have problems with them, raising the following compilation error:

"source/AssetPaths.hx:3: characters 2-7 : Duplicate class field declaration : __DS_Store"

It'd make sense to simply avoid adding hidden files. In most Unixes like OSX filenames starting with a "." are automatically hidden from user view.

**Comment by games** [comment]
is it fixed ?

I still got this error :

```
source/AssetPaths.hx:3: characters 2-7 : Duplicate class field declaration : __DS_Store
source/AssetPaths.hx:4: characters 0-19 : Defined in this class
```

my version list as below:
> haxelib list
actuate: [1.8.6]
box2d: [1.2.3]
flixel-addons: [1.1.0]
flixel-demos: [1.1.2]
flixel-templates: [1.0.2]
flixel-tools: [1.1.0]
flixel-ui: [1.0.2]
flixel: [3.3.10]
hxcpp: [3.2.102]
layout: [1.2.0]
lime-samples: [2.3.0]
lime: [2.4.5] 2.4.7
openfl-samples: [2.2.2]
openfl: [3.1.1]
swf: [1.8.9]

**Comment by sruloart** [comment]
It is fixed, but only on the dev branch (for quite a long time now). If you know your way around git you can merge the FlxAssets part or just copy&paste the fix https://github.com/HaxeFlixel/flixel/blob/dev/flixel/system/FlxAssets.hx#L85.

**Comment by Gama11** [comment]
Actually, the fix was supposed to be in 3.3.9, but I messed something up with the cherry picking there that undid the change again. Might do a 3.3.11 release...

**Comment by sruloart** [comment]
@Gama11, 4.0.0 release is anytime soon?

**Comment by Gama11** [comment]
@games 3.3.11 is now on haxelib and should fix this.

@sruloart Maybe, maybe not? ;)
