### ISSUE TITLE
Don't default scrollFactor to 0 on UI elements

### ISSUE THREAD

**Issue by JoeCreates** [HaxeFlixel/flixel#1315]
Defaulting the scroll factor of UI elements such as buttons and sliders seems a bit presumptuous and inconsistent.

Using individual `scrollFactor`s is a fairly inflexible way of positioning UI, with more flexible approaches including using a separate camera (thus allowing for zooming and such), or placing UI elements in a `FlxSpriteGroup` (or equivalent) with the desired scrollFactor. Furthermore, using >0 `scrollFactor` on UI elements allows for things like scrolling transitions, and UI attached to world entities.

The inconsistency comes in when you are constructing a HUD containing buttons/sliders/etc, which default to 0 `scrollFactor`, and regular `FlxSprite`s. If you wish to use the individual `scrollFactor.set(0, 0)` method to position your UI, you have to do this on each `FlxSprite` anyway, so there really isn't anything saved by making buttons/sliders default to 0. Much easier to stick it in a `FlxSpriteGroup`

Conversely, if you wish to have a `scrollFactor` of 1 on your UI, you must single out the buttons/sliders to set their `scrollFactor`s to 1.

Perhaps it would be best to consistently default `scrollFactor` to 1, even on UI components?

**Comment by JoeCreates** [comment]
@Gama11 Has this been ignored? It still seems to me there isn't a good argument to keep two different defaults. The current method panders to an inferior and inflexible way of implementing UI, and honestly can be confusing if you're trying to implement a more professional-looking and interesting UI.

If you're aware of the issue, it boils down to remembering "oh yeah, my game is broken because of this inconsistency in flixel. I need to account for this special case". For someone who isn't aware, it can cost the time of actually investigating. Sure, for beginners doing very simple games, this might save them a line or two. However, this general approach of making special cases for simpler games usually ends up reducing the flexibility, causing more work for the less simple cases, and making the code less intuitive. Consistency itself means there is less to learn and remember.

Adding features to cater to simpler games is fine provided it doesn't encroach  on the development of less simple games. This issue does, and it feels like messy design.

**Comment by Gama11** [comment]
I'm not totally convinced that this change is worth it - it's the sort of thing that, unlike breaking API changes, can break things in subtle ways without throwing a compiler error.

I'd be happy to consider it if there's enough support for it, but so far there hasn't been much input from anyone else on this topic.

**Comment by JoeCreates** [comment]
@Gama11 Could we possibly leave it open so that it doesn't get forgotten? Perhaps eventually it could be bundled with bigger structural fixes?

**Comment by Gama11** [comment]
As mentioned before, I don't think there's a way of making this change without introducing a lot of subtle issues, and I'm not convinced it's a good idea in the first place. From the activity on this issue, nobody else seems to have strong feelings about it either.
