### ISSUE TITLE
Grouping of tweens

### ISSUE THREAD

**Issue by goshki** [HaxeFlixel/flixel#1321]
I remember a conversation about defficiencies of the tweening system, expecially in regard of inability to control when a given tween is updated. Maybe a solution to this problem would be to add the ability of tween grouping. What I mean by that is that tweens would be created withing an indicated group, i.e.: global tweens, state tweens, substate tweens, group tweens and sprite tweens. They could be created in such manner:

* FlxTween.globalTween()
* FlxTween.stateTween()
* etc.

Moreover, state/substate and group tweens would pracitcally be reduced to a group tween that would update when its parent group updates (and the above methods would be strictly convenience methods). Similarly, sprite tweens would be updated when their parent sprite updates. Of course it would require the developer to always call super.update() or to call some kind of a updateTweens() function manually.

Quite possibly, the TweenManager class would become obsolete because tween parents would be responsible for updating their tweens. On the other hand such change would definitely cause some inconsistencies in existing code (tween updates would be launched at different moments).

Other thing to keep in mind is that such solution add extra responsibilities to HaxeFlixel classes such as FlxGroup and FlxSprite (FlxObject?).

**Comment by Gama11** [comment]
Closing this, since it's in principle the same issue as #1087.

I do like Joe's suggestion though.
