### ISSUE TITLE
Frustratingly complicated bug

### ISSUE THREAD

**Issue by JoeCreates** [HaxeFlixel/flixel#1328]
I've already spent nearing 8 hours trying to solve this, most of that was simply trying to create a simple test case, but it proved exceedingly difficult to reproduce. Please, please help!

The bug occurs when you have one camera on top of another. When you move the back camera, where its borders are, a thin line of transparency appears on the _front_ cameras outer 1px, exposing the camera behind where it shouldn't be. I first noticed this on a HUD camera when the world camera behind it was shaking.

Here is a test case: http://pastebin.com/U8g1wCHd

Note that in the test case, there is no issue present until the state switches to itself. **This bug only occurs after a state switch**. Keep your eye on the left of the sprite after the state switch, and you will see white flickering from the camera behind.

Also, this bug does not occur as long as there is something visible on the front camera when the state is loaded (hence in the test case, the sprite is tweened on from off screen). Tweening itself does not cause the issue. The sprite simply needs to be off camera to begin with, then moved on camera.

Oh, and it's also specific to the flash target.

Summary of how to reproduce:
- Have one camera on top of another, and move the background camera a very small amount.
- Only occurs after a state switch.
- Nothing must be visible on the front camera when the state is first drawn. If there is any sprite visible anywhere on the first frame, the bug will not occur.
- Make window resolution larger than game resolution with RatioScaleMode.
- Flash target

Note that the bug does not seem to have anything to do with screen shake or tweening, and can be reproduced in other ways without them.

Your help is much appreciated!
##

**Comment by Gama11** [comment]
If I remember correctly, I think the latest conclusion on this from @Beeblerox was that this is a Flash Player bug. Considering the Flash target is no longer as relevant as most major browsers are blocking it by default, and HTML5 support is quite decent now with OpenFL 8, I think this can be closed / is not worth investing more time into.
