### ISSUE TITLE
Assets handling system...

### ISSUE THREAD

**Issue by sruloart** [HaxeFlixel/flixel#1344]
I think it would be quite helpful to have a built-in system for assets handling, probably with an assets frontend that will allow you to load / remove assets nodes (asset node = an array of assets paths) asynchronously, whe/n/r/ever you choose.

```haxe
FlxG.assets.createNode(a node's name, a list of assets paths); 

//Place this somewhere in your code. A default Flx loading bar will appear on screen while it loads.
FlxG.assets.loadNode(the node's name);
```

It can be optimized to fit specific limitations, e.g. you would be able to set an "allowedMemory" (so you won't load an asset before there's enough room for it for example); or auto-create a FlxAtlas / several atlases if one isn't enough (mobile limits). Sounds could be loaded / removed together... stuff like that...

**Comment by Gama11** [comment]
This might be nice to have, but I don't see myself implementing this any time soon. Doesn't look like others are too interested in this etiher judging from this discussion.

It might be a case of trying to do too much. Things like a default loading bar - I feel like most people will want to customize that.
