### ISSUE TITLE
Offsettable Clippable Tiled Images

### ISSUE THREAD

**Issue by JoeCreates** [HaxeFlixel/flixel#1354]
I'd like to suggest the inclusion of an offsettable clippable tiled graphic, something like TiledImage in HaxePunk, that can have the graphic offset and scrolled, and also clipped.

**Comment by Beeblerox** [comment]
Done here: https://github.com/HaxeFlixel/flixel-addons/commit/12a47f94fb2ba4789c375a167c7e9c1b2883ac10
