### ISSUE TITLE
setColorTransform not working on native (dev branch)

### ISSUE THREAD

**Issue by sruloart** [HaxeFlixel/flixel#1383]
As described here (and tested by me, bender): http://haxeflixel.com/forum/?place=msg%2Fhaxeflixel%2FD-KAaS1lYj4%2FI1KF5iAU1FsJ
 
It doesn't look like an OpenFL issue (as someone would have complained already :), is there anything that might cause this over HaxeFlixel's side?

**Comment by Gama11** [comment]
Let's just document it accordingly.
