### ISSUE TITLE
drawDebugOnCamera does not work in FlxSpine class.

### ISSUE THREAD

**Issue by Partysun** [HaxeFlixel/flixel#1384]
https://github.com/Partysun/flixel-addons/commit/1a2012d80fef644c42cbbafab534748d667243ac

I can launch drawDebugOnCamera, only if I write it in draw method. 

... draw {

drawDebugOnCamera(FlxG.camera);
}

I use debug mode. I see bounding box of sprites, but method couldn't override.

**Comment by Gama11** [comment]
Yeah, looks like the method became obsolete in the latest refactor and can be removed safely - the `wrapper.draw()` calls take care of the bounding boxes.

This issue belongs to flixel-addons btw.
