### ISSUE TITLE
FlxBitmapText border inconsistency between flash and native

### ISSUE THREAD

**Issue by JoeCreates** [HaxeFlixel/flixel#1387]
Example: https://github.com/HaxeFlixel/flixel/issues/1386

Note the difference between the borders on flash and native. On flash there is no extra padding by default, thus the border is chopped off.
##

**Comment by Gama11** [comment]
There's a very good chance this is no longer an issue with OpenFL 8, at least I can't spot any issues in the FlxBitmapText demo. Can't check against your original code snippet from #1386 since the hastebin link is dead.
