### ISSUE TITLE
FlxTilemap#computePathDistance() works in neko and flash targets, but not in html5 target

### ISSUE THREAD

**Issue by bguiz** [HaxeFlixel/flixel#1390]
The class `flixel.tile.FlxTilemap` has a method `computePathDistance`. When compiled with the neko or flash targets, this compiles and runs without issue. When compiled using openfl-bitfive with the html5 target, however, this compiles, but **does not run**.

The relevant parts of the transpiled Javascript code:

    flixel.tile.FlxTilemap.prototype = $extend(flixel.FlxObject.prototype,{
    ...
    ,computePathDistance: function(StartIndex,EndIndex,WideDiagonal,StopOnEnd) {
        ...
        while(i < mapSize) {
            if(this._tileObjects[this._data[i]].allowCollisions != 0) distances[i] = -2; else distances[i] = -1;
            i++;
        }

An error occurs on the line before the `i++`, because `this._tileObjects[this._data[i]]` is *sometimes* `undefined`:

     Uncaught TypeError: Cannot read property 'allowCollisions' of undefined

@YellowAfterlife the maintainer of openfl-bitfive thinks that this issue has to do with haxeflixel, not openfl-bitfive: https://github.com/YellowAfterlife/openfl-bitfive/issues/31#issuecomment-64843735

After comparing the original Haxe source and the transpiled Javascript output, it does look as if the error surfaces here, but most likely occurs earlier on, elsewhere. The likely culprits are when `_tileObjects` (`Array<FlxTile>`) or `_data` (`Array<Int>`) are populated. However, that is about as deep as I know how to dig.

Can someone smarter than I please take a look and see if there is something going amiss here?

**Comment by Gama11** [comment]
Can't reproduce this issue in the Pathfinding demo anymore on latest dev. There've been fixes here and there, so I assume this is not an issue anymore.
