### ISSUE TITLE
Use trello service for tracking work/progress

### ISSUE THREAD

**Issue by Beeblerox** [HaxeFlixel/flixel#1394]
Here is an example of spine-runtime tracking: https://trello.com/b/frGlgsF7/spine-editor
Thanks to @Partysun for the idea

**Comment by Tembac** [comment]
Any update with this? I would like to know how the HaxeFlixel development is progressing. Is there a new release soon?

**Comment by Gama11** [comment]
I think GitHub milestones are sufficient - we've tried waffle.io for flixel but nobody was using it.

I just created a 4.0.0 milestone. https://github.com/HaxeFlixel/flixel/issues?q=is%3Aopen+is%3Aissue+milestone%3A4.0.0
