### ISSUE TITLE
Support for full dce

### ISSUE THREAD

**Issue by RafaelOliveira** [HaxeFlixel/flixel#1397]
I'm making a html5 mobile game, and in this target it's important that the game has a small size to be loaded on 3G. It would be good if games in haxeflixel can be compiled with dce full.

**Comment by Gama11** [comment]
This should mostly be working now (ran into [what appears to be a Haxe bug](https://github.com/HaxeFoundation/haxe/issues/3749) along the way), though I'm sure there are still issues.

The Haxe manual [claims that `-dce full` is the default for js](http://haxe.org/manual/cr-dce.html), I guess OpenFL must change that...

**Comment by sruloart** [comment]
A great addition! :+1:

**Comment by RafaelOliveira** [comment]
Just to show the numbers, with a project of mine, in html5:
default dce: 1,85mb
dce full: 845kb
dce full with -minify: 558kb

thanks, this is really good!

**Comment by Gama11** [comment]
Wow, nice.

Have you tried [HaxMin](https://github.com/YellowAfterlife/HaxMin)?

**Comment by RafaelOliveira** [comment]
506kb with HaxMin, but the game is not loading. In another time I will look this.
