### ISSUE TITLE
Animation Callback triggering every frame when animation is set in update

### ISSUE THREAD

**Issue by 01010111** [HaxeFlixel/flixel#1405]
The animations are still working fine, but the animation callback is being called every frame the animation is played regardless if the frame has changed or not.

See: http://haxeflixel.com/forum/?place=topic%2Fhaxeflixel%2F6iYW77y5OuY%2Fdiscussion

**Comment by MSGhero** [comment]
It should be noted that you have to set `force` to true in `animation.play()` or else issues come up. I just updated, and the current animation would have to update through a full loop before it would stop showing the old animation. Like, animation walk_up would be playing for a second even though `animation.name == "walk_down"`.

I think the condition needs to be fixed.

**Comment by Beeblerox** [comment]
@MSGhero i don't quite understand your problem, can you explain it in more details or provide test example?

**Comment by MSGhero** [comment]
The old animation continues until it finishes before the new animation begins playing. `animation.name` will trace the new animation. It works normally when `force=true` or when you re-add the line.

```haxe
var f:FlxSprite;
	
override public function create():Void {
	super.create();
		
	f = new FlxSprite();
	f.setFrames(FlxAtlasFrames.fromTexturePackerJson("assets/spritesheet.png", "assets/spritesheet.json"), false);
	f.animation.addByNames("walk_left", ['Kon Walk Left 1.png', 'Kon Walk Left 2.png', 'Kon Walk Left 3.png'], 6, true);
	f.animation.addByNames("walk_right", ['Kon Walk Right 1.png', 'Kon Walk Right 2.png', 'Kon Walk Right 3.png'], 6, true);
		
	add(f);
}
	
override public function update(elapsed:Float):Void {
	super.update(elapsed);
	
	if (FlxG.keys.anyPressed([A])) f.animation.play("walk_left");
	else if (FlxG.keys.anyPressed([D])) f.animation.play("walk_right");
}
```

**Comment by Beeblerox** [comment]
@MSGhero oh yes, now i see. thanks for noting this! can you test my fix?

**Comment by MSGhero** [comment]
Works correctly when `force=false` :+1:
