### ISSUE TITLE
FlxBitmapText width not being set

### ISSUE THREAD

**Issue by 01010111** [HaxeFlixel/flixel#1406]
This also breaks alignment for me - also tested with autoSize set to true and false.
![test](https://cloud.githubusercontent.com/assets/1042453/5467185/9c2c8f54-8588-11e4-9744-931ee4190792.jpg)

**Comment by Beeblerox** [comment]
Sorry for the inacceptable delay, but i hadn't time to work on lib

You need to set `autoSize` to `false` before setting `fieldWidth`
```
var bitmapText:FlxBitmapText = new FlxBitmapText();
bitmapText.text = "TEST";
bitmapText.autoSize = false;
bitmapText.fieldWidth = FlxG.width;
bitmapText.alignment = FlxTextAlign.CENTER;
add(bitmapText);
```
