### ISSUE TITLE
Problems when using accents in a bitmap font

### ISSUE THREAD

**Issue by luigivieira** [HaxeFlixel/flixel#1409]
Hi there. I am trying to use a bitmap font and I am facing some problems when rendering texts with accents (like the word "créditos" in Portuguese).

The word character with an accent is rendered in Flash but not in native. You can check the images from this thread at the StackOverflow in Portuguese:
http://pt.stackoverflow.com/questions/45000/uso-de-fonte-bitmap-no-haxeflixel

or download the sample project that I prepared to reproduce the problem (with the bitmap font fnt and png files) from 4shared:
http://www.4shared.com/zip/nLrY16YEce/ProjetoHaxeflixel.html

Digging a little I found out that there were some issues with the calls of string.charCodeAt and string.fromCharCode (https://github.com/HaxeFoundation/haxe/issues/2382) and after doing some minor changes in file PxBitmapFont.hx (as suggested by jonasmalacofilho in the previous referred link, to use the Haxe.utf8 class) I was able to fix the problem at the current version (master).

I am new to Haxe/HaxeFlixel and I have noticed that the PxBitmapFont class has been renamed to FlxBitmapFont in the dev branch (and changed quite substantially). But I noticed that you guys are still using calls from the string class. So, I don't know if the problem has been fixed at its origin (Haxe) or not, of if you handled it differently. But, in any case, here is the new version of the PxBitmapFont that is currently working for me:
http://www.4shared.com/file/e9kRiUGtce/PxBitmapFont.html

The two changes I have done (which basically involve the use of Haxe.utf8 class for doing decoding the charCode to the glyph in the conditional blocks for native rendering) are marked by commentaries like this:

// LUIZ VIEIRA - UPDATE
// ------------------------
// Changed this:
. . . . . . . . 
// To this:
. . . . . . . . 

If you guys have not already corrected that, perhaps this can be helpful. :)

Happy holidays!

Cheers,
Luiz

**Comment by Beeblerox** [comment]
@luigivieira thank you very much for your fix idea. i've implemented it on dev branch, and FlxBitmapText shows text correcly now

**Comment by luigivieira** [comment]
@Beeblerox you are welcome. And thank you for your help. :) Cheers
