### ISSUE TITLE
FlxAnalog can't work on neko

### ISSUE THREAD

**Issue by MadIcecream** [HaxeFlixel/flixel#1410]
Code:

``` haxe
var analog = new FlxAnalog();
add(analog);
```

And the error:

```
Invalid operation (-)
Called from flixel.ui.FlxAnalog::createZone line 177
```

My libs version:

```
flixel: [3.3.6]
flixel-addons: [1.1.0]
lime: 2.0.0 2.0.1 2.0.2 [2.0.3]
openfl: 2.1.6 2.1.7 [2.1.8]
```

It works on other platforms(flash, windows),
and apologyze for my poor English, i'm not an English native speaker

**Comment by royletron** [comment]
Hey @Gama11 I am still having the same issue with Flixel v3.3.8?

**Comment by Gama11** [comment]
This fix hasn't made it into a release yet.
