### ISSUE TITLE
Wobbly rendering of objects moving in a straight line

### ISSUE THREAD

**Issue by hourglasseye** [HaxeFlixel/flixel#1415]
This is a cross-post from [the HaxeFlixel forum](http://haxeflixel.com/forum/?place=topic%2Fhaxeflixel%2FIJrwDFvLCyY%2Fdiscussion).

---

I notice that there is some wobbling happening with sprites that are moving in a straight line. See [this page](https://dl.dropboxusercontent.com/u/21382055/wobbly/index.html) for a demonstration. There are three directions where the boxes are heading, in radians:

* 2.33774678762164063
* -0.922261703465222
* 0.7853981633974483

If you look closely, the boxes look like they are wobbling along a straight line. To see the code I used for this demonstration, see https://github.com/hourglasseye/flixel_wobbly_demo.

I initially thought this was due to position synchronization problems with Nape bodies and Flixel sprites, but then it appears that even without Nape the problem persists as shown in my demo project. Then I tried to enable antialiasing but that did not help either.

Is this problem due to pixel snapping of some sort? Is there a way to make FlxSprites look like they are moving smoothly in a straight line towards any direction?

**Comment by goshki** [comment]
I think it's because on Flash target HaxeFlixel renders the scene using blitting and thus there's inherent pixel-snapping. Try enabling antialiasing on those rectangles.

**Comment by Gama11** [comment]
Try `pixelPerfectRender = false;` in `Wobbler#create()`, that seems to fix the issue.

**Comment by hourglasseye** [comment]
Indeed it does. Many thanks, @Gama11.
