### ISSUE TITLE
FlxSpriteGroup.remove()

### ISSUE THREAD

**Issue by MSGhero** [HaxeFlixel/flixel#1417]
`add` adds x and y to the child sprite, but `remove` doesn't remove them. Repeatedly adding and removing causes the child to eventually go offscreen. You could just alpha=0 I guess, but would it make sense for `FlxSpriteGroup.remove()` to also subtract away x and y?

**Comment by Gama11** [comment]
I guess it would only be consistent, but that would also create the same expectation for `sprite.alpha`, which is not as easy to handle...

**Comment by MSGhero** [comment]
We had that discussion before and said there's only hacky ways to solve it: #1373 

`cameras` should probably be set to null for GC reasons rather than being left alone.

**Comment by kevinresol** [comment]
I had even proposed a pull request for this.... https://github.com/HaxeFlixel/flixel/pull/698
