### ISSUE TITLE
Errors when using the current dev version with OpenFL 2.2.3

### ISSUE THREAD

**Issue by puggsoy** [HaxeFlixel/flixel#1421]
When trying to compile my project using the latest HaxeFlixel version on the dev branch and OpenFL 2.2.3 I get these errors:

    C:/HaxeToolkit/haxe/lib/flixel/git/flixel/util/FlxBitmapDataUtil.hx:127: characters 4-63 : haxe.Int32 should be flixel.util.FlxColor
    C:/HaxeToolkit/haxe/lib/flixel/git/flixel/util/FlxBitmapDataUtil.hx:128: characters 4-55 : haxe.Int32 should be flixel.util.FlxColor
    C:/HaxeToolkit/haxe/lib/flixel/git/flixel/FlxSprite.hx:892: characters 3-98 : haxe.Int32 should be flixel.util.FlxColor

However, if I roll back to OpenFL 2.2.2 it builds fine.

**Comment by Gama11** [comment]
Should be working now, thanks.
