### ISSUE TITLE
FlxText blurry rendering when align="center" and wordWrap is applied

### ISSUE THREAD

**Issue by Ohmnivore** [HaxeFlixel/flixel#1422]
![](http://snag.gy/Vhyay.jpg)

Here's my code:
```
var tOffset:Float = 8;
text = new FlxText(back.x + tOffset, tOffset, back.width - 2 * tOffset,
getPhrase());
text.color = 0xffffffff;
text.alignment = "center";
add(text);
```
The blurring only seems to happen to the last line, btw.

**Comment by larsiusprime** [comment]
This bug has been around pretty much forever, right? I remember it in the old days of Vanilla AS3 flixel.

**Comment by Ohmnivore** [comment]
Oh well then I guess it's here to stay... I'm gonna try and write a class that will break up a multi-line string into single FlxTexts, so that there's one FlxText instance per line. I hoped it wouldn't come to this but ok.

**Comment by larsiusprime** [comment]
Sorry, I didn't mean to be the final authority on this or anything, let's see if @gama11 or anyone else can confirm :P

**Comment by Gama11** [comment]
Yeah, I don't think there's a simple fix for this... This issue seems related btw: #778

**Comment by goshki** [comment]
Try putting extra spaces around "SUBJECTS (AGAIN)" so it looks like " SUBJECTS (AGAIN) ".

**Comment by larsiusprime** [comment]
Did we actually fix this????

**Comment by Gama11** [comment]
To some degree.. there are still some cases where the workaround doesn't work I think.

**Comment by adrianulima** [comment]
My trick only works when the `space char` in the used font have an odd `width`, the blurry problem happens when the line `width` is odd, so I add an extra space to make it even.

**Comment by Geokureli** [comment]
This issue is back, and CI is failing on openfl 9.5.1
https://github.com/openfl/openfl/issues/2839
