### ISSUE TITLE
Q: Is it real to do this lighting effect in haxeflixel?

### ISSUE THREAD

**Issue by Partysun** [HaxeFlixel/flixel#1423]
Hello, Here is cool tutorial of 2d lighting - http://www.mattgreer.org/articles/dynamic-lighting-and-shadows/
Is it real to do this in haxeflixel now? I know is very newbe question, but...
I hope it's real ;)

Thank you,

**Comment by Gama11** [comment]
The [forum](http://haxeflixel.com/forum/) is a better place for questions, the issue tracker is for bug reports, feature suggestions and the like.

I assume by "real" you mean "possible"? The dev branch supports post processing shaders, you could try this shader with the [PostProcess](https://github.com/HaxeFlixel/flixel-demos/tree/dev/Effects/PostProcess) demo and see if you can get it to work.

**Comment by Partysun** [comment]
Sorry, You are right.
