### ISSUE TITLE
Make a way to enable anti-aliasing globally

### ISSUE THREAD

**Issue by MintPaw** [HaxeFlixel/flixel#1424]
From what I understand right now there is no way to set aa globally. You can set it recursively, but if a new object is created you must also set that. I guess you could set recursively at the end of every frame but this involves a setter so I'm not guaranteed how expensive this could be.

I've been placing this in constructor of FlxSprite to solve this problem for me.
if (Type.resolveClass("Reg") != null) antialiasing = Reflect.field(Type.resolveClass("Reg"), "aa");

But then of course I can't update the library and this is also likely pretty slow.

I can think of instances where you would want to set this individually, but I think it's much more common to need to turn it on and off globally.

**Comment by Gama11** [comment]
Doesn't FlxCamera#antialiasing take care of that?

**Comment by MintPaw** [comment]
If that's true then it should be commented differently because it's not obvious at all. :/

"Whether the camera display is smooth and filtered, or chunky and pixelated. Default behavior is chunky-style."

**Comment by Gama11** [comment]
Not sure what to improve about that description, seems fairly intuitive that the antialiasing setting of the camera has to affect the sprites rendered on it? What else would it do? :)

How would you word the description?

**Comment by MintPaw** [comment]
So does it toggle the antiantialiasing property of FlxSprites as it moves over to render then? What if their are multiple cameras? Does aa work on a camera level? I'm pretty sure it's per object.

**Comment by MintPaw** [comment]
Can you stop closing my issues without at least glancing over the source to make sure I'm wrong.

var f:FlxSprite = new FlxSprite();
f.antialiasing = false;
trace(f.antialiasing); // false
add(f);
trace(f.antialiasing); // false
FlxG.camera.antialiasing = true;
trace(f.antialiasing); // false
super.update(FlxG.elapsed);
trace(f.antialiasing); // false

"Doesn't FlxCamera#antialiasing take care of that?"
No, it doesn't. All it seems to do is set the bitmap smoothing when using FLX_RENDER_BLIT.

This is still an issue, there's no way to make sure everything always has AA on at all times without constantly looping through every object.

**Comment by Gama11** [comment]
Why do you care about the physical antialiasing property of `FlxSprite`? Of course that isn't set if you set the camera's `antialiasing`, a sprite can be rendered on mutliple cameras after all. A sprite is rendered antialiased if either:

- `sprite.antialiasing` is true
- or `camera.antialiasing` is true

On `FLX_RENDER_BLIT`, this logic ends up [in the `smoothing` param of `BitmapData#draw()`](https://github.com/HaxeFlixel/flixel/blob/637e4a541978cd26a8c6a6babaefb1d837b87a6d/flixel/FlxSprite.hx#L624).
[Pretty much the same thing with `FLX_RENDER_TILE`, the `smooth` param of `drawTiles()`](https://github.com/HaxeFlixel/flixel/blob/ee41986a3573bd45c0c562f39221425e57f0bc77/flixel/graphics/tile/FlxDrawTilesItem.hx#L77) is also determined by `antialiasing || camera.antialiasing`.

**Comment by Tiago-Ling** [comment]
This is very confusing as it is. What happens if:
* A FlxSprite with AA is rendered in a Camera without AA?
* And what if a FlxSprite with no AA is drawn in two cameras, one with and other without AA?

Does FlxCamera simply override the setting on individual sprites? If so, shouldn't we simply remove this setting from them? 

Or, if individual AA / smoothing is more of a Flash thing, shouldn't the comments be clear about this?

**Comment by MintPaw** [comment]
Mm, looking at this now, I think it'd be best for FlxCamera to have the "global" aa setting, and FlxSrite to have a properties called forcedAA which should have an enum like FlxForcedAA.ON/OFF/NONE or something, with NONE being default.

**Comment by EliteMasterEric** [comment]
For people looking in this old thread for info on this, HaxeFlixel 5.0.0 adds the static `FlxSprite.defaultAntialiasing` property, which initializes the value of `antialiasing` when constructed. This essentially acts as a "global" AA setting that can easily be overridden on a per-sprite basis.
