### ISSUE TITLE
Virtualpad/FlxButton not registering mutiple press at the same time in ios

### ISSUE THREAD

**Issue by solewalker** [HaxeFlixel/flixel#1425]
Virtualpad is not working if two or more button is pressed, tested on both ios simulator and on real device. It looks like it is registering mouse input even on mobile target. Even buttons are not registering if two button is pressed together. So the problem lies in FlxButton I think. Also disabling Mouse input for mobile makes FlxButton unusable.

**Comment by Gama11** [comment]
Wouldn't hurt to have [some more details](https://github.com/HaxeFlixel/flixel/blob/dev/CONTRIBUTING.md#reporting-a-bug) (flixel / openfl version? reproducible example?).

Testing this with Mode on Android and Flixel dev, this works just fine for me (with `FLX_NO_MOUSE`). `FlxButton`s should generally be able to handle multitouch just fine.

**Comment by solewalker** [comment]
Why are you keep closing issues I don't get it. I said this problem is happening on ios not on android. It is fine on android. And before creating any issue I check them with latest version of libs. I am using flixel git and I updated all my libraries with haxelib upgrade so
lime 2.0.5
hxcpp 3.1.48
openfl 2.2.3 
If that helps.

**Comment by Gama11** [comment]
The handling of touch events is exactly the same across all targets, so if there's any difference between iOS and Android here, so there's not much we can do about it on flixel's side (and in that case it seems more likely that this is an OpenFL / Lime issue).

Besides, I don't own any iOS devices to test this with. Did you test this on Android as well? If so, what results are you getting?

I'm on the same libray versions btw.

**Comment by solewalker** [comment]
Android is fine as expected. I can press multiple button on gamepad with or without disabling mouse on mobile target. I will test input of an openfl project then report back.

**Comment by solewalker** [comment]
Not to mention that muti-touch demo is also not working properly only for ios. It's registering them way off. I reported to the openfl forum though, waiting for their reply.

**Comment by solewalker** [comment]
Update: By testing multi-touch demo further I have found that touch is generated for twice as value of FlxG.width and FlxG.height. Normally, touch value of top left corner should be (0,0) and bottom right corner should be (FlxG.width, FlxG.height) but in this case Top left corner is fine (0,0) but bottom right corner returns a value of (FlxG.width * 2, FlxG.height) By dividing both touch.x and touch.y by 2 I get accurate touch point. Don't know why touch is generated such way.

**Comment by Tiago-Ling** [comment]
This is happening in which version of iOS?

**Comment by solewalker** [comment]
OSX version 10.10, Xcode version 6.1.1. This is what I get with haxelib install 

actuate: [1.7.5]
flixel-addons: 1.1.0 git [dev:/usr/lib/haxe/lib/flixel-addons/git]
flixel-demos: git [dev:/usr/lib/haxe/lib/flixel-demos/git]
flixel-templates: [1.0.2]
flixel-tools: git [dev:/usr/lib/haxe/lib/flixel-tools/git]
flixel: 3.3.6 git [dev:/usr/lib/haxe/lib/flixel/git]
hxcollision: [1.1.0]
hxcpp: 3.1.39 [3.1.48]
install: git [dev:/usr/lib/haxe/lib/install/git]
lime: 2.0.2 [2.0.5]
node-webkit: [1.0.7]
openfl-samples: [2.1.0]
openfl: 2.1.8 [2.2.3]
swf: [1.7.1] 

This guy is also having such issues http://haxeflixel.com/forum/?place=msg%2Fhaxeflixel%2Fyp442--JZPA%2FDey3P2wNJ0gJ

**Comment by Tiago-Ling** [comment]
What iOS version is the game targetting?

I don't know what is the default setting for this, but you can use a line
like this in your project.xml file to set the version:

*<ios deployment="6" binaries="armv7" devices="universal" />*

I ask this because i heard that in iOS 8 there were some changes in the
screen size / positioning. So, if you're targetting iOS 8 this could be one
possible reason you're getting these problems.

**Comment by solewalker** [comment]
I was not deploying for ios 8, but to be sure I tried changing deployment target to 5/6 through xcode and project.xml, but the problem remains the same.

**Comment by solewalker** [comment]
Update: I have tried this multi-touch openfl code https://gist.github.com/solewalker/47c092f1943c1364a8d8 it is working as expected both on simulator and on device, haxeflixel muti-touch is not. So it's definitely a haxeflixel issue.

**Comment by solewalker** [comment]
If this is not haxeflixel related issue then why openfl touch works and I was able to fix this problem temporarily by changing haxeflixel code? Anyway I am done with this, this is my first and last haxeflixel project, I don't want to trouble people with my *stupid* issues anymore.

**Comment by Beeblerox** [comment]
@solewalker i'm really sorry about your troubles with haxeflixel, but now i don't have free time to solve its issues

**Comment by Tiago-Ling** [comment]
@solewalker Did you manage to solve the problem by changing HaxeFlixel
code? If so, please tell us what did you do so it can be fixed in the
repository. If you are comfortable with git / github, make a pull request
so people can test and implement it in the library.

This is not a stupid issue by the way, it is just the way open source works
sometimes - other contributors ask a lot of questions about an issue to
understand what exactly is happening and if possible help to fix it.
Sometimes, as it appears to be your case, the person who opened the issue
ends up correcting the problem himself - in this case you need to send the
code to be tested and merged in the repository.

A lot of bug fixes and improvements were made this way, this is why the
community is so important for us.

Please post the code here so we can test it.

Thanks!

**Comment by solewalker** [comment]
I wasn't demanding an immediate fix, and I have been using open source engines all my life. Issues are created so other people can see and report if they are having the same problems, closing down issues before they are properly understood or acknowledged is not going to help anyone.

Anyway I was having twice the expected value of touch position in Multi-touch haxeflixel demo, I tried an openfl demo but it was working fine. So all I did was diving the touch positions I get by 2. This also fixed button or virtual pad issue.  So I changed this https://github.com/HaxeFlixel/flixel/blob/dev/flixel/input/touch/FlxTouchManager.hx#L181 also #L212 line into this
``touch.setXY(Std.int(FlashEvent.stageX * .5), Std.int(FlashEvent.stageY * .5)); `` 
for ios though. I don't know why its returning twice as value, all I know it fixed the problem in a hackish way, just before I was going to send a build to someone and saved me from a big trouble.

**Comment by Beeblerox** [comment]
@solewalker maybe that's because i haven't updated touch input classes (i hadn't tested it on mobile )

**Comment by solewalker** [comment]
@Beeblerox this problem is only happening on ios not on android, so you have to test it on either ios simulator or device.

**Comment by solewalker** [comment]
My hack works for ios8 that I can confirm, I tested it on ipod with ios 6.1.6 touch is messed up with my hack. So my question is, what kinda code haxeflixel has that makes touch behave differently on different ios version, have not tested on any ios7 devices.

**Comment by solewalker** [comment]
If anyone really care, I finally found the root cause and solution to this problem. It's not haxeflixel issue but I had to use haxeflixel code to solve this. I found out that on ios8 stageHeight and stageWidth is getting wrong values from init(). Don't know why but they were getting half the expected value. That's why FlxGame was initialized with wrong values. I also noticed they were returning expected value after Event.Resize is called. So I added an event handler and re-initialized FlxGame with correct values. One thing to notice Event.Resize is not called in any other platform, only ios 8.

**Comment by Tiago-Ling** [comment]
Hi @solewalker, are the half size values ocurring only in iOS 8? Seems to be a pretty nasty bug, it can in theory affect other stuff that relies on stageWidth and stageHeight.

Could you please post your solution so we can analyze it and think of a way to solve this internally?

**Comment by sruloart** [comment]
This is old. The problem is the on iOS 6/7/8/+ there's a very short delay before the Event.Resize is fired, so you're left with the non-retina values for your stage until then. This is why you see so many OpenFL projects do this:
```haxe
#if ios
haxe.Timer.delay(init, 100); // iOS v. > 6
#else
init();
#end
```

**Comment by Tiago-Ling** [comment]
Nice to know - so it's only a matter of updating the flixel project template.

I created a PR for this here: https://github.com/HaxeFlixel/flixel-templates/pull/18

**Comment by solewalker** [comment]
Yah, it was happening on ios 8 only. Event.Resize is also called only in ios 8. And here is my solution: 

- Added this  inside my init()
```Haxe
 Lib.current.stage.addEventListener(Event.RESIZE, onResize);
```
- Here is my onResize() function 
```Haxe
	private function onResize(?E:Event):Void
	{
		if (Lib.current.stage.hasEventListener(Event.RESIZE))
		{
			Lib.current.stage.removeEventListener(Event.RESIZE, onResize);
		}
		var stageWidth:Int = Lib.current.stage.stageWidth;
		var stageHeight:Int = Lib.current.stage.stageHeight;
		var ratioX:Float = stageWidth / gameWidth;
		var ratioY:Float = stageHeight / gameHeight;
		zoom = Math.min(ratioX, ratioY);
		gameWidth = Math.ceil(stageWidth / zoom);
		gameHeight = Math.ceil(stageHeight / zoom);
		FlxG.resizeZoom(zoom);
		FlxG.resizeGame(gameWidth,gameHeight);
	}
```
- Finally I had to add this resizeZoom function inside FlxG.hx
```Haxe
	public static function resizeZoom(Zoom:Float):Void
	{
		FlxG.initialZoom = FlxCamera.defaultZoom = Zoom;
	}
```
I can't tell if this is the best way to do this but this worked for me, maybe you guys can come up with a better solution.

**Comment by solewalker** [comment]
This is of course openfl side of problem. Once I mentioned that openfl multi-touch is working but haxeflixel is not, because of this code https://github.com/frosty/NME-Multitouch-Example/blob/master/src/Main.hx#L26
```Haxe
	#if iphone
	Lib.current.stage.addEventListener(Event.RESIZE, init);
	#else
	addEventListener(Event.ADDED_TO_STAGE, init);
	#end
```
He was indeed waiting for Event.Resize for ios but why? he didn't mention it, but unfortunately this does not work for all iOS version, as Event.Resize is not always called.
