### ISSUE TITLE
Flixel 3.3.6 crashing compiling to windows with openfl 2.2.3

### ISSUE THREAD

**Issue by Tembac** [HaxeFlixel/flixel#1426]
The latest flixel release, 3.3.6 is crashing when compiling to windows or neko using openfl 2.2.3.

I tested this with My project and then the minimalisticTD demo. It works choosing openfl 2.2.1

The console output with Flash Develop is the following:

Running process: C:\Program Files (x86)\FlashDevelop\Tools\fdbuild\fdbuild.exe "C:\Users\Agustin\Documents\Tools\haxe\MinimalistTD\MinimalistTD.hxproj" -ipc 93027560-a7cd-4e88-abc7-4871980c62cf -version "3.1.0" -compiler "C:\HaxeToolkit\haxe" -notrace -library "C:\Program Files (x86)\FlashDevelop\Library" -target "windows"
Building MinimalistTD
Running Pre-Build Command Line...
cmd: "C:\HaxeToolkit\haxe/haxelib" run lime build "Project.xml" windows -release -Dfdb
C:/HaxeToolkit/haxe/lib/flixel/3,3,6/flixel/FlxSprite.hx:1148: characters 3-93 : haxe.Int32 should be Int
C:/HaxeToolkit/haxe/lib/flixel/3,3,6/flixel/util/FlxCollision.hx:233: characters 37-114 : haxe.Int32 should be Int
C:/HaxeToolkit/haxe/lib/flixel/3,3,6/flixel/util/FlxCollision.hx:233: characters 37-114 : For function argument 'Color'
Build halted with errors.
Done(1)

**Comment by Gama11** [comment]
I was pretty confident that this issue [only affected the current dev branch](https://github.com/HaxeFlixel/flixel/issues/1421), as 3.3.6 does not have the `FlxColor` abstract.

I can't reproduce this issue. Could you try updating your outdated haxe version (3.1.0) to 3.1.3?

**Comment by Tembac** [comment]
Fixed with the Haxe upgrade! :+1: Thanks!

Is confusing that haxe doesn't update with haxelib and that when I update it Flash Develop keeps the old version number. I know HF doesn't have anything to do with it but it makes the tools needed more confusing everyday. I hope this is simplified in the future.

**Comment by Gama11** [comment]
What do you mean by "FD keeps the old" version number? It still says `-version "3.1.0"`?

This has been simplified actually - the dev branch [refuses to compile with Haxe versions below 3.1.1](https://github.com/HaxeFlixel/flixel/blob/dev/flixel/system/macros/FlxConditionals.hx#L66-L69).

**Comment by Tembac** [comment]
Yes. I updated from the haxe website and from the fd appman but the brain
number is still the old one. If I check on the directory of installation
the library is updated.

**Comment by Tiago-Ling** [comment]
You can set the current Haxe version from inside FlashDevelop:

Go to Project -> Properties -> SDK -> Choose the Haxe version you want from
the dropdown list or click on "manage" to add the path to your new version.

**Comment by Tembac** [comment]
Thanks! I did that!

Hope to remember next time haxe updates :smile:
