### ISSUE TITLE
Sprites on the same y-coordinate but different x-coordinate flicker with FlxSort byY()

### ISSUE THREAD

**Issue by ericmbernier** [HaxeFlixel/flixel#1427]
I recently upgraded to Flixel 3.3.6 and it brought to my attention a custom fix I put in my 3.3.5's FlxSort.byY() method. In its current form, if a FlxSprite overlaps another FlxSprite, both are on the same y-coordinate but have different x-coordinates, then the two sprites flicker. If you sort by the x-value and a y-value multiplied by a value to simply give the y-val more prominence then the issue goes away.

Here is the fix I made:

```haxe
	/**
	 * You can use this function in FlxTypedGroup.sort() to sort FlxObjects by their y values.
	 */
 	public static inline function byY(Order:Int, Obj1:FlxObject, Obj2:FlxObject):Int
	{
		return byValues(Order, Obj1.x + Obj1.y * 8, Obj2.x + Obj2.y * 8);
	}
```
 
This fix is in my personal instance of Flixel. If the fix is deemed appropriate I can submit a pull request for this small change. I submitted a [forum post](http://haxeflixel.com/forum/?place=msg%2Fhaxeflixel%2Fm0FHqeg6zrU%2Fvgn4U14LzBEJ) awhile ago, but forgot to submit this issue until now.

**Comment by JoeCreates** [comment]
I don't think this fixes the issue. It just distorts it while also producing some erroneous results. Consider a sprite A at (1000, 10) and  B at (1010, 9). B has the smaller y position, and yet will still be sorted to after A. The use of X also means the issue will still remain if both x and y are the same for two sprites. A better solution might be to assign each sprite a unique id, then do two sorts, first by id, then by y. You can already implement this with the existing system. :)

**Comment by ericmbernier** [comment]
I guess I've been lucky with my results so far. :) I'll close the issue and go the ID route.

**Comment by mrcdk** [comment]
If you want to preserve the order of equals elements you will want to use [`ArraySort.sort()`](http://api.haxe.org/haxe/ds/ArraySort.html#sort) Something like `ArraySort.sort(group.members, FlxSort.byY.bind(FlxSort.ASCENDING))` should work, but it will be slower.

**Comment by larsiusprime** [comment]
I think you mean this?

http://api.haxe.org/haxe/ds/ArraySort.html

**Comment by MSGhero** [comment]
I had this issue in an isometric project even with using a stable sort (isometric sorting isn't transitive) when I added a new FlxSprite. I had to `add` to the group's members using insertion sort rather than `push` or else it would flicker.
