### ISSUE TITLE
FlxTween.angle 

### ISSUE THREAD

**Issue by Matej244** [HaxeFlixel/flixel#1429]
When i compile the game for PC and NEKO the  FlxTween.angle seems to rotate in a cricle ("moving entire thing") it doesnt rotate it at all. Works fine on Flash/Android export.

I just upgraded to newest version 10minutes ago.

Code i am using for angle, i can also provide gif animation if needed
FlxTween.angle(title, -10, 10, 1, { type: FlxTween.PINGPONG, ease: FlxEase.quadInOut } );

title code
title = new FlxText(0, FlxG.height/3, FlxG.width, "Text here", 80);
		title.setFormat("assets/data/kimberley.ttf", 80, 0xFFFFFF, "center");
		title.y -= title.height;
		title.antialiasing = true;

**Comment by Gama11** [comment]
Please provide a .gif, I can't really see any difference between flash and neko with that code.

**Comment by Matej244** [comment]
Flash : http://puu.sh/f3dGr/a6e7089946.gif
Neko/Pc : http://puu.sh/f3dHT/4b59a5fab2.gif

**Comment by Gama11** [comment]
It seems that your font is not being loaded on neko, maybe that's related?

**Comment by Matej244** [comment]
The font stopped working when i updated yestarday, but it worked before fine. It just htat Angle Tween didnt work right before and now

**Comment by Gama11** [comment]
Yeah, I definitely can't reproduce that with your code, neither on master nor dev. Are you sure you provided all relevant code?

**Comment by Gama11** [comment]
I guess your OpenFL and Lime versions might be relevant, are they up to date / what versions are you using? Lime 2.0.6 and OpenFL 2.2.4 here.

**Comment by Matej244** [comment]
Yes it is up to date , i updated everything yestarday.

**Comment by Gama11** [comment]
This is my code, pretty much exactly what you posted:

```haxe
package;

import flixel.FlxG;
import flixel.FlxState;
import flixel.text.FlxText;
import flixel.tweens.FlxEase;
import flixel.tweens.FlxTween;

class PlayState extends FlxState
{
	override public function create() 
	{
		var title = new FlxText(0, FlxG.height / 3, FlxG.width, "Text here", 80);
		title.setFormat(null, 80, 0xFFFFFF, "center");
		title.y -= title.height;
		title.antialiasing = true;
		add(title);
		
		FlxTween.angle(title, -10, 10, 1, { type: FlxTween.PINGPONG, ease: FlxEase.quadInOut } );
		
	}
}
```

Btw, you can check the versions of haxelibs via `haxelib list`, no need to look at the folders.

**Comment by Matej244** [comment]
I copypasted your code and tried it , it doesnt work right

Gif :  http://puu.sh/f41QV/46231a9ff7.gif

**Comment by Tiago-Ling** [comment]
I just tested the code from @gama11 in Windows and Neko targets, tweening
angles work fine here (i.e. rotates around the center).

My library versions:
Haxe 3.1.3
Lime - 2.0.6
OpenFL - 2.2.4
HaxeFlixel - latest dev

Did you try the code from gama in a new project?

**Comment by Matej244** [comment]
I tried same code in other game project i'm making, it works there.
