### ISSUE TITLE
Annoying output

### ISSUE THREAD

**Issue by MSGhero** [HaxeFlixel/flixel#1430]
Pretty much every time autocomplete occurs, this happens. It sounds like a macro issue.
![flixelerror](https://cloud.githubusercontent.com/assets/5033927/5893281/ba275768-a4ab-11e4-8184-ff0d481ba31a.png)

I think it started when `FlxPool` was changed to be faster in #1256, and it's coming up in [FlxFlicker's static pool](https://github.com/HaxeFlixel/flixel/blob/dev/flixel/effects/FlxFlicker.hx#L15). I'm not sure, though, because it also comes up in `haxe.ds.GenericStack`->`hscript.Parser`->`DConsole`.

Everything builds fine, and there are no issues, it's just annoying. I'm on a nightly haxe build from a month or two ago if you guys don't get this issue.

**Comment by Gama11** [comment]
Interesting, so you actually got the haxe dev branch to work with OpenFL? They've been incompatible for a while as far as I can tell, I always get this error when running lime:

```
Called from ? line 1
Called from CommandLineTools.hx line 1330
Called from CommandLineTools.hx line 25
Called from CommandLineTools.hx line 64
Called from CommandLineTools.hx line 1037
Called from /usr/lib/haxe/std/neko/_std/sys/io/File.hx line 30
Uncaught exception - [file_contents,/haxelib.json]
```

Or are you on an older OpenFL / Lime version?

Regarding your issue, I've never seen that before, and it's not unlikely to be a Haxe issue. Have you tried on a newer Haxe dev build?

**Comment by MSGhero** [comment]
I'm on the most recent Lime and OpenFL, my haxe version is [dev_790e67e](http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/windows-installer/) which was compiled Oct 7. Did I just get lucky and pick the one version that works with OpenFL? I installed dev to try out the python target.

I'll try the newest build out tomorrow, maybe 3.1.3 if I have time, and see if anything changes.

**Comment by MSGhero** [comment]
`haxe --help` says I'm on 3.2.0 dev but the compiler is setting `-version 3.1.3`, so I'm not sure what's going on there. If no one else is getting the issue, then it's a dev haxe problem and this can be closed probably. I thought it was something a lot of people had but were too silent to say.

**Comment by Gama11** [comment]
`--version` is set based on the latest git tag, and there will only be a `3.2.0` tag when that version is actually released, so you are on dev.

I'd still be curious if you can get projects to compile with both latest Lime / OpenFL and latest Haxe dev.

**Comment by MSGhero** [comment]
Latest dev haxe doesn't work with OpenFL, and master 3.1.3 doesn't have the output issue.

One cool thing about the dev version I was on is that FD autocomplete sorted variables and functions separately. Doesn't happen in master.

**Comment by MSGhero** [comment]
This still happens in Haxe 3.2.0 rc1, and now it'd be weird if other people didn't get it too.

**Comment by Gama11** [comment]
Is your FlashDevelop version up to date?

**Comment by MSGhero** [comment]
I'm using FD 5. I went back to haxe 3.1.3 and the issue doesn't arise, so it's something with haxe. I have no idea what, though; the output always has to do with FlxFlicker and FlxPool.

If you've updated haxe, try using FlxFlicker somewhere. These errors show up during type completion in the class that uses a flicker. 

Also, if you have "check syntax on save" enabled in FD, it shows up each time you save a file.

**Comment by Gama11** [comment]
Can't reproduce that with haxe 3.2.0 rc1 and FD5. Got a concrete example?

**Comment by MSGhero** [comment]
Found it: https://github.com/HaxeFoundation/haxe/issues/2902

It's tagged 3.2.0, but I downgraded to 3.1.3 since -Dfdb was messed up. I'll try it again when they officially release 3.2. But it's not a flixel issue :+1:
