### ISSUE TITLE
If directory requires administrator rights - it shows wrong output

### ISSUE THREAD

**Issue by as3boyan** [HaxeFlixel/flixel#1435]
Minor issue

If directory requires administrator rights, like root directory - it shows wrong output

Flixel 3.3.6, tools 1.0.4
![](http://i.imgur.com/dnxYfM9.png)

In other directory like C:\A it works fine

**Comment by Gama11** [comment]
Moved to the correct repo: https://github.com/HaxeFlixel/flixel-tools/issues/47
