### ISSUE TITLE
Error: Invalid array access in FlxTilemap::ray

### ISSUE THREAD

**Issue by tanis2000** [HaxeFlixel/flixel#1436]
I'm getting the following error:

```
Invalid array access
Called from Array::__get line 291
Called from a C function
Called from flixel.tile.FlxTilemap::ray line 1353
```

I already looked at past issues and there was one about passing negative numbers in the tilemap, but I do not have any negative number there. 
This is happening with version 3.3.6.
Any clue of what might be happening?

**Comment by tanis2000** [comment]
After further analysis it looks like I might be trying to cast a ray from a source that is outside the tilemap and this might be causing this issue.

**Comment by Beeblerox** [comment]
could you provide test project, so i can add checks in code for such cases?

**Comment by tanis2000** [comment]
@Beeblerox sure, just give me a couple of days to get a test project up and running. Cheers!

**Comment by Gama11** [comment]
Closing this since there hasn't been any followup.
