### ISSUE TITLE
FlxSprite animation issue with invalid finishCallback access

### ISSUE THREAD

**Issue by puggsoy** [HaxeFlixel/flixel#1439]
I have a sprite with this function:

	private function animCallback(name:String, frameNum:Int, frameIndex:Int)
	{
		if (endAnim == name && animation.finished)
		{
			destroy();
		}
	}

Where `endAnim` is the string name of the animation I want to end on. If I set `animation.callback` to this function, then once the animation ends I get this:

	Invalid field access : finishCallback
	Called from flixel/animation/FlxAnimation.hx line 226
	Called from... etc etc

I realised that this is due to the sprite destroying itself once the animations ends. I have a sprite that has a similar function, but doesn't destroy itself. Also, if I modify the function to only take the `name` parameter and set `animation.finishCallback` to it instead, the error doesn't happen and it works normally.

**Comment by Beeblerox** [comment]
this issue should be resolved on the dev branch. 
What version do you use?

**Comment by puggsoy** [comment]
I'm using the latest version of the dev branch. I just tried updating but I'm already up-to-date.

**Comment by Beeblerox** [comment]
ok, i'll look into it tonight

**Comment by Beeblerox** [comment]
why do you want to destroy sprite but not to kill it?
do you remove it from parent groups?

**Comment by puggsoy** [comment]
It's simply an effect sprite, not an actual game object. Once it's done animating I want it to be destroyed. I do remove it from the parent group before destroying, but I removed that from my code for simplicity.

Thanks for the fix, it works! In this case I'll be using `finishCallback` instead anyway, but I figured it would be best to get this fixed.
