### ISSUE TITLE
Incorrect Button IDs on XBoxButtonID.hx for Mac builds

### ISSUE THREAD

**Issue by 01010111** [HaxeFlixel/flixel#1442]
#elseif mac
	/**
	 * Button IDs
	 */
	public static inline var A:Int = 1;
	public static inline var B:Int = 1;
	public static inline var X:Int = 2;
	public static inline var Y:Int = 3;

should be 

    #elseif mac
	/**
	 * Button IDs
	 */
	public static inline var A:Int = 0;
	public static inline var B:Int = 1;
	public static inline var X:Int = 2;
	public static inline var Y:Int = 3;

**Comment by Beeblerox** [comment]
@01010111 thanks for noting this
