### ISSUE TITLE
FlxSignal has/remove not working on NEKO target

### ISSUE THREAD

**Issue by darkoverlordofdata** [HaxeFlixel/flixel#1443]
I ran into an issue with the FlxSignal remove method, and it manifests as well in the has method. FlxSignal does not recognize the callback that was added, and then cannot remove it individually. The removeAll method does work. You can use this gist to reproduce the issue:

https://gist.github.com/darkoverlordofdata/459bd409f21d64b68f08

When I use this class in my NEKO target, I get FAIL. Other platforms (HTML5/Andoid/CPP) get PASS.

**Comment by Gama11** [comment]
Probably fixed by https://github.com/HaxeFlixel/flixel/pull/1223?

**Comment by darkoverlordofdata** [comment]
Probably... but also a ton of breaking changes. At this point, I don't see enough documentation to work through all the changes. I'll probably wait for a future project. When will 4.0 release?
