### ISSUE TITLE
Centering App On-Screen in Flash

### ISSUE THREAD

**Issue by ashes999** [HaxeFlixel/flixel#1446]
Related to [my previous issue](https://github.com/HaxeFlixel/flixel/issues/1432), I'm trying to figure out how to position UI elements (images, buttons) consistently across devices, while using the default scale mode (ratio).

By default, the app will create whitespace / dead space at the bottom (or right side) of the screen. Is there an easy way to simply center my application, while still using the default coordinate system (eg. if `project.xml` specifies a height of `500`, and my device is `800` pixels high, moving something to `(0, 500)` should be, on that device, at a position of `(0, 650)`).

**Comment by Beeblerox** [comment]
@ashes999 can you attach some images which will show what you want to achieve? i will try to help you

**Comment by ashes999** [comment]
While writing this out, I looked at my code, and I think I have this wrong. My code is already using `FlxG.width` and `FlxG.height` to add things in the center. But this makes it hard to position elements consistently.

Instead, I've reworded my issue to: how can I easily center the empty space around my app?

**Comment by Beeblerox** [comment]
@ashes999 can you provide some test project and i'll try to "fix" it.
But i think the problem could be in the `Main` class - in the line like:
```
addChild(new FlxGame(640, 480, initialState, 1, 60, 60, false, false));
```

**Comment by Beeblerox** [comment]
i mean that you should try to pass exact values (not calculated on stage size, like in default template project)

**Comment by ashes999** [comment]
@Beeblerox these values, and this code, is generated from the HaxeFlixel project templates. You can create a new project, and see it for yourself.

Or you can use [my work in progress](https://github.com/ashes999/card-game).

**Comment by Beeblerox** [comment]
I'll try to look into your project tonight. And maybe push fix for this problem

**Comment by Beeblerox** [comment]
@ashes999 i've made pull request for your project which should help - https://github.com/ashes999/card-game/pull/1

**Comment by ashes999** [comment]
I can't believe how fast you resolved it @Beeblerox . 

1) Can you please explain how your changes resulted in this? Is it the sizes or the zoom that fixed it?
2) Should the standard new-game template be updated to include this fix?

Thanks!!

**Comment by Beeblerox** [comment]
1) actually changing only `zoom` value is needed for fixing this issue, since if `zoom` is equal to default value of `-1` then the default code will try to calculate actual game zoom and correct game size basing on calculated zoom and stage size.
2) i doubt about making those changes in default template, since the issue you had is caused only by not specified zoom value

**Comment by ashes999** [comment]
@Beeblerox I haven't changed the zoom myself. It generated from the template that way. Thanks for the explanation.
