### ISSUE TITLE
Add anyJustMovedXAxis and anyJustMovedYAxis to FlxGamepadManager.hx ?

### ISSUE THREAD

**Issue by Txori** [HaxeFlixel/flixel#1449]
Hi,
I'm using FlxG.gamepads.anyJustPressed a lot in my game's menus so that I don't bother finding which gamepad is plugged or not. But there's no function in order to do the same thing with the axes.

So what do you think of adding those two functions in flixel/input/gamepad/FlxGamepadManager.hx ?

    /**
    * Check to see if the X axis is moved on any Gamepad.
    * 
    * @param AxisID The axis id
    * @return Float Value from -1 to 1 or 0 if no X axes were moved
    */
    public function anyMovedXAxis(AxisID:Int):Float
    {
    	for (gamepad in _gamepads)
    	{
    		if ((gamepad != null) && gamepad.getXAxis(AxisID) != 0)
    		{
    			return gamepad.getXAxis(AxisID);
    		}
    	}
    
    	return 0;
    }

    /**
    * Check to see if the Y axis is moved on any Gamepad.
    * 
    * @param AxisID The axis id
    * @return Float Value from -1 to 1 or 0 if no Y axes were moved
    */
    public function anyMovedYAxis(AxisID:Int):Float
    {
    	for (gamepad in _gamepads)
    	{
    		if ((gamepad != null) && gamepad.getYAxis(AxisID) != 0)
    		{
    			return gamepad.getYAxis(AxisID);
    		}
    	}
    
    	return 0;
    }

I would gladly propose a fork, but I don't know much about git...

**Comment by Beeblerox** [comment]
@Txori thank you for your code! i'll merge it in the dev branch tomorrow (not going to do it today, because i'm going to sleep now)
