### ISSUE TITLE
FlxColor Int32 causes compile error on Linux

### ISSUE THREAD

**Issue by jotson** [HaxeFlixel/flixel#1451]
The error message is:

**/usr/lib/haxe/lib/flixel/git/flixel/util/FlxColor.hx:19: lines 19-780 : You can only declare from/to with compatible types**

I can compile when targeting neko and flash (`lime test neko`). Building linux works (`lime test linux`) if I remove the `from Int32` and `to Int32`.

This is related to #1421 I think. I'm using the latest git version (30487a7).

flixel-addons: git 1.1.0 1.0.3 [dev:/usr/lib/haxe/lib/flixel-addons/git]
flixel-demos: [1.1.1] 1.0.2
flixel-templates: 1.0.1 [1.0.2]
flixel-tools: [1.0.4] 1.0.2
flixel-ui: 1.0.1 [1.0.2]
flixel: git 3.3.6 [dev:/usr/lib/haxe/lib/flixel/git]
haxelib_client: [3.1.0-rc.4]
hxcpp: [3.1.48] 3.1.21 3.1.39 3.1.22 3.0.2
hxlibc: [1.1.4]
lime: [2.0.4]
nape: 2.0.13 2.0.9 [2.0.16]
openfl-bitfive: [2.1.6]
openfl-compatibility: [1.0.1]
openfl-html5-dom: [1.2.2] 1.2.0 1.2.1
openfl-html5: 1.0.2 1.1.0-beta 1.0.5 [1.4.2-beta]
openfl-native: [1.4.0]
openfl-samples: 2.2.0 [2.2.2]
openfl-tools: 1.0.3 [1.0.10]
openfl: 2.2.1 [2.2.2] 2.2.8

**Comment by jotson** [comment]
I tested openfl 2.2.3 and it gets worse:

/usr/lib/haxe/lib/flixel/git/flixel/util/FlxBitmapDataUtil.hx:201: characters 5-38 : haxe.Int32 should be Int
/usr/lib/haxe/lib/flixel/git/flixel/util/FlxBitmapDataUtil.hx:202: characters 5-38 : haxe.Int32 should be Int
/usr/lib/haxe/lib/flixel/git/flixel/util/FlxGradient.hx:76: characters 15-36 : haxe.Int32 should be Int
/usr/lib/haxe/lib/flixel/git/flixel/util/FlxGradient.hx:76: characters 15-36 : For function argument 'x'
/usr/lib/haxe/lib/flixel/git/flixel/util/FlxCollision.hx:231: characters 36-113 : haxe.Int32 should be Int
/usr/lib/haxe/lib/flixel/git/flixel/util/FlxCollision.hx:231: characters 36-113 : For function argument 'Value'
/usr/lib/haxe/lib/flixel/git/flixel/util/FlxColor.hx:19: lines 19-780 : You can only declare from/to with compatible types

And `lime test neko` just reports "Segmentation fault"

This might be the culprit (but I  don't know enough about what is actually going on here):
https://github.com/openfl/openfl/commit/4608d170826a2b2b79738014ca011a577dc3155e

**Comment by Gama11** [comment]
What's your Haxe version?

**Comment by jotson** [comment]
`$ haxe -v`
`Haxe Compiler 3.1.3 - (C)2005-2014 Haxe Foundation`

Problem was also occurring with 3.1.1.

**Comment by Gama11** [comment]
@Beeblerox removed the `to` / `from` [here](https://github.com/HaxeFlixel/flixel/commit/1228b806d43946fd2cda2fa1d141b5452b30e94b#diff-470fc8126cf26af3df38eaad8f77c5deR17) so I guess this is fixed.
