### ISSUE TITLE
Kill all tweens of

### ISSUE THREAD

**Issue by MSGhero** [HaxeFlixel/flixel#1458]
TweenLite has a static function like this, and it would be good to have to avoid null object refs when something gets destroyed during its tween.

My question is, since this only affects VarTweens but needs access to the Tween Manager's private list of tweens AND VarTween's private `object`, which one should be exposed? Should it be `FlxTween.killTweensOf(obj)` or should it go into `FlxDestroyUtil`?

**Comment by Tiago-Ling** [comment]
+ 1 for `FlxTween.killTweensOf(obj)`, imho much better than having to use `FlxDestroyUtil` to do that.

**Comment by Beeblerox** [comment]
Good idea! Will try to implement it in the next iteration of tween refactoring

**Comment by MSGhero** [comment]
I'm going to do something for this in my project right now, and I'll post it in case it gives you any ideas.

Going to include `addTweenOf(obj, tween)` to also be able to kill NumTweens and others whose target object is different, but whose `onUpdate`, `onComplete`, etc callbacks use `obj` in some way. I think there are no null object reference errors that can occur in this setup unless you forget to manually `addTweenOf`.

**Comment by MSGhero** [comment]
https://github.com/MSGhero/flixel/commit/831ca44b8129f15219c7456ae88fc4026137b0f1

@Tiago-Ling  What should happen when the tween completes normally and is removed from `_tweens`?

Should it be a `Map<Dynamic, Array<FlxTween>>` or an `Array<ObjTweenPair>`? Map is (theoretically) faster object lookup but slower tween lookup inside each array.

Should `VarTween` and `Motion` automatically add the object-tween pair, or should this be something the user manually does each time? They have to manually do this for `NumTween` and the rest no matter what.

**Comment by Tiago-Ling** [comment]
@MSGhero You mean when the tween completes and it is inside the Map<Dynamic, Array<FlxTween>>? I suppose there's no easy / fast way to remove it from there without checking inside - in this case using an Array<ObjTweenPair> would be better i think.

In any case we need to take care with the overhead this could add - adding these references automatically could eventually kill the performance, especially if for any completed tween we have to traverse a full tween array.

I'll analyze FlxTween more before suggesting anything.

**Comment by MSGhero** [comment]
The other way is to `Std.is` to see if it's a `VarTween` or `Motion`, cast, use its own object property to index into the Map, then splice it out of the Array.

**Comment by MSGhero** [comment]
Though `NumTween` is less clear what to do since there's no object you can use.

**Comment by MSGhero** [comment]
Ok: https://github.com/HaxeFlixel/flixel/compare/dev...MSGhero:dev

I changed it to be entirely manual, so you have to add and cancel the tweens yourself. I guess I should add a removeTween method for consistency?

**Comment by sruloart** [comment]
"removeTween"? do you mean "unregisterTween"? can't all of this be done with groups of tweens instead of going at it one at a time?

**Comment by MSGhero** [comment]
That's what I meant lol

You mean pass in an array of tweens rather than a single one? Yeah I guess.

**Comment by sruloart** [comment]
```haxe
FlxTween.hx:694: characters 17-52 : Abstract Map has no @:to function that accepts IMap<Dynamic, Array<flixel.tweens.FlxTween>>
```

**Comment by MSGhero** [comment]
Does this look good for users? I'll get the bugs out before pulling.

**Comment by sruloart** [comment]
Looks good to me. I wonder if we can use the _objMappings + `Array<FlxTween>` methods for a timeline of sorts, hmm...

**Comment by MSGhero** [comment]
TweenLite has TimelineLite. That could be the next refactor for flixel.

I hate creating new Maps because they require the type params and then they don't and I never remember.

**Comment by MSGhero** [comment]
I ended up giving each of my sprites a `TweenController` class. `sprite.destroy()` clears all tweens to avoid null obj ref errors, and `sprite.update()` updates the controller and checks for completed tweens to remove.

A lot easier to deal with that the pull request.

**Comment by Gama11** [comment]
Closing this since the corresponding PR (#1495) has been closed as well. #1087 already deals with the whole "tween manager in FlxBasic" thing.
