### ISSUE TITLE
Stop Animation on FlxSprite

### ISSUE THREAD

**Issue by ashes999** [HaxeFlixel/flixel#1459]
Hi,

I'm using [the animation tutorial starter code](http://haxeflixel.com/documentation/part-iv-sprites-and-animation/). With this, the player moves once you press and release a button. (NB: the linked sample has an older version of  `movement` than the documentation.)

I updated it so that the player stops moving if there are no buttons held down. But the animation keeps playing.

1) Is the right way to stop an animation this:
```
if (this.animation.curAnim != null) {
  this.animation.curAnim.curFrame = 0;
  this.animation.curAnim.stop();
}
```

2) If so, can we encapsulate this into a `stop()` method on `FlxAnimationController`? Doing this makes the `FlxSprite` class break encapsulation (digging into `this.animation.curAnim`).

**Comment by Beeblerox** [comment]
I've added `stop()` method in `FlxAnimationController` on the dev branch today. Thanks for the idea!
By the way, which version of flixel do you use?

**Comment by ashes999** [comment]
That was awfully quick. Thanks for that.

I use flixel `3.3.6`, which I think is still the latest production version.

Is there any rough timeline on when the next version is going out?

**Comment by Beeblerox** [comment]
i think it will be right after haxe 3.2 release, since it contains some breaking changes.

**Comment by ashes999** [comment]
Ok, thanks.
