### ISSUE TITLE
FlxScreenGrab ios/android

### ISSUE THREAD

**Issue by CherryAnt** [HaxeFlixel/flixel#1460]
If i set to capture all screen this works well on flash, but in ios/android it just capture a part of screen

**Comment by goshki** [comment]
What part of screen is captured (i.e. a quarter)? May it be a camera zoom issue?

**Comment by sruloart** [comment]
I don't think it's actually supported on non-blitting targets...

**Comment by CherryAnt** [comment]
yes its capture a quarter aprox.

**Comment by MSGhero** [comment]
Can you multiply the screen grab's width and height bounds by 2 to capture the full screen? It might be a zoom issue.

**Comment by CherryAnt** [comment]
it depends on mobile resolution, on each one will be a different zoom

**Comment by MSGhero** [comment]
But you should have access to that zoom, and you can multiply that value.

**Comment by goshki** [comment]
Btw. it's strange that you get a cropped image. In my Android/iOS game, [Saving Alley Cats!](http://j.mp/saving-alley-cats), I'm just calling

```
var screenshot:Bitmap = FlxScreenGrab.grab();
```

and I get a proper screenshot.

**Comment by Gama11** [comment]
Closing this since there's not really enough information here to debug this and it's technically the wrong repo (FlxScreenGrab is flixel-addons).
