### ISSUE TITLE
flash.display.BitmapData has no field dumpBits when running 'lime test mac'

### ISSUE THREAD

**Issue by tyleranton** [HaxeFlixel/flixel#1461]
I am running on OS X Yosemite 10.10.1.

I just setup haxe/haxeflixel/openfl. When I run `lime test mac` on a project I get this error:

`/usr/lib/haxe/lib/flixel/3,3,7/flixel/util/loaders/CachedGraphics.hx:77: characters 3-18 : flash.display.BitmapData has no field dumpBits`

**Comment by Gama11** [comment]
OpenFL 3+ uses the new lime backend ("next") which the haxelib release of flixel is not compatible with. You can instruct it to use lime legacy with:

`<set name="legacy" />`

in your Project.xml before including flixel.

I also just released 3.3.8 which does exactly that, so you should be fine after running `haxelib update flixel`.

**Comment by tyleranton** [comment]
Thanks!
