### ISSUE TITLE
Request: "Simple" Function that returns the first object in a group that overlaps

### ISSUE THREAD

**Issue by SeiferTim** [HaxeFlixel/flixel#1466]
Ideally, there should be a function that you call like this:

 getFirstOverlap(Object:FlxObject, Group:FlxObject):FlxObject

You pass it an object and it returns the first item in the group that overlaps that object, or null if there are none.

**Comment by winterismute** [comment]
I implemented it: https://github.com/HaxeFlixel/flixel/pull/1574
However, it seemed to me that having an Array instead of a Group would make this more intuitive since the "order" in a FlxGroup sometimes gets lost, but it is just my opinion.

**Comment by Gama11** [comment]
@winterismute Where does the order "get lost"? A `FlxGroup` isn't much more than a fancy array.

@SeiferTim What was your original use case for this? I'm not sure it's useful enough to include...

**Comment by SeiferTim** [comment]
@Gama11 Oh man, this was a while ago... I think it was just that I wanted some simple way to tell what object, if any, I was overlapping while within an `if` statement... something like:
```
if (something)
{
  var obj = group.firstCollision(player);
  if (obj != null)
  {
    // do something with obj
  }
}
```
I don't really remember the specifics...

**Comment by winterismute** [comment]
@Gama11 What I meant is that, if I remember correctly, a flxGroup does a sort of "compaction" on additions while an array does not.
So, if you have

```Haxe
var group = new FlxGroup();
var queryObject = new FlxSprite();
var obj1 = new FlxSprite()
var obj2 = new FlxSprite()
var obj3 = new FlxSprite() // OVERLAPS queryObject
group.add(obj1);
group.add(obj2);
group.add(obj3);
obj2 = null // Trigger GC

var obj4 = new FlxSprite() // OVERLAPS queryObject
group.add(obj4); // Takes the null place that was of object2

var obj = group.firstCollision(queryObject); // returns obj4, user might have expected obj3 since it was added BEFORE object4
```
But maybe it is just a detail.

**Comment by Gama11** [comment]
I'd rather not include this in `FlxG` for now, that class is already big enough...

Tim's example there suggests he wanted to have this in `FlxGroup`. With the implementation in #1574, that would mean having a function in `FlxGroup` depend on `FlxG.overlap()`, which doesn't really feel right either.
