### ISSUE TITLE
Can't run in Linux

### ISSUE THREAD

**Issue by MintPaw** [HaxeFlixel/flixel#1467]
Running a project build with "openfl build linux -debug" will cause a segmentation fault when initiating a new FlxGame, I've tried with a variety of version of Lime, Openfl, and HaxeFlixel. Everything fails for one reason or another.

The error when using:
flixel: [3.3.8]
hxcpp: [3.2.37]
lime: [2.3.1]
openfl: [3.0.1]

Is:
`Called from openfl._legacy.utils.ByteArray::__init__ openfl/_legacy/utils/ByteArray.hx line 759
Error : Null Function Pointer`

It's likely this is related to this recent issue: https://github.com/openfl/openfl/issues/545
Although I can't pin point what exactly is wrong.

**Comment by Gama11** [comment]
Does this happen with all Flixel projects? Were you able to reproduce this with pure OpenFL (openfl-samples, -Dlegacy might be required to have the same conditions that flixel has)?

**Comment by Gama11** [comment]
Also, what Haxe version?

**Comment by MintPaw** [comment]
Yes, it happens in any initiation of FlxGame
And I've tried haxe 3.1.3 and 3.2.0-rc.1 with the same effect.

**Comment by jgranick** [comment]
Does this fix it?

https://github.com/openfl/openfl/commit/5d4fa685e330b22c273ab1d1acafd0304de605fb

**Comment by MintPaw** [comment]
No it doesn't I made that change after updating to:
flixel: git [dev:/usr/lib/haxe/lib/flixel/git]
hxcpp: [3.2.81]
lime: [2.3.1]
openfl: [3.0.2]

And it doesn't seem to change anything.

**Comment by Gama11** [comment]
I think openfl 3.0.2 needs lime 2.3.2.

**Comment by MintPaw** [comment]
The Linux version of haxelib is pretty broken, I got the current git version of lime (eb2b293) installed. But when compiling I get:
>"/usr/lib/haxe/lib/lime/git/legacy/ndll/Linux64/lime-legacy.ndll" does not exist

**Comment by jgranick** [comment]
@MintPaw If you are using a GIT version of Lime, make certain that you clone the submodules, then `lime rebuild linux` and `lime rebuild linux -Dlegacy`

**Comment by MintPaw** [comment]
When using the first rebuild command I get:
`
Error: In file included from /usr/include/stdint.h:25:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/4.8/include/stdint.h:9,
                 from /usr/lib/haxe/lib/hxcpp/3,2,81/include/hx/OS.h:61,
                 from /usr/lib/haxe/lib/hxcpp/3,2,81/include/hx/CFFI.h:4,
                 from ./src/ExternalInterface.cpp:10:
/usr/include/features.h:374:25: fatal error: sys/cdefs.h: No such file or directory
 #  include <sys/cdefs.h>
                         ^
compilation terminated.
`
This was also tested on multiple machines. Although on a 32bit machine the error is can't include lib/curl/files.xml

I thought Linux was a supported platform, hardly anything seems to work. Is this just me? Or does no one test the Linux releases?

**Comment by jgranick** [comment]
That's strange that stdint.h wouldn't work properly. Do you have `gcc-multilib` and `g++-multilib` installed?

**Comment by jgranick** [comment]
As I said, you also need to clone all submodules, if it cannot find lib/curl/files.xml, you probably need to `git submodule init && git submodule update` in the checkout folder

**Comment by MintPaw** [comment]
Ah, ok, after building lime successfully I sadly get the same ByteArray error both with and without the legacy.ndll on both 32 and 64 bit.

**Comment by jgranick** [comment]
Does this occur with a simple OpenFL sample?

**Comment by MintPaw** [comment]
No, It's just when creating a new FlxGame.
Although now when running DisplayABitmap I get a Segmentation fault with no other error information.

I guess we should first better define what exactly I should be testing, what should be at what version? Should I just be using the latest git of everything?

**Comment by jgranick** [comment]
Try the latest GIT of both OpenFL and Lime. See if you can run something like DisplayingABitmap. If that doesn't work, let me know what happens

**Comment by MintPaw** [comment]
I still get the fault. http://i.imgur.com/IHhDiKy.png

**Comment by jgranick** [comment]
Does `openfl test` work?

**Comment by MintPaw** [comment]
```openfl test linux``` Works, I assume this uses Neko, which also works.

**Comment by jgranick** [comment]
I'm guessing this has to do with the current working directory, `openfl test` changes the working directory to the directory with your executable.

Now that I understand what's going on, I should be able to make a fix soon

**Comment by MintPaw** [comment]
Oh... You have to be in the same working directory... https://i.imgur.com/KlsCvRG.png

There should really be a better error than that.

**Comment by MintPaw** [comment]
I'm closing the issue here and I'll open one on the openfl tracker in a while, or would it be haxe tracker?

**Comment by jgranick** [comment]
It's a hack, but this is what is in place for -Dlegacy to try and resolve this issue:

https://github.com/openfl/openfl/blob/5d4fa685e330b22c273ab1d1acafd0304de605fb/templates/legacy/haxe/ApplicationMain.hx#L75-L83

We could do something similar (`#if !static_link`) using "lime.ndll" instead of "lime-legacy.ndll"
