### ISSUE TITLE
Changing FlxTileblock's width does not work.

### ISSUE THREAD

**Issue by diegomachado** [HaxeFlixel/flixel#1468]
Hey guys.

I don't know if this is fixed on the dev branch but changing a FlxTileblock's width after it has been created is not working, but changing it's height works fine.

I got this while trying to make a 16x8 tileable spike. I rotated it to put it on the walls and tried to change width and height to change it's collision box.

**Comment by Gama11** [comment]
Can't reproduce this on 3.3.8. Could you provide a reproducible example?

Keep in mind that neither `width` nor `height` affect the graphic's dimensions, only the hitbox.

**Comment by diegomachado** [comment]
I've just updated to 3.3.8. I'll try to reproduce it and reply here as soon as I can.

**Comment by diegomachado** [comment]
I'm sorry for the late response, but this works fine in 3.3.8. Thanks @Gama11 !
