### ISSUE TITLE
Inaccurate FlxSpriteUtil.drawRect() boundary

### ISSUE THREAD

**Issue by Aleph0Null** [HaxeFlixel/flixel#1470]
If you drawRect like this:

```haxe
var boundary = new FlxSprite();
boundary.makeGraphic(width, height, backgroundColor);
var lineStyle:LineStyle = { thickness: boundaryThickness, color: boundaryColor };
var fillStyle:FillStyle = { hasFill: true, color: fillColor };
FlxSpriteUtil.drawRect(boundary, 0, 0, width, height, boundaryColor, lineStyle, fillStyle);
add(boundary);
```

the left and bottom sides of the rectangle are 1 pixel narrower than they should be, and the right side is missing. I think the problem stems from how flash.display.Sprite (which FlxSpriteUtil uses) does the drawing.

This is almost accurate:

```haxe
FlxSpriteUtil.drawRect(boundary, 1, 0, width - boundaryThickness - 1, height - 1, boundaryColor, lineStyle, fillStyle);
```

but there's color blending at the border between the boundary and fill.

I haven't checked, but all this may apply to the other drawing functions like drawRoundRect also.

**Comment by MSGhero** [comment]
You have to make the original sprite bigger to account for the border that you're adding to its dimensions.

**Comment by Aleph0Null** [comment]
Thanks. The 'error dimensions' I gave in the original post were off; didn't realize I had a mismatch between the game dimensions and window dimensions when I did the rendering.

Nonetheless, the rendering still isn't accurate. The attached image was rendered with the above code, with boundaryThickness = 3 and all other Float params (width, height, X, Y) integer values. The top, bottom and right sides are indeed 3 pixels thick, but the left side is 4 pixels thick, and there's blending between the boundary and fill. It seems like those 3 pixels are being rendered at 'non-integer coords' across 4 pixels. If you set boundaryThickness = 4, then the left size is 4 pixels thick and solid, but top, bottom and right are rendered across 5 pixels. However the rendering is supposed to be done, the result should be symmetrical.

![drawrect](https://cloud.githubusercontent.com/assets/11797752/7107633/bf9845d4-e19d-11e4-8854-fc39f5ee3558.png)

**Comment by sruloart** [comment]
Just try tweaking the pixelperfect position/render, it looks like the natural results of a sub-pixels rounding.

**Comment by Gama11** [comment]
This works fine for me:

```haxe
package;

import flixel.FlxSprite;
import flixel.FlxState;
import flixel.util.FlxColor;
using flixel.util.FlxSpriteUtil;

class PlayState extends FlxState
{
	override public function create():Void
	{
		bgColor = FlxColor.WHITE;
		
		var width = 100;
		var height = 20;
		var backgroundColor = FlxColor.RED;
		var boundaryThickness = 3;
		var boundaryColor = FlxColor.BLACK;
		var fillColor = FlxColor.YELLOW;
		
		var boundary = new FlxSprite(100, 100);
		boundary.makeGraphic(width + boundaryThickness, height + boundaryThickness, backgroundColor);
		var lineStyle:LineStyle = { thickness: boundaryThickness, color: boundaryColor };
		boundary.drawRect(boundaryThickness / 2, boundaryThickness / 2, width, height, fillColor, lineStyle);
		add(boundary);
	}
}
```

![image](https://cloud.githubusercontent.com/assets/2620907/8273274/70554774-1866-11e5-814a-d796ad10a62e.png)


You need to account for `boundaryThickness` for `x`, `y`, `width` and `height`.
