### ISSUE TITLE
OuyaSDK.IsOuya Wrapper

### ISSUE THREAD

**Issue by ashes999** [HaxeFlixel/flixel#1475]
Hi,

I mistakenly (?) opened an [OpenFL discussion here](http://community.openfl.org/t/calling-into-ouyasdk-isouya/1114) about their "OUYA integration." If I'm not mistaken, integration is at the HaxeFlixel level, isn't it? (Although I can't see where you keep the OUYA SDK JAR file.)

If I'm correct, is it possible we could get a wrapper around the `OuyaSDK.IsOuya` method? This allows us to distinguish OUYA from (vanilla? non-OUYA) Android.

**Comment by ashes999** [comment]
(25 days later)

Any comments @sruloart or @Beeblerox ?

**Comment by sruloart** [comment]
Ouya is pretty much a dead parrot, recent news are alarming at best (http://ouyaforum.com/showthread.php?16141-**-Ouya-Looking-For-Buyer-Quickly-**/). 

There was a relatively successful HaxeFlixel game for Ouya some time ago (more than a year, now it's on Steam naturally): http://www.lazaknitez.com/ the devs even released a controllers class over the forum back then if you're that interested...

**Comment by ashes999** [comment]
So you're yanking support for OUYA through HaxeFlixel as of now? @sruloart

**Comment by sruloart** [comment]
There wasn't any real support to begin with :) flixel doesn't support any native native-extentions...

**Comment by ashes999** [comment]
I'm not sure I understand. I can create a Flixel game today, add controller support, and deploy it to my OUYA with no problem. I think my question is:

1) Is that workflow/support going away (either being yanked out, or dying out slowly)?
2) If no, is there any reason not to extend it with something like this request (OUYA-specific detection)?

**Comment by MSGhero** [comment]
There's nothing in flixel that *does* anything Ouya related. I think "Ouya support" is really "export to android oh hey it works on Ouya too, neat." The sdk stuff would be in lime or openfl if it exists at all.

But inside `lime.ui.Gamepad`, there's the [name](https://github.com/openfl/lime/blob/master/lime/ui/Gamepad.hx#L15) property. Does tracing that give you something helpful?

**Comment by Gama11** [comment]
That contains the event name, not the gamepad name I think - afaik, there's no way to obtain that atm.

**Comment by sruloart** [comment]
This is the class I was talking about BTW: https://gist.github.com/joonjoonjoon/f105e64029d32de76488

**Comment by MSGhero** [comment]
@Gama11 hot off the presses: https://github.com/openfl/openfl/commit/92647f46e908aa1945b52b58daf634c59a29b18f

**Comment by Gama11** [comment]
Like @sruloart and @MSGhero said, OUYA support doesn't happen at HaxeFlixel level.
