### ISSUE TITLE
Fix the docs

### ISSUE THREAD

**Issue by MintPaw** [HaxeFlixel/flixel#1480]
I don't think they're currently up to day with the master branch, more less the dev branch.

They're even incorrect within themselves.
https://i.imgur.com/I6rC6yr.png

Aren't these auto-generated?

**Comment by Gama11** [comment]
Guess [nobody removed the `Color` and `Thickness` parameter docs](https://github.com/HaxeFlixel/flixel/blob/master/flixel/util/FlxSpriteUtil.hx#L242-L243) when they were moved into `lineStyle` (they've been removed on dev though).

The docs should be up to date with master, do you have any example where they're not?

**Comment by MintPaw** [comment]
Mm, I thought it was inconsistent, but it's just that master is so far behind. I can't even remember the last time I'm imported FlxPoint from util rather than math.
