### ISSUE TITLE
Android: immersive mode not working properly

### ISSUE THREAD

**Issue by JunoNgx** [HaxeFlixel/flixel#1484]
In OpenFL, Android's [Immersive Mode](https://developer.android.com/training/system-ui/immersive.html) is enabled by adding `<android target-sdk-version="19" />` (19, aka 4.4 KitKat, or higher is required) to `Project.xml`.

While the feature technically works and navigation bar is hidden, the game's content is not properly displayed:

![flixelbugimmersive2](https://cloud.githubusercontent.com/assets/5671813/7377152/2db257f0-ee17-11e4-8648-8fcbeb18bcd9.png)

Note the blackbar on two sides of the screen, whereby the content should have fully covered.

The game's configuration is confirmed to be fit to the device's screen. The size of 1280 x 720 was set in `Main.hx` (The line `<window if="mobile" orientation="landscape" fullscreen="true" width="0" height="0" />` was kept without modification in `Project.xml`). This has been tested across multiple devices whose display resolutions were all 1080p.

This is unlikely to be OpenFL's bug, since the identical method is confirmed to work on OpenFL-based HaxePunk without any issue.
##

**Comment by Gama11** [comment]
Have you tried using `StageSizeScaleMode`?

**Comment by sruloart** [comment]
Probably something to do with choosing the correct scaleMode, like @Gama11 said, but this thread could be related: http://community.openfl.org/t/android-screensize/1279

Also, @Gama11 did you know that ```Waiting for ADDED_TO_STAGE is entirely unnecessary nowadays. The Main class will already be onstage by the time you add that event listener, thanks to DocumentClass``` - http://community.openfl.org/t/android-screensize/1279/7 ?! :0

**Comment by MSGhero** [comment]
@sruloart 99% of the time, it's not necessary in regular flash, but that 1% (that I don't remember), it is needed. Some weird edge case where the stage doesn't exist. How can you be sure the stage exists in DocClass?

**Comment by JunoNgx** [comment]
Managed to fix this as instructed, by adding ```FlxG.scaleMode = new StageSizeScaleMode();``` to the running ```FlxState```. Thanks.

However, shouldn't the engine be already doing this by default?

**Comment by Gama11** [comment]
Not sure, I think the current default (`ResizeScaleMode`) makes the most sense (especially on non-mobile platforms), as it maintains the aspect ratio. It works "out of the box", as opposed to `StageSizeScaleMode`, where you're required to handle positioning of objects / UI elements in an aspect-ratio-indepedant way.

**Comment by sruloart** [comment]
@JunoNgx there are more targets than just mobile, sometimes you want a different behavior, but you have a point!
@MSGhero Keep in mind I'm just quoting player_03, it just seems weird to me that Flixel's Main's main part is unnecessary...

**Comment by Gama11** [comment]
@sruloart Not sure about that. Would be nice to have a simpler `Main.hx`, but then again, better to be safe than sorry?

Guess we can close this as @sruloart opened a separate issue for discussion about the default scalemode.

**Comment by sruloart** [comment]
@Gama11 safe is best, but it's good to keep that in mind...

**Comment by GimmickyApps** [comment]
Why tag it OpenFL when it appears to not be OpenFL's bug according to the OP at https://github.com/HaxeFlixel/flixel/issues/1484#issue-71667341 ?  Or is that not what the tag means exactly?  ;-)

**Comment by GimmickyApps** [comment]
Further to the original topic, would it be worth integrating https://gist.github.com/leoncvlt/f398e629ec1ca5bad9b0 into HaxeFlixel, and providing an option in the API?  Then anyone using immersive doesn't have to remember to modify their templates whenever there's a library update.

**Comment by Gama11** [comment]
@GimmickyApps For me, immersive mode works without any template modifications.

**Comment by Gama11** [comment]
This appears to be working correctly now with OpenFL 8. 😄
