### ISSUE TITLE
Consider targets flags for setting the default ScaleMode.

### ISSUE THREAD

**Issue by sruloart** [HaxeFlixel/flixel#1486]
We don't have to [default to ```RatioScaleMode```](https://github.com/HaxeFlixel/flixel/blob/1228b806d43946fd2cda2fa1d141b5452b30e94b/flixel/FlxG.hx#L137-L140) with every target - sometimes a different default may suit a target better: https://github.com/HaxeFlixel/flixel/issues/1484

**Comment by Gama11** [comment]
Changing the default to `StageSizeScaleMode` on android doesn't really help with #1484 (at least not in all cases, Mode for example).

**Comment by sruloart** [comment]
Yeah, I didn't find any real world application for this yet...
