### ISSUE TITLE
updateHitbox() not updating hitBox after changing sprite's scale

### ISSUE THREAD

**Issue by diegomachado** [HaxeFlixel/flixel#1487]
Hey guys.

I was trying to make a squish effect and bumped into this. After changing sprite's scale, updateHitBox() don't work. I've tried with setGraphicSize() too, same issue, so it's probably an updateHitBox() issue. 

I've made a gist to show it:
https://gist.github.com/diegomachado/df3ea349df16bb88c8bb

Am I'm missing something or it's really a bug?

Thanks!

**Comment by Gama11** [comment]
`player.updateHitbox;` is not a function call - you're missing the `()`.

**Comment by diegomachado** [comment]
Haxe didn't throw any errors and I totally missed that...thanks @Gama11 and I'm sorry. :disappointed_relieved:
