### ISSUE TITLE
Consider making Stats.hx available to non-debug compilation.  

### ISSUE THREAD

**Issue by sruloart** [HaxeFlixel/flixel#1489]
There's no reason why we cannot enjoy a full stats window also in release mode if so we choose. OpenFL FPS is pretty minimal out-of-the-box and the alternative is to call another library or to write a new class altogether...It's very useful for a fast non-debug iteration...

**Comment by MSGhero** [comment]
You can't do something like -macro include the stats class? (I don't know how macros work lol)

**Comment by sruloart** [comment]
- macro give me money ;-)

**Comment by sruloart** [comment]
In second thought, I think a debug "line" is a better solution than the current debug windows.

**Comment by Gama11** [comment]
A debug line?

**Comment by sruloart** [comment]
At the moment I'm just talking about a line of text with basic figures, like FPS/CPU/GPU/Memory/Build, nothing fancy.
