### ISSUE TITLE
BitmapData.colorTransform() acts simultaneously on different FlxSprites with the same BitmapData pixels 

### ISSUE THREAD

**Issue by Aleph0Null** [HaxeFlixel/flixel#1490]
This is for windows and neko (BitmapData.colorTransform() doesn't work on html5 and flash, and I can't test other platforms). Consider the following code:

		var image1 = new FlxSprite(100, 100);
		image1.makeGraphic(64, 32, FlxColor.BLUE);
		add(image1);
		
		var image2 = new FlxSprite(300, 100);
		image2.makeGraphic(64, 32, FlxColor.BLUE);
		add(image2);
				
		var changedRect = new Rectangle(32, 0, 32, 32);
		var toTransparent = new ColorTransform(0, 0, 0, 0, 0, 0, 0, -0xFF);
		image1.pixels.colorTransform(changedRect, toTransparent);

Only image1 has pixels.colorTransform() called, but the transformation is applied to both image1 and image2. If you change image2's color to something else, or load different graphics onto both of them, then the transformation is applied to only image1.

If you add
		
		FlxG.debugger.visible = true;
		FlxG.log.add(image1.pixels == image2.pixels);

then the debugger log displays "true". The Haxe == operator on objects only returns true when both  references are identical (the values of the member variables are irrelevant). So what seems to be happening is HaxeFlixel (or one of the libraries it uses?) is copying a reference when identical BitmapData is generated, instead of creating a new instance of BitmapData with the same pixels.

**Comment by MSGhero** [comment]
The next parameter in makeGraphic is Unique which is false by default. You'll have to set that to true so they don't share bmds.

**Comment by Aleph0Null** [comment]
Thanks, I hadn't paid attention to that parameter.
