### ISSUE TITLE
Smoothing HaxeFlixel out

### ISSUE THREAD

**Issue by sruloart** [HaxeFlixel/flixel#1496]
- **The problem**: HaxeFlixel's fixed-step games aren't as smooth as they should be (aka, stuttering/spikes now and then, not to be confused with sub-pixel induced jitter). 
- **The cause**: a small Asynchrony between the logic and the rendering in the original game-loop (a lot of other related factors, but this is the main culprit). 
- **The solution**: interpolate rendering positions using some kind of a lag factor (examples: [flixel like but unsuccessful](http://stackoverflow.com/questions/23401922/actionscript-3-flash-basic-game-loop-stuttering-problems), [lag offset](http://www.html5gamedevs.com/topic/8716-game-loop-fixed-timestep-variable-rendering/), [in interpolation](http://www.openfl.org/archive/community/general-discussion/drawtilestilelayer-dilemma/)).
- **Detailed explanation**: you can read all about it right here: http://gameprogrammingpatterns.com/game-loop.html#stuck-in-the-middle. The lucky thing is that HaxeFlixel uses pretty much the same loop as the article with minor changes ("lag" = "accumulator", "MS_PER_UPDATE = stepMS", "update()"="step()", etc.), so you don't have to read the entire article (but it surely helps to understand what's going on). 
- **Implementation**: We already have the lag offset value (explained in the article as lag/MS_PER_UPDATE, so in our case accumulator/stepMS), so the main problem would be implementing the suitable `render(accumulator/stepMS);` HaxeFlixel's equivalents.
##

**Comment by Tiago-Ling** [comment]
The main difficulty i see is in testing the possible solution. I have been [experimenting](https://github.com/Tiago-Ling/JitterDemo) with this issue in various Haxe frameworks and it is hard "see" the problem - a lot of people attribute this to monitor refresh rates and vsync which is/can be one of the causes.

Other thing i noticed is that the same effect appears at lower levels (OpenFL, Lime, possibly even SDL), so this might be not related to flixel itself. I would however definitely like to see this new implementation and help test it in any way i can. This problem has been "a thorn on my side for far too long" already :)

**Comment by sruloart** [comment]
@Tiago-Ling, 
- Detection is part of the problem, but it would be very noticeable.
- It's not caused by anything else. I can go into this with far greater detail later.
- Low level stuff is actually a lot more prone to this type of problem (logic/render mismatch) due to a crude game-loop implementation. HaxeFlixel's game-loop is far superior, but as I said, it's not perfect.

**Comment by larsiusprime** [comment]
Would love to help test this!

**Comment by Gama11** [comment]
Very interesting article you linked there. And yeah, sounds pretty difficult to test properly...

Would also be a pretty big breaking change (pretty much the same as adding elapsed to `update()` functions, except with `draw()` this time around).

**Comment by MSGhero** [comment]
I skipped this chapter since I thought flixel handled it all already! But are you sure this even happens? Is it a result of floating point precision (0.0166645 doesn't trigger an update and 0.0166672 triggers one with lag)?

**Comment by MSGhero** [comment]
@Gama11 most people don't override `draw()` so it'd be far less annoying for users than the `update()` refactor. For contributors though...

**Comment by larsiusprime** [comment]
@MSGhero that's a good point; I override update() all over the place, I'm not sure I override draw() even once.

**Comment by sruloart** [comment]
General plan: 
- FlxG: Add a FlxG.renderSync (Float) to serve as our interpolation factor.
- FlxGame: if (fixedTimeStep)... renderSync = accumulator/_stepMS (0. to 0.99...), else renderSync = 1. 
- FlxGame: store previous position/scale and rotation after before the next update (matrices and all of that, haven't fully figured this out yet, but I think position is not enough).
- FlxObject, FlxSprite, FlxTilemapBuffer, FlxCamera and wherever that is relevant - add this kind of interpolation: ```current * renderSync + previous * (1 - renderSync) // previous = 0 if it's not a fixedTimeStep``` along side the anti-jitter rounding of pixelPerfectRender (haven't fully figured this either).

**Comment by Gama11** [comment]
@sruloart The article you linked suggests extrapolation, so why are you going with interpolation?

**Comment by sruloart** [comment]
Because I've read many more articles :)

**Comment by Tiago-Ling** [comment]
I'd love to read more about it - also seeing a demo showing the problem in a noticeable, "non-mistakeable" way. This would help a lot!

**Comment by sruloart** [comment]
@Tiago-Ling there are two more links in the end of the article (well, book chapter to be exact). If you want more I can probably track more than a few (including posts, answers and alike). Again, with so many variables the only real proof would be a before and after demo.

**Comment by Tiago-Ling** [comment]
@sruloart Cool, i'm gonna read them - just asking to see if there was another source material you read.

About the demo, that's exactly what i meant: it would be useful to have a "before demo" to use as a test bed for solutions.

**Comment by MSGhero** [comment]
@sruloart in the before demo, you'd have to hardcode delta t's or at least manually set delta t every so often. Unless this problem happens consistently in a game for everyone, you'd have to force it to happen. I've noticed Flash tearing issues like always, but I don't believe I've ever noticed this issue.

**Comment by Gama11** [comment]
Is anything happening here?

**Comment by Gama11** [comment]
I guess that's a no.
