### ISSUE TITLE
Incorrect check in FlxTilemap.findPath

### ISSUE THREAD

**Issue by SwCosmos** [HaxeFlixel/flixel#1501]
On line 788 of FlxTilemap.hx, where findPath checks whether or not the current tile is accessible, the check confirms that `allowCollisions > 0`. If so, it returns null. However, 0 is NONE, and values greater than 0 are the "accessible" values. A correct check would be `allowCollisions == FlxObject.ALL`, going off the docs for that function.

**To reproduce:** Create a Tilemap and call findPath, with either the source or the destination being a tile set to, say, FlxObject.ALL for collisions.
**Targets:** Tested on native Windows. I'm not sure about the others (my code has various unrelated problems with them, so I can't test it), but I doubt it would be different - a platform choice shouldn't change something as simple as that without conditionals.
**Versions:** flixel: 3.2.2 3.3.5 [3.3.8] lime-tools: 1.2.9 1.3.1 [1.5.7] lime: 0.9.4 0.9.5 0.9.6 1.0.1 2.0.0-alpha.5 [2.4.1] openfl-bitfive: [3.0.0] openfl-html5-dom: 1.2.0 1.2.1 [1.2.2] openfl-html5: [1.4.2-beta] openfl-native: 1.2.2 1.3.0 [1.4.0] openfl: 1.2.2 1.3.0 2.0.1 2.1.3 [3.0.6]

**Comment by MSGhero** [comment]
The value of `allowCollisions` is the direction(s) that the FlxObject is colliding with or, in tilemap's case, the values that are not pathable. https://github.com/HaxeFlixel/flixel/blob/dev/flixel/FlxObject.hx#L442

**Comment by Gama11** [comment]
It's interesting though that it the start and end tiles need to be clear. You'd think it'd be enough that they're traversable in the path's direction...

**Comment by SwCosmos** [comment]
@MSGhero That are not pathable. That are not pathable. That solves it for me then. I just misread the docs, that's all. Thanks.
