### ISSUE TITLE
Update Xbox360ID.hx for linux and mac

### ISSUE THREAD

**Issue by Gama11** [HaxeFlixel/flixel#1503]

**Comment by MSGhero** [comment]
And an updated demo.

**Comment by Gama11** [comment]
What's not updated about the demo?

**Comment by MSGhero** [comment]
I didn't look at all the changes, but are there any new features or changes or anything that should be showcased in the demo?

**Comment by larsiusprime** [comment]
He's write, we could add justPressed/justReleased visual notifications to all the inputs, for instance. Like a glowing halo that appears and quickly fades besides just notifying pressed/notpressed
