### ISSUE TITLE
Just calling the FlxTileMap constructor without loading a Tilesheet causes an "Invalid Bitmap Error"

### ISSUE THREAD

**Issue by sano98** [HaxeFlixel/flixel#1504]
It seems that with the current implementation on **dev**, with a flash target, you cannot simply create an empty ```FlxTilemap``` without giving it a tile sheet and a list of numbers via one of the new loadmap functions (e.g. loadMapFromCSV ). Simply calling the constructor results in an

      ArgumentError: Error #2015: Invalid BitmapData.

I don't think this has always been the case, and I guess it shouldn't be that way, either?
It can be reproduced by simply adding:

     var testTileMap:FlxTilemap = new FlxTilemap();

somewhere without calling one of the load functions. To my understanding, a constructor should safely create an instance without any further requirements. Sure, I would never see the Tilemap without loading the mapdata and adding it to the scene, but at least it shouldn't crash?

**Comment by Gama11** [comment]
The same crash happens with the lastest release actually, but yeah, I agree, this seems unecessary / counter-intuitive.
