### ISSUE TITLE
FlxGamepad: retroactively use globalDeadZone if it's set

### ISSUE THREAD

**Issue by Gama11** [HaxeFlixel/flixel#1509]
It seems counter-intuitive that gamepads ignore the global deadzone if they've already been created (when they're connected). Instead there should be get_deadZone that returns globalDeadZone if it's not null (requires #1508).

**Comment by larsiusprime** [comment]
yeah, it seems like if you set a global deadzone after gamepads have been created you'd want that to immediately propagate.

Related: separate deadzones for triggers vs. analog sticks? Separate deadzones for each stick? Too much?

**Comment by Gama11** [comment]
Actually, it seems like this already happens via `set_globalDeadZone()`.

Not sure about individual deadzones... It might be overkill?

**Comment by larsiusprime** [comment]
I think as far as individual deadzones go, we should probably wait for user demand before implementing any more complexity like that. Probably at max we'd only need separate deadzones for different types of things -- like triggers vs analog sticks. Individual deadzones for each stick seems a bit too much especially if no one's asked for it.

**Comment by Gama11** [comment]
Thinking about this again - `set_globalDeadZone()` works, but it overwrites the value in `FlxGamepad`.

So in this scenario, the current approach leads to a deadzone of 0.7 in `gamepad`, my approach will lead to the the gamepad using the original 0.3 value.

```haxe
gamepad.deadZone = 0.3;
FlxG.gamepads.deadZone = 0.7;
FlxG.gameapds.deadZone = null;
```

Which one is preferable?

**Comment by larsiusprime** [comment]
Here's the scenario I prefer:

```Haxe
gamepad.deadZone = 0.3;
FlxG.gamepads.deadZone = 0.7;
FlxG.gameapds.deadZone = null;
//gamepad.deadZone is now effectively equal to 0.3
```

```Haxe
gamepad.deadZone = 0.3;
FlxG.gamepads.deadZone = 0.7;
//gamepad.deadZone is now effectively equal to 0.7
```

**Comment by Gama11** [comment]
Yeah, that one seems the most intuitive to me as well.
