### ISSUE TITLE
FlxG.sound.music is null

### ISSUE THREAD

**Issue by as3boyan** [HaxeFlixel/flixel#1510]
I am using

`!FlxG.sound.music.playing`

to check if music is playing

when I run this, music is not playing and it

throws null pointer exception, basically `music` is null, but this

`!FlxG.sound.music.playing`

used to work for me in previous versions of lime.

Currently I have installed latest lime 2.4.1

Is that an API change or something?

**Comment by Gama11** [comment]
`music` will be null before a `playMusic()` call - that's been the case for as long as I can think. The usual way to check if the muisc is playing is checking for null. Not sure if that's the best behavior.

I very much doubt that a change in Lime could affect this behavior.
