### ISSUE TITLE
FlxCamera#follow() defaults to Lerp == 1

### ISSUE THREAD

**Issue by Gama11** [HaxeFlixel/flixel#1515]
Instead, it should be `60 / FlxG.updateFramerate` / the same value as `followLerp` is initialized with.

Also, I think the docs on the range of `followLerp` values is wrong.

**Comment by MSGhero** [comment]
Back then, you said we should revisit followLerp and its consistency at different frame rates. Are you satisfied with it besides this issue?

**Comment by Gama11** [comment]
Well, I haven't noticed any issues with it, but that doesn't say much as I've not tested cameras explicitly and certainly not at framerates different from 60...

The issue was that it's not framerate-independant, right?

**Comment by MSGhero** [comment]
Yeah, `60 / updateFR` is what makes it frame rate "mostly independent." The most stable results will be at 60 fps, but I've never tested multiple ones side by side.
