### ISSUE TITLE
"FLX_NO_GAMEPAD" is broken for Flash 11.2 in debug mode

### ISSUE THREAD

**Issue by sruloart** [HaxeFlixel/flixel#1517]
Set: dev branch, Flash target, Debug mode, SWF_VERSION to 11.2 (or less I assume). Result:

`c:/user/HaxeToolkit/haxe/lib/flixel/git/flixel/input/gamepad/FlxGamepadManager.hx:345: characters 33-60 : Accessing this field requires flash version 11.8 (use -swf-version 11.8)`

And more similar errors.

**Comment by Gama11** [comment]
I can't reproduce that, I get the expected:

```
C:/HaxeToolkit/haxe/lib/flixel/git/flixel/system/macros/FlxDefines.hx:188: characters 4-23 :
Gamepad input is only supported in Flash Player version 11.8 or higher.
Define FLX_NO_GAMEPAD to disable this feature or add <set name="SWF_VERSION"
value="11.8" /> to your Project.xml.
```

error from `FlxDefines`.

I did find an error related to `flash.system.Capabilities` in `FlxGamepad` though.

More details please?

**Comment by sruloart** [comment]
Hmm, it only happens with the ```<haxedef name="next"/>``` flag.

**Comment by Gama11** [comment]
Ah, that would explain it. We don't test next on Travis either...

**Comment by Gama11** [comment]
...though I still can't seem to reproduce it. :P What Openfl and Lime versions?

**Comment by sruloart** [comment]
Hmm*Hmm. I always use the latest lime/openfl releases (i.e 2.4.3/3.0.8). FD 5. Haxe 3.2.0. I can't think of anything else. The error:
>c:/user/HaxeToolkit/haxe/lib/flixel/git/flixel/input/gamepad/FlxGamepadManager.hx:345: characters 33-60 : Accessing this field requires flash version 11.8 (use -swf-version 11.8)

suggests maybe something to do with haxe? I mean, something must give that error message...

I also get this openfl error when I try to target neko/windows with the next flag (both on release&debug) but that's unrelated I think: 
>c:/user/HaxeToolkit/haxe/lib/openfl/3,0,8/openfl/ui/GameInputDevice.hx:4: characters 7-22 : Type not found : lime.ui.Gamepad

**Comment by Tiago-Ling** [comment]
Do you have <set name="SWF_VERSION" value="11.8" /> on your project.xml?

**Comment by Gama11** [comment]
@Tiago-Ling No he doesn't, that's the entire point of this discussion. ;)

**Comment by Tiago-Ling** [comment]
Sorry, just saw the first comment on the issue here. My bad! :)

**Comment by Tiago-Ling** [comment]
By the way, isn't the gamepad support added for Flash Player on versions
11.8 and up only?

https://forums.adobe.com/thread/1385364

I don't think it'll work with 11.2 (?)

**Comment by Gama11** [comment]
@sruloart That error message comes from the `@:require(flash11_8)` in the `GameInput.hx` extern that is included in the Haxe std lib.

@Tiago-Ling Yes, but he should be getting Flixel's error message instead.

Can anyone else reproduce this?

**Comment by Gama11** [comment]
Nevermind, I can repdroduce it now.

**Comment by MSGhero** [comment]
@Tiago-Ling I believe Gamepad.isSupported existed in 11.0 or 11.2, obviously defaulting to false until 11.7 or 8.

**Comment by Tiago-Ling** [comment]
@MSGhero The Gamepad class is gone from Adobe AS3 docs, i tried to look for it but couldn't find anything. There's only GameInput, which started in Air 3.7

**Comment by MSGhero** [comment]
@Tiago-Ling someone on NG a while ago said it was removed around fp17 (swf version 28). I only compile to 11.8 so it may be worth seeing if that's true and if it breaks flixel.

I would but I don't have internet right now to update my libs.

**Comment by sruloart** [comment]
@Gama11 can confirm the issue is gone :)
@Tiago-Ling and @MSGhero gamepad support has been introduced starting with 11.8: 
http://www.adobe.com/devnet/flashplatform/whitepapers/roadmap.html
