### ISSUE TITLE
ColorTransform on FlxSprite  cpp/neko doesn't work 

### ISSUE THREAD

**Issue by OpmSaitama** [HaxeFlixel/flixel#1519]
I tried to flash enemy sprite white when it gets hit but the color transform only colors things into black and shades of black. 

Here is a quote from another user : 

It appears that the color offsets in the setColorTransform function of FlxSprite are not being used. I tested on several sprites (neko target) and could get sprites to change color using the weights but not with the offsets.

**Comment by Gama11** [comment]
Duplicate of #1383.
