### ISSUE TITLE
FlxTileMap behaves differently Neko vs CPP

### ISSUE THREAD

**Issue by FryDay** [HaxeFlixel/flixel#1520]
In Neko, FlxTileMap behaves as expected.
![screen shot 2015-06-07 at 4 09 09 pm](https://cloud.githubusercontent.com/assets/754086/8026104/cd5f1a90-0d2f-11e5-95e8-af6c30efcd76.png)

In CPP, however, there is what appears to be a rending issue.
![screen shot 2015-06-07 at 4 09 48 pm](https://cloud.githubusercontent.com/assets/754086/8026111/e61e5e92-0d2f-11e5-8607-14f1b800a2ab.png)

You'll notice on the right side, there is extra tiles and some background showing.

**Comment by Gama11** [comment]
Code to reproduce?

Flixel version?

**Comment by FryDay** [comment]
This is the latest dev branch. I'll work on pulling some code out to reproduce.

**Comment by FryDay** [comment]
This CSV can be used to reproduce:
http://pastebin.com/raw.php?i=bUzjVjE6

`var wallsMap1:FlxTilemap = new FlxTilemap();

wallsMap1.loadMapFromCSV(theCSVfromPasteBin, "images/wall.png", Reg.WallSize, Reg.WallSize, AUTO);

wallsMap1.updateBuffers();`

The wall file I am using is https://drive.google.com/file/d/0ByA4i-641qG2ZkRaTV9YaDAxS3M/view?usp=sharing

Also to note, I have not tried this on anything other then OSX yet. I will try in Windows and Linux and report back.

**Comment by FryDay** [comment]
This is an issue on all platforms.

**Comment by leoncvlt** [comment]
I have got a similar issue that might be related to this, my FlxTileMap is incorrectly parsed from a TiledLayer when using CSV format - works fine with base64 and 1D arrays.

More infos in this forum post: http://haxeflixel.com/forum/?place=msg%2Fhaxeflixel%2F5FgwBq6nWhs%2F3_pdcsOBCAAJ

**Comment by Gama11** [comment]
This happens because trailing commas are parsed differently on different platforms. Has nothing to do with rendering or auto-tiling.

```haxe
package;
 
import flixel.FlxState;
import flixel.graphics.FlxGraphic;
import flixel.tile.FlxTilemap;
import flixel.util.FlxColor;

class PlayState extends FlxState
{
	override public function create():Void
	{
		bgColor = FlxColor.WHITE;
		
		var tilemap = new FlxTilemap();
		tilemap.loadMapFromCSV("1,", FlxGraphic.fromClass(GraphicAuto));
		add(tilemap);
		
		trace(tilemap.getData()); // [1] on neko, [1,0] on flash and cpp
	}
}
```
