### ISSUE TITLE
FlxSprite.loadGraphicForSprite() drops exception when using it on an FlxSprite without an animation controller

### ISSUE THREAD

**Issue by notboring** [HaxeFlixel/flixel#1535]
In FlxSprite the function loadGraphicFromSprite(Sprite:FlxSprite) calls the function updateFrameData() which has a line that sets animation.frameIndex=0.

When animation is null that line causes an exception. That was the case in my project when using the following code to create the FlxSprite the graphics are copied to:

```haxe
var preview:FlxSprite=new FlxSprite(singlePreviewWidth*x,singlePreviewHeight*y);
add(preview);

In another function I access those preview sprites:

previews[cnt].loadGraphicFromSprite(prerenderedLevelPreviews.get(id+(modeIdx+cnt)));

prerenderedLevelPreviews is a Map<String,LevelPreview> where LevelPreview extends FlxSprite.

**Comment by notboring** [comment]
I found a scenario where the same code works. I'll reopen the issue as soon as I figured out what exactly is happening.

**Comment by notboring** [comment]
In case it helps someone else: In the title in question level previews were generated when starting the game and then saved in an array. Then during the level selection screen those the preview bitmaps (or flxsprites, tried both) were passed to FlxSprites using loadGraphics() or loadGraphicsFromSprite(). That worked well - until the FlxStates destroy() function got called. Seems that the bitmap that was passed by reference gets disposed during destroy(). Cloning the bitmap before passing it fixed the problem.

**Comment by Gama11** [comment]
`sprite.graphic.persist = true;` should also do the trick. That avoids the increased memory usage caused by cloning the bitmap.

**Comment by notboring** [comment]
Thanks! That did the trick. In case someone else tries this: You have to set the persist property on sprite.cachedGraphics.

**Comment by Gama11** [comment]
Yeah, that's for the latest release. It's `sprite.graphic` on the dev branch.
