### ISSUE TITLE
FlxRandom.color has broken null checks.

### ISSUE THREAD

**Issue by JoeCreates** [HaxeFlixel/flixel#1536]
```FlxG.random.color(FlxColor.GRAY)```, for example, breaks because of trying to access properties of the max color which is null.

In FlxRandom.color() there are checks like ```if (Max == null) {red = int(0, Max.red)}```. I'm not sure what the intended behaviour is.

@steverichey

**Comment by steverichey** [comment]
Thanks for pointing this out; what is your desired behavior for `FlxG.random.color(FlxColor.GRAY)`?

**Comment by MSGhero** [comment]
It's a bit ambiguous. It could be an int < gray with 0xff alpha, an int less than 0xff gray, or 3-4 bytes representing a random int from each channel of gray's argb.

**Comment by steverichey** [comment]
Since you're passing in a `Min` value and not a `Max`, I'll assume that the desire is a color between that minimum value and full white. This could easily be changed in a later revision, if desired.
