### ISSUE TITLE
Auto-Add multiple animations from a spritesheet's .xml

### ISSUE THREAD

**Issue by sruloart** [HaxeFlixel/flixel#1539]
A method that "imports" multiple animations from a spritesheet data seems very useful; it's much more convenient than adding many animations manually (and individually).

The basic mechanism is already in-placed ("prefix" in [FlxAnimationController](https://github.com/HaxeFlixel/flixel/blob/dev/flixel/animation/FlxAnimationController.hx)). I'm suggesting adding a method that takes a graphic and a data / FlxAtlas, a "prefix", and adds all of the available animations within the data that have the proper prefix ("**player**run", "**player**eat", "**player**dance"). 

Maybe a similar method can actually create and add FlxSprites into a state using the base prefix (like "player") as the name for the sprites, with a possibility to auto-generate suitable FlxSprite based classes to handle them.

**Comment by MSGhero** [comment]
I'll post how I do this with json and reflection later today. Uses reflection to grab all the anim objects in a file, and it could be fiddled with to include XML.

**Comment by MSGhero** [comment]
```haxe
public static function setAnimationsOf(fs:FlxSprite, animId:String, ?forceLoop:Bool = false, ?prefix:String):Void {
		
	var o:DynamicAccess<Dynamic> = Consts.obj.json.get('anims/$animId');
		
	var initFrame = true;
		
	var anim:DynamicAccess<Dynamic>, looped:Bool, frames:Array<String>;
	for (field in o.keys()) {
		
		anim = o.get(field);
		looped = !anim.exists("looped") || forceLoop ? true : anim.get("looped");
		
		frames = anim.get("frames").copy();
		
		if (prefix != null) {
			for (i in 0...frames.length) {
				frames[i] = '$prefix/${frames[i]}';
			}
		}
			
		fs.animation.addByNames(field, frames, anim.get("fps"), looped);
		
		if (initFrame) {
			fs.animation.play(field);
			fs.animation.stop();
			initFrame = false;
		}
	}
}
```
with json looking like
```
{
  "face_right": {
    "fps": 0,
    "frames": [
      "Applebug Face Right"
    ]
  },
  "walk_right": {
    "fps": 6,
    "frames": [
      "Applebug Walk Right 1",
      "Applebug Walk Right 2"
    ]
  },
  "onDeath": {
    "fps": 8,
    "looped": false,
    "frames": [
      "Applebug Face Down 1",
      "Applebug Death 1",
      "Applebug Death 2",
      "Applebug Death 3",
      "Applebug Death 4",
      "Applebug Death 5",
      "Applebug Death 5"
    ]
  }
}
```

**Comment by sruloart** [comment]
Nice! why do you use [dynamic](http://haxe.org/manual/std-Json-parsing.html)? or am I missing something...also, this way you need a utility to actually create this .json or else the user is left with writing it himself, so, no major gain here?...so I was thinking, for the time being, to just use the existing data formats. 

I do like this concept a lot - if Flixel had some kind of a general .xml/.json "save" file format which you could just load, it would have been a lot easier to handle a bunch of stuff. There's FlxScene but it's pretty limited, and [IceEntity](https://github.com/NicoM1/IceEntity) have/had hscript issues and wasn't complete. Maybe for HaxeFlixel 5 :D

**Comment by MSGhero** [comment]
Yeah, sorry. I have a macro that parses my json files into dynamics at compile time. The line with `Consts` would instead be a parameter to the function. There are two functions for texture packer XML/json, so there might need to be two here as well.

**Comment by sruloart** [comment]
After some testing I think this won't change much because you still need to adjust individual animations. It's actually making FlxAnimation a bit worse to handle. 

I'm not over the all "load everything from data" issue, but it needs a far more robust solution...

**Comment by MSGhero** [comment]
What do you mean by "adjust individual animations"?

**Comment by sruloart** [comment]
"Regular" spritesheets' data files don't have custom properties like the ones in your .json, so, since you still need to change these per animation, with a couple of lines, I don't really see the benefit over adding them with the animation in one line. The "frames" ([3,3,6,1....] part is still a bit of a hassle though.
