### ISSUE TITLE
Move screenCenter() from FlxSpriteUtil to FlxObject

### ISSUE THREAD

**Issue by Gama11** [HaxeFlixel/flixel#1540]

**Comment by SeiferTim** [comment]
I had a thought about this... why restrict it to 'screen' centering?
Why not add a function to FlxObject called 'align', you pass it a FlxObject and an array of alignment types? (Left, Right, Top, Bottom, Center-X, Center-Y)
So, if you want to align an object to ANY other object (including a `FlxState`), you might say:
`object.align(FlxG.currentState, [Align.LEFT, Align.CENTER_Y])`
Thoughts?

**Comment by Gama11** [comment]
Sounds quite useful, two issues with your suggestion:

- `FlxG.state` is not a `FlxObject`
- an array it quite messy, it doesn't restrict the amount of values you can pass, you can pass the same value multiple times, array allocations, etc etc... lots of undefined behavior. It would be much better to use two enums like [these](https://github.com/HaxeFlixel/flixel/blob/dev/flixel/system/scaleModes/BaseScaleMode.hx#L120-L132).

For further discussion on that, we should probably open a new issue. I feel like we would still want to keep `screeCenter()` (in some form anyway) when adding an `alignTo()`.

**Comment by Tiago-Ling** [comment]
+1 for the possibility to align a FlxObject to any other FlxObject. +1 for
using Enums to do that :)

On Tue, Jun 30, 2015 at 11:33 AM Gama11 <notifications@github.com> wrote:

> Sounds quite useful, two issues with your suggestion:
>
>    - FlxG.state is not a FlxObject
>    - an array it quite messy, it doesn't restrict the amount of values
>    you can pass, you can pass the same value multiple times, array
>    allocations, etc etc... lots of undefined behavior. It would be much better
>    to use two enums like these
>    <https://github.com/HaxeFlixel/flixel/blob/dev/flixel/system/scaleModes/BaseScaleMode.hx#L120-L132>
>    .
>
> For further discussion on that, we should probably open a new issue. I
> feel like we would still want to keep screeCenter() (in some form anyway)
> when adding an alignTo().
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HaxeFlixel/flixel/issues/1540#issuecomment-117208898>.
>
-- 
Tiago Ling Alexandre
Tel: +55 41 8819-3191

**Comment by sruloart** [comment]
:+1: to opening a new issue, maybe we can integrate the layout library by player_03 with Flixel...

**Comment by larsiusprime** [comment]
Flixel-UI's anchor class does this already, but maybe you guys have another API in mind:
https://github.com/HaxeFlixel/flixel-ui/blob/dev/flixel/addons/ui/Anchor.hx

Anyways, felt I'd leave a note in case there's something useful to grab there.
