### ISSUE TITLE
FlxG.mouse.justPressed and FlxG.mouse.wheel do not work right

### ISSUE THREAD

**Issue by OpmSaitama** [HaxeFlixel/flixel#1544]
When you use FlxG.mouse.justPressed it will detect any mouse button as left button press 
FlxG.mouse.wheel always return 0
Both of these issues are on  CPP/NEKO

**Comment by Gama11** [comment]
These are OpenFL / Lime issues, Flixel is listenting to the right events and this works on flash (and used to work on native).

Pinging @jgranick

**Comment by OpmSaitama** [comment]
I think its LIME , because i checked in openfl.ui.mouse and there isnt almost any code there except two functions (show and hide )

**Comment by Gama11** [comment]
Nothing we can do about this since it's an OpenFL / Lime isse, see openfl/openfl#722.
