### ISSUE TITLE
BitmapFrontEnd: maxTextureSize doesn't belong on Flash and HTML5

### ISSUE THREAD

**Issue by sruloart** [HaxeFlixel/flixel#1545]
[This property](https://github.com/HaxeFlixel/flixel/blob/fb6722a08ae42c9e21fd75aefb513e00b4a8c540/flixel/system/frontEnds/BitmapFrontEnd.hx#L25) uses a GL call in order to get the value on native targets, but there aren't any compiler flags for non-native targets. I don't know how OpenFL compiles that to Flash, but NME won't.

**Comment by Gama11** [comment]
Also, that should be a `(get, never)` property.

**Comment by sruloart** [comment]
:+1: but does it suppose to work on html5? because it returns a wrong value anyway (I'm just looking at the .js output)?

**Comment by Gama11** [comment]
Not sure, generally, OpenGL isn't impossible on HTML5, but as long as WebGL isn't used...

**Comment by sruloart** [comment]
At least it compiles :)
