### ISSUE TITLE
FlxTilemap one-way collision bug

### ISSUE THREAD

**Issue by Gama11** [HaxeFlixel/flixel#1546]
Originally reported [here](http://haxeflixel.com/forum/?place=msg%2Fhaxeflixel%2F3Lxwjz9Q5Ro%2FDxWRgDFnlc8J).

Code to reproduce:

```haxe
package;

import flixel.FlxG;
import flixel.FlxSprite;
import flixel.FlxState;
import flixel.graphics.FlxGraphic;
import flixel.tile.FlxTilemap;
import flixel.util.FlxColor;

class PlayState extends FlxState
{
	public var sprite:FlxSprite;
	public var tiles:FlxTilemap;
	
	override public function create():Void
	{
		super.create();
		
		sprite = new FlxSprite(0, 8);
		sprite.makeGraphic(8, 8);
		add(sprite);
		
		tiles = new FlxTilemap();
		tiles.loadMapFrom2DArray([[1],[0]], FlxGraphic.fromClass(GraphicAuto));
		tiles.x += 20;
		
		add(sprite);
		add(tiles);
	}

	override public function update(_):Void
	{
		super.update(_);
		readInput();
		FlxG.collide(sprite, tiles);
	}	
	
	public function readInput()
	{
		var speed = 50;
		sprite.velocity.y =
			if (FlxG.keys.anyPressed([UP, W])) -speed;
			else if (FlxG.keys.anyPressed([DOWN, S])) speed;
			else 0;
			
		sprite.velocity.x =
			if (FlxG.keys.anyPressed([LEFT, A])) -speed;
			else if (FlxG.keys.anyPressed([RIGHT, D])) speed;
			else 0;
	}
}
```

Moving from left to right works fine - right to left doesn't though, the sprite gets stuck at the edeg of the tilemap. Doesn't seem to be a target-specific issue.

Supposedly, this doesn't happen in AS3 Flixel (haven't tested myself), so comparing some of the collision code might be helpful.
Originally reported [here](http://haxeflixel.com/forum/?place=msg%2Fhaxeflixel%2F3Lxwjz9Q5Ro%2FDxWRgDFnlc8J).

Happens in both dev and 3.3.8, so not a recent regression.

**Comment by SeiferTim** [comment]
If you add another column, this stops happening.
I'm not sure what the issue is, yet.

**Comment by Gama11** [comment]
Depends on what the column looks like... The original csv from the thread looked like this:

```haxe
1,1,1,1,1,1,1,1,1,1
1,0,4,0,0,0,0,4,0,1
1,1,1,0,0,0,0,1,1,1
0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0
1,1,1,0,0,0,0,1,1,1
1,0,4,0,0,0,0,4,0,1
1,1,1,0,0,0,0,1,1,1
1,0,4,0,0,0,0,4,0,1
1,1,1,0,0,0,0,1,1,1
2,0,0,0,0,0,0,0,0,3
2,0,0,0,0,0,0,0,0,3
2,0,0,0,0,0,0,0,0,3
1,1,1,0,0,0,0,1,1,1
1,0,4,0,0,0,0,4,0,1
1,1,1,1,1,1,1,1,1,1
```

I just reduced it as much as possible.

**Comment by chiguire** [comment]
I assume this code compiles on Dev, it doesn't on 3.3.8. Tim, how did you add the other column? I'm using a CSV in a string "1,1\n0,0" and I'm still getting the collision.

**Comment by SeiferTim** [comment]
`tiles.loadMapFrom2DArray([[1, 0],[0, 0]], FlxGraphic.fromClass(GraphicAuto));`

**Comment by chiguire** [comment]
In AS3 Flixel, in FlxTilemap.overlapsWithCallback selectionX and selectionY are respectively set to 0 if they're less than 0. I added this in Haxe and the collision was correct.

**Comment by SeiferTim** [comment]
It looks like the issue with with `FlxTilemap.overlapsWithCallback` not bounding the `selectionX` and `selectionY` variables. I'll add the change to dev.

**Comment by chiguire** [comment]
It also seems to solve the problem in the original case :-) when debugging before, it seems that the collision function was looking in a negative column (-2), maybe it was accessing an invalid tile.

**Comment by chiguire** [comment]
Cheers, thanks for all the help.
