### ISSUE TITLE
FlxTilemap.loadMap doesn't respect trailing whitespace in CSV files

### ISSUE THREAD

**Issue by rrohrer** [HaxeFlixel/flixel#1550]
I'm calling loadmap as such:
```haxe
foo.loadMap(Assets.getText("assets/foo.txt"), "assets/my_image.png", x, y, FlxTilemap.OFF);
```
with a foo.txt that looks like:
```
0,0,0,0,0
1,0,0,0,0
0,0,0,0,0
0,0,0,0,0
1,1,1,1,1
~this is a newline character~
```
having a newline character at the end of the file (to make it a valid text file), [which is allowed by the CSV format](http://edoceo.com/utilitas/csv-file-format) causes this call to silently fail.

On OSX under the neko and native target I'm getting back:
```haxe
trace(foo.widthInTiles); // this prints 0
```

Looking into how FlxTilemap is implemented if the last line is a newline, it fails the whole call (silently).

To fix this, you need to call loadMap as such:
```haxe
foo.loadMap(StringTools.rtrim(Assets.getText("assets/foo.txt")), "assets/my_image.png", x, y, FlxTilemap.OFF);
```

It seems like it would make more sense to have that call to StringTools.rtrim *in* loadMap, or at the very least throw an exception saying that whitespace isn't allowed at the end of the CSVs.

**Comment by Gama11** [comment]
This works fine on the dev branch, CSV parsing in general is a bit more robust there as there have been some fixes. I might release a 3.3.9 patch soon though, might as well include a fix for this.

A unit test for this would also be nice.
