### ISSUE TITLE
FlxFlicker and FlxTimer.pause()?

### ISSUE THREAD

**Issue by MSGhero** [HaxeFlixel/flixel#1553]
I know there's superissue #1087 in the air, but in the meantime, would it break anything if I added pause/resume methods to `FlxTimer` and by extension `FlxFlicker`? Are there other classes to add that to?

**Comment by Gama11** [comment]
Seems redundant, you can already pause and resume timers with `active`.

**Comment by MSGhero** [comment]
For FlxTimer ok didn't know that, but since FlxFlickers aren't exposed, can there be a `public static pause/resumeFlickersOf(obj)`?

**Comment by Gama11** [comment]
Meh, not a fan of that API... then again I'm not a huge fan of `FlxFlicker` to begin with.

We could simply have the `FlxSpriteUtil` methods return the `FlxFlicker` instances?

**Comment by MSGhero** [comment]
That would be fine. Flickers feel like tweens which throws me off when `static flicker()` doesn't return the flicker object.

**Comment by sruloart** [comment]
Also, if we're already at `FlxFlicker` it would've been nice if it could also have an option to color the sprite white before the flickering begins (I'm thinking about old-school 8-bit enemy hit)...

**Comment by sruloart** [comment]
On second thought, maybe this is better suited on another (`FlxHit`) class (somewhere at flixel-addons) as there are a lot of things (flickers, explosions, sprite positioning...) to consider when a sprite gets hit...

**Comment by Gama11** [comment]
Or maybe just let the programmer implement something for a change, instead of trying to provide *everything* in the engine. ;)

**Comment by sruloart** [comment]
Never! :) btw, there's very little support for AI in Flixel...how about making a FlxBrain for sprites? ;D

**Comment by MSGhero** [comment]
Just looked, and `FSU.flicker` returns the FlxObject, so it'd probably be breaking to change that to return the flicker object.

**Comment by Gama11** [comment]
Yeah. I don't think that's a huge deal though.
