### ISSUE TITLE
Performing overlap call that also updates the "touching" flags of objects

### ISSUE THREAD

**Issue by winterismute** [HaxeFlixel/flixel#1556]
Hello,
I used to use flixel a lot in the past, mostly for AS3 projects, and recently I am toying with some other ideas for which I am trying haxeFlixel: I am really liking it, it is very cool to have an actively developed, cross-platform version of flixel.
I recently found myself into wanting to call FlxG.overlap() but also wanting to have the "touching" variables of the objects involved update. This did not seem to be possible with current flixel, am I right?
Therefore, I have changed it: https://github.com/HaxeFlixel/flixel/pull/1555
I do not know how is contribution to HaxeFlixel organized, but if it looks interesting, I can polish (like, adding a unit test).
Hope it helps!

**Comment by Gama11** [comment]
Well, if you're offering, I'm not gonna say no to unit tests. ;)

**Comment by winterismute** [comment]
Hello @Gama11 , I have added a test: https://github.com/HaxeFlixel/flixel/pull/1560
hope it looks ok, if it does not please let me know how I can improve it.
