### ISSUE TITLE
PS3 Right Axis Issue

### ISSUE THREAD

**Issue by diegomachado** [HaxeFlixel/flixel#1559]
There's no RIGHT_ANALOGUE on release branch for PS3 Gamepad mappings.
http://api.haxeflixel.com/flixel/input/gamepad/PS3ButtonID.html

I know that you guys refactored all gamepad's stuff in dev branch, but is there a way to get this right in release branch? I've tried to use PS4 Bindings, but I can only get the X Axis value.

I'm using a Mac, connected through Bluetooth.

Thanks!

**Comment by Gama11** [comment]
Have you tried these values? https://github.com/HaxeFlixel/flixel/blob/fbab5e7b7d54aed861fc881044969e410ea7aa3d/flixel/input/gamepad/id/PS3ID.hx#L29-L30

**Comment by Gama11** [comment]
@larsiusprime Interested in your thoughts on this, since PS3 mappings are removed entirely in #1563.

**Comment by larsiusprime** [comment]
Hmmmm, interesting. The PS3 controller basically doesn't work at ALL on windows, but if it works on mac I could consider adding the ID class back and just making it a mac-only thing.

First step -- what values do you get from this tool?
http://www.html5rocks.com/en/tutorials/doodles/gamepad/gamepad-tester/tester.html

I don't have a mac handy atm, but maybe it will help identify the axis ID's you need, then we can patch released flixel, and come up with a mac-only PS3 class for dev.

**Comment by Gama11** [comment]
Linux would also have to be considered.

**Comment by larsiusprime** [comment]
Yeah sure, if someone can get valid hardware ID's for it and report them, I'll add the class and mappings for it.

**Comment by diegomachado** [comment]
Forgive my hiatus, but I'm on a trip for over a week now. As soon as I get home I'll check into all of this.

**Comment by diegomachado** [comment]
@larsiusprime I got nothing from the tester using PS3 gamepads on my Mac connected through Bluetooth.

**Comment by Gama11** [comment]
Support for PS3 controllers has been dropped, see https://github.com/HaxeFlixel/flixel/pull/1715.

**Comment by larsiusprime** [comment]
Your best bet with a PS3 controller is just to find some software that makes it look like an XBox 360 controller to the system, in which case it will work perfectly fine with Flixel. Otherwise it's just way too fiddly to get it to work natively.
