### ISSUE TITLE
FlxTilemap collisions while moving

### ISSUE THREAD

**Issue by nospoone** [HaxeFlixel/flixel#1561]
While upgrading my project to HF4 (mainly for the controller improvement) I've noticed that my character has started going through floors and ceilings. [I've built a barebones project](http://files.q-bit.ca/hf4-collision.zip) to illustrate the issue: if you *push* against the wall at certain places, you will go through the floor (or ceiling).

![hf4-maptest](https://cloud.githubusercontent.com/assets/708588/8643856/252e8cd6-2907-11e5-845e-f72fd4a2b157.gif)

Move with the arrow keys and jump with space. I've also noticed that if I resize both the game and window to 480x480, it does not happen anymore. I've been able to reproduce this on both native (windows) and Neko builds.

**Comment by Gama11** [comment]
Thanks for reporting, this should be fixed now.
