### ISSUE TITLE
FlxAngle.angleFromFacing should not require FlxSprite

### ISSUE THREAD

**Issue by SeiferTim** [HaxeFlixel/flixel#1567]
currently, `FlxAngle.angleFromFacing` looks like this:
`angleFromFacing(Sprite:FlxSprite, AsDegrees:Bool = false):Float`

I think it would be better to be able to simple pass it your facing flag(s), since `FlxSprite` is not the only place you might use it...
For example:
`angle = FlxAngle.angleFromFacing(myObject.direction); // where myObject.direction = FlxObject.UP| FlxObject.RIGHT`

**Comment by winterismute** [comment]
It's small but requires changes in flixel: https://github.com/HaxeFlixel/flixel/pull/1571
and flixel-addons: https://github.com/HaxeFlixel/flixel-addons/pull/181

**Comment by MSGhero** [comment]
Breaking change, not sure how many people actually use facing (I don't).
