### ISSUE TITLE
Console doesn't work properly in 3.3.1 when compiling to Neko.

### ISSUE THREAD

**Issue by Yaru2585** [HaxeFlixel/flixel#1569]
After updating to 3.3.1, the debugger console fails to work as usual. Pressing TAB doesn't activates the field to write the commands and I must click on it to be able to write, and after using a command, the keyboard activity keeps being caught by the console, so I can't move or do anything that requires keys.
I'm using 3.3.1. with OpenFL 3.1.3

**Comment by Gama11** [comment]
By 3.3.1 you mean 3.3.11?

**Comment by Yaru2585** [comment]
Yes.

**Comment by xerosugar** [comment]
possibly related:
when I try to open the console while running on Neko and OpenFL-Next it crashes the whole application. but works fine on windows target.

**Comment by Gama11** [comment]
Closing here since it works on the dev branch.
