### ISSUE TITLE
Xbox controller support.

### ISSUE THREAD

**Issue by JordanWIlliford** [HaxeFlixel/flixel#1573]
I'm having a bit of trouble with the CPP and neko builds. the Xbox controller IDs are mapping the face buttons to the dpad, the triggers to start/select and right stick is perpetually held to the left.

I've been using the rock candy controllers so maybe that has something to do with it.

**Comment by larsiusprime** [comment]
Which target are you using? And what version of flixel?

**Comment by JordanWIlliford** [comment]
I've been using the neko and windows targets. and the version of flixel I'm using is 3.3.11

**Comment by larsiusprime** [comment]
Okay, great. I assume you've also been using the legacy target? Ie, when you compile you're *not* specifically setting the "-Dnext" flag or setting ```<haxedef name="next">``` in your project.xml?

3.3.11 looks like the latest flixel version from github -- that's what you're using right? Not the older haxelib release?

If that's all true, I can probably help you with this.

**Comment by JordanWIlliford** [comment]
OH I'm sorry I just kinda repeated myself.

yeah I'm using the legacy target.
and yes I'm using the latest version of flixel.

Thank you I admit I'm still a bit new to the language of haxe and flixel.

**Comment by larsiusprime** [comment]
Okay, great, this puts us all on the same page. So, I'll take a closer look tomorrow, but the first thing you should do is clone the flixel-demos repo and build the Input/GamepadTest demo for windows or neko, then tell me what happens when you connect your controller and try to use it.

- What is your controller detected as?
- Do the button inputs on screen match what they are physically?
- Do you get different results in flash compared to neko/windows?

**Comment by JordanWIlliford** [comment]
So, I think it's detecting it as an Xbox controller, but I'm not 100% sure how to tell. will the sprite for the controller change in the test?

That said, I do have the results for the different builds.
Flash works properly, everything is mapped to the right inputs. 
HTML isn't working, but it was working before and I haven't changed anything so I think it's user error here.
Windows and Neko have identical results

the L and R buttons are mapped to back and start respectively on the test
Clicking the left and right thumbsticks  map to L and R
the left thumbstick is fine.
Left Trigger is mapped to right stick's x axis. (pressing it halfway causes the right stick on the test to rest in the middle, otherwise the sprite for the stick is constantly pressing to the left)
the D-pad seemingly does nothing.
The Xbox button is mapped to A
X and Y are mapped to left and right on the D-Pad
A and B are mapped to up and down on the D-Pad
the back and start buttons go nowhere as well.

and that's everything.
it should be noted I recently installed the drivers for xbox one controllers so that may have something to do with it.

thanks again for looking into this!

**Comment by Gama11** [comment]
@larsiusprime 3.3.11 is not the dev branch, it's the latest haxelib release.

**Comment by larsiusprime** [comment]
Ah thanks gamma, that makes this a bit more complicated...

**Comment by madnotdead** [comment]
I've been having the same problem and my conclusion is that is a openfl/lime issue. I've been looking for some clues and many post i found ended up with some openfl/lime update that breaks mapping. Maybe you can downgrade o update if you haven't done it.

**Comment by Gama11** [comment]
Closing here since it works on the dev branch.
