### ISSUE TITLE
FlxEmitter start function documentation is false

### ISSUE THREAD

**Issue by Txori** [HaxeFlixel/flixel#1578]
This is the parameters explanation of the FlxEmitter start function:

> @param	Explode			Whether the particles should all burst out at once.
> @param	Frequency		Ignored if Explode is set to true. Frequency is how often to emit a particle. 0 = never emit, 0.1 = 1 particle every 0.1 seconds, 5 = 1 particle every 5 seconds.
> @param	Quantity		Ignored if Explode is set to true. How many particles to launch. 0 = "all of the particles".

What I think would be useful is that the quantity is not ignored when Explode is set to true.
This way, we could make different explosions but with a defined number of particles. If the number is not set, then all the particles should burst out at once.

...

Nevermind, after reading the source of FlxEmitter update function, it appears that Quantity is not ignored when Explode is set to true, only Frequency is. So it is only a matter of wrong explanations for the function. And maybe we should invert the order of the parameters Frequency and Quantity in the start function.

Cheers!

**Comment by Gama11** [comment]
Good catch.
