### ISSUE TITLE
FlxObject's 'getScreenXY' does not account for zoom

### ISSUE THREAD

**Issue by Mixerman123** [HaxeFlixel/flixel#1582]
FlxObject contains a getScreenXY method, however it's source reviews that it does not account for zoom, which should be fairly easy to add.

I might be worth renaming it to getScreenPosition to be more consistent with the API, as not many methods, as far as I know, end with XY.

**Comment by Gama11** [comment]
This method is used for rendering and overlap checks and not really supposed to account for zoom.

It's already been renamed to `getScreenPosition()` a while ago on the dev branch. :)
