### ISSUE TITLE
HTML Target - cannot read property charCodeAt

### ISSUE THREAD

**Issue by smks** [HaxeFlixel/flixel#1585]
haxe_xml_Parser.doParse = function(str,strict,p,parent) {
	if(p == null) p = 0;
	var xml = null;
	var state = 1;
	var next = 1;
	var aname = null;
	var start = 0;
	var nsubs = 0;
	var nbrackets = 0;
	var c = str.charCodeAt(p);

Uncaught TypeError: Cannot read property 'charCodeAt' of null

**Comment by Gama11** [comment]
How is this flixel-related?

**Comment by smks** [comment]
added to haxe repo.
