### ISSUE TITLE
DPad "sticks"

### ISSUE THREAD

**Issue by nospoone** [HaxeFlixel/flixel#1586]
Playing with the dpad on my controllers (PS4, Xbox 360, PS4 as Xbox 360 via DS4 Windows) often causes it to "stick" to one direction: it stays in the _pressed_ state. I can't seem to figure out when exactly this happens, but it happens relatively often - effectively rendering it unusable. This happens to me on both Neko and Windows.

I created a simple project that shows the issue [here](http://files.q-bit.ca/hf4-sticky_dpad.zip). 

Versions: 
```
box2d: [1.2.3]
flixel-addons: 1.1.0 git [dev:C:\HaxeToolkit\haxe\lib\flixel-addons/git]
flixel-demos: 1.1.1 [1.1.2]
flixel-templates: [1.0.2]
flixel-tools: 1.0.5 1.1.0 [1.1.1]
flixel-ui: [1.0.2]
flixel: 3.3.11 git [dev:C:\HaxeToolkit\haxe\lib\flixel/git]
haxelib_client: [3.2.0-rc.3]
hxcpp: [3.2.102] 3.2.94
hxlibc: [1.1.4]
hxtelemetry: [0.3.1]
layout: 1.2.0 [1.2.1]
lime-samples: 2.3.0 2.4.0 [2.5.1]
lime: 2.3.1 2.4.1 2.4.7 2.4.8 2.4.9 2.5.0 2.5.2 [2.5.3]
openfl-samples: 2.2.2 [3.1.0]
openfl: 3.0.1 3.0.6 3.1.1 3.1.2 3.1.3 3.1.4 3.2.2 [3.3.0]
swf: 1.8.7 1.8.9 1.9.0 [1.9.1]
```

**Comment by nospoone** [comment]
pinging @larsiusprime as I assume that you'd maybe know something about this <3

**Comment by larsiusprime** [comment]
Great bug report, so this is happening to you on what looks like the dev version of flixel (you've got latest commits?) and the latest openfl as well. Are you compiling specifically with "-Dnext" or just the defaults?

I'll take a look at the repro sample and see if I can figure it out. Might not get to it until Monday but if I have some time today I'll look.

**Comment by MSGhero** [comment]
Spitballing, does it happen when you're holding it down diagonally and let go? Maybe it's only registering one of the directions being released and not both.

I thought gamepad and keyboard used the same pressed/released system but maybe not.

**Comment by nospoone** [comment]
@larsiusprime I updated to latest commits just before trying my demo out and I'm compiling with just the defaults. I tried with `-Dnext` and it yields the same results!
@MSGhero Just tried, and had about the same "stick" rate from diagonal to not, so I don't think it's related~

**Comment by nospoone** [comment]
Update: just found out that this only seem to happen when using the `justPressed`, `pressed` or `justReleased` helpers. Using `checkStatus()` works correctly for me.

**Comment by MSGhero** [comment]
@nospoone When you say `justPressed` helpers, do you mean the functions like `anyJustPressed`, or do you mean the actual `justPressed` variable? If you mean the functions, try using the variable directly (skip `checkStatus()`). If you're using the variables already, I guess do a once over to make sure your code's logic makes sense.

**Comment by MintPaw** [comment]
I'm having this issue as well with the dev version of Flixel with and without -Dlegacy, and with checkStatus as well.

**Comment by nospoone** [comment]
Yep, can confirm that it still happens with `checkStatus`. We showed Holobunnies at PAX with what I thought was a workaround but it still happened a couple times~

**Comment by sruloart** [comment]
I think there's a potential general input "stuckness" bug, maybe events have something to do with it. I would try to use a much older version of OpenFL/Lime...

**Comment by Gama11** [comment]
Nice test project! However, I haven't been able to reproduce this. I've tried Flash, Neko legacy and Neko next using my Xbox One controller. The indicators in the demo always revert to the red / justReleased state (I assume the issue is them being suck at yellow?).

Did this only happen on a specific target?

**Comment by larsiusprime** [comment]
@nospoone does this still happen after the latest changes?

**Comment by nospoone** [comment]
@Gama11 This only happened to me on CPP, didn't think to check the other targets! My bad.
@larsiusprime Haven't checked it out just yet. Will try this out tomorrow!

**Comment by nospoone** [comment]
Test results (from the above test project) are below. I think they make it pretty clear that Next fixes the issue... Also, pretty sure DS4 as XInput is redundant, but included them to make sure.

### Native (Windows 10)
| Controller | Legacy/Next | Result |
| --- | --- | --- |
| DS4 (as DirectInput) | Legacy | **Sticks** |
| DS4 (as XInput through [DS4Windows](http://ds4windows.com/)) | Legacy | **Sticks** |
| Xbox 360 | Legacy | **Sticks** |
| DS4 (as DirectInput) | Next | *Doesn't Stick* |
| DS4 (as XInput through [DS4Windows](http://ds4windows.com/)) | Next | *Doesn't Stick* |
| Xbox 360 | Next | *Doesn't Stick* |

### Neko
| Controller | Legacy/Next | Result |
| --- | --- | --- |
| DS4 (as DirectInput) | Legacy | **Sticks** |
| DS4 (as XInput through [DS4Windows](http://ds4windows.com/)) | Legacy | **Sticks** |
| Xbox 360 | Legacy | **Sticks** |
| DS4 (as DirectInput) | Next | *Doesn't Stick* |
| DS4 (as XInput through [DS4Windows](http://ds4windows.com/)) | Next | *Doesn't Stick* |
| Xbox 360 | Next | *Doesn't Stick* |
*Note: I was only able to make Neko with Next on Debug, Release was crashing upon entering PlayState.*

### Flash
| Controller |  Result |
| --- | --- | --- |
| DS4 (as DirectInput) | *Doesn't Stick* |
| DS4 (as XInput through [DS4Windows](http://ds4windows.com/)) | *Doesn't Stick* |
| Xbox 360 | *Doesn't Stick* |


Here's my current config (repos were pulled from at 1:33PM EST - flixel is at 1f2871d)
```
actuate: [1.8.6]
box2d: [1.2.3]
crashdumper: git [dev:C:\HaxeToolkit\haxe\lib\crashdumper/git]
firetongue: [1.0.0]
flixel-addons: git [dev:C:\HaxeToolkit\haxe\lib\flixel-addons/git]
flixel: git [dev:C:\HaxeToolkit\haxe\lib\flixel/git]
haxelib_client: [3.2.0-rc.3]
hscript: [2.0.5]
hxcpp: 3.2.180 3.2.193 [3.2.205]
hxtelemetry: [0.3.3]
layout: [1.2.1]
lime-samples: [2.6.0]
lime: 2.6.8 2.6.9 2.7.0 2.8.1 2.8.2 2.8.3 [2.9.0]
node-webkit: [1.0.7]
openfl-samples: [3.3.1]
openfl: 3.3.8 3.3.9 3.4.0 3.5.2 3.5.3 [3.6.0]
swf: 2.1.1 2.1.2 2.1.3 2.1.6 [2.2.0]
task: [1.0.7]
```

**Comment by larsiusprime** [comment]
Wow, that's super detailed! Looks like it's exclusively an issue with the legacy api ...

I guess we need to know if it's an error in openfl or in flixel. Can you run the "GamepadInput" and "JoystickInput" tests in openfl-samples/features/ui, and tell us what behavior you see there, if there's something that indicates the "stickiness" is originating at the openfl layer?

**Comment by nospoone** [comment]
Sure thing. Both tests don't stick for all their relevant platforms, with all my controllers!

**Comment by Gama11** [comment]
Hm, I'm actually able to reproduce this now, although it took a while of randomnly pressing dpad buttons (maybe I didn't try hard enough last time I tried).

I've only gotten it to stick on the x axis so far - when it gets stuck, it only seems to be stuck on that axis. I guess it probably happens with y as well?

**Comment by nospoone** [comment]
I don't think I remember it sticking on Y axis, either. I'll keep an eye out for it, though.

**Comment by larsiusprime** [comment]
@nospoone -- it seems like this might be a flixel level issue, but just to be sure, did you do the joystick tests with the -Dlegacy define? (Flixel adds -Dlegacy by default and turns it off if you supply -Dnext, but vanilla OpenFL is the reverse)

**Comment by nospoone** [comment]
Ah, no I didn't. Still a beginner at all that OpenFL stuff :)

Re-ran them with -Dlegacy, and they did not stick either.

**Comment by larsiusprime** [comment]
Okay, so since you didn't get them to stick in the base joystick demo with -Dlegacy, and gama has reproduced it himself, I think we can safely conclude this is a rare edge case in flixel. Any clue what it is @Gama11 ? I can try to help if necessary.

**Comment by nospoone** [comment]
Nice work, but unfortunately, this still happens for me on Native and Neko. I can also now make it stick on the Y axis as well...

**Comment by Gama11** [comment]
Hm, you're right.. it seems way harder to reproduce now, but it's fairly easy when generating the events yourself. I added this to the state:

```haxe
@:access(flixel)
private function hatMove(x, y):Void
{
	FlxG.gamepads.handleHatMove(new JoystickEvent("hatMove", false, false, 0, x, y, 0));
}
```

and then call

```
state.hatMove(1, 1)
state.hatMove(0, -1)
```

via the console.

**Comment by Gama11** [comment]
Alright, fairly confident that it's fixed this time.

**Comment by nospoone** [comment]
Works for me! Awesome work! :+1:
