### ISSUE TITLE
The background isn't scaled properly on native targets when 0<zoom<1

### ISSUE THREAD

**Issue by sruloart** [HaxeFlixel/flixel#1588]
see here: http://haxeflixel.com/forum/?place=msg%2Fhaxeflixel%2FAf21i7o6LWg%2FDDdT02dHEgAJ

Only relevant to FLX_RENDER_TILE and FLX_RENDER_TRIANGLE.

**Comment by sruloart** [comment]
Two more related points to add: 
* It doesn't happen on Android (apparently).
* On html5 the background sometimes disappears completely. Might be related. But the test case above works fine though.

I think that's something to do with OpenFL/Lime (the Hardware don't scale the BG sprite properly), but let's keep it open in case this requires a flag / I'm wrong :)


And here are two gifs to better illustrate what's actually going on: 

`Trying to scale the game up/down when the initial zoom value is smaller than 1`
![bad scaling background](https://cloud.githubusercontent.com/assets/5843924/9588035/867541c6-502e-11e5-9b39-11cf181a7113.gif)
`The black rectangle is actually the background sprite :|`

`And here's what happens when going fullscreen:`
![bad scaling background - fullscreen](https://cloud.githubusercontent.com/assets/5843924/9588112/0fbc51f4-502f-11e5-961f-3b2a7b56c21d.gif)

**Comment by solewalker** [comment]
It does not happen in mobile target, only happen when window or display size is smaller than game size (defined in Main.hx) And in mobile normally window size is bigger than game size.

**Comment by solewalker** [comment]
Bump.

**Comment by Beeblerox** [comment]
i think i've fixed it

**Comment by Gama11** [comment]
See 97545354ba3ee9974997a80f544ec563fb13331f.

**Comment by arthurferrai** [comment]
When will it be available?

**Comment by Beeblerox** [comment]
@arthurferrai i don't know, but it's one line fix in `FlxCamera`, so you can make this change yourself in local copy of the lib
