### ISSUE TITLE
PixelPerfectRender is wrong on native until the window gets resized

### ISSUE THREAD

**Issue by JoeCreates** [HaxeFlixel/flixel#1589]
We have `pixelPerfectRender = false` for native. On flash, as expected, movement is blocky. On native, incorrectly, movement is just as blocky as on flash, i.e. sprites move at least one game pixel at a time. Considering our game is scaled up, on native it should appear smoother. When we resize the window, even slightly, suddenly the subpixel rendering is working correctly, and everything moves smoothly.

It seems that at the default window size, subpixel rendering is not being used.

**Comment by Tiago-Ling** [comment]
What was the problem / how did you solve it?

On Tue, Aug 25, 2015, 8:59 PM Joe Williamson <notifications@github.com>
wrote:

> Closed #1589 <https://github.com/HaxeFlixel/flixel/issues/1589>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HaxeFlixel/flixel/issues/1589#event-392273840>.
>
-- 
Tiago Ling Alexandre
Tel: +55 41 8819-3191

**Comment by Tiago-Ling** [comment]
@JoeCreates I'm having a similar problem when resizing or going fullscreen. My FlxSprites appear at wrong positions (even though everything is floored).

No resizing / fullscreen:
![stage_resize_no_scale](https://cloud.githubusercontent.com/assets/1617118/9550855/1fad43f0-4d84-11e5-9490-6fc16dade024.jpg)

After resizing or going fullscreen:
![stage_resize_scaled](https://cloud.githubusercontent.com/assets/1617118/9550931/9149838e-4d84-11e5-9ee6-6908ee64794b.jpg)

You mentioned it's not a flixel issue - could you please elaborate? 

Thanks!

**Comment by Tw1ddle** [comment]
Original issue was our own confusion rather than a code problem, sorry to waste your time.

@JoeCreates might have suggestions as he spent a long time looking at issues with jittering.

**Comment by Tiago-Ling** [comment]
@Tw1ddle Thanks for the reply. I'm gonna create a dedicated issue for that. :+1:
