### ISSUE TITLE
filter in FlxInputText doesn't replace text

### ISSUE THREAD

**Issue by happinesssam** [HaxeFlixel/flixel#1592]
To reproduce:
Create and add a FlxInputText instance, set it's filterMode to ONLY_NUMERIC.
I can enter letters and other symbols when testing on Flash

Looks like the culprit is Line 639:
pattern.replace(text, "");
should probably be
text = pattern.replace(text, "");

Which seems to fix the issue for me, unless I'm missing something.

**Comment by Gama11** [comment]
`FlxInputText` is part of [flixel-ui](https://github.com/HaxeFlixel/flixel-ui). Normally I'd say feel free to reopen the issue there, though I think [this has already been fixed on the dev branch](https://github.com/HaxeFlixel/flixel-ui/blob/dev/flixel/addons/ui/FlxInputText.hx#L731).
