### ISSUE TITLE
Changing screen size causes tearing in FlxSprites in cpp

### ISSUE THREAD

**Issue by Tiago-Ling** [HaxeFlixel/flixel#1594]
Whenever the screen size changes (either by resizing the window or toggling fullscreen) there's a weird effect on FlxSprites. 

The image below is composed of several FlxSprites, similar to a tilemap (the difference being that each tile is a FlxSprite and the "tiles" have different sizes / positions). All sprite positions are floored and there's no change in their position after changing screen size.

This has been tried with all possible combinations of `pixelPerfectRender` and `pixelPerfectPosition` on both the sprites themselves as well as on the camera. 

No resizing / fullscreen:
![stage_resize_no_scale](https://cloud.githubusercontent.com/assets/1617118/9550855/1fad43f0-4d84-11e5-9490-6fc16dade024.jpg)

After resizing or going fullscreen:
![stage_resize_scaled](https://cloud.githubusercontent.com/assets/1617118/9550931/9149838e-4d84-11e5-9ee6-6908ee64794b.jpg)

UPDATE:
If you change either width OR height the problem does not appear. However changing width AND height, even by 1px causes the problem.

**Comment by Gama11** [comment]
I'm not sure what's going on here, but anyone trying to debug this is going to have a tough time without any way to reproduce it (you're just giving us two screenshots).

**Comment by Gama11** [comment]
This might be relevant: https://twitter.com/hexdie/status/637405415337234432

**Comment by Tiago-Ling** [comment]
@Gama11 I'll post a working test soon.

One possible cause: odd width and/or height in the image frames. (e.g.: a 48x48 image does not have the problem, while a 47x48 or 48x49 might present it. Have no way to test it currently, but that might be related).

**Comment by solewalker** [comment]
I also mentioned about uneven image/frame size in an issue here https://github.com/HaxeFlixel/flixel/issues/1401#issuecomment-66359454

**Comment by Tiago-Ling** [comment]
@solewalker I knew we had already seen this problem somewhere else!

This might be caused by some flooring or casting frame width and/or height divided by 2 to int somewhere in the framework.

**Comment by Tiago-Ling** [comment]
It's apparently a hardware thing that must be prevented by using repeated-pixel borders around your atlas frames. 

@Beeblerox solved it by telling me about the extrude option in the new texture packer.

**Comment by MSGhero** [comment]
When would you need to use extrude? I blit my tiles (and I can't compile to cpp right now), so that has never come up for me.

**Comment by Tiago-Ling** [comment]
@MSGhero Apparently some image sizes are better than others for gpu. In my experience odd numbers may cause this (e.g. one of my frames has a height of 737 pixels). I suppose the gpu transforms the image by adding an extra transparent pixel at the bottom and/or at the right border to optimize it.

This is pure speculation on my side though - what really happens might be different. I think @Beeblerox might know more about it.
