### ISSUE TITLE
HTML5: Fixing the fonts/audio problems on Firefox and IE11 and Safari

### ISSUE THREAD

**Issue by sruloart** [HaxeFlixel/flixel#1597]
* Fonts: AFAI can tell, the fonts became an issue with this commit: https://github.com/HaxeFlixel/flixel/commit/7c0a0dc66f315ced29f9203ff26b045151e6b397, so maybe some html5 flags can fix at least the fonts problems (which are relevant anywhere but on Chrome). Not embedding fonts (and using Assets.load... instead of Assets.get... obviously) seems to do the trick.

* Audio: The audio files were always a problem on IE11/Edge and Safari because they don't support the .ogg format, and you can't legally include .mp3 with your build (unless you have less than 5000 total downloads, which is ridiculous). A probable fix would be not using the same name for the different files (.mp3/.ogg), and adding another "safe" format (.m4a) version (and .wav files do work anywhere but on IE11, so that's also worth considering, as long as they are kept small enough).

**Comment by sruloart** [comment]
###### O.K, I'm half way done. There are some necessary consequences though:
* Sound: 
  * Use only `.m4a` files (or `.wavs`, that's fine too if you don't mind the size) for html5 (`.ogg` isn't supported anywhere but Chrome, so don't use it for html5 at all).
 * `FlxSplash` doesn't auto-play the `flixel.m4a` file on html5, but that's not because of the file format, it's something to do with `FlxSplash` itself (there's a bug somewhere preventing it to load/play, I dunno). `.m4a` files work very well otherwise, on all major browsers, so I think that's a reasonable outcome for now.

* Fonts
 * Create the missing web fonts on your own (check your console, use anything available) and you should be fine.
 * BUT We need to replace `arial.ttf` because it's a huge unnecessary beast of a font (760kb! wat) that causes problem on html5. 
 * So, suggestions / preferences would be welcomed. Just mind the license. A monospace font scales better on the other platforms, but would require a specific solution on html5 to make it scale like it should, so we actually need two fonts: one free monospace to replace `arial`, and something different for html5. 

Now I guess some .m4a files / web fonts should be added to the demos section as well, I'll get there soon enough.

**Comment by Gama11** [comment]
There's not really much to be done here [as .m4a files aren't working consistently either](https://github.com/HaxeFlixel/flixel/pull/1602#issuecomment-149040724).
