### ISSUE TITLE
Adding a Dashed line to HaxeFlixel

### ISSUE THREAD

**Issue by sruloart** [HaxeFlixel/flixel#1599]
A dashed line would be useful for many things, like trajectory and selection but it's not a straight-through process, as it's not a part of the Graphics.LineStyle, but it needs to be available for all of the drawn shapes as if it were (probably with a fake `gap` value).

Now, there are a few possible implementations to choose from; [like this] (https://github.com/kasoki/GameMechanicExplorer-HaxeFlixel/blob/master/src/examples/bullets/display-trajectory/src/states/PlayState.hx#L154-L193), or [this](https://github.com/polygonal/gl/blob/master/src/de/polygonal/gl/VectorRenderer.hx#L1599-L1666), and probably plenty of more options. I do prefer a solution that would allow for the user to change how his line looks like by altering the line's cap (round/square), but maybe `FlxSpriteUtil.space()` can get a possible FlxPath / FlxPolygon for spacing a bunch of objects around a path.

Here's another interesting implementation: https://github.com/benrhodes/graffiti-as3-drawing-lib/blob/master/src/com/nocircleno/graffiti/tools/LineTool.as

**Comment by xerosugar** [comment]
Don't know if it's helpful here, but here are some ways to do linestyles in js: http://perfectionkills.com/exploring-canvas-drawing-techniques/

**Comment by sruloart** [comment]
That's a cool article. The html5 canvas already has this feature: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/setLineDash, for example: http://www.rgraph.net/blog/2013/january/html5-canvas-dashed-lines.html but we don't since we use a bitmapData implementation.

**Comment by larsiusprime** [comment]
We have a FlxShapeLine already in flixel-addons, maybe see if that can be adapted?

**Comment by sruloart** [comment]
That should be impacted actually, as it uses both the FlxSpriteUtil and the LineStyle. I would probably go about adding a fake 'gap' value to the LineStyle, and have some kind of `gap generator` method in the FlxSpriteUtil to actually pull that off.

**Comment by Gama11** [comment]
I don't think this belongs in FlxSpriteUtil, the drawing functions there are just lightweight wrappers around the `flash.display.Graphics` API.
