### ISSUE TITLE
Changing the arial font

### ISSUE THREAD

**Issue by sruloart** [HaxeFlixel/flixel#1601]
The arial font isn't free, and there are some smaller size alternatives that are (like Noto). However, I'm not really seeing the point in including any such font to begin with, so...

My overall suggestion here is to use different system fonts on different targets instead of bundling a default font.

**Comment by larsiusprime** [comment]
Consistent cross-platform rendering might still be important? I think Liberation Sans is a good free alternative to Arial (it's a Helvetica lookalike, just like Arial is, IIRC)

**Comment by sruloart** [comment]
Liberation Sans would work too, sure, there are some other options as well. 

The problem here is that you have a (relatively) gigantic unicode (most users use plain English) font included as default in size-sensitive targets like Flash/Html5/Android. I mean, what default languages does HaxeFlixel even support? by the look of things: English.

I think that by using the correct system fonts, rendering would not only be consistent but also improved (by using non-hinted fonts on Android/Mac for example, html5 would look better in almost any case), but that requires some testing...

For consistent "HaxeFlixel-ish" look a user can always use the nokiafc22 font (or his own choice). You don't generally look at Arial and say, hey, that's a Flixel font! :)

**Comment by larsiusprime** [comment]
Ah, that's a good point :)

**Comment by Gama11** [comment]
Arial is basically just included for the debugger.

**Comment by sruloart** [comment]
So I'll be disposing of it in my html5 PR :) question is should we replace it or just let whatever default system font available to to take over?

**Comment by Gama11** [comment]
I don't know. At the time there was some inconsistency between the font in the debugger on windows vs flash, which Arial fixed.

**Comment by sruloart** [comment]
I did see some logic in having a multiple-languages supported font, but if that's not really used to begin with it seems kind of redundant to add a new one. 

I'll test with and without, and if that makes sense I'll add a debug default font that looks like Arial but is much much smaller and free to use.

**Comment by Gama11** [comment]
This was addressed by #1602.

**Comment by Ohmnivore** [comment]
[posted earlier in the pull request because was confused]

What do you think of using DejaVu Sans? It's public domain. Same size as monsterrat, practically the same look but a lot crisper. I find it a lot easier to read the debugger console with DejaVu.

Here's a side by side comparison of both (DejaVu Sans on the right):
![fonts](https://cloud.githubusercontent.com/assets/3769354/12209496/588305c4-b621-11e5-89d2-6eb0898017c1.png)

**Comment by Gama11** [comment]
@Ohmnivore Not really sure which look I prefer. But DejaVu Sans takes up **a lot** more space than Monsterrat (30 KB vs 739 KB)

**Comment by Ohmnivore** [comment]
You're right. I just realized it's super bloated and takes a while to load. :(
