### ISSUE TITLE
collide() broken for tilemaps with tiles larger than 70x70?

### ISSUE THREAD

**Issue by ManlyChicken** [HaxeFlixel/flixel#1605]
Hey, I'm currently making a game with rather large sprites and I noticed that my large 80x80 tilesheets won't collide correctly. Mainly falling through multiple solid tiles. The problems seem to get worse the further right I travel though I can fall through the tiles pretty much anywhere.
When I scaled them down to around 60x60 or less they work.
(sorry if this is a bad post or whatever, don't use github often)

**Comment by JoeCreates** [comment]
Sounds like you might not be making the worldbounds big enough?

**Comment by ManlyChicken** [comment]
that solved it, thanks.
