### ISSUE TITLE
Gamepad Left Trigger and Right Trigger not working.

### ISSUE THREAD

**Issue by OpmSaitama** [HaxeFlixel/flixel#1607]
I'm using xbox 360 gamepad  on HaxeFlixel 3.3.11.
I tried using  getAxis() , getButton() , getXAxis() , getYAxis() , anyButton(), anyInput() , checkStatus() , firstPressedButtonID() .

Non of these return anything when i press Left or right triggers.

**Comment by Gama11** [comment]
Duplicate of #1573. Xbox 360 support on 3.3.x is somewhat broken, but works pretty well on the dev branch.
