### ISSUE TITLE
HaxeFlixel is slow on Windows in some configurations

### ISSUE THREAD

**Issue by starry-abyss** [HaxeFlixel/flixel#1608]
I'm a beginner HaxeFlixel user, running FlixelTut tutorial (the one with only mouse cursor).
The default window configuration runs very slow on windows and neko (but runs well on flash target).

 It is as follows:

    <window width="640" height="480" fps="60" background="#000000" hardware="true" vsync="true" />

The following configurations run smoothly though:

    <window width="640" height="480" fps="60" background="#000000" hardware="false" vsync="true" />
    <window width="640" height="480" fps="60" background="#000000" hardware="true" vsync="false" />

It is as slow as 1 fps (I think).

flixel: [3.3.11]
openfl: [3.3.3]

My system is i5-3570, 8Gb RAM, GTX 660, Windows 7.

**Comment by Gama11** [comment]
By "the one with only mouse cursor", do you mean basically an empty project?

Have you tried some of the OpenFL / Lime demo projects? Chances are this is not a Flixel issue, those two libs deal with all the low-level stuff that could affect performance like that.

**Comment by sruloart** [comment]
You're just disabling your vsync BTW, so this can be a well known problem with SDL (and by extension Llime) with certain GPUs' vsync. Now, it's mostly related to the Intel on-board graphics (vsync is broken), but since your GPU is quite the "antique" (that's crazy I know) I guess it's possible.

**Comment by starry-abyss** [comment]
@Gama11 Yes, it seems like it's an empty project.
Strange thing, I tried Heroku Shaders, NyanCat, and EZPlatformer adding to project.xml this tag with true-true values. All ran fine, and then I tried empty project again, and it ran fine too!
I noticed that my Windows taskbar changed itself from semi-transparent to blue gradient just between the two tries (when it was 1 fps and when it was ok).
May be I have a problem with my OS then?
@sruloart What is that problem with SDL? Any test or info to verify that my GPU's vsync is broken?
Thanks!

**Comment by sruloart** [comment]
* It's more of a hardware problem SDL can't circumvent AFAI understand it. 
* The only test I know of is to set your vsync to false (while hardware="true") and see if your low FPS problem is resolved. If it is, then it's most likely connected to the vsync issue (there's more info about that in the OpenFL forum).

**Comment by starry-abyss** [comment]
Re-launched aero in Windows, everything is still fine. I can guess it somehow is related to my GPU being connected to monitor via a receiver or some nasty apps that screwed the HaxeFlixel rendering.
@sruloart Thanks for assistance. It's no more issue for me (hopefully), closing
