### ISSUE TITLE
FlxTileFilters are not working properly

### ISSUE THREAD

**Issue by SeiferTim** [HaxeFlixel/flixel#1615]
If you set up a TileFilter on a tilemap, after the collision is checked, the tile's `allowCollisions` flag is not being returned to its original value properly.

To reproduce:
Set up a tilemap with some tiles that collide.
Setup 2 classes of objects that can be moved somehow.
Setup a tilefilter for one of those objects, with collision flags : `tilemap.addTileFilter(1, SecondObjectClass, FlxObject.WALL, doSomething);`
In your PlayState, check collisions for both objects and your tilemap:
```
FlxG.collide(firstObject, tilemap);
FlxG.collide(secondObject, tilemap);
```

Test your project: firstObject should collide with the tilemap properly, UP UNTIL secondObject collides with the tile that the filter is on, at which point, firstObject will NO LONGER collide with that tile properly.

**Comment by Gama11** [comment]
What's `tilemap.addTileFilter()`?

**Comment by SeiferTim** [comment]
It's in `FlxBaseTilemap.addTileFilter`
(I used `tilemap` as an variable name in that example)

**Comment by Gama11** [comment]
It's not though.

**Comment by Gama11** [comment]
I guess you forgot that [you implemented this yourself?](https://github.com/HaxeFlixel/flixel/pull/1579) :P

**Comment by SeiferTim** [comment]
Ah-ha... yeah... wow... sorry about that... I'll try to fix it myself later on.... but.. if this does work, it only comes close to solving the issue I'm having with collision right now, but not completely... so, not urgent to fix it now. Thanks.
