### ISSUE TITLE
Reflected results sometimes being returned from FlxAngle.rotatePoint()

### ISSUE THREAD

**Issue by Nihilate** [HaxeFlixel/flixel#1619]
The x and y components returned by FlxAngle.rotatePoint() seem to be reflected when the point you want to rotate has a non-0 y component. For example:

- Rotating (1, 0) around (0, 0) by 45 degrees results in (x: 0.708 | y: 0.708), which is correct (if a little inaccurate - 1/sqrt(2) should be 0.707).

- Rotating (0, 1) around (0, 0) by 45 degrees, however, results in (x: 0.708 | y: -0.708) when it should be (x: -0.708 | y: 0.708).

- Rotating (0, -1) around (0, 0) by -45 degrees (that is to say counterclockwise) results in (x: 0.708 | y: 0.708) when it should be (x: -0.708 | y: -0.708).

I've made a diagram in Paint to make it easier to parse: http://i.imgur.com/SQ013Iz.png. The results can be reproduced using:

>FlxAngle.rotatePoint(1, 0, 0, 0, 45);
FlxAngle.rotatePoint(0, 1, 0, 0, 45);
FlxAngle.rotatePoint(0, -1, 0, 0, -45);

The issue seems to be present on all platforms (I've tried it with CPP, Flash and HTML5). It's a single line fix ("var dy:Float = Y - PivotY;" goes to "var dy:Float = PivotY - Y;") and I'd push it across myself, but the function doesn't look like it's present in the dev branch. Was it just not pulled over when FlxAngle was moved from util to math or is it becoming deprecated?

**Comment by Gama11** [comment]
Have you tried FlxPoint#rotate() on the dev branch? FlxAngle.rotatePoint() was kind of broken.

**Comment by Nihilate** [comment]
Ooh, thanks. Didn't realise there was another option around - I'll check it
out and get back to you.

**Comment by Gama11** [comment]
Not really "another option", the method has been moved there (and fixed) on dev.

**Comment by Nihilate** [comment]
Yep, looks like FlxPoint#rotate() is working as expected, thanks for the heads up. I'll go ahead and close the issue.
