### ISSUE TITLE
"get" console command

### ISSUE THREAD

**Issue by MSGhero** [HaxeFlixel/flixel#1621]
Playing around with the debugger for the first time. I know there's the watch table already, but sometimes I just want to see the value of something without writing it in the code. "get hero.isDead" or something using `getProperty()`. I'm not familiar with `addCommand()`, otherwise I would have pulled something.

Also, "fields" doesn't do anything for me, should it be listing things in the log window?

Recent dev, not the latest.

**Comment by Gama11** [comment]
What's your problem with `addCommand()`? Should be fairly straightforward.

**Comment by MSGhero** [comment]
The spawn enemy example doesn't have parameters and doesn't print anything to the console. The "set" command was just a lot of code, and I assumed "get" would be something that could be implemented by default.

**Comment by MSGhero** [comment]
I guess as an example, dconsole lets you type "sprite.x" and "sprite.x = 50" and both get printed to the log.

I'll figure it out and pull something, don't worry.

**Comment by Gama11** [comment]
I agree that this would be something that's useful to have built-in.

**Comment by MSGhero** [comment]
Let's say I registered some FlxSprite as "thing" and an Array_Int as "arr".

Do you think it should be able to handle `get thing`, `get arr`, and `get arr[0]` in addition to `get thing.x`.? I have everything but `get arr[0]` working, but that one is a bit of a pain based on how the `set` command that I copied from is structured.

**Comment by Gama11** [comment]
Perfectly fine not to support that.
