### ISSUE TITLE
FlxSpriteGroup changing position value when colliding

### ISSUE THREAD

**Issue by jmle** [HaxeFlixel/flixel#1622]
Hi there,

I'm having an issue when colliding a `FlxSpriteGroup` with a static object in my level's map. The problem is that when running into something and colliding, the sprite itself (its image) stops, but it's inner position keeps moving if I keep running it into the colliding object. So the sprite itself doesn't move over the object in the map, but the value of its position does. This screws the whole thing because I depend on the value of the position to do some calculations.

The way that I'm doing the collision is by using `FlxG.overlap(map, flxSpriteGroup, notify, FlxObject.separate)`, and I'm using the Tiled example to build my test map.

You can check the sample project here: https://github.com/jmle/jackal . If you activate the debug console you should be able to see the position of the `FlxSpriteGroup` changing when colliding with something. There are three main classes: `CombatJeep`, `Cannon` and `Jeep`. Also, the `TiledLevel` class is basically a copy of the sample project's one.

- This seems to happen with every target that I've tested (so far flash and OSX).
- The versions I'm using are: `openfl: 3.0.5 [3.0.6] 3.2.2` and `flixel: 3.3.11 [3.3.8]`.

Thank you.

**Comment by MSGhero** [comment]
This is more of a logic issue on your end. A sprite group can't collide with things; the things inside the group get collided. You have to specify that when one of the children stops, the entire group stops. Or the position of the sprite group is "always 50px less" than the child's position, something like that.

**Comment by adrianulima** [comment]
`FlxGroups` are not objects, is more like a list, I think you should use `FlxNestedSprite` instead.

**Comment by jmle** [comment]
@MSGhero @adrianulima Thank you both for the suggestions, I'll try them
