### ISSUE TITLE
When Pressing "LEFT", HaxeFlixel doesn't recognize "W" or "D"

### ISSUE THREAD

**Issue by JuiceBoos** [HaxeFlixel/flixel#1624]
Let me get this out of the way first, the way I'm checking for keyboard input is like this:

"_up = FlxG.keys.pressed.W;"

I have encountered a problem that when you press and hold "LEFT", HaxeFlixel doesn't seem to recognize "D" if you're pressing "W", and vice versa. I'm pretty sure this is a HaxeFlixel bug and not an issue with my game, since I commented out large chunks of code with arrow key input to test if the problem still exists without scripted inputs. And guess what, it still did.

I've tested this with both flash and neko, and the problem occurs in both. (Note that I'm also using Windows 10) If this doesn't occur for anyone else, then it might just be a problem on my end (obviously)

Flixel Version: 3.3.11
OpenFL Version: 3.3.3 [3.3.4]

**Comment by MSGhero** [comment]
That doesn't make sense. Either
- You're hitting your keyboard's key rollover limit (probably not)
- Your logic is incorrect (it is)

What you're doing is checking `if left/A are pressed`, `else if right/D are pressed` in your movement logic. If left is pressed, D just gets ignored because of the way your logic is set up. If you want to account for both at the same time, you can't put one in an `else if` which may never get run.
```haxe
up = FlxG.keys.pressed.W || FlxG.keys.pressed.UP;
down = FlxG.keys.pressed.S || FlxG.keys.pressed.DOWN;
if (up && down) up = down = false; // up and down cancel each other
else if (up) moveUp();
else if (down) moveDown();
```

**Comment by Gama11** [comment]
Yeah, definitely sounds like a logic error on your side. The following code can detect all 3 keys just fine at the same time:

```haxe
override public function update():Void 
{
	FlxG.watch.addQuick("Left pressed", FlxG.keys.pressed.LEFT);
	FlxG.watch.addQuick("W pressed", FlxG.keys.pressed.W);
	FlxG.watch.addQuick("D pressed", FlxG.keys.pressed.D);
	
	super.update();
}
```

![](http://i.imgur.com/CqQMwNo.png)

**Comment by JuiceBoos** [comment]
First of all, my code doesn't look like that at all. The arrow keys have absolutely nothing to do with movement. All of my input is handled like this:
```
_up = FlxG.keys.pressed.W;
_left = FlxG.keys.pressed.A;
_down = FlxG.keys.pressed.S;
_right = FlxG.keys.pressed.D;
```
Also I have put the keys into the watch list, and it actually doesn't recognize the keys being pressed. But, if you guys say it's a logic error, I'll just try to look through my code for another hour.

**Comment by sruloart** [comment]
I don't know if this case is related or not, but it seems like there are more issues with input events in the last few months than ever before, and I don't think it's Flixel's fault. 

@JuiceBoos what's your OS? What's your Haxe version and can you post your haxelib list? Are you using the "next" flag by any chance? try using a much, much older version of lime/openfl (say, 2.1.3/2.2.8 - you may have to change a few things in order for stuff to compile, but I'm not sure).

**Comment by JuiceBoos** [comment]
@sruloart 

I mentioned my OS before, it's Windows 10.
And sure, I'll post my haxelib list.
![haxelib list](http://puu.sh/ky8Mp/3b6b0e1da0.png)

I haven't used the "next" flag, haven't even heard of it until just now. I won't downgrade over a little bug like this, though. It's not a huge deal at the moment, since my project is only in its first stages of development. So a little bug like this won't make or break anything.

**Comment by larsiusprime** [comment]
Just to rule things out -- you sure it's not an issue with lack of N-key rollover on your keyboard? IE, will ANY application recognize that you have both LEFT and W held down at the same time? Many keyboards have a limit for how many keys you can have pressed at once and it depends a lot on which specific keys and how your keyboard has them wired up.

**Comment by JuiceBoos** [comment]
@larsiusprime 
Yeah, it's actually completely my fault. I feel a bit stupid now because of this :c 
I just tested it in a few other applications, an it is my computer. Thanks for reminding me of keyboard rollover ^)^

**Comment by larsiusprime** [comment]
NP. It's actually happened to me a bunch of times and every time it took me forever to figure it out ;)
