### ISSUE TITLE
FlxTilemap performance when using FlxAtlasFrames

### ISSUE THREAD

**Issue by IkonOne** [HaxeFlixel/flixel#1627]
On html5, when I create a FlxTilemap and use FlxAtlasFrames as the graphic, there is a performance impact directly related to the dimensions of the atlas frames bitmapdata.  The playstate pasted at the end of this comment is a demo of the issue.  It can be run and profiled in Chrome to see the impact quickly.

I have tried the pull request #1606 with no change in results(it actually may be worse).

I have no idea how to troubleshoot this because I am bad at javascript(or maybe javascript is bad at everything that ever made sense?).

OMG PLEASE HALP!!!!1!!11oneoneone

```
package;

import flixel.FlxG;
import flixel.FlxSprite;
import flixel.FlxState;
import flixel.text.FlxText;
import flixel.ui.FlxButton;
import flixel.tile.FlxTilemap;
import flixel.graphics.FlxGraphic;
import flash.geom.Rectangle;
import flixel.util.FlxColor;
import flixel.input.touch.FlxTouch;

import flixel.math.FlxPoint;
import flixel.math.FlxRect;
import flixel.graphics.atlas.FlxAtlas;
import flixel.graphics.frames.FlxAtlasFrames;
import flixel.graphics.frames.FlxTileFrames;

class PlayState extends FlxState
{
	var _frames:FlxAtlasFrames;
	var _map:FlxTilemap;
	var _touches:Array<FlxTouch>;
	var _dims:Int;

	public function new(dims:Int = 128) {
	   	super();
	   	_dims = dims;
	}

	override public function create():Void
	{
		super.create();

		var child = FlxG.stage.getChildByName("dims");

		var graphic = FlxGraphic.fromRectangle(_dims, _dims, FlxColor.TRANSPARENT);
		graphic.bitmap.fillRect(new Rectangle(32, 0, 32, 32), FlxColor.YELLOW);
		graphic.bitmap.fillRect(new Rectangle(64, 0, 32, 32), FlxColor.BLUE);
		graphic.bitmap.fillRect(new Rectangle(96, 0, 32, 32), FlxColor.RED);

		_frames = new FlxAtlasFrames(graphic);
		_frames.addAtlasFrame(FlxRect.get(0, 0, 32, 32), FlxPoint.get(32, 32), FlxPoint.get(), "tile_0");
		_frames.addAtlasFrame(FlxRect.get(32, 0, 32, 32), FlxPoint.get(32, 32), FlxPoint.get(), "tile_1");
		_frames.addAtlasFrame(FlxRect.get(64, 0, 32, 32), FlxPoint.get(32, 32), FlxPoint.get(), "tile_2");
		_frames.addAtlasFrame(FlxRect.get(96, 0, 32, 32), FlxPoint.get(32, 32), FlxPoint.get(), "tile_3");

		_map = new FlxTilemap();
		_map.immovable = true;
		_map.loadMapFromCSV(
			"1,1,1,1,1,
			2,2,2,2,2,
			3,3,3,3,3",
			_frames,
			32,
			32);
		_map.x = FlxG.width / 2 - _map.width / 2;
		_map.y = FlxG.height / 2 - _map.height / 2;
		add(_map);

		_touches = new Array<FlxTouch>();
	}

	override public function update(elapsed:Float):Void
	{
		// FlxG.touches.justStarted(_touches);
		if (FlxG.keys.justPressed.ANY || _touches.length > 0) {
			switch (_frames.parent.width) {
				case 128:
					FlxG.switchState(new PlayState(512));

				case 512:
					FlxG.switchState(new PlayState(1024));

				case 1024:
					FlxG.switchState(new PlayState(128));
			}
		}

		super.update(elapsed);
	}	
}
```

**Comment by IkonOne** [comment]
It may be useful to note that I am using FlxAtlasFrames instead of FlxAtlas because I am using Shoebox to create texture atlases and building the frames directly mimics the same behavior.  I'm not sure if that is relevant or not.

**Comment by sruloart** [comment]
Build in debug mode, enter the `viewCache` command onto the debugger's console. If you see a big bitmap that is as big as the screen, and you're not seeing `drawTiles` in the FPS window in the upper (your) right corner of the debugger, then you're not using 1606 (perhaps you didn't add the ```haxedef name="webgl"``` definition or used ```set name="webgl"``` instead).

**Comment by IkonOne** [comment]
So I was missing the haxedef in my project.xml, that increased the performance on desktop by miles.  Now chrome doesn't even blink at the game.  However, the issue still persists on Mobile since it is not using webgl.

Side note, I can't get the debugger to show up in html5.  Is there a guide or something that I can use to make that happen?

**Comment by sruloart** [comment]
`

**Comment by IkonOne** [comment]
Yes I meant mobile browsers.  Thank you for linking me to that matrix.

Did you mean to link/type something about the debugger?

**Comment by sruloart** [comment]
You press ``` ` ```

**Comment by IkonOne** [comment]
I'm using Sublime Text on OSX.  I build using ```openfl test html5``` which I assume does the same thing.  I have tried showing the debugger using ```FlxG.debugger.visible = true;``` as well to no avail.  Both methods (tilde and code) work a charm in flash, but not html5 for me.

**Comment by mrcdk** [comment]
You have to compile it with debug information: `openfl test html5 -debug`

**Comment by IkonOne** [comment]
Thank you both!

**Comment by IkonOne** [comment]
The issue I was having was a mistake I was making when compiling and not something inherently wrong with haxeflixel.  Although, the documentation on html5 is sparse at the moment, so I had to learn this the hard way(which is probably better anyway).

I was compiling with:

```openfl test html5```

When I _should_ have been compiling with:

```openfl test html5 -debug -Dwebgl -DFLX_RENDER_TILE```
