### ISSUE TITLE
Jittering on just 1 or 2 bullets?

### ISSUE THREAD

**Issue by ManlyChicken** [HaxeFlixel/flixel#1628]
Hey, I've been looking around and can't find a specific answer:
When I shoot bullets in a spread pattern, one or two tend to lag behind the others and jutter.
I've tried all combinations of pixelperfectrender and pixelperfect position and want to know if this is a problem that's in the process of being fixed or has been fixed.
I'm using the latest dev branch and exporting to Neko.

GIF of the problem:
https://i.gyazo.com/44ce2bc874c72580f9e1e7a87eb6c3b8.gif

**Comment by MSGhero** [comment]
That has to be some kind of logic problem, that doesn't look like a pixel perfect issue. The jittering maybe, but I can't see that from your gif. The lagging behind, that's your bullet not bouncing or something weird like that.

**Comment by ManlyChicken** [comment]
The bullets don't bounce, when the main bullet hits a wall it spawns a bunch of new bullets, so it technically doesn't bounce, unless you mean something else.
What kind of logic problems you think could cause it?

**Comment by MSGhero** [comment]
The pixel perfect issues really only affect the rendering of sprites, not their actual x,y position. Even then, they only affect it by at most ~1 pixel. 

I guess I say it's a logic problem because it looks like the first/last bullet that gets spawned is the one that gets messed up consistently each time. I'd have to see code to confirm, of course.

**Comment by ManlyChicken** [comment]
One more .gif (of the auto gun)
https://i.gyazo.com/c58ec559c0185cb3489dc0f9c4fb656e.gif
and here's a zip containing the shoot and player files (it's long and messy)
http://www.newgrounds.com/dump/item/c45922b9369ce1761da4466418a4035e

**Comment by sruloart** [comment]
It's 100% not related to pixel-perfect rendering/positioning. The delta is just way too big, it's impossible. Most likely you're not updating that lagging bullet at the correct time.

**Comment by ManlyChicken** [comment]
Cool, so I should just move the update function?
If so, where?
(I'm still somewhat new to Haxeflixel)

**Comment by sruloart** [comment]
Not what I've meant (a bad choice of words), but yeah, if we're at it, move the `super.update(_)` to the top of your update function. I could have been more specific but I can't physically read those two god-classes, at least without proper indentation, spaces and some comments :|

**Comment by ManlyChicken** [comment]
Sorry, I'm the only programmer working on this game and am pretty sloppy.
Putting the update at the beginning of the bullet, player, playstate does nothing.
Anyone else run into this problem, and if so was there a fix?

**Comment by MSGhero** [comment]
Can you post code? Flixel automatically updates everything that you add to the state, so you don't have to manually call that.

**Comment by ManlyChicken** [comment]
That zip contains my code, I've been trying to fix it, but can't get it to work.

**Comment by ManlyChicken** [comment]
I'm just gonna rewrite the bullet code from scratch, because that seems to be working.
Thanks everyone for all your help, I really appreciate it.
