### ISSUE TITLE
Unsupplied "Alignment" in FlxtText.setFormat() reverses alignment to LEFT

### ISSUE THREAD

**Issue by leoncvlt** [HaxeFlixel/flixel#1629]
Let's say I have a FlxText, and set its position and alignment.
```
_textTime = new FlxText(16, 16, FlxG.width);
_textTime.alignment = "right";
```
Afterwards setFormat() to use a custom font.
```
.setFormat(AssetPaths.pixel_font__ttf);
```

This reverts the alignment back to `LEFT`
I think It would be preferrable to keep the original alignment.

The `Alignment` argument in setFormat is optional and comes without a default value, which according to Haxe should return null. However `set_alignment` in FlxText runs thorugh `FlxTextAlign.fromOpenFL` which defaults to `LEFT`

Might be worthy to default it to `null` and in setFormat() do
```
if (Alignment != null) alignment = Alignment;
```

**Comment by MSGhero** [comment]
The problem with this is that AS3's TextFormat defaults to "left" each time you make a new one, so this is supposed to be the default behavior.

**Comment by leoncvlt** [comment]
I'm not making a new one though, I'm modifying an existing one - That's why I think it would make more sense to retain whatever alignment it posses in this case...
