### ISSUE TITLE
Javascript haxe_xml_Parser.doParse error

### ISSUE THREAD

**Issue by smks** [HaxeFlixel/flixel#1630]
**Uncaught TypeError: Cannot read property 'charCodeAt' of null**

    haxe_xml_Parser.doParse = function(str,strict,p,parent) {
	    if(p == null) p = 0;
	    var xml = null;
	    var state = 1;
	    var next = 1;
	    var aname = null;
	    var start = 0;
	    var nsubs = 0;
	    var nbrackets = 0;
	    var c = str.charCodeAt(p);

^^ p is **null**

It doesn't seem to correctly retrieve the XML, passing null instead. Issue seems to occur around this point. From the bottom of the stack:

    var flixel_util_loaders_SparrowData = function(Description,AssetName) {
	    flixel_util_loaders_TexturePackerData.call(this,Description,AssetName);
    };

....

    var flixel_util_loaders_TexturePackerData = function(Description,AssetName) {
	    this.assetName = AssetName;
	    this.description = Description;
	    this.frames = [];
	    this.parseData();
    };

....

    flixel_util_loaders_SparrowData.prototype = $extend(flixel_util_loaders_TexturePackerData.prototype,{
	parseData: function() {
		if(this.frames.length != 0) return;
		if(this.assetName == null || this.description == null) return;
		this.asset = flixel_FlxG.bitmap.addWithSpaces(this.assetName,0,0,1,1,false,null).bitmap;
		var data = new haxe_xml_Fast(Xml.parse(openfl_Assets.getText(this.description)).firstElement());

    Xml.parse = function(str) {
	return haxe_xml_Parser.parse(str);
    };

....

    haxe_xml_Parser.parse = function(str,strict) {
	if(strict == null) strict = false;
	var doc = Xml.createDocument();
	haxe_xml_Parser.doParse(str,strict,0,doc);

....

    haxe_xml_Parser.doParse = function(str,strict,p,parent) {
	if(p == null) p = 0;
	var xml = null;
	var state = 1;
	var next = 1;
	var aname = null;
	var start = 0;
	var nsubs = 0;
	var nbrackets = 0;
	var c = str.charCodeAt(p);

**ERROR**

The XML and PNG at this point are correct and work in all other targets, but not HTML5. The image and XML have successfully been loaded into the page. Could this be because there is a limit to how big the XML or PNG can be?

**Comment by Gama11** [comment]
The error alone isn't very useful without any code to reproduce it.

**Comment by smks** [comment]
class GameSpriteSheet
     {
	private static var atlas:SparrowData = null;

	public static function get():SparrowData
	{		
		if (GameSpriteSheet.atlas == null || GameSpriteSheet.atlas.asset == null) {
			GameSpriteSheet.atlas = new SparrowData(
				PathAssets.getAtlasXml(),
				PathAssets.getAtlasAsset()
			);
		}
		
		return atlas;
	}

**Comment by Gama11** [comment]
Code that can't be compiled (missing assets) isn't very usfeul either. ;)

**Comment by smks** [comment]
Yeah you're not wrong... :(

desktop.png
http://i.imgur.com/8WsV8n9.png

desktop.xml
<?xml version="1.0" encoding="UTF-8"?>


<TextureAtlas imagePath="desktop.png" width="1024" height="1024">
    <SubTexture name="awards/1" x="717" y="622" width="40" height="47"/>
    <SubTexture name="awards/10" x="966" y="2" width="55" height="79"/>
    <SubTexture name="awards/11" x="775" y="414" width="65" height="112" frameX="-2" frameY="0" frameWidth="69" frameHeight="112"/>
    <SubTexture name="awards/12" x="955" y="471" width="65" height="112" frameX="-2" frameY="0" frameWidth="69" frameHeight="112"/>
    <SubTexture name="awards/13" x="573" y="460" width="65" height="112" frameX="-2" frameY="0" frameWidth="69" frameHeight="112"/>
    <SubTexture name="awards/14" x="774" y="528" width="65" height="112" frameX="-2" frameY="0" frameWidth="69" frameHeight="112"/>
    <SubTexture name="awards/15" x="841" y="546" width="65" height="112" frameX="-2" frameY="0" frameWidth="69" frameHeight="112"/>
    <SubTexture name="awards/2" x="428" y="421" width="41" height="47"/>
    <SubTexture name="awards/3" x="908" y="546" width="40" height="47"/>
    <SubTexture name="awards/4" x="908" y="595" width="40" height="47"/>
    <SubTexture name="awards/5" x="908" y="644" width="40" height="47"/>
    <SubTexture name="awards/6" x="966" y="83" width="55" height="79"/>
    <SubTexture name="awards/7" x="966" y="164" width="55" height="79"/>
    <SubTexture name="awards/8" x="966" y="245" width="55" height="79"/>
    <SubTexture name="awards/9" x="962" y="326" width="55" height="79"/>
    <SubTexture name="backgrounds/grass" x="484" y="242" width="480" height="57"/>
    <SubTexture name="backgrounds/hills-1" x="2" y="314" width="240" height="19"/>
    <SubTexture name="backgrounds/hills-2" x="484" y="301" width="360" height="45"/>
    <SubTexture name="backgrounds/hills-3" x="2" y="265" width="480" height="47"/>
    <SubTexture name="backgrounds/night-sky" x="484" y="2" width="480" height="83"/>
    <SubTexture name="backgrounds/running-ground" x="2" y="2" width="480" height="198"/>
    <SubTexture name="backgrounds/sky" x="484" y="87" width="480" height="83"/>
    <SubTexture name="backgrounds/tree-1" x="244" y="314" width="182" height="106"/>
    <SubTexture name="backgrounds/tree-2" x="2" y="335" width="182" height="106"/>
    <SubTexture name="enemies/fox-running-shadow" x="640" y="550" width="89" height="8"/>
    <SubTexture name="enemies/fox-running000" x="842" y="454" width="111" height="44" frameX="0" frameY="-15" frameWidth="124" frameHeight="59"/>
    <SubTexture name="enemies/fox-running001" x="649" y="348" width="124" height="45" frameX="0" frameY="-14" frameWidth="124" frameHeight="59"/>
    <SubTexture name="enemies/fox-running002" x="649" y="395" width="124" height="42" frameX="0" frameY="-17" frameWidth="124" frameHeight="59"/>
    <SubTexture name="enemies/fox-running003" x="842" y="500" width="109" height="44" frameX="0" frameY="-15" frameWidth="124" frameHeight="59"/>
    <SubTexture name="enemies/fox-running004" x="640" y="500" width="97" height="48" frameX="0" frameY="-11" frameWidth="124" frameHeight="59"/>
    <SubTexture name="enemies/fox-running005" x="649" y="439" width="101" height="59" frameX="0" frameY="0" frameWidth="124" frameHeight="59"/>
    <SubTexture name="enemies/fox-stand-shadow" x="428" y="410" width="43" height="9"/>
    <SubTexture name="enemies/fox-stand001" x="846" y="301" width="114" height="49"/>
    <SubTexture name="enemies/fox-stand002" x="846" y="301" width="114" height="49"/>
    <SubTexture name="enemies/fox-stand003" x="846" y="301" width="114" height="49"/>
    <SubTexture name="enemies/fox-stand004" x="846" y="301" width="114" height="49"/>
    <SubTexture name="enemies/fox-stand005" x="846" y="352" width="114" height="49"/>
    <SubTexture name="enemies/fox-stand006" x="846" y="352" width="114" height="49"/>
    <SubTexture name="enemies/fox-stand007" x="846" y="352" width="114" height="49"/>
    <SubTexture name="enemies/fox-stand008" x="846" y="352" width="114" height="49"/>
    <SubTexture name="enemies/fox-stand009" x="846" y="352" width="114" height="49"/>
    <SubTexture name="enemies/fox-stand010" x="846" y="352" width="114" height="49"/>
    <SubTexture name="enemies/fox-stand011" x="846" y="352" width="114" height="49"/>
    <SubTexture name="enemies/fox-stand012" x="846" y="352" width="114" height="49"/>
    <SubTexture name="foregrounds/foreground" x="484" y="172" width="480" height="68"/>
    <SubTexture name="gui/scoreboard-bg" x="846" y="403" width="113" height="49"/>
    <SubTexture name="gui/scoreboard-bread" x="717" y="579" width="11" height="13"/>
    <SubTexture name="gui/scoreboard-corn" x="481" y="635" width="15" height="19"/>
    <SubTexture name="gui/scoreboard-heart" x="481" y="616" width="16" height="17"/>
    <SubTexture name="intro/smks" x="950" y="617" width="63" height="63"/>
    <SubTexture name="items/bread-shadow" x="739" y="500" width="10" height="3"/>
    <SubTexture name="items/bread" x="700" y="637" width="14" height="16"/>
    <SubTexture name="items/corn-shadow" x="739" y="500" width="10" height="3"/>
    <SubTexture name="items/corn" x="613" y="668" width="17" height="22"/>
    <SubTexture name="items/orb-1-shadow" x="739" y="500" width="10" height="3"/>
    <SubTexture name="items/orb-1" x="266" y="548" width="23" height="23"/>
    <SubTexture name="items/orb-2-shadow" x="739" y="500" width="10" height="3"/>
    <SubTexture name="items/orb-2" x="266" y="573" width="23" height="23"/>
    <SubTexture name="items/orb-3-shadow" x="739" y="500" width="10" height="3"/>
    <SubTexture name="items/orb-3" x="369" y="584" width="23" height="23"/>
    <SubTexture name="menu/buttons/button-bg-large-shade" x="775" y="348" width="69" height="64"/>
    <SubTexture name="menu/buttons/button-bg-large" x="640" y="560" width="75" height="75"/>
    <SubTexture name="menu/buttons/button-bg-shade" x="462" y="582" width="35" height="32"/>
    <SubTexture name="menu/buttons/button-bg" x="293" y="521" width="38" height="38"/>
    <SubTexture name="menu/buttons/icon-arrow" x="591" y="665" width="20" height="13"/>
    <SubTexture name="menu/buttons/icon-back" x="569" y="659" width="20" height="15"/>
    <SubTexture name="menu/buttons/icon-cross" x="375" y="509" width="20" height="20"/>
    <SubTexture name="menu/buttons/icon-help" x="569" y="676" width="19" height="23" frameX="-2" frameY="0" frameWidth="23" frameHeight="23"/>
    <SubTexture name="menu/buttons/icon-home" x="610" y="574" width="23" height="22"/>
    <SubTexture name="menu/buttons/icon-level" x="456" y="616" width="23" height="21" frameX="0" frameY="-1" frameWidth="23" frameHeight="23"/>
    <SubTexture name="menu/buttons/icon-play-large" x="424" y="530" width="38" height="41"/>
    <SubTexture name="menu/buttons/icon-play" x="658" y="657" width="18" height="19"/>
    <SubTexture name="menu/buttons/icon-replay-large" x="186" y="380" width="45" height="51"/>
    <SubTexture name="menu/buttons/icon-replay" x="372" y="531" width="23" height="25"/>
    <SubTexture name="menu/buttons/icon-settings" x="372" y="558" width="23" height="24"/>
    <SubTexture name="menu/buttons/icon-share" x="375" y="486" width="20" height="21"/>
    <SubTexture name="menu/buttons/icon-sound-volume-on" x="233" y="380" width="9" height="16"/>
    <SubTexture name="menu/buttons/icon-sound" x="717" y="560" width="12" height="17"/>
    <SubTexture name="menu/buttons/icon-star" x="547" y="659" width="20" height="20"/>
    <SubTexture name="menu/buttons/icon-store" x="394" y="586" width="23" height="23"/>
    <SubTexture name="menu/buttons/icon-tick" x="633" y="661" width="18" height="19"/>
    <SubTexture name="menu/judge/dislike" x="523" y="657" width="22" height="22"/>
    <SubTexture name="menu/judge/judge-bg" x="397" y="487" width="25" height="25"/>
    <SubTexture name="menu/judge/like" x="634" y="637" width="22" height="22"/>
    <SubTexture name="menu/judge/neutral" x="592" y="641" width="22" height="22"/>
    <SubTexture name="menu/main-menu-bar" x="2" y="202" width="480" height="61"/>
    <SubTexture name="menu/main-menu-ronnie" x="480" y="348" width="167" height="110"/>
    <SubTexture name="menu/main-menu-title" x="2" y="479" width="141" height="63"/>
    <SubTexture name="menu/progress/progress-bar-overlay" x="2" y="443" width="161" height="34"/>
    <SubTexture name="menu/ratings/star-false" x="950" y="682" width="62" height="60"/>
    <SubTexture name="menu/ratings/star-true" x="229" y="486" width="62" height="60"/>
    <SubTexture name="menu/social/email" x="541" y="584" width="29" height="29"/>
    <SubTexture name="menu/social/facebook" x="572" y="599" width="29" height="29"/>
    <SubTexture name="menu/social/share" x="603" y="610" width="29" height="29"/>
    <SubTexture name="menu/social/twitter" x="499" y="603" width="29" height="29"/>
    <SubTexture name="obstacles/fence" x="233" y="422" width="163" height="62"/>
    <SubTexture name="obstacles/hay-shadow" x="186" y="335" width="49" height="43"/>
    <SubTexture name="obstacles/hay" x="961" y="407" width="61" height="62"/>
    <SubTexture name="obstacles/hole" x="950" y="585" width="65" height="30"/>
    <SubTexture name="obstacles/log-shadow" x="165" y="443" width="19" height="38"/>
    <SubTexture name="obstacles/log" x="752" y="439" width="21" height="47"/>
    <SubTexture name="obstacles/log2" x="428" y="314" width="50" height="53"/>
    <SubTexture name="obstacles/mud" x="774" y="642" width="65" height="32"/>
    <SubTexture name="obstacles/rock-shadow" x="423" y="573" width="37" height="12"/>
    <SubTexture name="obstacles/rock" x="464" y="562" width="37" height="18" frameX="0" frameY="0" frameWidth="37" frameHeight="19"/>
    <SubTexture name="players/ronnie/ronnie-die000" x="658" y="637" width="19" height="18" frameX="-13" frameY="-10" frameWidth="45" frameHeight="39"/>
    <SubTexture name="players/ronnie/ronnie-die001" x="752" y="488" width="21" height="20" frameX="-12" frameY="-9" frameWidth="45" frameHeight="39"/>
    <SubTexture name="players/ronnie/ronnie-die002" x="397" y="565" width="24" height="19" frameX="-10" frameY="-10" frameWidth="45" frameHeight="39"/>
    <SubTexture name="players/ronnie/ronnie-die003" x="419" y="587" width="35" height="31" frameX="-5" frameY="-4" frameWidth="45" frameHeight="39"/>
    <SubTexture name="players/ronnie/ronnie-die004" x="906" y="693" width="40" height="35" frameX="-2" frameY="-2" frameWidth="45" frameHeight="39"/>
    <SubTexture name="players/ronnie/ronnie-die005" x="428" y="369" width="45" height="39"/>
    <SubTexture name="players/ronnie/ronnie-die006" x="561" y="630" width="29" height="27" frameX="-9" frameY="-6" frameWidth="45" frameHeight="39"/>
    <SubTexture name="players/ronnie/ronnie-die007" x="530" y="615" width="29" height="29" frameX="-9" frameY="-5" frameWidth="45" frameHeight="39"/>
    <SubTexture name="players/ronnie/ronnie-die008" x="398" y="422" width="28" height="7" frameX="-9" frameY="-16" frameWidth="45" frameHeight="39"/>
    <SubTexture name="players/ronnie/ronnie-die009" x="398" y="444" width="27" height="9" frameX="-9" frameY="-15" frameWidth="45" frameHeight="39"/>
    <SubTexture name="players/ronnie/ronnie-die010" x="398" y="455" width="27" height="9" frameX="-9" frameY="-15" frameWidth="45" frameHeight="39"/>
    <SubTexture name="players/ronnie/ronnie-die011" x="397" y="514" width="25" height="9" frameX="-10" frameY="-15" frameWidth="45" frameHeight="39"/>
    <SubTexture name="players/ronnie/ronnie-die012" x="397" y="525" width="25" height="9" frameX="-10" frameY="-15" frameWidth="45" frameHeight="39"/>
    <SubTexture name="players/ronnie/ronnie-die013" x="524" y="646" width="23" height="9" frameX="-11" frameY="-15" frameWidth="45" frameHeight="39"/>
    <SubTexture name="players/ronnie/ronnie-die014" x="397" y="547" width="25" height="7" frameX="-10" frameY="-16" frameWidth="45" frameHeight="39"/>
    <SubTexture name="players/ronnie/ronnie-die015" x="397" y="556" width="25" height="7" frameX="-10" frameY="-16" frameWidth="45" frameHeight="39"/>
    <SubTexture name="players/ronnie/ronnie-die016" x="398" y="477" width="26" height="8" frameX="-9" frameY="-15" frameWidth="45" frameHeight="39"/>
    <SubTexture name="players/ronnie/ronnie-die017" x="541" y="575" width="30" height="7" frameX="-7" frameY="-16" frameWidth="45" frameHeight="39"/>
    <SubTexture name="players/ronnie/ronnie-die018" x="739" y="544" width="33" height="7" frameX="-6" frameY="-16" frameWidth="45" frameHeight="39"/>
    <SubTexture name="players/ronnie/ronnie-die019" x="499" y="594" width="35" height="7" frameX="-5" frameY="-16" frameWidth="45" frameHeight="39"/>
    <SubTexture name="players/ronnie/ronnie-die020" x="739" y="510" width="34" height="8" frameX="-6" frameY="-15" frameWidth="45" frameHeight="39"/>
    <SubTexture name="players/ronnie/ronnie-die021" x="739" y="533" width="33" height="9" frameX="-6" frameY="-15" frameWidth="45" frameHeight="39"/>
    <SubTexture name="players/ronnie/ronnie-die022" x="739" y="520" width="33" height="11" frameX="-6" frameY="-14" frameWidth="45" frameHeight="39"/>
    <SubTexture name="players/ronnie/ronnie-die023" x="572" y="586" width="32" height="11" frameX="-7" frameY="-14" frameWidth="45" frameHeight="39"/>
    <SubTexture name="players/ronnie/ronnie-die024" x="541" y="562" width="30" height="11" frameX="-8" frameY="-14" frameWidth="45" frameHeight="39"/>
    <SubTexture name="players/ronnie/ronnie-die025" x="398" y="466" width="27" height="9" frameX="-9" frameY="-16" frameWidth="45" frameHeight="39"/>
    <SubTexture name="players/ronnie/ronnie-die026" x="498" y="648" width="23" height="8" frameX="-11" frameY="-17" frameWidth="45" frameHeight="39"/>
    <SubTexture name="players/ronnie/ronnie-die027" x="679" y="652" width="19" height="8" frameX="-13" frameY="-17" frameWidth="45" frameHeight="39"/>
    <SubTexture name="players/ronnie/ronnie-die028" x="616" y="657" width="15" height="9" frameX="-15" frameY="-18" frameWidth="45" frameHeight="39"/>
    <SubTexture name="players/ronnie/ronnie-die029" x="759" y="637" width="13" height="11" frameX="-16" frameY="-17" frameWidth="45" frameHeight="39"/>
    <SubTexture name="players/ronnie/ronnie-die030" x="717" y="594" width="11" height="12" frameX="-17" frameY="-17" frameWidth="45" frameHeight="39"/>
    <SubTexture name="players/ronnie/ronnie-die031" x="759" y="622" width="13" height="13" frameX="-16" frameY="-18" frameWidth="45" frameHeight="39"/>
    <SubTexture name="players/ronnie/ronnie-die032" x="616" y="641" width="15" height="14" frameX="-15" frameY="-17" frameWidth="45" frameHeight="39"/>
    <SubTexture name="players/ronnie/ronnie-die033" x="679" y="637" width="19" height="13" frameX="-13" frameY="-19" frameWidth="45" frameHeight="39"/>
    <SubTexture name="players/ronnie/ronnie-die034" x="499" y="634" width="23" height="12" frameX="-11" frameY="-20" frameWidth="45" frameHeight="39"/>
    <SubTexture name="players/ronnie/ronnie-die035" x="398" y="431" width="27" height="11" frameX="-9" frameY="-21" frameWidth="45" frameHeight="39"/>
    <SubTexture name="players/ronnie/ronnie-die036" x="606" y="598" width="32" height="10" frameX="-7" frameY="-22" frameWidth="45" frameHeight="39"/>
    <SubTexture name="players/ronnie/ronnie-die037" x="573" y="574" width="35" height="10" frameX="-5" frameY="-23" frameWidth="45" frameHeight="39"/>
    <SubTexture name="players/ronnie/ronnie-die038" x="424" y="506" width="39" height="10" frameX="-3" frameY="-28" frameWidth="45" frameHeight="39"/>
    <SubTexture name="players/ronnie/ronnie-die039" x="424" y="518" width="39" height="10" frameX="-3" frameY="-26" frameWidth="45" frameHeight="39"/>
    <SubTexture name="players/ronnie/ronnie-flying001" x="503" y="562" width="36" height="30" frameX="-1" frameY="-10" frameWidth="39" frameHeight="40"/>
    <SubTexture name="players/ronnie/ronnie-flying002" x="503" y="562" width="36" height="30" frameX="-1" frameY="-10" frameWidth="39" frameHeight="40"/>
    <SubTexture name="players/ronnie/ronnie-flying003" x="333" y="521" width="37" height="38" frameX="-1" frameY="-2" frameWidth="39" frameHeight="40"/>
    <SubTexture name="players/ronnie/ronnie-flying004" x="333" y="521" width="37" height="38" frameX="-1" frameY="-2" frameWidth="39" frameHeight="40"/>
    <SubTexture name="players/ronnie/ronnie-flying005" x="227" y="548" width="37" height="38" frameX="-1" frameY="-2" frameWidth="39" frameHeight="40"/>
    <SubTexture name="players/ronnie/ronnie-flying006" x="227" y="548" width="37" height="38" frameX="-1" frameY="-2" frameWidth="39" frameHeight="40"/>
    <SubTexture name="players/ronnie/ronnie-flying007" x="145" y="525" width="39" height="33" frameX="0" frameY="-7" frameWidth="39" frameHeight="40"/>
    <SubTexture name="players/ronnie/ronnie-flying008" x="145" y="525" width="39" height="33" frameX="0" frameY="-7" frameWidth="39" frameHeight="40"/>
    <SubTexture name="players/ronnie/ronnie-flying009" x="186" y="544" width="39" height="33" frameX="0" frameY="-7" frameWidth="39" frameHeight="40"/>
    <SubTexture name="players/ronnie/ronnie-flying010" x="186" y="544" width="39" height="33" frameX="0" frameY="-7" frameWidth="39" frameHeight="40"/>
    <SubTexture name="players/ronnie/ronnie-flying011" x="145" y="525" width="39" height="33" frameX="0" frameY="-7" frameWidth="39" frameHeight="40"/>
    <SubTexture name="players/ronnie/ronnie-flying012" x="145" y="525" width="39" height="33" frameX="0" frameY="-7" frameWidth="39" frameHeight="40"/>
    <SubTexture name="players/ronnie/ronnie-flying013" x="186" y="544" width="39" height="33" frameX="0" frameY="-7" frameWidth="39" frameHeight="40"/>
    <SubTexture name="players/ronnie/ronnie-flying014" x="186" y="544" width="39" height="33" frameX="0" frameY="-7" frameWidth="39" frameHeight="40"/>
    <SubTexture name="players/ronnie/ronnie-flying015" x="293" y="486" width="39" height="33" frameX="0" frameY="-7" frameWidth="39" frameHeight="40"/>
    <SubTexture name="players/ronnie/ronnie-flying016" x="293" y="486" width="39" height="33" frameX="0" frameY="-7" frameWidth="39" frameHeight="40"/>
    <SubTexture name="players/ronnie/ronnie-flying017" x="334" y="486" width="39" height="33" frameX="0" frameY="-7" frameWidth="39" frameHeight="40"/>
    <SubTexture name="players/ronnie/ronnie-flying018" x="334" y="486" width="39" height="33" frameX="0" frameY="-7" frameWidth="39" frameHeight="40"/>
    <SubTexture name="players/ronnie/ronnie-flying019" x="145" y="483" width="39" height="40"/>
    <SubTexture name="players/ronnie/ronnie-flying020" x="145" y="483" width="39" height="40"/>
    <SubTexture name="players/ronnie/ronnie-in-hole" x="186" y="506" width="39" height="36"/>
    <SubTexture name="players/ronnie/ronnie-stand0002" x="186" y="470" width="41" height="34" frameX="0" frameY="-1" frameWidth="41" frameHeight="35"/>
    <SubTexture name="players/ronnie/ronnie-stand0003" x="186" y="470" width="41" height="34" frameX="0" frameY="-1" frameWidth="41" frameHeight="35"/>
    <SubTexture name="players/ronnie/ronnie-stand0004" x="730" y="588" width="41" height="32" frameX="0" frameY="-2" frameWidth="41" frameHeight="35"/>
    <SubTexture name="players/ronnie/ronnie-stand0005" x="731" y="553" width="41" height="33" frameX="0" frameY="-2" frameWidth="41" frameHeight="35"/>
    <SubTexture name="players/ronnie/ronnie-stand0006" x="427" y="470" width="41" height="34" frameX="0" frameY="-1" frameWidth="41" frameHeight="35"/>
    <SubTexture name="players/ronnie/ronnie-stand0007" x="186" y="433" width="41" height="35"/>
    <SubTexture name="players/ronnie/ronnie-stand0008" x="291" y="561" width="37" height="35" frameX="-2" frameY="0" frameWidth="41" frameHeight="35"/>
    <SubTexture name="players/ronnie/ronnie-stand001" x="330" y="561" width="37" height="35" frameX="-2" frameY="0" frameWidth="41" frameHeight="35"/>
    <SubTexture name="players/ronnie/shadow" x="397" y="536" width="25" height="9"/>
    <SubTexture name="ui/base" x="471" y="460" width="100" height="100"/>
    <SubTexture name="ui/thumb" x="841" y="660" width="63" height="62"/>
</TextureAtlas>

**Comment by Gama11** [comment]
Not sure if that was meant to be sarcastic, but like I said, code that can't be compiled is not too useful for reproducing an issue.
