### ISSUE TITLE
Where is FlxSpriteFilter

### ISSUE THREAD

**Issue by CurlyBraceTT** [HaxeFlixel/flixel#1632]
How should I use GlowFilter etc?

Commit with deleting:
SHA-1: 78035722c1ce897958a480d47f8fdcae506f3e05

* Merge branch 'dev' into render_refactor_3

Conflicts:
	flixel/math/FlxPoint.hx
	flixel/tile/FlxBaseTilemap.hx
	flixel/tile/FlxTileblock.hx
	flixel/tile/FlxTilemap.hx
	flixel/ui/FlxButton.hx
	flixel/util/loaders/CachedGraphics.hx

**Comment by Gama11** [comment]
That commit you linked isn't really related to the refactor. Anyway, please refer to [the demo](https://github.com/HaxeFlixel/flixel-demos/blob/dev/Effects/FlxSpriteFilters/source/PlayState.hx) for filter usage.

**Comment by CurlyBraceTT** [comment]
Ok, my bad, thank you!
