### ISSUE TITLE
FlxBitmapText dies on draw if text == ""

### ISSUE THREAD

**Issue by SeiferTim** [HaxeFlixel/flixel#1639]
To reproduce:

create a new FlxBitmapText, give it text, and a font, add it to your state.
at some point after that, set your text = ""
Also dies if you try to get `width` once text == ""

**Comment by larsiusprime** [comment]
Could you define "dies" -- crash, or calls the kill() function, or
something else?

On Thu, Oct 22, 2015 at 2:13 PM, Tim I Hely <notifications@github.com>
wrote:

> To reproduce:
>
> create a new FlxBitmapText, give it text, and a font, add it to your state.
> at some point after that, set your text = ""
> Also dies if you try to get width once text == ""
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HaxeFlixel/flixel/issues/1639>.
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by SeiferTim** [comment]
Crashes with an `Invalid BitmapData` in `draw`.

**Comment by Beeblerox** [comment]
i'll try to fix it tomorrow (i'd like to be "back in the saddle")

**Comment by SeiferTim** [comment]
It looks like it could be related to the `width` being = 0. There's a check that says `if height <= 0 then height = 1` but nothing similar for width... I'm not positive, though...

**Comment by Beeblerox** [comment]
@SeiferTim yeah, i think you're right about it

**Comment by Beeblerox** [comment]
so you can fix by changing the line 556 from:
`frameWidth = txtWidth;`
to
`frameWidth = (txtWidth == 0) ? 1 : txtWidth;`

**Comment by Beeblerox** [comment]
i believe that this issue is resolved.
@SeiferTim can you check it.
getting the `width` of bitmap text caused the same crash due to the fact that `width` getter runs checks whether text field had been changed or not and then it could run regeneration of its canvas => `Invalid BitmapData`

**Comment by SeiferTim** [comment]
I won't be able to look at it until Monday maybe... sorry...

**Comment by Beeblerox** [comment]
no worries at all :)

**Comment by SeiferTim** [comment]
Yeah, that fixes the issue. Thanks!
