### ISSUE TITLE
Flash games slow down when key repetition is fast

### ISSUE THREAD

**Issue by jmle** [HaxeFlixel/flixel#1643]
This is happening with OSX Yosemite when a game is compiled for the flash target.

To reproduce, set the Key repetition in the Keyboard Preferences to the fastest possible and try to move a sprite around. The sprite moves, but very slowly. If the Key repetition is slowed, the game behaves correctly.

Versions being used:

- flixel: 3.3.11 [3.3.8]
- openfl: 3.0.5 [3.0.6] 3.2.2

Code being tested:

- https://github.com/jmle/jackal

This is not happening for the rest of the targets (i.e native OSX), so I'm guessing it's just flash being somehow unable to cope with so much input so fast, but anyway wanted to register it here.

Thanks.

**Comment by Gama11** [comment]
Issues like that have come up multiple times in the forums in the past. It's just the flash player being the flash player, not something flixel can do much about (especially the flash debug player can behave a little erratic).

**Comment by jmle** [comment]
@Gama11 fair enough, I supposed it. Thank you.
