### ISSUE TITLE
No sound on load: [Sound.hx:118: Error]

### ISSUE THREAD

**Issue by pizzamakesgames** [HaxeFlixel/flixel#1644]
Happening inconsistently on both neko and cpp, resulting in no sound being able to load.

On both targets, it may happen at any time the game is started, after it's already been compiled.

Neko:
```
Build succeeded
Done(0)
haxelib run lime run "Project.xml" neko -debug
Running process: D:\hyperdev\haxe\haxe\haxelib.exe run lime run "Project.xml" neko -debug
Sound.hx:118: Error: Could not load "assets/music/SnowPath_nonproperloop.ogg"
AL lib: (EE) MMDevApiOpenPlayback: Device init failed: 0x80004005
Invalid operation (/)
Called from flixel.system.FlxSound::update line 241
Called from flixel.system.frontEnds.SoundFrontEnd::update line 273
Called from flixel.FlxGame::update line 696
Called from flixel.FlxGame::step line 648
Called from flixel.FlxGame::onEnterFrame line 493
Called from openfl._legacy.events.EventDispatcher::dispatchEvent line 98
Called from openfl._legacy.display.DisplayObject::__dispatchEvent line 182
Called from openfl._legacy.display.DisplayObject::__broadcast line 161
Called from openfl._legacy.display.DisplayObjectContainer::__broadcast line 280
Called from openfl._legacy.display.Stage::__render line 1103
Called from openfl._legacy.display.Stage::__checkRender line 351
Called from openfl._legacy.display.Stage::__pollTimers line 1084
Called from openfl._legacy.display.Stage::__doProcessStageEvent line 430
Done(1)
```
Windows:
```
Build succeeded
Done(0)
haxelib run lime run "project.xml" windows -debug
Running process: D:\Projects\hyperdev\haxe\haxelib.exe run lime run "project.xml" windows -debug
Sound.hx:118: Error: Could not load "assets/sounds/PizzaIntro4_1.ogg"
```

This error has been persisting across different sounds (both .ogg and .wav), states and even games for me. If you want to try it yourself, this game should have the error on about every 20th start, bringing up my silly [workaround screen](http://i.imgur.com/mWAHUmX.png): https://www.dropbox.com/s/rdksc78r6l3vxm7/SkullzTwoSoundError118.rar

**Comment by pizzamakesgames** [comment]
Had a lot of people test it for me and even got a program written that starts the game in quick succession in the hope to force the error, though it has not been happening anywhere but on my own PC. Would that help narrow the issue down? I did do a complete reinstall of HaxeFlixel, Haxe, Neko, OpenFL, Lime and Flashdevelop already. What else could be the cause of this?

**Comment by larsiusprime** [comment]
Hmmm, this is really weird! As it happens, I seem to recall running across this myself once or twice.

Are you using the -Dnext flag or not?

**Comment by pizzamakesgames** [comment]
I'm not using the -Dnext flag. Using it for the windows target results in a lot of stuttering and frequent crashes. Using it for the neko target results in an error prompt saying something about a procedure entry point "neko_buffer_length" not found in "neko.dll" DLL and then this in the cmd window: Uncaught exception - load.c(237) : Failed to load library : ./std.ndll.

**Comment by larsiusprime** [comment]
It's hard to tell.

The neko_buffer_length thing might be related to your total project size; IIRC neko can't compile projects above a certain size, especially if you're embedding assets.

Also, are you using the release version of flixel or the dev version? dev version of HaxeFlixel combined with -Dnext has been very stable for me on a very large project.

**Comment by sruloart** [comment]
As far as I can read, this error is related to quite particular hardware setups / old audio drivers. 

I did open an issue a long time ago (https://github.com/openfl/lime/issues/109), but it was on a laptop with a quirky sound system as well (laptop is now sadly deceased). 

I see here: http://community.openfl.org/t/openal-errors-in-windows/111/4 that openfl-next might be able to prevent this crash (only on cpp?), and it seems important enough since we know that OpenFL based games are vulnerable (https://steamcommunity.com/app/253790/discussions/0/540732347262423880/#p2). @jgranick, @mrcdk is it something that can be resolved somehow on your end?

**Comment by pizzamakesgames** [comment]
Looking at this script: http://pastebin.com/DXf3nmkL

Might that be that issue: "I don't know what lime_sound_from_file is, but don't you typically pass the URLRequest itself, not the string version of the url" ?

**Comment by pizzamakesgames** [comment]
Well, I'm sorry to say this now keeps happening during gameplay:

```
Build succeeded
Done(0)
haxelib run lime run "project.xml" neko -debug
Running process: D:\Projects\hyperdev\haxe\haxelib.exe run lime run "project.xml" neko -debug
AL lib: (EE) alc_cleanup: 1 device not closed
Invalid operation (/)
Called from flixel.system.FlxSound::update line 241
Called from flixel.group.FlxTypedGroup::update line 89
Called from flixel.system.frontEnds.SoundFrontEnd::update line 278
Called from flixel.FlxGame::update line 696
Called from flixel.FlxGame::step line 648
Called from flixel.FlxGame::onEnterFrame line 493
Called from openfl._legacy.events.EventDispatcher::dispatchEvent line 98
Called from openfl._legacy.display.DisplayObject::__dispatchEvent line 182
Called from openfl._legacy.display.DisplayObject::__broadcast line 161
Called from openfl._legacy.display.DisplayObjectContainer::__broadcast line 286
Called from openfl._legacy.display.Stage::__render line 1103
Called from openfl._legacy.display.Stage::__checkRender line 351
Called from openfl._legacy.display.Stage::__pollTimers line 1084
Called from openfl._legacy.display.Stage::__doProcessStageEvent line 430
Done(1)
```

Specifically, upon ProgressMusic() in this script:

```
package;
import flixel.FlxG;
import flixel.FlxState;
import flixel.system.FlxSound;

class SnowWalk extends FlxState
{
	public var MusicProgression:Int = 0;
	public var Music01 = new FlxSound();
	public var Music02 = new FlxSound();
	public var Music03 = new FlxSound();
	public var Bridge:Int = 0;

	override public function create():Void
	{
		Music01 = FlxG.sound.load("snowwalk_01",1,false,false,true,"",ProgressMusic);
		add(Music01);
		
		Music02 = FlxG.sound.load("snowwalk_02",1,false,false,false,"",ProgressMusic);
		add(Music02);
		
		Music03 = FlxG.sound.load("snowwalk_03",1,false,false,false,"",ProgressMusic);
		add(Music03);
	}
	
	override public function update():Void
	{
		
		//trace (Music01.playing);
	}
	public function ProgressMusic():Void
	{
		if (MusicProgression == 0)
		{
			Music02.play();
		}
		if (MusicProgression == 1)
		{
			Music03.play();
		}
		MusicProgression += 1;
	}
}
```

Sounds are being handled in the Project.xml like this.
```
	<assets path="assets/sounds" unless="flash">
	<music path="snowwalk_01.ogg" id="snowwalk_01" />
	<music path="snowwalk_02.ogg" id="snowwalk_02" />
	<music path="snowwalk_03.ogg" id="snowwalk_03" />
	</assets>
```

This suuucks, man.

**Comment by pizzamakesgames** [comment]
Got a case in which the error is consistently thrown during runtime now.
It happens on neko, but not on windows cpp.

Here's the error: http://pastebin.com/sDPvJxv5
Here's the class: http://pastebin.com/guPVFZUm

The error happens on ProgressMusic01() every time with both .ogg and .wav.

**Comment by Gama11** [comment]
OpenFL issue tracking this bug: https://github.com/openfl/openfl/issues/962

**Comment by Gama11** [comment]
https://github.com/openfl/lime/blob/master/legacy/project/src/common/Audio.cpp

**Comment by pizzamakesgames** [comment]
Thank you, I was going to try out your fix but ever since changing to the dev branch of flixel and updating all libs in the process, I seem to be unable to reproduce the issue. I've run a program to start and close the game continuously in short intervals and even after close to 50 attempts the issue did not come up. For me, this would mark the issue as solved, as I don't have any reason to go back to the master branch of flixel, though I guess for the purposes of using the master branch, the issue'd pertain. I'd say I keep on developing and if it ever comes up again I'll chime in again...?

**Comment by Gama11** [comment]
I doubt this is a Flixel issue / that you'd be able to reproduce it by going back to the master branch (there have barely been any changes to `FlxSound`, and none of those seem relevant to this). If anything, OpenFL / Lime changes made a difference.

I guess I'll close this until it comes up again.

**Comment by pizzamakesgames** [comment]
Happened for the first time again in forever, but it did happen. Completely different and new project.

![](http://i.imgur.com/CoNNpXl.png)

Should I open an issue with OpenFL or...?

**Comment by pizzamakesgames** [comment]
[Video showing the issue.](https://youtu.be/PjcJBSdUS0E)
