### ISSUE TITLE
Camera.fade doesn't seem to work on HTML5

### ISSUE THREAD

**Issue by SeiferTim** [HaxeFlixel/flixel#1646]
Just as described, setup a FlxState with some stuff on it, and set the camera to fade in or out and nothing happens on HTML5.

`FlxG.camera.fade(FlxColor.BLACK, 1, true);`
##

**Comment by sruloart** [comment]
I think this is just a symptom of the background sprite not scaling on html5 issue.

**Comment by smks** [comment]
Yes this has been a known issue for a while in my project. Any update on this?

**Comment by Gama11** [comment]
>The same applies to flash.

Are you sure about that? I don't know about any issues on Flash.

**Comment by smks** [comment]
Sorry I mean FlxG.camera.flash

**Comment by smks** [comment]
Alpha does not work. Just shows a solid color for a few seconds.

**Comment by Gama11** [comment]
Please open a separate, proper issue with a way to reproduce the issue.

**Comment by oxue** [comment]
The first comment is the way to reproduce this issue is it not?

**Comment by DanilaFe** [comment]
Just ran into this. Is there no workaround?

**Comment by besserwisser** [comment]
Just ran into this, too. Works fine when compiling to android, but does not work with HTML5.

**Comment by Gama11** [comment]
I can no longer reproduce this with OpenFL 8.
