### ISSUE TITLE
FlxSprite.animation.finished returns false in callback (for the third time?)

### ISSUE THREAD

**Issue by filipp8** [HaxeFlixel/flixel#1652]
Thread from last year is [here](FlxSprite.animation.finished returns false in callback)
animation.finished is true in update() but not in animation.callback
Example code:

	class ExampleSprite extends FlxSprite
	{
	
		public function new(X:Float=0, Y:Float=0) 
		{
			super(X, Y);
			loadGraphic(AssetPaths.enemy01__png, true, 16, 16);
			animation.add("play", [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], 10, false);
			animation.callback = animationCallback;
			animation.play("play");
		}
		
		override public function update():Void {
			trace("UPDATE " + animation.finished);
			super.update();
		}
		
		private function animationCallback(anim:String, frameNumber:Int, frameIndex:Int):Void {
			trace("Animation " + anim + ", frame " + frameNumber + " index " + frameIndex + " finished " + animation.finished);
		}
	}

From the trace it seems that the callback is not fired after the last frame.

**Comment by Gama11** [comment]
Flixel version?

**Comment by filipp8** [comment]
latest... everything is up to date...

**Comment by Beeblerox** [comment]
that's because animation update is called in super.update(elapsed);

**Comment by Beeblerox** [comment]
and you wrote "latest". Did you mean latest from haxelib or from gihub?

**Comment by filipp8** [comment]
I'm sorry, it's up to date with "haxelib upgrade"

**Comment by filipp8** [comment]
ok, I was using 3.3.11...
Now I'm using 4.0.0 and I have a ton of errors when building my project and I can't see anymore vars in my Reg class...
Is there a more detailed guide on using flixel-dev than the changelog?

**Comment by sruloart** [comment]
No, at least not yet. If you really want to see how dev projects look like you can check out the dev branch of the demos.

Still, the "ton of errors" are probably about adding elapsed to your update() functions and changing a few imports. It's really not that different for the average user, as most of the changes are under the hood.

Your Reg class should still be pretty much the same. Maybe it's something to do with bad completion due to the wrong imports.

**Comment by filipp8** [comment]
Ok, I'm closing this because I have no reason to believe that animation callback won't work in flixel-dev.
But master branch is broken and should be fixed.
Anyone know if a new release is scheduled?
