### ISSUE TITLE
Null Object Reference

### ISSUE THREAD

**Issue by smks** [HaxeFlixel/flixel#1653]
When switching between states, sometimes it crashes.

I have buttons that bind to mouse event manager like so:

	function addToMouseEventManager() 
	{
		MouseEventManager.add(
			this, 
			onMouseDown, 
			onMouseUp, 
			onMouseOver, 
			onMouseOut
		);
	}
	
	override public function destroy():Void 
	{
		MouseEventManager.remove(this);
		super.destroy();
	}

Then when switching, doesn't always happen, but crashes app.

    FlxG.switchState(new MainMenuScreen());

Null Object Reference
Called from openfl._legacy.display.Stage.__pollTimers (openfl/_legacy/display/Stage.hx line 1084)
Called from openfl._legacy.display.Stage.__checkRender (openfl/_legacy/display/Stage.hx line 351)
Called from openfl._legacy.display.Stage.__render (openfl/_legacy/display/Stage.hx line 1103)
Called from openfl._legacy.display.DisplayObjectContainer.__broadcast (openfl/_legacy/display/DisplayObjectContainer.hx line 286)
Called from openfl._legacy.display.DisplayObject.__broadcast (openfl/_legacy/display/DisplayObject.hx line 161)
Called from openfl._legacy.display.DisplayObject.__dispatchEvent (openfl/_legacy/display/DisplayObject.hx line 182)
Called from openfl._legacy.events.EventDispatcher.dispatchEvent (openfl/_legacy/events/EventDispatcher.hx line 98)
Called from flixel.FlxGame.onEnterFrame (flixel/FlxGame.hx line 493)
Called from flixel.FlxGame.step (flixel/FlxGame.hx line 648)
Called from flixel.FlxGame.update (flixel/FlxGame.hx line 698)
Called from flixel.plugin.MouseEventManager.update (flixel/plugin/MouseEventManager.hx line 322)
Called from flixel.plugin.MouseEventManager.checkOverlap (flixel/plugin/MouseEventManager.hx line 406)
Called from flixel.group.FlxTypedSpriteGroup.pixelsOverlapPoint (flixel/group/FlxTypedSpriteGroup.hx line 195)
Called from flixel.group.FlxTypedSpriteGroup.pixelsOverlapPoint (flixel/group/FlxTypedSpriteGroup.hx line 195)
Called from flixel.FlxSprite.pixelsOverlapPoint (flixel/FlxSprite.hx line 1147)
Called from flixel.system.layer.frames.FlxFrame.paintOnBitmap (flixel/system/layer/frames/FlxFrame.hx line 78)
AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by Gama11** [comment]
I wasn't able to reproduce that with the code snippets you provided. If you still experience this issue, it would be helpful if you provided a complete example that reproduces the crash consistently.

Also, there are sprite groups in the callstack, which doesn't really seem button-related (unless you're using sprite groups as buttons instead of `FlxButton`).
