### ISSUE TITLE
Cannot load TexturePacker atlas

### ISSUE THREAD

**Issue by Miltage** [HaxeFlixel/flixel#1654]
When trying to load sprites from a spritesheet

    var tex = new TexturePackerXMLData("sheet.xml", "sheet.png");
    var sprite = new FlxSprite();
    test.loadGraphicFromTexture(tex, true, "frame1.png");

I get the following error

    Invalid field access : __s
    Called from flixel.system.layer.TileSheetData::addTexturePackerFrame line 252
    Called from flixel.system.layer.TileSheetData::getTexturePackerFrames line 238
    Called from flixel.FlxSprite::updateFrameData line 1189
    Called from flixel.FlxSprite::loadGraphicFromTexture line 540

**Comment by Beeblerox** [comment]
can you attach sample atlas so i can reproduce this issue on my side?

**Comment by Miltage** [comment]
My spritesheet: 

![sheet](https://cloud.githubusercontent.com/assets/4193173/11022690/8fea203a-866d-11e5-83d1-a07e71fe59b8.png)
This is what my XML file looks like:

    <TextureAtlas imagePath="sheet.png">
	    <SubTexture name="carriage1.png" x="0" y="0" width="255" height="51"/>
	    <SubTexture name="carriage2.png" x="0" y="143" width="219" height="50"/>
	    <SubTexture name="carriage3.png" x="0" y="51" width="225" height="92"/>
    </TextureAtlas>

**Comment by Beeblerox** [comment]
I think you should use `SparrowData` instead of `TexturePackerXMLData`. It's located in the same package but works with different xml format

**Comment by Miltage** [comment]
Well, that worked. Thank you very much, @Beeblerox. I'll leave the decision of closing this report to someone with more authority over the repo. After all, this might still be something that warrants fixing.

**Comment by MSGhero** [comment]
This has been changed/fixed in the dev version of the library.

**Comment by Beeblerox** [comment]
Yes, it has been changed, but `TexturePackerXMLData` and `SparrowData` classes handle different atlas formats
