### ISSUE TITLE
'Type not found: JoystickEvent' in neovim with vaxe.

### ISSUE THREAD

**Issue by danbruegge** [HaxeFlixel/flixel#1655]
Hi, i use neovim with the vaxe plugin.

I startet with a HelloWorld template.
```
flixel tpl -n "HelloWorld"
```
If i try to use the the autocompletion i got this error:
![vaxe-error-1](https://cloud.githubusercontent.com/assets/1296438/11041027/a3b7400a-870f-11e5-9db4-f4d67d5ef809.png)

A simple build with neko works. So no erros on this part. I only got this on editor completion. 
I opened an issue here, because i think it is more related to haxeflixel rather than vaxe.

Regards, Dan

**Comment by sruloart** [comment]
http://www.openfl.org/blog/2015/10/06/october-update/

**Comment by danbruegge** [comment]
Ok, thanks. If i install the 'dev' version of flixel, the error message is gone. :)

**Comment by Tiago-Ling** [comment]
This also happens to me with the development version of flixel (using Lime
2.6.8 and OpenFL 3.3.8) in FlashDevelop 5.0.2

Tiago Ling Alexandre
Tel: +55 41 8819-3191


2015-11-09 16:12 GMT-02:00 Daniel Brüggemann <notifications@github.com>:

**Comment by danbruegge** [comment]
@Tiago-Ling try install openfl version 3.3.6.

I've now installed:
```
$ haxelib list
flixel-addons: [1.1.0]
flixel-demos: [1.1.2]
flixel-templates: [1.0.2]
flixel-tools: [1.1.1]
flixel-ui: [1.0.2]
flixel: [3.3.11]
lime: [2.7.0]
openfl: [3.3.6]
```

**Comment by danbruegge** [comment]
Maybe, flixel needs a fixed version of openfl when installing via haxelib?

**Comment by sruloart** [comment]
I think this simply requires a small update to: https://github.com/HaxeFlixel/flixel/blob/00d2b1d68b88abc7d114c929763b6e5dae156670/flixel/input/gamepad/FlxGamepadManager.hx with a proper #if to cover older versions of OpenFL that support `JoystickEvent`. 

I'm not too sure if that's worth another release (3.3.12) though.
