### ISSUE TITLE
Support for lime-hybrid mode

### ISSUE THREAD

**Issue by petamoriken** [HaxeFlixel/flixel#1660]
flixel: 3.3.11
openfl: 3.4.0
lime: 2.7.0

I tried to build with `lime-hybrid` option:

	$ flixel tpl -n "test"
	$ cd test
	$ lime test neko -Dlime-hybrid

And I got the error:

	export/mac64/neko/haxe/DefaultAssetLibrary.hx:1408: characters 189-192 : Unknown identifier : src
	export/mac64/neko/haxe/DefaultAssetLibrary.hx:1408: characters 189-192 : Invalid assign
	export/mac64/neko/haxe/DefaultAssetLibrary.hx:1409: characters 181-184 : Unknown identifier : src
	export/mac64/neko/haxe/DefaultAssetLibrary.hx:1409: characters 181-184 : Invalid assign

This error can occur in `lime test mac -Dlime-hybrid` build.
I want to use newer OpenFL API so please support for `lime-hybrid` mode.

**Comment by Gama11** [comment]
If you want to use the new OpenFL API, you should already be able to use `-Dnext`.

**Comment by petamoriken** [comment]
Thank you!
