### ISSUE TITLE
Request: Loop music from specific point

### ISSUE THREAD

**Issue by SeiferTim** [HaxeFlixel/flixel#1662]
So, after working with a couple of different music artists on projects, something that I keep getting asked is: "Can you make this track loop from a specific point, after the first play?"

Apparently, this is something that is pretty common in a lot of games? A track will have a few seconds of 'lead' for the first time it's played, but when it loops, it's meant to skip that section...

I'm not sure the best way to implement, or how we have it work, but it would be a nice feature to add.

**Comment by MSGhero** [comment]
I feel like you split up the track into the intro and the part that loops, play the intro once, then play the loop onComplete.

**Comment by SeiferTim** [comment]
That is how I've solved this issue in the past, but, it's a common-enough issue that I think it could be solved with code, instead...

Also, it looks like it's something that is RPG Maker (and possibly other software) handles already?
http://forums.rpgmakerweb.com/index.php?/topic/9251-how-to-make-looping-music-the-right-way/

Or, maybe it's something in the Ogg format that 'just works' that could be duplicated? (I don't know that much about music...)

**Comment by winterismute** [comment]
In any case, this is quite simple to implement, see PR https://github.com/HaxeFlixel/flixel/pull/1736
