### ISSUE TITLE
Fading back in within onComplete of fading out doesn't work

### ISSUE THREAD

**Issue by leoncvlt** [HaxeFlixel/flixel#1666]
I tried having the screen fade out, doing some things, and then fading back in. But running `fade(x, x, true) inside the callback function doesn't seem to work:

```haxe
package;

import flixel.FlxG;
import flixel.FlxState;
import flixel.text.FlxText;

class PlayState extends FlxState
{
    override public function create():Void
    {
        add(new FlxText(0, 0, 100, "Hello World!"));

        FlxG.camera.fade(0xff000000, 1, false, function() {
            trace("fade callback running");
            FlxG.camera.fade(0xff000000, 1, true);
        });
    }
}
```

using `neko` on the dev branch.

It works if I set `force` to `true` on the second callback, but shouldn't it work without?

**Comment by Gama11** [comment]
Yeah, that's a bug. Also, it works if you reverse the fade (fade in, then fade out in the callback).
