### ISSUE TITLE
Expose tile map's data?

### ISSUE THREAD

**Issue by MSGhero** [HaxeFlixel/flixel#1667]
In the comments for `tilemap.loadMapFromArray()`, it says that it stores a `copy()` of the source array in case you do other things with the source. I kinda want the opposite to happen, where the tilemap parses my CSV, and then I grab a copy of that to do other things with. Right now I'm manually regex-ing the CSV to an array in order to store a reference to it.

What would be better:
* `public var data(get, never)` with `get_data` returning the underlying array
* ^ but returning `_data.copy()`
* ^ but instead of `never`, `set_data` just calls `loadMapFromArray()`
* `function getData()` which is more clear that it's copying the source instead of directly returning it

?

**Comment by Gama11** [comment]
`getData(false)` already returns the internal array which you can freely manipulate. In Mode's `PlayState#create()` you could do something like this:

```haxe
var data = _tileMap.getData();
for (i in 0...data.length)
	data[i] = 3;
```

Or do you mean something else?
.

**Comment by MSGhero** [comment]
Omg I'm dumb. I didn't actually look for an existing `getData` function... I assumed it would be `public var data`.

Don't mind me :children_crossing:
