### ISSUE TITLE
FlxVirtualPad with DpadMode LEFT_RIGHT crash on android

### ISSUE THREAD

**Issue by oknoorap** [HaxeFlixel/flixel#1669]
code:
```
virtualPad = new FlxVirtualPad(LEFT_RIGHT, NONE);
add(virtualPad);
````
if I change dpad to FULL it will works? whats going on?

**Comment by Gama11** [comment]
Flixel version?

**Comment by oknoorap** [comment]
@Gama11 it's 3.3.11

![Flixel Version](https://i.gyazo.com/12eb4720e4cf296306dda73dae792f88.png)

**Comment by oknoorap** [comment]
bump, is there any update?

**Comment by Gama11** [comment]
I can't reproduce that (using Flixel 3.3.12, OpenFL 3.5.2 and Lime 2.8.1). Anything specific you have to do, or does it simply crash on startup?

Were you able to get any info on the crash using `adb logcat`?

Is the `FlxVirtualPad` the only thing you have in your state?

**Comment by oknoorap** [comment]
adb logcat gives no error, I just follows haxeflixel website's tutorial, and playing with FlxVirtualPad arguments.
