### ISSUE TITLE
Using 2 FlxAnalog 

### ISSUE THREAD

**Issue by thecocce** [HaxeFlixel/flixel#1672]
I tried to use  2 FlxAnalog on same scene. 
Only one at time work propertly.

Seems the touch events are catched  by the other one.

**Comment by Gama11** [comment]
`FlxAnalog` is having some trouble with multitouch here it seems.. Happens both on master and dev.

Some test code to reproduce:

```haxe
package;

import flixel.FlxState;
import flixel.ui.FlxAnalog;
using flixel.util.FlxSpriteUtil;

class PlayState extends FlxState
{
	override public function create():Void
	{
		var analog1 = new FlxAnalog();
		analog1.screenCenter();
		analog1.x -= 100;
		add(analog1);
		
		var analog2 = new FlxAnalog();
		analog2.screenCenter();
		analog2.x += 100;
		add(analog2);
    }
}

```

**Comment by thecocce** [comment]
I solved this issue modifing the xml


	<haxedef name="FLX_NO_MOUSE_ADVANCED" />
	
	
	<haxedef name="FLX_NO_NATIVE_CURSOR" />
	
	
	<haxedef name="FLX_NO_MOUSE" if="mobile" />
	<haxedef name="FLX_NO_KEYBOARD" if="mobile" />
	<haxedef name="FLX_NO_TOUCH" if="desktop" />
	<haxedef name="FLX_NO_GAMEPAD" />

Please try it.

**Comment by Gama11** [comment]
Hm, looks like defining `FLX_NO_MOUSE` fixes it.. I don't think that should be necessary.
