### ISSUE TITLE
Find a way to get rid of transition functions in FlxState

### ISSUE THREAD

**Issue by Gama11** [HaxeFlixel/flixel#1676]
Really not a fan of [having `isTransitionNeeded()` and `transitionToState()` in `FlxState`](https://github.com/HaxeFlixel/flixel/blob/637e4a541978cd26a8c6a6babaefb1d837b87a6d/flixel/FlxState.hx#L132-L149). They're only needed by the transitions classes in flixel-addons. which makes them a hack in my opinion. The system should be flexible enough that you can create addon classes like this without modifying the base `FlxState` class.

I'd also like to avoid them becoming part of the public API we have to keep compatibility with in a 4.0.0 release.

**Comment by Tiago-Ling** [comment]
+1

Tiago Ling Alexandre
Tel: +55 41 8819-3191


2015-12-20 8:18 GMT-02:00 Gama11 <notifications@github.com>:

**Comment by Gama11** [comment]
I think I've found a more flexible solution...

**Comment by larsiusprime** [comment]
Cool

**Comment by Gama11** [comment]
The new `FlxState#switchTo()` should be a bit more flexible.. Even if not, it doesn't have "transition" in the name and the implementation is simpler. :)
