### ISSUE TITLE
Wrong touch position with scaled scaleMode

### ISSUE THREAD

**Issue by SARFEX** [HaxeFlixel/flixel#1685]
*First, sorry for my english, i'm trying my best x(*

Subj. 
You can reproduce the bug, but for mouse (just for understanding what i'm talking about), 
by making change in update() function FlxMouse (flixel\input\mouse\FlxMouse.hx)
to:
```actionscript
		_globalScreenX = Math.floor(FlxG.game.mouseX);
		_globalScreenY = Math.floor(FlxG.game.mouseY);
``` 
from:
```actionscript
		_globalScreenX = Math.floor(FlxG.game.mouseX / FlxG.scaleMode.scale.x);
		_globalScreenY = Math.floor(FlxG.game.mouseY / FlxG.scaleMode.scale.y);
```
And now, when your scaleMode.scale > 1 you can't correct press buttons and etc.
Click areas like remain in their places when scaleMode.scale = 1;

The same thing is happening for me on android tablet.
I offer this: https://github.com/SARFEX/flixel/commit/18692b9601733e7677895bc0364ff082010cb579 (same as mouse for FlxTouch)
I think It looks sensible, but i have only my tablet with old Android version 4.2.2, and I do not know how extensive this issue is, or is it only happens with me.

HaxeFlixel: dev, OpenFL: 3.5.3, Lime: 2.8.2, Haxe: 3.2.1

Thank you for attention.

**Comment by Gama11** [comment]
Thanks, good catch. Better to solve this using a shared method in the `FlxPointer` base class to avoid redundancy though. :)
