### ISSUE TITLE
The future of shaders?

### ISSUE THREAD

**Issue by Ohmnivore** [HaxeFlixel/flixel#1687]
I'm writing a lighting system using the flixel dev branch's PostProcess, but at the moment the shaders are applied to the final rendered frame. This means that lights would affect user interfaces which is a big limitation.

I digged into the post process code and I couldn't find a way to alter it so that shaders are only fed the frame right after the first camera has rendered so that the subsequent cameras can render in an unaltered way. The idea behind that is to have a shader that can modify the game world, but not the ui.

While messing around with that I noticed that openfl next's BitmapData has a getTexture():GLTexture function which I find interesting, and I suppose overall a more direct access to OpenGL textures. Would a reworked shader system using next allow more shader acrobatics like reading and writing to BitmapDatas/FlxCameras?

I'm going to try to explore this path when I find the right openfl/lime versions combination that doesn't crash with the dev branch (if someone already found it can you please tell me). So what do you guys think?

**Comment by Gama11** [comment]
It's just lime 2.8.3 that crashes, if you downgrade to 2.8.2 you should be fine.

Per-camera shaders are already supported with OpenFL next: #1635 HaxeFlixel/flixel-demos#205

**Comment by Ohmnivore** [comment]
Oh my I don't know how I missed that demo. It's awesome!

**Comment by Gama11** [comment]
The demo could actually do a much better job of showing off the per-camera nature of filters - it's just a copy of the PostProcess demo and only has one camera.

Contributions welcome. ;P

**Comment by larsiusprime** [comment]
Can we do per-FlxSprite shaders yet? If so I might be interesting in putting together a demo for it.

**Comment by Gama11** [comment]
I don't think so.

**Comment by larsiusprime** [comment]
Don't we have the ability to do per-(openfl.display.Sprite) shaders in regular OpenFL tho?

I suppose it comes down to sorting out the rendering pipelines.

**Comment by Ohmnivore** [comment]
Hmm I'm hoping to port my shader lights demo to shader filters and submit it to flixel-demos, but I just can't find how to manually set uniforms using GL.setUniform. Been through the OpenFL code and can't find the GLProgram variable to call GL.getUniformLocation with. Ideally I would be able to call `GL.setUniform1i(GL.getUniformLocation(prog, "lights[" + i + "].energy"), light.energy);`

switching to lime 2.8.2 solved the crash, btw. thanks Gamma!

**Comment by larsiusprime** [comment]
@Ohmnivore sounds like a question for the OpenFL guys. Are you on that slack chat?

**Comment by Ohmnivore** [comment]
You're right. Could you send me an invite?
