### ISSUE TITLE
Sound is not playing after general volume is changed

### ISSUE THREAD

**Issue by Tembac** [HaxeFlixel/flixel#1689]
For some of the sounds of my game I create the sound so I can if it is playing instead of just using: FlxG.sound.play()

The code for the sounds that I'm using is:
   var elevatorOnSound:FlxSound = new FlxSound();
   elevatorOnSound.loadEmbedded("assets/sounds/ascensor_comienzo.mp3");

    if (!elevatorOnSound.playing)
    {
	elevatorOnSound.play();
    }

My solution is to add the Volume parameter to the play function of FlxSound:

	public function play(ForceRestart:Bool = false, Volume:Float = 1):FlxSound
	{
		if (!exists)
		{
			return this;
		}
		if (ForceRestart)
		{
			cleanup(false, true, true);
		}
		else if (playing)
		{
			// Already playing sound
			return this;
		}
		
		if (_paused)
		{
			resume();
		}
		else
		{
			startSound(0);
		}
		volume = Volume;
		return this;
	}

Do you agree with this solution?

**Comment by Gama11** [comment]
I'm not sure why settings the volume afterwards would cause issues, I'll have a look at it later. If it does, your suggested solution is really just a workaround and would still fail should someone adjust the volume afterwards.

You don't need to create sound objects manually btw, `FlxG.sound.play()` returns the instance.

**Comment by Gama11** [comment]
Can you provide a more complete example? What do you mean by "general volume"? This works for me:

```haxe
var sound = new FlxSound();
sound.loadEmbedded("assets/sounds/beep.mp3");
sound.play();
sound.volume = 0.5;
FlxG.sound.volume = 0.5;
```

**Comment by Gama11** [comment]
Can you provide a more complete example? What do you mean by "general volume"? This works for me on flash and neko:

```haxe
var sound = new FlxSound();
sound.loadEmbedded("assets/sounds/beep.mp3");
sound.play();
sound.volume = 0.5;
FlxG.sound.volume = 0.5;
```

Which target?

**Comment by Tembac** [comment]
Thanks for you answers Gamma. 

Using FlxG.sound.play(), How can I know if the sound is already playing?

The reproduction of the issue I'm talking about is this:
- Play the game with default FlxG.sound.volume = 0.5;, all sounds are playing.
- Then, turn the volume down using "-" (Minus Key) to reach mute.
- Then the sound that uses sound.play(); keeps playing at full volume.

**Comment by Gama11** [comment]
`FlxG.sound.load()` might be better in your case if you don't want to start playing it right away.

**Comment by Tembac** [comment]
Thanks, this solves my problem without my changes.

**Comment by Gama11** [comment]
Btw, I was able to reproduce your issue, but it's not a bug. If you create a sound outside of flixel's sound management (`FlxG.sound`), you'll have to take care of calling `update()` on it yourself. It calls `updateTransform()`, which updates the volume.

Using `FlxG.sound.load()` seems preferable.
