### ISSUE TITLE
Aliasing constants for LogitechButtonID.hx

### ISSUE THREAD

**Issue by ashes999** [HaxeFlixel/flixel#1690]
Hi,

As mentioned in the mailing list, I tried to get HaxeFlixel to work with my Logictech F310 (it works). I discussed the possibility of aliasing the constants of [LogitechButtonID.hx](flixel/flixel/input/gamepad/LogitechButtonID.hx), by adding something like:

```
public static inline var X:Int = ONE;
public static inline var A:Int = TWO;
public static inline var B:Int = THREE;
public static inline var Y:Int = FOUR;
```

(The F310 has A/B/X/Y buttons). The `DPAD_*` values don't work, so I planned to add a comment mentioning this, and referring to the other DPAD API (checking `_gamePad.dpadLeft`).

1) Is this (aliasing constants) a good idea?
2) If so, should I put this at the bottom of the class, under the `#end` statement?

**Comment by Gama11** [comment]
I don't really like that idea - all other button IDs are unique, so this could cause some confusion. Also, with the new Gamepad API on the dev branch, all controller-specific IDs are mapped to [`FlxGamepadInputID`](https://github.com/HaxeFlixel/flixel/blob/dev/flixel/input/gamepad/FlxGamepadInputID.hx), so you'd rarely want to access those ID classes directly anyway.

Dpad values should work on the dev branch as well.

**Comment by ashes999** [comment]
Thanks for the feedback. That makes sense. It's not ideal (I don't know how many Logitech controllers are out there that use ABXY for buttons), but the comments on the existing API are explanatory enough.
