### ISSUE TITLE
Refactor FlxGamepadMapping to be extensible

### ISSUE THREAD

**Issue by Gama11** [HaxeFlixel/flixel#1691]
Currently, everything is hardcoded in switch-statements. Ideally, the user has the freedom to customize or add entirely new mappings. Each mapping could fairly easily be modelled as a child class of `FlxGamepadMapping` which defines a common interface.

**Comment by larsiusprime** [comment]
Not a bad idea.

**Comment by Tembac** [comment]
Sorry to bother, maybe it is no related, but I was looking for something to make the controls configurable but also confortable to program.

I made this class: http://justpaste.it/qnid

I add that to each state of the game and it allows me to configure different keys to the same actions. To call it I use a static variable from the Reg class.
I'm not sure if it is the best approach to do something like this and if it is completely related to the initial idea by @Gama11, but I wanted to show my problem with the controls configurations and my proposed solution.

**Comment by Gama11** [comment]
@Tembac Yeah, that's a different thing, more along the lines of #752.
