### ISSUE TITLE
StageSizeScaleMode maximize/unmaximize does not resize correctly, even though resize event fires

### ISSUE THREAD

**Issue by GimmickyApps** [HaxeFlixel/flixel#1695]
This applies to the scaleMode StageSizeScaleMode, but not the default.  (Not sure about others.)

It seems that maximizing or unmaximizing a Flash window on Windows 7, while firing the resize event correctly (I can see trace output from `onResize()`) does not actually resize things correctly.  An additional, manual call to onResize after the maximize or unmaximize fixes things.

Sample code and further explanation at https://github.com/GimmickyApps/ScaleHuh/issues/4

FlashDevelop 5.0.2.2, Haxe 3.2.1, flixel: [3.3.12], openfl: [3.5.3], targets:

* flash debug
* flash release
* windows (cpp) release

**Comment by Gama11** [comment]
Works as expected on dev.
