### ISSUE TITLE
StageSizeScaleMode resizing ONLY wider causes black bar to appear

### ISSUE THREAD

**Issue by GimmickyApps** [HaxeFlixel/flixel#1696]
Sample at https://github.com/GimmickyApps/ScaleHuh/issues/5

Interestingly, this only applies to flash/debug and flash/release, but not windows (cpp) release.

Win7 with FlashDevelop 5.0.2.2, Haxe 3.2.1, flixel: [3.3.12], openfl: [3.5.3].

**Comment by Gama11** [comment]
Not reproducible on the dev branch.
