### ISSUE TITLE
Generating Intel APKs for android

### ISSUE THREAD

**Issue by GimmickyApps** [HaxeFlixel/flixel#1697]
I have a problem.  My phone is too low-qual to even have USB drivers for it, so sending APKs to it is a slow affair.

An Intel HAXM emulator runs OK, but will not load the APKs generated by HaxeFlixel/FlashDevelop, citing error INSTALL_FAILED_NO_MATCHING_ABIS because they're made for ARM.  I'd run the ARM emulator, but it's hella slow (my laptop is mid-low-range, 4 GB of RAM, Win7.)

Is there a way to generate Intel APKs so that one can test them in an Android emulator at a reasonable speed?

**Comment by Gama11** [comment]
Flixel isn't responsible for generating .apk files. Try the OpenFL forums or the Lime issue tracker.

**Comment by GimmickyApps** [comment]
@Gama11 My bad, will do.  Thanks!
