### ISSUE TITLE
Cleanup static variables from FlxPoint / FlxRect / FlxMatrix

### ISSUE THREAD

**Issue by gamedevsam** [HaxeFlixel/flixel#1698]
These variables should be stored where they are used: https://github.com/HaxeFlixel/flixel/blob/dev/flixel/math/FlxPoint.hx#L16-L19
https://github.com/HaxeFlixel/flixel/blob/dev/flixel/math/FlxRect.hx#L13-L15

We should think about cleaning up this type of API bloat for this major release.

**Comment by Gama11** [comment]
Make them private or remove them, using pooling instead?

**Comment by gamedevsam** [comment]
I would use pooling, or in cases where the points are hit once per frame, I would store them as static variables on the class that actually uses them.

**Comment by Gama11** [comment]
I've already done the cleanup, see the referenced commits. It's just the static flash objects that are leftover (but made private).
