### ISSUE TITLE
Not prompted to run update.hxml when switching to dev

### ISSUE THREAD

**Issue by GimmickyApps** [HaxeFlixel/flixel#1701]
http://haxeflixel.com/documentation/install-development-flixel/ says, "You should be prompted to run the update.hxml," but my output was:

```
C:\HaxeToolkit\haxe>haxelib selfupdate
Downloading haxelib_client-3,2,0-rc,3.zip...
Download complete : 69579 bytes in 0.2s (310.2KB/s)
  Install src/tools/haxelib/Validator.hx
  Install src/tools/haxelib/SiteApi.hx
  Install src/tools/haxelib/SemVer.hx
  Install src/tools/haxelib/Rebuild.hx
  Install src/tools/haxelib/Main.hx
  Install src/tools/haxelib/Data.hx
  Install src/tools/haxelib/ConvertXml.hx
  Install haxelib.json
  Current version is now 3.2.0-rc.3
Done
Haxelib successfully updated.
rebuild launched

C:\HaxeToolkit\haxe>
```

Did something go wrong, are the docs out of date, or was the output changed by accident to not include this anymore?

Should I run update.hxml even though it doesn't tell me to in the current output?

**Comment by Gama11** [comment]
The docs were based on an older haxelib version, the latest one runs update.hxml by itself I think. In fact, I believe the selfupdate step can be revmoed entirely from the docs.

This is more of a [flixel-docs](https://github.com/HaxeFlixel/flixel-docs) than a flixel issue.

**Comment by GimmickyApps** [comment]
OK I'll make the changes.  Thanks!
