### ISSUE TITLE
FlxTextFormatMarkerPair shifted two characters to the right.

### ISSUE THREAD

**Issue by xerosugar** [HaxeFlixel/flixel#1702]
For example, if I work with the following string: "you _absolutely_ must do this" and use '_' as markers the string that gets the applied format is: "solutely m". Expected string is: "absolutely"

**Comment by Gama11** [comment]
Please provide some code that reproduces the issue and list your library versions.

**Comment by xerosugar** [comment]
var formatBlue = new FlxTextFormat(0xff269fff);		
    txt.setFormat(null, 43, 0xff000000, FlxTextAlign.LEFT);
    txt.applyMarkup("If there’s one piece of knowledge that you _absolutely_ must bring with you, it's this!", [new FlxTextFormatMarkerPair(formatBlue, "_")]);
    add(txt);

libs:
- openfl 3.5.3
- flixel: git
- haxe 3.2.1

**Comment by Gama11** [comment]
Reduced it a bit:

```haxe
package;

import flixel.FlxState;
import flixel.text.FlxText;
import flixel.util.FlxColor;

class PlayState extends FlxState
{
	override public function create():Void
	{
		var text = new FlxText();
		text.applyMarkup("’ _absolutely_ must",
			[new FlxTextFormatMarkerPair(new FlxTextFormat(FlxColor.CYAN), "_")]);
		add(text);
	}
}
```

![](http://i.imgur.com/Hj3doKZ.png)

Two observations:

- works fine on flash
- seems to be caused by the `’` character.

**Comment by Gama11** [comment]
This working correctly implies that it's probably not an OpenFL issue:

```haxe
package;

import flixel.FlxG;
import flixel.FlxState;
import flixel.util.FlxColor;
import openfl.text.TextField;
import openfl.text.TextFormat;

class PlayState extends FlxState
{
	override public function create():Void
	{
		bgColor = FlxColor.WHITE;
		
		var text = new TextField();
		text.text = "’ shifted right";
		text.setTextFormat(new TextFormat(null, null, 0xff0000), 2, 9);
		FlxG.stage.addChild(text);
	}
}
```

**Comment by Gama11** [comment]
This traces 1 on Flash and 3 on neko / cpp:

```haxe
trace("’".length);
```

I think we need to use `haxe.Utf8` here like in `FlxBitmapText`.

**Comment by Gama11** [comment]
Should be working now.

**Comment by xerosugar** [comment]
thank you for that very quick turnaround, you're on fire! :fire:
