### ISSUE TITLE
onResize does not fire until mouseup on windows-release target

### ISSUE THREAD

**Issue by GimmickyApps** [HaxeFlixel/flixel#1703]
On flash (release or debug), dragging a window border to resize it fires the onResize event more or less continually.  On windows release, it only fires the event when you let go.

Win7, HF dev branch, haxe 3.2.1.

**Comment by Gama11** [comment]
This is an inconsistency of the underlying OpenFL `Event.RESIZE` event: https://github.com/openfl/openfl-native/issues/158
