### ISSUE TITLE
FlxText graphic not initialized after constructor with FlxG.renderTile

### ISSUE THREAD

**Issue by GimmickyApps** [HaxeFlixel/flixel#1706]
I tried the same stamping code as in https://github.com/HaxeFlixel/flixel/issues/1704 (the first and third blocks in the OP).  On flash (debug or release) it looks fine.  On windows (debug or release) the stamped text is lowered a whole line (or maybe not a line per se, but the height of a capital character.)  This is on the dev branch, up-to-date.

**Comment by Gama11** [comment]
Repro code:

```haxe
package;

import flixel.FlxSprite;
import flixel.FlxState;
import flixel.text.FlxText;
import flixel.util.FlxColor;

class PlayState extends FlxState
{
    override public function create():Void
    {
        var stampText = new FlxText(0, 0, 0, "Text");
		stampText.color = FlxColor.RED;
		
		var sprite = new FlxSprite().makeGraphic(100, 100, FlxColor.BLUE);
		sprite.stamp(stampText);
		add(sprite);
    }
}
```

On both neko and flash, the upper next character of the `T` is at (2, 3). The code from the last issue suggests you're using a font different from the default one?

**Comment by GimmickyApps** [comment]
Yes, that's correct, I forgot to mention that.  It's Graduate Regular if it makes a difference which one exactly.

-----Original Message-----

**Comment by Gama11** [comment]
Can you provide a complete example? Are you sure this is caused by `stamp()`? I'd expect the same issue when just adding the text directly.

This sort of inconsistency is usually caused by OpenFL's `TextField` implementation, in which case there's not much Flixel can do about it. Have you tried with OpenFL Next? The `TextField` implementation there is generally more accurate.

**Comment by GimmickyApps** [comment]
Yes, a complete example is here: https://github.com/GimmickyApps/HaxeFlixelDevRepros/tree/b4ac6a4c9f22ba0f8838f787cb3422b8c95a77f6

Yes, this is caused by `stamp()`, although in complete isolation I could not reproduce it, so it may have something to do with FlxTypedButton as well, as you'll see in the example.

(Turns out it does not have to do with fonts, as you can also see.)

Upon further investigation, it had to do with FlxText.frameHeight changing after the `stamp()` call on windows, but not on flash.  The first number in each pair below is the frameHeight of the FlxText being used as the brush:

windows:
```
CustomButton.hx:30: 0,12
CustomButton.hx:32: 23,1
```

flash:
```
CustomButton.hx:30: 22,1
CustomButton.hx:32: 22,1
```

**Comment by Gama11** [comment]
So really, this issue can be reduced down to two lines of code:

```haxe
var text = new FlxText(0, 0, 0, "T");
// traces (0, 0) on neko and (11, 14) on flash
trace(text.frameWidth, text.frameHeight);
```

**Comment by GimmickyApps** [comment]
@Gama11 Well...I had initially tried it just by itself, and hadn't found a problem.  I guess I hadn't re-evaluated the situation once I had figured out it had to do with frameHeight.  You're probably quite right...

**Comment by GimmickyApps** [comment]
Sorry!

**Comment by Gama11** [comment]
No worries, can be tricky to isolate an issue down to the bare minimum.

Should be working consistently now (well, the `frameWidth` is off by one pixel, but that's due to OpenFL legacy's TextField implementation not being very accurate - with OpenFL next it's consistent).

**Comment by GimmickyApps** [comment]
@Gama11  Confirmed working here too.  Thanks again!

**Comment by GimmickyApps** [comment]
I'm getting this exact behaviour again, but on android/release, on a real phone running android 4.4.2.  On flash (debug or release) it looks fine.

**Comment by GimmickyApps** [comment]
@Gama11 After some rewarding arduousness, I narrowed it down to the following line in my Project.xml file:

```xml
<haxeflag name="-dce" value="full" unless="debug" />
```
With this line, stamped text is shifted down a line on android/release.  Without it, it's not.

I wonder what the compiler thinks is "dead code" that actually isn't...

**Comment by Gama11** [comment]
Didn't you open a separate issue for this (#1721)? Or are these two separate issues?

**Comment by GimmickyApps** [comment]
Two separate issues.  In this one, the text is offset downwards for some reason, regardless of font.  In the other, any text in the default Nokia font is just plain not shown (other font's OK).  Both are specific to android, with the exact same code that works fine on flash, windows, and html5.

**Comment by GimmickyApps** [comment]
Although, as I just discovered, they have the exact same cause!  At least to some extent.  I just used the code from your post above in this thread with a slight modification to show two fonts:

```haxe
package;

import flixel.FlxSprite;
import flixel.FlxState;
import flixel.text.FlxText;
import flixel.util.FlxColor;

class PlayState extends FlxState
{
    override public function create():Void
    {
        var stampText = new FlxText(0, 0, 0, "[Text]", 24);
        stampText.color = FlxColor.RED;

        var sprite = new FlxSprite().makeGraphic(100, 100, FlxColor.BLUE);
        sprite.stamp(stampText);

        stampText = new FlxText(0, 0, 0, "    [Other Text]", 24);
		stampText.font = "assets/fonts/graduate-regular-webfont.ttf";
        stampText.color = FlxColor.GREEN;
        sprite.stamp(stampText);

        add(sprite);
    }
}
```

...and with DCE disabled, it's fine.  With it enabled, the Nokia text disappears, while the other text remains visible.

**Comment by GimmickyApps** [comment]
And, as it turns out, the "something in my project's code" was exactly as in this original thread: wrong values coming out for frameWidth/frameHeight on FlxText.

Compile [this](https://github.com/GimmickyApps/HaxeFlixelDevRepros/tree/1c863f06c7d72752a65cffe9072361cb04f2a52e) with and without the DCE line enabled in Project.xml, and if your results are like mine you'll see the following numbers (the frame size for the text "    [Other Text]"):

flash/release: 226, 34
android/release, without DCE: 227, 34 (close enough for the gov't)
**android/release, with DCE: 5, 4**

**Comment by GimmickyApps** [comment]
@Gama11  can I request a reopen, now that I have a reproducible example?  Or is this considered something different than the original issue reported in this thread and I should open a new issue?

**Comment by Gama11** [comment]
Definitely seems like a different issue. Might already be covered by #1721 though, considering both issues are caused by DCE.

**Comment by GimmickyApps** [comment]
OK, I made a new issue and tried to make the titles a bit more helpful for comparing/contrasting.
