### ISSUE TITLE
Debug console broken in dev branch for flash target

### ISSUE THREAD

**Issue by winterismute** [HaxeFlixel/flixel#1707]
Just running a default haxeflixel template in debug on flash target does not work, it returns the error:
'Error #1069: Property __enum__ not found on MenuState and there is no default value.'
Which comes from haxe, file haxe\std\flash\_std\Reflect.hx
The "culprit" seems to be the 'isEnumValue' method, which is basically

    #if as3
    return try Type.getEnum(v) != null catch ( e: Dynamic) false;
    #else
    return try v.__enum__ == true catch ( e : Dynamic) false;
    #end

The second part gets called, which is wrong, and I don't understand if it is a problem of my haxe installation or a real bug. I have haxe ver 3.2.1.

**Comment by Gama11** [comment]
The second part getting called is correct. The `as3` define refers to the `-as3` target of Haxe, which generates AS3 code rather than SWF bytecode.

**Comment by Gama11** [comment]
Can you provide more details? I can't reproduce this.

Do you have a stacktrace?
Which version of flixel-templates do you have?
You didn't change anything in the generated project?

**Comment by Gama11** [comment]
You mention the debug console in the title, which is a bit confusing since the rest of your description sounds like just running the project causes the crash. Did you have to run any specific command there?

**Comment by winterismute** [comment]
The error happens when just running a project in debug in the flash target, the default template is just the easiest way to get have it working. I am using dev branch of haxeflixel and a flixel-addons master branch. To run the default template, I had to remove the flxmath import and ad the float parameter in the update functions.
The fact is that I upgraded my haxeflixel installation (with haxelib) and then installed also new haxe (which seemed required) and my haxeflixel projects broke. So I decided to create a new template to the debug the issues from a clean codebase, and this is the first issue I encountered.

I don't get a java stacktrace, but this is the call stack:

    Reflect$/isEnumValue at C:\HaxeToolkit\haxe\std\flash\_std\Reflect.hx:110
    Reflect$/isObject at C:\HaxeToolkit\haxe\std\flash\_std\Reflect.hx:101
    flixel.system.debug.console::ConsoleUtil$/registerObject at C:\HaxeToolkit\haxe\lib\flixel\git\flixel\system\debug\console\ConsoleUtil.hx:73
    flixel::FlxGame/switchState at C:\HaxeToolkit\haxe\lib\flixel\git\flixel\FlxGame.hx:647
    flixel::FlxGame/create at C:\HaxeToolkit\haxe\lib\flixel\git\flixel\FlxGame.hx:341
    flash.display::DisplayObjectContainer/addChild
    Main/setupGame at [PATH]\NewProject\source\Main.hx:66

If I run the project in release, it seems to be fine.
My versions:
$ haxelib.exe list flixel
flixel-addons: git [dev:C:\HaxeToolkit\haxe\lib\flixel-addons/git]
flixel-demos: 1.1.1 [1.1.2]
flixel-templates: 1.0.2 git [dev:C:\HaxeToolkit\haxe\lib\flixel-templates/git]
flixel-tools: 1.0.5 [1.1.2]
flixel-ui: [1.0.2]
flixel: 3.3.12 git [dev:C:\HaxeToolkit\haxe\lib\flixel/git]

**Comment by Gama11** [comment]
My guess is that you have `Debug -> Break on all Errors` enabled in FlashDevelop. That line in `isEnumValue()` leads to an exception, but that can safely be ignored since it also handles that exception.

**Comment by winterismute** [comment]
If I turn off "Break on all Errors", the code of the Playstate::create(), for example, is never reached, although the application does not crash...
My only question is whether you can reproduce it or not according to the info above. If you can't, then something might be messed up in my system.

**Comment by Gama11** [comment]
I get the same behavior as you with Break on all Errors, but that's exactly what it does - break on all errors, no matter whether they're handled or not. That doesn't make it a bug.

Not sure what you mean by `PlayState::create()` not being reached then, surely that's unrelated. Note that if you're using the template project, it starts in `MenuState::create()`.

**Comment by winterismute** [comment]
You are right. The "Break on all Errors" was probably the problem, thanks.
