### ISSUE TITLE
BitmapData.draw(FlxG.stage) on NEXT cpp/neko targets

### ISSUE THREAD

**Issue by SARFEX** [HaxeFlixel/flixel#1708]
### Problem: 
BitmapData.draw(Lib.current.stage) returns/shows empty white content, or sometimes crash.
If i draw(SomeSprite) all works fine.
I tested clean openfl and... the issue is reproducing only in HaxeFlixel (how it possible? o0)

### Reproducing: 
Simply add the code below (or similar) into update() function to an existing project,
compile for windows with -Dnext and press Enter for capture
```haxe
	if (FlxG.keys.justPressed.ENTER) {
		var testBitmapData:BitmapData = new BitmapData(200, 200);
		testBitmapData.draw(Lib.current.stage);
		var testBitmap:Bitmap = new Bitmap(testBitmapData);
		testBitmap.x = 20; testBitmap.y = 20;
		FlxG.addChildBelowMouse(testBitmap);
	}
```
### Targets / versions
Works on flash and legacy
Broken on windows/neko next

I know about the problem for a long time (about a year), and all this time I thought that OpenFL NEXT simply does not support BitmapData.draw(). However here's a list of versions that I use:
HaxeFlixel dev, OpenFL 3.6.0, Lime 2.9.0, Haxe 3.2.1

Thank You :)

**Comment by larsiusprime** [comment]
In cpp & neko it uses the draw tiles pathway, which IIRC doesn't actually *put* anything on the stage. On flash target it has a single bitmap that it draws everything too. It's a little weird though because presumably legacy uses drawtiles as well...

in any case if you want to get a "screenshot" that functionality was recently added to lime

**Comment by SARFEX** [comment]
Thanks for the quick response. Cool! How to use screenshow functionality? I cant find it Q.Q

**Comment by larsiusprime** [comment]
It's called "readPixels" I believe, and it might be attached to the lime Window or Display class, which you can usually find as children of Lib.current or Lib.current.stage -- I'm not on my regular dev machine at the moment.

Eventually I'll roll this all up into a fixed up API for FlxScreenGrab so you don't have to worry about the implementation details.

**Comment by SARFEX** [comment]
Thank you very much. Now I'm really looking forward to this functionality :+1: 
Perhaps it will also help to fix wrong PrintScreen capture

**Comment by Gama11** [comment]
I don't think there's anything Flixel can do about this.

**Comment by SARFEX** [comment]
I think OpenFL / Lime tag is wrong, It is not the fault of Openfl :D Because as i said (now I began to doubt it), on clean openfl project this issue can not be reproduced (BitmapData.draw(Lib.current.stage) returns correctly

**Comment by Gama11** [comment]
I'm fairly confident it's still an OpenFL issue - every part required to reproduce it is OpenFL API - `draw()`, the stage and the drawTiles API for rendering. I guess you probably didn't use the latter in your OpenFL test.

**Comment by Gama11** [comment]
You can easily verify this by switching the render method to `FlxG.renderBlit` (currently requires hacking `FlxG.initRenderMethod()`, we need to implement a setter to be able to switch at runtime...). With that renderer, your code works correctly even on OpenFL Next.

**Comment by SARFEX** [comment]
@Gama11, thanks for the explanation, I need to learn more HaxeFlixel
