### ISSUE TITLE
more details about FlxCamera.screen?

### ISSUE THREAD

**Issue by IBwWG** [HaxeFlixel/flixel#1719]
```haxe
	/**
	 * Sometimes it's easier to just work with a FlxSprite than it is to work directly with the BitmapData buffer.  
	 * This sprite reference will allow you to do exactly that.
	 */
	public var screen:FlxSprite;
```
For the "sometimes" here, could someone with experience using it comment on when you might want to use it?

Looking at the rest of FlxCamera.hx, I see only five references to `screen.`anything...and I don't seem to be able to grok what it actually does.

```haxe
// constructor:
			screen.pixels = buffer;
			screen.origin.set();
// checkResize():
			var oldBuffer:FlxGraphic = screen.graphic;
			buffer = new BitmapData(width, height, true, 0);
			screen.pixels = buffer;
			screen.origin.set();
			_flashBitmap.bitmapData = buffer;
			_flashRect.width = width;
			_flashRect.height = height;
			_fill = FlxDestroyUtil.dispose(_fill);
			_fill = new BitmapData(width, height, true, FlxColor.TRANSPARENT);
			FlxG.bitmap.removeIfNoUse(oldBuffer);
```

There's that one line in checkResize() that sets the old buffer to it...and then nothing is done with the old buffer, and then the old buffer is removed.

Maybe it's a leftover that should be removed?  If not, maybe someone can help me put more details into the description?

**Comment by GimmickyApps** [comment]
Also, in general, I find it a bit difficult to discern the relationships among `screen`, `flashSprite`, `_flashRect`, `_scrollRect`, and `_flashBitmap`--at least two of them say simply `Internal, used to render buffer to screen space.`  Is there more design documentation on them outside the source code?
