### ISSUE TITLE
Only with DCE enabled, only on android/release: default Nokia font missing/invisible

### ISSUE THREAD

**Issue by IBwWG** [HaxeFlixel/flixel#1721]
I have a problem appearing in two different contexts: stamping and directly-visible `FlxText`.  I use two fonts in my game, a custom one I include in my assets folder, and the default one, "Nokia Cellphone FC Small."  On flash, windows, and html5 targets, both fonts work fine in both contexts.  **On android (on a real phone running Android 4.4.2), the Nokia font does not show in either context**, but the custom one works fine in both contexts.

When stamping, I use the Nokia font by not setting `EmbeddedFont` in my `FlxText` constructor calls, nor setting `font` afterwards.

For the straight up `FlxText`, I explicitly set the font based on a variable, so sometimes I use my custom font and it works, and sometimes I set `.setFormat( "Nokia Cellphone FC Small", 24 );` and then just as with the stamping, no text is shown at all.

This is on the HaxeFlixel dev branch, updated yesterday, compiled on Win7/64 using haxe 3.2.1.
##

**Comment by Gama11** [comment]
Please provide a code snippet to reproduce.

**Comment by GimmickyApps** [comment]
Sure.  For stamping:
```haxe
			stampText = new FlxText( 0, 0, width, Std.string(count), Std.int(height * 0.2) );
			stampText.alignment = FlxTextAlign.CENTER;
			stampText.color = FlxColor.BLACK; // POLISH: vary colour based on count
			this.stamp( stampText, 0, Std.int( height * 0.5 ) );
			stampText = null;
```

**Comment by GimmickyApps** [comment]
Huh, with that code replacing my game's PlayState, even though it works fine on html5, in crashes on my phone.  :(

**Comment by GimmickyApps** [comment]
I narrowed it down to the following line in my Project.xml file:

```xml
<haxeflag name="-dce" value="full" unless="debug" />
```
With a slight modification to show two fonts:

```haxe
package;

import flixel.FlxSprite;
import flixel.FlxState;
import flixel.text.FlxText;
import flixel.util.FlxColor;

class PlayState extends FlxState
{
    override public function create():Void
    {
        var stampText = new FlxText(0, 0, 0, "[Text]", 24);
        stampText.color = FlxColor.RED;

        var sprite = new FlxSprite().makeGraphic(100, 100, FlxColor.BLUE);
        sprite.stamp(stampText);

        stampText = new FlxText(0, 0, 0, "    [Other Text]", 24);
		stampText.font = "assets/fonts/graduate-regular-webfont.ttf";
        stampText.color = FlxColor.GREEN;
        sprite.stamp(stampText);

        add(sprite);
    }
}
```

...and with DCE disabled, it's fine.  With it enabled, the Nokia text disappears, while the other text remains visible.  (Only on android.  On flash/windows/html5 this line does not cause problems.)

**Comment by GimmickyApps** [comment]
It's nothing beyond what's posted above, I believe, but if you want it all in one place, compile https://github.com/GimmickyApps/HaxeFlixelDevRepros/tree/af4fe7687eb54a89dd0a6cdc3b85abf4e70c9036 for android/release and you should see the red text missing from how it looks on flash/release:

![text-two-fonts-ok-flash-release](https://cloud.githubusercontent.com/assets/16719964/13015176/f752e848-d1b7-11e5-8049-c89dceacc7f8.png)

**Comment by GimmickyApps** [comment]
Not sure if it's relevant, but within the DCE'd APK's assets\flixel\fonts\ directory, the nokia font does actually exist, so it's not that it gets excluded in that manner.

**Comment by Gama11** [comment]
I can't reproduce that - both texts are visible on Android.

**Comment by Gama11** [comment]
Hm, nevermind, I was compiling in debug mode.

**Comment by Gama11** [comment]
I just tested the [code snippet from your comment](https://github.com/HaxeFlixel/flixel/issues/1721#issuecomment-183219795), and it seems this is no longer an issue with the latest dev branch and OpenFL 8. 😄
