### ISSUE TITLE
StageSizeScaleMode ignored on html5/release and html5/debug

### ISSUE THREAD

**Issue by GimmickyApps** [HaxeFlixel/flixel#1722]
Just what the title says.  Behaves more like the default (I think), where the game width/height is scaled as large as can be, and when that doesn't match the aspect ratio of the window (whether windowed or fullscreen) you get black bars at the sides or at the top and bottom.  Same code on flash or windows targets works as it should.

This is on the HaxeFlixel dev branch updated yesterday, on Win7/64 with Firefox 44.0.2, haxe 3.2.1.

**Comment by Gama11** [comment]
Try setting `<window width="0" height="0" />` in your `Project.xml`. OpenFL's HTML5 backend does some letterboxing.

**Comment by GimmickyApps** [comment]
Interestingly, I put this in a `if="web"` tag, and on a flash target (which I didn't know implied web...thinking AIR) it made my window a seemingly random 800x500 (my Project.xml and Main both specify 1024x600.)

**Comment by Gama11** [comment]
Flash and HTML5 are both "web" (it's a define for a collection of targets, [similar to mobile or desktop](https://github.com/HaxeFlixel/flixel#runtime-targets)). That's probably just OpenFL's default size.

**Comment by GimmickyApps** [comment]
Ah, gotcha.  Thanks.  (I am trying to test this out, but for some reason my game is just blank on html5 right now.  Looking into it...)

**Comment by GimmickyApps** [comment]
`width="0" height="0"` does indeed fix it (I couldn't get my game working in html5 just now, but a demo worked this way.)  Thanks again!
