### ISSUE TITLE
Warning when compiling for android api 19

### ISSUE THREAD

**Issue by GimmickyApps** [HaxeFlixel/flixel#1723]
`C:/Development/Android NDK/toolchains/arm-linux-androideabi-4.4.3/prebuilt/windows/bin/../lib/gcc/arm-linux-androideabi/4.4.3/../../../../arm-linux-androideabi/bin/ld.exe: Warning: C:\Development\Android NDK/platforms/android-9/arch-arm/usr/lib/crtbegin_so.o: Unknown EABI object attribute 44`

Example code all found in [this project at this point in time](https://github.com/GimmickyApps/HaxeFlixelDevRepros/tree/41ca25cc727e14387db9737285d5be03af7ef310)

Latest HaxeFlixel dev branch, haxe 3.2.1, Win7/64 using FlashDevelop.

**Comment by Gama11** [comment]
I doubt this is a Flixel issue, you'd almost certainly get the same warning with a pure OpenFL project.

**Comment by GimmickyApps** [comment]
Oh.  How come, if you don't mind me asking?

-----Original Message-----

**Comment by Gama11** [comment]
Flixel doesn't really do anything Android-related, that all happens at Lime / OpenFL-level.

**Comment by GimmickyApps** [comment]
Ah, OK.  I had thought it did just based on a few issues mentioning Android like the immersive mode one. Good to know.  This may also apply to the text issues then too, eh?


-----Original Message-----

**Comment by Gama11** [comment]
It might.
