### ISSUE TITLE
Only with DCE enabled, only on android/release: FlxText.frameWidth/Height incorrect

### ISSUE THREAD

**Issue by IBwWG** [HaxeFlixel/flixel#1724]
Compile [this](https://github.com/GimmickyApps/HaxeFlixelDevRepros/tree/bee942e3d311291b1f534c5e8f5b8c45a930dfcc) with and without the DCE line enabled in Project.xml, and if your results are like mine you'll see the following numbers (the frame size for the text "    [Other Text]"):

windows/release, without DCE: 227, 34
flash/release, with or without DCE: 226, 34 (close enough for the gov't)
android/release, without DCE: 227, 34
**android/release, with DCE: 5, 4**

The gist:

``` haxe
var stampText = new FlxText(0, 0, 0, "    [Other Text]", 24);
stampText.font = "assets/fonts/graduate-regular-webfont.ttf";
stampText.color = FlxColor.GREEN;
stampText.text = stampText.frameWidth + ", " + stampText.frameHeight;

var sprite = new FlxSprite().makeGraphic(300, 300, FlxColor.BLUE);
sprite.stamp(stampText);
add(sprite);
```

The alternate font used is necessary at this point (in order to see the numbers in the visual output) due to #1721, which is also caused by having DCE enabled, and thus may be related.  (#1721 affects the default font, whereas this example shows other fonts being affected, but in a different way.)
##

**Comment by Gama11** [comment]
Hm, so this only happens in release mode.. very strange.

**Comment by Gama11** [comment]
With OpenFL 8, this now gives me:

- flash: 226, 34
- html5: 226, 32
- neko: 226, 34
- android: 226, 34

All release builds with DCE enabled.
