### ISSUE TITLE
Allow foregoing a save dialog on VCRFrontEnd.stopRecording() with flash target

### ISSUE THREAD

**Issue by GimmickyApps** [HaxeFlixel/flixel#1725]
- **Flixel version:** dev, updated just now
- **OpenFL version:** 3.6.0
- **Lime version:** 2.9.0
- **Affected targets:** flash (d/r)

________________________________

**Code snippet reproducing the issue**:

```haxe
		var save:String = FlxG.vcr.stopRecording();
```

________________________________

**Observed behavior:** A native Save dialog box opens, allowing the user to save the recording.
**Expected behavior:** A way to avoid this, so that I can use the VCR for integration testing.  (Or, suppose you want to handle the data internally, like for an instant replay a la Worms, without saving the file somewhere.)

**Comment by Gama11** [comment]
That seems sensible. Could be done via an added flag argument (`openSaveDialog` or similar).

**Comment by GimmickyApps** [comment]
Sorry for that first one, I forgot I had the pull request open on dev.  I rebased it and submitted a separate pull request with just the VCR change.

**Comment by GimmickyApps** [comment]
BTW I like the new issue template :)
