### ISSUE TITLE
FlxFilterFrames crashes on Android

### ISSUE THREAD

**Issue by DleanJeans** [HaxeFlixel/flixel#1731]
- **Flixel version:** 4.0.0
- **OpenFL version:** 3.6.0
- **Lime version:** 2.9.0
- **Affected targets:** Android (4.4.2)

________________________________

The [`FlxSpriteFilters`](https://github.com/HaxeFlixel/flixel-demos/tree/dev/Effects/FlxSpriteFilters) demo crashed on my Android, so did my game with `FlxFilterFrames` and `DropShadowFilter`. I think there's something wrong with them.
Also the demo need to be renamed to `FlxFilterFrames`.

**Comment by Gama11** [comment]
Can't reproduce this crash in the demo, even after triggering all of the animations and letting them play for a while.

The demo [didn't compile](https://github.com/HaxeFlixel/flixel-demos/commit/6959d370884ea7774249c2f5f8fa484667a12d19) with the current config though.

**Comment by Gama11** [comment]
Are you still experiencing this issue / is there any additional info that would help in reproducing it?

**Comment by DleanJeans** [comment]
Yeah, sorry. It works now. I just don't know why my game still crashes on my phone when I add shadow to the button.

**Comment by Gama11** [comment]
I guess this can be closed for now then.

Have you ever tried that on cpp desktop instead of Android? It's rare that one works and the other doesn't, since the rendering is pretty much the same, and debugging seems a lot easier on desktop.
