### ISSUE TITLE
VCR save dialog doesn't show intended file filter

### ISSUE THREAD

**Issue by GimmickyApps** [HaxeFlixel/flixel#1738]
- **Flixel version:** dev
- **OpenFL version:** 3.6.0
- **Lime version:** 2.9.0
- **Affected targets:** flash/debug (on Win7x64, running in standalone debugger)

________________________________

**Code snippet reproducing the issue**:

```haxe
FlxG.vcr.stopRecording();
```

________________________________

**Observed behavior:** Save dialog pops up with "All files (*.*)" in the type selector.  No other types present.
**Expected behavior:** Type selector should contain only "Flixel Game Recording", "*.fgr".  Not because I'm so picky about it, but because I noticed there's [code to do just that...already present](https://github.com/HaxeFlixel/flixel/blob/dev/flixel/system/frontEnds/VCRFrontEnd.hx#L21).

**Comment by Gama11** [comment]
The file filter is used for `onOpen()`. I don't think the `FileReference` API allows you to specify a file filter with `save()`...

**Comment by GimmickyApps** [comment]
Whoops, my bad.  Interesting difference...I wonder why that is.  Oh well.

**Comment by MSGhero** [comment]
When systools was used, the cpp library specifically excluded the parameter to specify file types on save. If openfl just copied it, then it won't be here. But the functionality exists, and it exists on flash iirc.
