### ISSUE TITLE
VCR doesn't record when keys and mouse used simultaneously

### ISSUE THREAD

**Issue by IBwWG** [HaxeFlixel/flixel#1739]
- **Flixel version:** dev (with unmerged vcr branch, but it should also affect main dev)
- **OpenFL version:** 3.6.0
- **Lime version:** 2.9.0
- **Affected targets:** flash/debug, but probably all

________________________________

**Code snippet reproducing the issue**:

(any working VCR.  try a "shift-click" for example, then try to find it in the .fgr output)

________________________________

**Observed behavior:** No shift-click recorded, only surrounding shifts.
**Expected behavior:**  Record the shift-click.

________________________________

**Cause:**  This behaviour seems oddly intentional, but maybe there was a different intention behind [the following code](https://github.com/HaxeFlixel/flixel/blob/dev/flixel/system/replay/FlxReplay.hx#L149), originally:

```haxe
	public function recordFrame():Void
	{
		var continueFrame = true;
		
		#if !FLX_NO_KEYBOARD
		var keysRecord:Array<CodeValuePair> = FlxG.keys.record();
		if (keysRecord == null) continueFrame = false;
		#end
		
		#if !FLX_NO_MOUSE
		var mouseRecord:MouseRecord = FlxG.mouse.record();
		if (mouseRecord == null) continueFrame = false;
		#end

		if (continueFrame)
		{
			frame++;
			return;
		}
		
		var frameRecorded = new FrameRecord().create(frame++);
//...
```

See, if either keys or mouse are null this frame, then we hit `continueFrame = false` and the frame gets recorded.  But if neither are null, it defaults to true, and the frame is incremented and the function returns without recording.

My best guess is the intention was to skip frames that didn't have keyboard or mouse input (I took care of this in my PR) but that the logic got implemented backwards--it probably should've been that continueFrame is false by default, and only made true if either keys or mouse are *not* null, i.e. only record when there's something to record.

**Comment by GimmickyApps** [comment]
The PR should be good to go, now, unless I missed anything else.
