### ISSUE TITLE
Width and height not set for graphic positioning

### ISSUE THREAD

**Issue by smks** [HaxeFlixel/flixel#1742]
- **Flixel version:** 4.0.1
- **OpenFL version:** 3.6.0
- **Lime version:** 2.9.0
- **Affected targets:** Flash

________________________________

```haxe
package;

import flixel.FlxState;

class PlayState extends FlxState
{
	override public function create():Void
	{
		createButtonBg();
                createIcon();
                positionIcon();
	}

	function createButtonBg():Void 
	{
		bgSprite = new FlxSpriteGroup();
		
		buttonBackground = new FlxSprite();
		
		buttonBackground.frame = textureAtlas.getByName(buttonBackgroundName);
		
		bgSprite.add(buttonBackground);
		
		bgShadow = new FlxSprite();
		
		bgShadow.frame = textureAtlas.getByName(buttonBackgroundShadeName);
		
		positionBgShadow();
		
		bgSprite.add(bgShadow);
		
		this.add(bgSprite);
	}
	
	function createIcon() 
	{
		iconSprite = new FlxSprite();
		
		iconSprite.frame = textureAtlas.getByName(this.icon);
		
		add(iconSprite);
	}

	function positionIcon() 
	{		
		this.iconSprite.offset = this.iconSprite.getGraphicMidpoint();
		
		this.iconSprite.setPosition(this.bgSprite.width / 2, this.bgSprite.height / 2);
	}
}
```

________________________________

The icon is not centered in the middle of the button background. Upon debugging I saw that width and height were set to 0.

The icon should appear in the middle of the button background.

**Comment by Gama11** [comment]
I didn't know there was a Flixel version 4.0.1. Where can I get that? :D

**Comment by Gama11** [comment]
That code snippet is not very helpful, as it can't be compiled.

**Comment by smks** [comment]
Sorry to waste your time. I was using the texture atlas assignment incorrectly.

		prop = new FlxSprite();
		prop.frames = textureAtlas;
		prop.animation.frameName = 'obstacles/rock';
		prop.resetSizeFromFrame();

Seems like more work though to do it this way?

**Comment by Gama11** [comment]
That seems to be how the TexturePackerAtlas demo does it, so I assume that's the correct usage. I don't really know much about this API, @Beeblerox is the expert there.

**Comment by MSGhero** [comment]
After setting `frames`, you add a new animation and play it. Although, I believe there's `setFrames()` that does the resize for you. It has a Boolean second parameter that you have to change from the default value so that it actually works. Not at my computer rn.

**Comment by MSGhero** [comment]
Proper usage is
```haxe
var sprite = new FlxSprite();
sprite.setFrames(textureAtlas, false);
sprite.animation.addByNames("default", ["obstacles/rock"], 0);
sprite.animation.play("default");
```
