### ISSUE TITLE
FlxG.overlap not triggering FlxTileMap callback

### ISSUE THREAD

**Issue by aprowe** [HaxeFlixel/flixel#1743]
- **Flixel version:** 4.0.0
- **OpenFL version:** 3.6.0
- **Lime version:** 2.9.0
- **Affected targets:** all

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxG;
import flixel.FlxSprite;
import flixel.FlxState;
import flixel.FlxObject;
import flixel.tile.FlxTilemap;

class TestState extends FlxState
{
	public var tilemap:FlxTilemap;
	public var sprite:FlxSprite;

	override public function create():Void
	{
		tilemap = new FlxTilemap();
		tilemap.loadMapFromCSV("1", "tiles.png", 16, 16);
		tilemap.setTileProperties(1, FlxObject.ANY, function(o1:FlxObject, o2:FlxObject) {
			FlxG.log.notice("Callback Triggered");
		});
		add(tilemap);

		sprite = new FlxSprite(0,32);
		sprite.makeGraphic(16,16);
		sprite.velocity.y = -8;
		add(sprite);
	}

	override public function update(dt:Float):Void
	{
		super.update(dt);

		FlxG.collide(sprite, tilemap); // 'Callback triggered', works correctly
		FlxG.overlap(sprite, tilemap); // Nothing happens!
	}
}
```

________________________________

**Observed behavior:**
`FlxG.collide` **does** trigger the supplied callback on tilemap.
`FlxG.overlap` **does not** trigger the callback.

**Expected behavior:**
`FlxG.overlap` should call the callback provided using `setTileProperties`

--------------------------

I hope the issue is clear. Basically `FlxG.overlap` is not calling the `setTileProperties` callback. 
Looking at the source, maybe it has to do with how `FlxObject.separate` specially treats Tilemaps? Any Ideas?

(Heres the tilemap png because I couldn't figure out how to generate a tilemap without one). 
![tiles](https://cloud.githubusercontent.com/assets/7191456/13313968/c4344fba-db67-11e5-8edb-dc8753c62605.png)

**Comment by aprowe** [comment]
Well, `tilemap.overlaps(sprite)` works, after getting a hint from https://github.com/HaxeFlixel/flixel/issues/1376. 
So it is solved.

**Comment by aprowe** [comment]
The problem complicates (perhaps a different issue?) -_-

I'm overlapping a tilemap with a FlxGroup, and `tilemap.overlaps(group)` correctly triggers the callback for the first sprite in the group (I'm using a group for bullets), but subsequent overlaps within the same group do not trigger the callback. 

When I use `group.forEachAlive` on `tilemap.overlaps(sprite)` it works fine, the callback triggers every time.

**Comment by Gama11** [comment]
For the record, you can't create a tilemap without a graphic, but you can use the one included by default:

```haxe
tilemap.loadMapFromCSV("1", FlxGraphic.fromClass(GraphicAuto));
```

**Comment by Gama11** [comment]
Alternatively to `tilemap.overlaps()`, you could try setting the `AllowCollisions` value of that tile type `FlxObject.NONE` to get the same behavior with `FlxG.overlap()` as you would with `collide()`.

That other thing you described does seem like a different issue, so I'm closing here. Feel free to open a new issue with a code snippet for that one.
