### ISSUE TITLE
FlxText randomly won't draw

### ISSUE THREAD

**Issue by AaronShea** [HaxeFlixel/flixel#1747]
- **Flixel version:** 4.0.0
- **OpenFL version:** 3.6.0
- **Lime version:** 2.9.0
- **Affected targets:** Windows (So far)

It seems some of my text fields used for dialog randomly refuse to draw, I've narrowed down the commit that caused this issue to 20ba6d3e061b6b12db91b46cea2bbb53f0a74493.

If I re-add the lines `_regen = true` and `calcFrame()` back into the constructor then remove `drawFrame()` everything works as expected.

**Comment by Gama11** [comment]
What exactly does "randonmly" mean? How can I reproduce this?

**Comment by AaronShea** [comment]
I'll work on getting a small example up to try and replicate this issue. 

But as for how it's implemented over here: I have a class that extends `FlxText`. A text buffer is added one letter at the time to the actual `text` member (creates a typing effect). This is contained inside a `FlxSpriteGroup` used for the actual dialog box.
This box is constructed in the `new` method of a map state, it's later added to the state after the tilemaps are built etc.

The DialogBox also is being drawn on a separate camera using `diagBox.cameras = [guiCamera];`, so I can avoid zooming the GUI when I zoom into the map.

**Comment by Gama11** [comment]
It's probably reproducible with a single `FlxText` instance - I doubt sprite groups or cameras have any influence here.

**Comment by GimmickyApps** [comment]
I also experienced this but have yet to narrow it down.  In my case I had an array of prepared FlxTexts, which show one at a time as I press a key.  After half way through the array, instead of showing the next one, the existing ones started to disappear in reverse order.  Bizarre.

**Comment by AaronShea** [comment]
Having some problems trying to make a nice neat package to reproduce this issue with. But I know that my dialog box and text are being added in the correct order. Interestingly enough, when the text has to word wrap, the text will suddenly appear, and then work for the rest of the running session. 
Very strange, still looking into this.

**Comment by AaronShea** [comment]
Right, figured out what was going on!
I was at first creating my camera an dialog box in the constructor, and adding them later in `create()`
This worked in older version of flixel, however, I now need to create these in `create()`, all works fine now!
