### ISSUE TITLE
FlxText randomly CRASHING

### ISSUE THREAD

**Issue by eminfedar** [HaxeFlixel/flixel#1748]
- **Flixel version:** 4.0.0
- **OpenFL version:** 3.6.0
- **Lime version:** 2.9.0
- **Affected targets:** Windows [XP to 10]

________________________________

**Code snippet reproducing the issue**:

```haxe
	// Text Adding Code.
	TestT = new FlxText(10, 10, 200, "Test", 14, true);
	TestT.text = "";
	TestT.font = "assets/data/arial.ttf";
	TestT.scrollFactor.set(0, 0);
	TestT.fieldWidth = 200;
	add(TestT);
```

________________________________

**Observed behavior:** http://imgur.com/bwRjPW3
**Expected behavior:** When I change text, it must be changed properly.

**Comment by Gama11** [comment]
I can't reprouce your problem with the provided code - the rendered code is empty / invisible like you would expect after `.text = ""`.

That "observed behavior" screenshot seems unrelated to your sample code?

**Comment by adrianulima** [comment]
I also tried to reproduce, I changed the `text` in the `update()` and it is all working fine to me.

**Comment by eminfedar** [comment]
It happens rarely, I don't know why. %90 percent works great with no problem, but rarely "boom!" it has crashed. I just use ".text" to change the text. Nothing unusual. Maybe it's about other codes prevent rendering text?

**Comment by Gama11** [comment]
Just to clarify, by "crashing" you mean the text looks jumbled like in your screenshot, not the game actually crashing?

**Comment by eminfedar** [comment]
> Just to clarify, by "crashing" you mean the text looks jumbled like in your screenshot, not the game actually crashing?

Sometimes both game and text crash, sometimes only texts. I actualy don't know why, step-by-step debugging not working on flashdevelop you know.

**Comment by Gama11** [comment]
Not much we can do here without some code that reproduces it.

**Comment by eminfedar** [comment]
Hey, I have news!
This is crash report from Visual Studio : http://imgur.com/pz0KcV5

@Gama11

**Comment by Gama11** [comment]
The call stack isn't that useful without a way to reproduce it. Especially considering this a C++, not a Haxe callstack.
