### ISSUE TITLE
HTML Preloader doesn't show for v4

### ISSUE THREAD

**Issue by smks** [HaxeFlixel/flixel#1750]
- **Flixel version:** 4.0.0
- **OpenFL version:** 3.6.0
- **Lime version:** 2.9.0

Affects HTML5

```xml
<app preloader="flixel.system.FlxPreloader" />
```

I used to see a white bar preloader for HTML5 go from left to right. Now it is just a blank screen when loading.

I should see the default white bar load the game.

**Comment by GimmickyApps** [comment]
Unit test candidate... :)

**Comment by Gama11** [comment]
@GimmickyApps I actually have no idea how you'd unit-test this...

**Comment by GimmickyApps** [comment]
I suppose by a pixel colour test, like the one you made for the font fix a few months ago?

**Comment by Gama11** [comment]
The problem is that the preloader would run before the unit tests.. to well, load them. You could maybe get it to be executed at a later point too, but then the game is already loaded, so it might just finish instantly.

**Comment by smks** [comment]
Can I ask why this has been closed as it is still an issue?

**Comment by Gama11** [comment]
Should be fixed, I see the preloader.
