### ISSUE TITLE
Oversize textures show up blank (black-filled) on windows target

### ISSUE THREAD

**Issue by GimmickyApps** [HaxeFlixel/flixel#1751]
- **Flixel version:** dev
- **OpenFL version:** 3.6.0 legacy
- **Lime version:** 2.9.0
- **Affected targets:** windows, but not flash

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxState;

class PlayState extends FlxState
{
	override public function create():Void
	{
		add(new FlxSprite(500,500).loadGraphic(AssetPaths.dolphinsCloseUp__png, false, 1893, 4198, true));
	}
}
```

________________________________

**Observed behavior:** Image at 500,500 is black.
**Expected behavior:** Image should show its actual content.

If I scale the image down 10x (and adjust the constructor call to match), it works fine on windows target.
If I use flash target, the giant image works fine the way it is (if a bit slow.)

This is on a laptop with Intel HD graphics (shared memory, I believe, eating into the 4 GB of system RAM.)

**Comment by Gama11** [comment]
That code to reproduce would be a lot more helpful with an asset so it can be compiled.

**Comment by GimmickyApps** [comment]
Really?  You need to see my dolphins?  Not any old non-black 1893x4198 will do?  OK, let me make something.

**Comment by Gama11** [comment]
`new BitmapData()` might be good enough as well, but either way, the code snippet is not compilable as is. :P

**Comment by GimmickyApps** [comment]
![dolphinscloseup](https://cloud.githubusercontent.com/assets/16719964/13374861/98f8f5c8-dd90-11e5-81b4-b2226bc0c105.png)
This file, while not my currently secret original dolphins, does also exhibit the problem, I just compiled to check.  :)

**Comment by GimmickyApps** [comment]
![this version of the file](https://cloud.githubusercontent.com/assets/16719964/13374879/d48352a0-dd90-11e5-9ae7-52fa02dc0bce.png) with this code:

```haxe
package;

import flixel.FlxState;

class PlayState extends FlxState
{
	override public function create():Void
	{
		add(new FlxSprite(500,500).loadGraphic(AssetPaths.dolphinsCloseUp__png, false, 190, 420, true));
	}
}
```
...has no problems.

**Comment by GimmickyApps** [comment]
But you're right, you don't need my very special drawings.  This also causes the problem (windows target but not flash target):

```haxe
add(new FlxSprite().makeGraphic(1893, 4198, FlxColor.GREEN, true));
```

**Comment by Gama11** [comment]
The first version of the image doesn't cause any issues for me. It seems very likely that you're simply hitting the max texture size of your graphics card (presumably 4096x4096?). You can check that via `FlxG.bitmap.maxTextureSize` - for me that value is16384.

**Comment by GimmickyApps** [comment]
Indeed, at 1893x4096 I see green on windows/release.  Thank you so much, and for the lead, I didn't realize that function existed.  I can use that to load alternative textures when need be.  Also, do you happen to know how common it might be to have a lower limit than 4096x4096?

**Comment by Gama11** [comment]
That depends on the target. On mobile devices, the limit can be quite low, on some older devices even as low as 1024x1024.

**Comment by GimmickyApps** [comment]
That's very handy to know.  Thanks again.
