### ISSUE TITLE
[HaxeDevelop] Bounty for OpenFL + HaxeFlixel setup in AppMan

### ISSUE THREAD

**Issue by gamedevsam** [HaxeFlixel/flixel#1753]
**(This is technically a [HaxeDevelop](https://github.com/fdorg/flashdevelop/issues/1091) issue, but I'm copying it here for visibility and tracking)**

-------------------------
__UPDATE: Points 1 and 3 of the bounty have been claimed by [Meychi](https://github.com/Meychi), point 2 was claimed by [PeyTy](https://github.com/PeyTy). Thanks everyone, bounty is now closed!__
-------------------------
It's become apparent to me that [HaxeFlixel](http://haxeflixel.com/) should be the easiest way to get started making cross platform 2D games. But the current [HaxeFlixel setup](http://haxeflixel.com/documentation/getting-started/) is somewhat involved, requiring command line usage and multiple steps. We live in an age of instant gratification, and quite frankly, that's more steps than it needs.

[HaxeDevelop](haxedevelop.org) already employs a clever solution to install additional libraries, AppMan! So in theory, it could be expanded to install OpenFl and HaxeFlixel. We could also make it easier for new users to get started by allowing them to start a [flixel-demo](https://github.com/HaxeFlixel/flixel-demos) project as a template.

![haxeflixel setup in appman](https://cloud.githubusercontent.com/assets/420996/13386016/9cd48ba4-de75-11e5-823a-98e629c5ae82.png)

I am offering a bounty for the developer(s) who can implement this request. I propose a tiered reward, to promote maximum availability of HaxeFlixel:

1. ~~$100 for the addition of OpenFL and HaxeFlixel to AppMan~~
2. ~~$50 for the addition of adding Flixel Demos as Templates in HaxeDevelop~~
3. ~~$50 for ensuring HaxeDevelop and HaxeFlixel can be installed in Mac and Linux~~

Total bounty: $200

**[To claim this bounty follow the instructions on this blog post to contact me](https://www.patreon.com/posts/financial-06-15-4421829)**.

__IMPORTANT:__ Updating the [Getting Started](http://haxeflixel.com/documentation/getting-started/) section of the docs with this alternative setup process is a requirement for claiming the bounty.

__PS:__ I am offering this bounty in good faith, in the interest of HaxeFlixel communty, and is funded through [Patreon](https://www.patreon.com/haxeflixel?ty=h) donations. If multiple people claim this bounty, I will do my best to make a fair distribution of the bounty (I reserve the right to deny the bounty if I suspect foul play).

-------------------------

https://github.com/HaxeFlixel/flixel/issues/1753

**Comment by MintPaw** [comment]
> ensuring HaxeDevelop and HaxeFlixel can be installed in Mac and Linux
What does this mean? HaxeDevelop cannot be run on Mac or Linux by design and will require emulation where results will vary vastly from release to release.

The current setup procedure is suited to multi-platform educated development, it doesn't really aim for the most general new game developer. It's recommended to use something like Stencyl for simplified development, as it does also run on HaxeFlixel.

**Comment by Gama11** [comment]
Stencyl does _not_ run on HaxeFlixel.

**Comment by MintPaw** [comment]
Oops, Stencyl used to run on the old version of Flixel, I should of researched that before saying it.

**Comment by gamedevsam** [comment]
I'm open to a solution that doesn't involve HaxeDevelop, but it should provide an IDE that is easy to use for beginners.

**Comment by gamedevsam** [comment]
```
What does this mean? HaxeDevelop cannot be run on Mac or Linux by design and will require emulation where results will vary vastly from release to release.
```

I don't specify what is required to claim that part of the bounty, because that's not my main concern with this bounty. I want to encourage the development of a setup process that caters to the absolute beginners, and that also integrates with an IDE that allows developers to make games without worrying about the command line. Ensuring users on Mac / Linux can access these tools is important to me, but since that wasn't my main goal I can accept requiring middleware to make that happen.

I'm open to a solution that doesn't involve HaxeDevelop, but adding HaxeFlixel setup to HaxeDevelop was the quickest way to meet those requirements.

**Comment by gamedevsam** [comment]
__This bounty has been claimed by [Meychi](https://github.com/Meychi)__

**Comment by gamedevsam** [comment]
Closed prematurely, one portion of the bounty remains: ```$50 for the addition of adding Flixel Demos as Templates in HaxeDevelop```

**Comment by PeyTy** [comment]
@gamedevsam @larsiusprime Here we are!

![2016-09-05 08-56-16](https://cloud.githubusercontent.com/assets/3642643/18239153/ee81066a-734b-11e6-9f57-c42d196aab28.png)

![2016-09-05 08-55-42](https://cloud.githubusercontent.com/assets/3642643/18239154/f1fb9c24-734b-11e6-846d-061fee2c678c.png)

This package effectively adds 79 demo templates. But my FD/HD installation is buggy so I have strange bugs on project creation. May you reproduce? Also, does this corresponds to the task?

Steps to reproduce:
1. Find your HD/FD installation path, usually `C:\Program Files\HaxeDevelop\`
2. Open file `C:\Program Files\HaxeDevelop\Tools\appman\Config.xml`
3. Change `<Config>` appman.xml tag link to `http://peyty.github.io/bin/appman.xml`
4. Start AppMan
5. Install HaxeFlixel Demos package
6. Open HD, `Project -> New Project...` scroll down

**Comment by PeyTy** [comment]
@gamedevsam @larsiusprime Updated packages, works for me!

**Comment by gamedevsam** [comment]
Have you made a pull request to HaxeDevelop / FlashDevelop github?

**Comment by PeyTy** [comment]
@gamedevsam Not yet, I awaited any feedback. Should I make a PR?

**Comment by gamedevsam** [comment]
Absolutely, the HD / FD crew are more likely to give you valuable feedback on your implementation, and having this integrated with HaxeDevelop would be much easier from an end user standpoint.

**Comment by Gama11** [comment]
Hosting this on peyty.github.io seems strange to me. The HaxeFlixel org on GitHub should be who's managing this. Also, how does updating the package work? Is there a script or something?

**Comment by PeyTy** [comment]
@Gama11 I hosted it just for a demo purposes. Flixel templates are hosted on https://raw.github.com/HaxeFlixel/flixel-templates/ so I will PR to flixel-demos the final version. Script is WIP and will be shared too.

**Comment by PeyTy** [comment]
@gamedevsam Yay! Demos are now bundled with official HaxeDevelop Appman distribution!

**Comment by gamedevsam** [comment]
Thank you very much for the great work, bounty is on its way!

**Comment by PeyTy** [comment]
Received! Thanks!
![image](https://cloud.githubusercontent.com/assets/3642643/18920785/1db80656-85ab-11e6-9f06-67112a963da0.png)
