### ISSUE TITLE
FlxStringUtil.formatMoney

### ISSUE THREAD

**Issue by smks** [HaxeFlixel/flixel#1754]
- **Flixel version:** 4.0.0
________________________________

var price:Int = 60; // in pence
trace('£' + FlxStringUtil.formatMoney(this.price / 100));

// shows £.60;

```haxe
package;

import flixel.FlxState;
import flixel.util.FlxStringUtil;

class PlayState extends FlxState
{
	override public function create():Void
	{
		var price:Int = 60; // in pence
                trace('£' + FlxStringUtil.formatMoney(this.price / 100));

                // shows £.60;
	}
}
```

________________________________

Should show as £0.60

**Comment by DleanJeans** [comment]
Didn't even know this function exists. BTW could you replace `EnglishStyle:Bool` with a String parameter named `Separator' or something? Since I want the decimals separated by a space instead of dots or commas.

**Comment by Gama11** [comment]
Yeah, that `EnglishStyle` arugment seems unnecessarily inflexible.. I don't really want to replace it right now though, that would break backwards compatibility. For now you can just run `StringTools.replace(".", " ")` on the result.

**Comment by DleanJeans** [comment]
Whoops! I edited the comment and Slack didn't seem to update that.
What I meant was (keep `EnglishStyle` for the decimal point and) add a parameter for the separators/delimiters to group the digits.

**Comment by Gama11** [comment]
Then we'd have two arguments that do almost the same thing. Which argument would take precedence? Seems a bit messy.
