### ISSUE TITLE
FlxSprite.pixels.draw() sometimes doesn't

### ISSUE THREAD

**Issue by GimmickyApps** [HaxeFlixel/flixel#1756]
- **Flixel version:** dev
- **OpenFL version:** 3.6.0
- **Lime version:** 2.9.0
- **Affected targets:** flash, maybe others

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxSprite;
import flixel.FlxState;
import flixel.util.FlxColor;
import openfl.geom.Rectangle;



class PlayState extends FlxState
{
    override public function create():Void
    {
		var source = new FlxSprite().makeGraphic(200, 100, FlxColor.GREEN, true);
		var destLeft = new FlxSprite(   0, 0).makeGraphic(100, 100, 0, true); // put it at the origin
		var destRight = new FlxSprite(300, 0).makeGraphic(100, 100, 0, true); // put it on the right, with a 200px gap between it and destLeft
		destLeft.pixels.draw( source.pixels, null, null, null, new Rectangle(0,   0, 100, 100)); // copy the left half of source
		destRight.pixels.draw(source.pixels, null, null, null, new Rectangle(100, 0, 100, 100)); // copy the right half of source
		add(destLeft);
		add(destRight);
		
    }
}
```

________________________________

**Observed behavior:**  Only `destLeft` has any green pixels from `source` drawn onto it.
**Expected behavior:** `destRight` ought to, too.  It should look the same as if you use `copyPixels` instead of `draw`:

```haxe
		destLeft.pixels.copyPixels(  source.pixels, new Rectangle(0,   0, 100, 100), new Point(0,0)); // copy the left half of source
		destRight.pixels.copyPixels( source.pixels, new Rectangle(100, 0, 100, 100), new Point(0,0)); // copy the right half of source
```

**Comment by GimmickyApps** [comment]
I'm not sure if https://github.com/openfl/openfl/issues/794 has any relevance here or not.  I guess this is most likely an OpenFL issue, but OTOH I'm experiencing it in a HaxeFlixel context and I haven't had a chance yet to look into what the barebones OpenFL equivalent would be (what does `makeGraphic()` use, what type of object should I use for the destinations, etc.)

**Comment by Gama11** [comment]
This can't really be an OpenFL issue on the Flash target.

**Comment by adrianulima** [comment]
You are drawing wrong, outside the bitmapData. Both should be `new Rectangle(0, 0, 100, 100)`.

**Comment by Gama11** [comment]
It seems like you need a transformation matrix as well for the `clipRect` argument to work as you expect (see http://blog.stroep.nl/2009/05/how-to-crop/).

Also, doing this with pure Flash API gets you the same result, so this has nothing to do with Flixel:

```haxe
package;

import flash.display.BitmapData;
import flixel.FlxG;
import flixel.FlxState;
import flixel.util.FlxColor;
import openfl.geom.Rectangle;

class MenuState extends FlxState
{
    override public function create():Void
    {
		var source = new BitmapData(200, 100, true, FlxColor.GREEN);
		var destLeft = new BitmapData(100, 100, true, 0);
		var destRight = new BitmapData(100, 100, true, 0);
		destLeft.draw(source, null, null, null, new Rectangle(0, 0, 100, 100));
		destRight.draw(source, null, null, null, new Rectangle(100, 0, 100, 100));
		
		FlxG.bitmapLog.add(source);
		FlxG.bitmapLog.add(destLeft);
		FlxG.bitmapLog.add(destRight);
    }
}
```

**Comment by GimmickyApps** [comment]
Thanks @Gama11 somehow I did not find that at all clear from Adobe's docs.
