### ISSUE TITLE
Neko+Tilemap problem

### ISSUE THREAD

**Issue by xerosugar** [HaxeFlixel/flixel#1757]
- **Flixel version:** 4.0.0.
- **OpenFL version:** 3.6.0
- **Lime version:** 2.9.0
- **Affected targets:** Neko

When trying to "trace" a FlxTilemap the program crashes because it cannot "stringify" it for some reason. Win target works tho.

**Observed behavior:** 
"$nargs
Called from Type::createInstance line 102
Called from flixel.util.FlxPool_flixel_util_LabelValuePair::get line 34
Called from flixel.util.LabelValuePair::weak line 603
Called from flixel.FlxObject::toString line 1088
..."

**Expected behavior:** To see something like: (x: 0 | y: 0 | w: 336 | h: 336 | visible: true | velocity: FlxPoint)

**Comment by Gama11** [comment]
Please provide some code to reproduce. Doing this in Mode works fine.

**Comment by xerosugar** [comment]
Hm, that's odd. I'm doing this with a TiledLevel also, if that could have something to do with it.
In the Tiled demo, try and add 'trace(tilemap);' under 'collidableTileLayers.push(tilemap);' on (row 94) to see what happens. That crashes it for me.

**Comment by Gama11** [comment]
That gets me this output, no crash:

```
TiledLevel.hx:92: (x: 0 | y: 0 | w: 7040 | h: 576 | visible: true | velocity: (x: 0 | y: 0))
```

What Haxe version are you on?

**Comment by xerosugar** [comment]
3.2.1

**Comment by Gama11** [comment]
No issues there either (I was on 3.2.0).

![](http://i.imgur.com/By3LiPw.png)

**Comment by xerosugar** [comment]
interesting
how do you generate a Tiled demo again?

**Comment by Gama11** [comment]
With flixel-tools you mean? `flixel create <demo-name>` (`TiledEditor` in this case).

**Comment by xerosugar** [comment]
ok, doing it from a fresh Tiled demo project worked

**Comment by xerosugar** [comment]
wonder if it's my .tmx file or something else that's messed up

**Comment by Gama11** [comment]
Try cleaning your export directory in the project where you have issues maybe?

Either way, seems like there isn't a bug here (with Flixel at least). Would still be interesting to know what's happening here.

**Comment by xerosugar** [comment]
nah, shouldn't be the tmx file. it works on win...
alright, thanks for the help!

**Comment by Gama11** [comment]
Do you have DCE enabled in the other project by chance?

**Comment by xerosugar** [comment]
I dunno, what's that?

**Comment by Gama11** [comment]
Dead code elimination, a Haxe feature that removes unused code. Can sometimes cause issues with code that isn't fully statically typed, like the `Type.createInstance()` call in your stacktrace. However, you would have to add that manually to your `Project.xml`, so I guess you're not using it. :)

http://haxe.org/manual/cr-dce.html

**Comment by Gama11** [comment]
Nevermind, that's actually exactly the stacktrace I get as well with `<haxedef name="dce=full" />`.

**Comment by xerosugar** [comment]
hehe, I had that in my project-file :)
ah, and I could trace the tilemap if I remove DCE, but it still crashes. same error message too.

**Comment by Gama11** [comment]
Are you sure it's the _exact_ same error message?

**Comment by xerosugar** [comment]
the lines in my 1st message are the same at least

**Comment by Gama11** [comment]
Should be fixed.. can you try with DCE enabled and latest dev?

**Comment by xerosugar** [comment]
the error is gone, yay :)
but now something else happens; the 'widthInTiles' property on my map is always the same as the heightInTiles... that's... interesting. And I can change the map's width in Tiled and the height will always get the same value as the width :D

**Comment by xerosugar** [comment]
oh, wait. hold on

**Comment by Gama11** [comment]
:+1:
