### ISSUE TITLE
FlxMousEventManager onMouseDown broken if registered before resize

### ISSUE THREAD

**Issue by GimmickyApps** [HaxeFlixel/flixel#1758]
- **Flixel version:** dev
- **OpenFL version:** 3.6.0
- **Lime version:** 2.9.0
- **Affected targets:** flash

________________________________
** this has a compiler problem I don't understand...see below**
**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxG;
import flixel.FlxSprite;
import flixel.FlxState;
import flixel.input.mouse.FlxMouseEventManager;
import flixel.util.FlxColor;

class PlayState extends FlxState
{
    override public function create():Void
    {
		FlxG.plugins.add(new FlxMouseEventManager());
		var sprite = new FlxSprite();
		FlxMouseEventManager.add(sprite, onDown, null, null, null, false, true, true, null);
		sprite.makeGraphic(200, 100, FlxColor.GREEN);
		add(sprite);
		
    }
	function onDown() 
	{
		trace("onDown");
	}
}
```

________________________________

**Observed behavior:** `source/PlayState.hx:19: characters 2-85 : Cannot skip non-nullable argument MouseChildren`
**Expected behavior:** I would think it would compile (especially since I did actually provide the non-nullable argument MouseChildren, which is actually nullable, anyway) and show a sprite that doesn't trace when clicked.

Within my project, which I was trying to narrow down to a reproducible example:
**Observed behavior:** No trace on click, unless I put the `FlxMouseEventManager.add()` call after the `makeGraphic()` and also a `setPosition` call.
**Expected behavior:** Trace on click.

**Comment by Gama11** [comment]
The function signature of `FlxMouseEventManager` callbacks is `FlxSprite->Void`, so `onDown()` has to look like this:

```haxe
function onDown(sprite:FlxSprite) {} 
```

Alternatively, it's common practice to name un unused argument `_`:

```haxe
function onDown(_) {} 
```

You're right in that this error message is quite misleading - it should really complain about the function type. However, that's not a Flixel issue and has been fixed on Haxe dev already (see https://github.com/HaxeFoundation/haxe/issues/2232) where I get this error:

```
source/PlayState.hx:15: characters 41-47 : Void -> Void should be Null<flixel.FlxSprite -> Void>
source/PlayState.hx:15: characters 41-47 : Void -> Void should be flixel.FlxSprite -> Void
source/PlayState.hx:15: characters 41-47 : For optional function argument 'OnMouseDown'
```

___________________

>especially since I did actually provide the non-nullable argument MouseChildren, which is actually nullable, anyway

`MouseChildren` is a `Bool` and as such not nullable on static targets like Flash.

**Comment by GimmickyApps** [comment]
Ah, thank you, of course I had forgotten the sprite in the function sig.  Okay, but that was just a side issue to the main issue, which I am still trying to narrow down.  It's apparently not about makeGraphic() since in my project I just tested with the mouse add *just* after the makeGraphic() call and it doesn't respond to mouse events.  So maybe it's setPosition(), hang on...
