### ISSUE TITLE
FlxTween.num's onUpdate vs TweenFunction

### ISSUE THREAD

**Issue by IBwWG** [HaxeFlixel/flixel#1759]
- **Flixel version:** dev

They're both called whenever there's an update, right?  So why are there these two separate concepts?  (Should `TweenOptions.onUpdate` be removed in the context of `FlxTween.num()`, and if not, could the reason for its existence be made clearer in the docs?)

**Comment by Gama11** [comment]
Ugh... I think the `TweenFunction` param was simply added before there was an `onUpdate` in `TweenOptions`. Though the former has the very minor advantage of directly having the `Float` as an argument I guess.

I wonder if you can mark function arguments as `@:deprecated`. Just remvoing it, you guessed it, would be a breaking change.

**Comment by MSGhero** [comment]
Not with `@:deprecated` you can't. All the tag does is display a warning message in the output, so we could do that too? `haxe.Log.trace()` or flixel's own.

**Comment by Gama11** [comment]
Let's leave this open for now to see if `@:deprecated` for function args gets added to Haxe eventually:

https://github.com/HaxeFoundation/haxe/issues/5151

**Comment by IBwWG** [comment]
Fair enough, sorry.

**Comment by Gama11** [comment]
Looks like that's not gonna happen.
