### ISSUE TITLE
Dead asset elimination?

### ISSUE THREAD

**Issue by GimmickyApps** [HaxeFlixel/flixel#1768]
- **Flixel version:** dev
- **OpenFL version:** 3.6.0
- **Lime version:** 2.9.0
- **Affected targets:** windows release

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxSprite;
import flixel.FlxState;

class PlayState extends FlxState
{
    override public function create():Void
    {
		var sprite = new FlxSprite().loadGraphic(Reflect.getProperty(AssetPaths, "dolphin__png"));
		add(sprite);
    }
}
```
Using [this dolphin.png](https://cloud.githubusercontent.com/assets/16719964/13374879/d48352a0-dd90-11e5-9ae7-52fa02dc0bce.png)
________________________________

**Observed behavior:**  Sprite placeholder appears instead of dolphin.png image, despite the fact that dolphin.png was correctly copied into the bin/assets/images/ folder (clean build.)
**Expected behavior:** That the requested image would appear, like it does in flash debug/release targets.

I tried to make a workaround, thinking if I loaded all my assets the normal way, then those that I accessed with Reflect would be available afterwards.  Not so.  The following code:

```haxe
var spriteWorkaround = new FlxSprite().loadGraphic(AssetPaths.dolphin__png);
add(spriteWorkaround);
var sprite = new FlxSprite().loadGraphic(Reflect.getProperty(AssetPaths, "dolphin__png"));
add(sprite);
```
...correctly loads dolphin.png the first time, but the second time gives a placeholder still.

**Comment by Gama11** [comment]
Why use `AssetPaths` at all here? Would be much nicer to just use the String path, instead of Reflection (which should be avoided).

**Comment by GimmickyApps** [comment]
Only because I thought that was The Way It Is Done In HaxeFlixel.  If I may pass the question back to you, why use `AssetPaths` normally, and why not use it here?  (And why should Reflection be avoided?  It seems to have so many handy DRY uses.)

**Comment by larsiusprime** [comment]
Reflection has two issues I know of:

1) It's slow, especially if you use it in core loops
2) Dead Code Elimination can't account for it

**Comment by Gama11** [comment]
`AssetPaths` just creates variables containing the String paths to assets. This provides
- auto-comletion in IDEs with Haxe compiler completion
- a certain degree of type-safety - if an asset is renamed / moved / deleted, the variable name will change, resulting in a _compile-time_ error (normally this would be a runtime error with String paths)

So, using Reflection on `AssetPaths`... defeats the whole point of `AssetPaths`. Reflection leads to runtime errors and is _not_ type-safe.

**Comment by larsiusprime** [comment]
For your loadGraphic function I think you give the actual asset name, so just `"assets/images/dolphin.png"` should do the trick.

**Comment by GimmickyApps** [comment]
I see.  Thanks both of you for your help, I understand much better now.

**Comment by larsiusprime** [comment]
Good luck!

**Comment by GimmickyApps** [comment]
Thanks :)
