### ISSUE TITLE
API document out of date/wrong

### ISSUE THREAD

**Issue by buckle2000** [HaxeFlixel/flixel#1773]
Many apis are missing or wrong on http://api.haxeflixel.com/.
e.g. on http://api.haxeflixel.com/openfl/utils/index.html, there is no openfl.utils.Timer.
same for flash.*
These apis are supposed here as they are on http://api.openfl.org/.

**Comment by Gama11** [comment]
There's no `openfl.utils.Timer` on that page. Try clearing your cache (Shift+F5).

**Comment by dstrekelj** [comment]
@Gama11, I believe that was his point.

`openfl.utils.Timer` is [present](http://www.openfl.org/documentation/api/openfl/utils/index.html) in the OpenFL API documentation, while it is missing from same package in the HaxeFlixel API documentation.

The "issue" appears to be that the API docs of HaxeFlixel dependencies (or, at the very least, OpenFL) are either outdated or improperly generated.

I find that all of the docs being in one place is a convenience, and not a necessity. However, if they are being included, then care must be taken to ensure they are correct.

**Comment by buckle2000** [comment]
Yes, I was trying to express that. @dstrekelj

**Comment by buckle2000** [comment]
Also, maintaining docs of flash.* is redundant, since they are almost the same as openfl.*.
By "almost", I mean that some (well, many) apis are only available on flash platform, but not yet implemented on others in OpenFL.

**Comment by Gama11** [comment]
There isn't really much "maintaining" there, it's all generated.

**Comment by Gama11** [comment]
@buckle2000 You say there are "many" missing APIs. What else besides openfl.utils.Timer?

**Comment by buckle2000** [comment]
e.g. 20+ new apis in openfl.display since the doc here was generated
just check here http://api.openfl.org/ and compare the indexs on the left

**Comment by Gama11** [comment]
Moved to flixel-docs: https://github.com/HaxeFlixel/flixel-docs/issues/160
