### ISSUE TITLE
Something unrelated in haxelib distribution.

### ISSUE THREAD

**Issue by buckle2000** [HaxeFlixel/flixel#1774]
- **Flixel version:** 4.0.0

`haxelib install flixel`
![default](https://cloud.githubusercontent.com/assets/10850402/13729280/3d603e0a-e96c-11e5-9078-7a148b000ddd.PNG)

I think the following files and folder should not appear in the distribution of haxelib `flixel`:
- tests/
- .editorconfig
- .gitattributes
- showcase.png

Well, it doesn't matter.

**Comment by Gama11** [comment]
Guess you're right, not much of a point to include these files in haxelib releases.
