### ISSUE TITLE
FlxSpriteUtil.alphaMask not working?

### ISSUE THREAD

**Issue by GimmickyApps** [HaxeFlixel/flixel#1776]
- **Flixel version:** dev
- **OpenFL version:** 3.6.0
- **Lime version:** 2.9.0
- **Affected targets:** flash/debug at least

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxSprite;
import flixel.FlxState;
import flixel.text.FlxText;
import flixel.util.FlxColor;
using flixel.util.FlxSpriteUtil;

class PlayState extends FlxState
{
    override public function create():Void
    {
        var myPic:FlxSprite = cast add(new FlxSprite().makeGraphic(300, 400, FlxColor.GREEN));
        var myLetters:FlxText = new FlxText(0, 0, 300, "QWERTQWERTQWERTQWERTQWERTQWERTQWERTQWERTQWERTQWERTQWERTQWERTQWERTQWERTQWERTQWERTQWERT", 30);
        myPic.stamp(myLetters, 0, 0);

        var mask:FlxSprite = cast add(new FlxSprite().makeGraphic(Std.int(myPic.width), Std.int(myPic.height), 0x0, true));
        mask.drawCircle(50, 50, 50, FlxColor.BLUE);

        var mirror:FlxSprite = cast add(new FlxSprite(300, 0).makeGraphic(Std.int(myPic.width), Std.int(myPic.height), 0x0, true));
        var mirror2:FlxSprite = cast add(new FlxSprite(300, 100).makeGraphic(Std.int(myPic.width), Std.int(myPic.height), 0x0, true));
        var mirror3:FlxSprite = cast add(new FlxSprite(300, 200).makeGraphic(Std.int(myPic.width), Std.int(myPic.height), 0x0, true));
        var mirror4:FlxSprite = cast add(new FlxSprite(300, 300).makeGraphic(Std.int(myPic.width), Std.int(myPic.height), 0x0, true));
        mirror.alphaMask(myPic, mirror);
        myPic.alphaMaskFlxSprite(mask, mirror2);
        FlxSpriteUtil.alphaMask(mirror3, myPic, mask);
        FlxSpriteUtil.alphaMaskFlxSprite(myPic, mask, mirror4);
	}
}
```

________________________________

**Observed behavior:**
![alphamask-observed](https://cloud.githubusercontent.com/assets/16719964/13823464/f6918ea8-eba9-11e5-8321-8d10e510057f.png)

**Expected behavior:**
![alphamask-expected](https://cloud.githubusercontent.com/assets/16719964/13823467/f9f0a1b0-eba9-11e5-8b9d-edfe0bbc431f.png)

Or am I missing some very crucial detail in the difference between `alphaMask` and `alphaMaskFlxSprite`'s descriptions?  Doesn't seem like it:

```
1c1
< 	 * Takes the image data from two FlxSprites and puts the resulting image into the output FlxSprite.
---
> 	 * Takes two source images (typically from Embedded bitmaps) and puts the resulting image into the output FlxSprite.
5c5
< 	 * get a circular image appear.
---
> 	 * get a circular image appear. Look at the mask PNG files in the assets/pics folder for examples.

```
From this, AFAICT the two functions just have different orders and different return values for chaining purposes, but otherwise should do the exact same thing with respect to the source, mask, and output.  But as you can see from the reproducible example, they don't...

I also tried using the return value, but it was identical to the results of the first four tests above:

		mirror5 = mirror5.alphaMask(myPic, mirror5);
		mirror6 = myPic.alphaMaskFlxSprite(mask, mirror6);
		mirror7 = FlxSpriteUtil.alphaMask(mirror7, myPic, mask);
		mirror8 = FlxSpriteUtil.alphaMaskFlxSprite(myPic, mask, mirror8);

If this is all as expected, I find the documentation fairly confusing, personally.  :)

**Comment by Gama11** [comment]
`alphaMask()` takes the graphics themselves as parameters (asset path, `BitmapData` or `Class<BitmapData>` it looks like), not sprites. So to get a result equivalent to:

```haxe
myPic.alphaMaskFlxSprite(mask, mirror);
```

you need to call:

```haxe
mirror.alphaMask(myPic.pixels, mask.pixels);
```

If you look at the implementation, you'll see that `alphaMask()` would just exit early with `return null` in case either `mask` or `source` is a `FlxSprite`.
