### ISSUE TITLE
FlxSpriteUtil.alphaMaskFlxSprite() not using mask when source was loaded from PNG without alpha

### ISSUE THREAD

**Issue by GimmickyApps** [HaxeFlixel/flixel#1777]
- **Flixel version:** dev
- **OpenFL version:** 3.6.0
- **Lime version:** 2.9.0
- **Affected targets:** flash/debug at least

________________________________

**Assets needed to reproduce the issue**:

problem.png:

![problem](https://cloud.githubusercontent.com/assets/16719964/13827211/91de13a2-ebbb-11e5-884e-5bb2845248e9.png)

fixed.png:

![fixed](https://cloud.githubusercontent.com/assets/16719964/13827213/929c93a4-ebbb-11e5-9ea1-e3de3d194990.png)

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxSprite;
import flixel.FlxState;
import flixel.system.FlxAssets;
import flixel.util.FlxColor;
import openfl.display.BlendMode;
using flixel.util.FlxSpriteUtil;

class PlayState extends FlxState
{
    override public function create():Void
    {
		var myPic:FlxSprite = new FlxSprite().loadGraphic(AssetPaths.fixed__png);
		var myPic2:FlxSprite = new FlxSprite().loadGraphic(AssetPaths.problem__png);
		var mask:FlxSprite = new FlxSprite().makeGraphic(Std.int(myPic.width), Std.int(myPic.height), 0x0, true);
		mask.drawCircle(50, 50, 50, FlxColor.BLUE);
		mask.drawRect(0, 50, 100, 50, FlxColor.WHITE, null, { blendMode: BlendMode.ERASE } ); // erase lower half
		
		var mirror:FlxSprite =  cast add(new FlxSprite(0, 0).makeGraphic(Std.int(myPic.width), Std.int(myPic.height), 0x0, true));
		var mirror2:FlxSprite = cast add(new FlxSprite(0, 100).makeGraphic(Std.int(myPic.width), Std.int(myPic.height), 0x0, true));

		myPic.alphaMaskFlxSprite(mask, mirror);
		myPic2.alphaMaskFlxSprite(mask, mirror2);
    }
}
```

________________________________

**Observed behavior:** 

![alphamaskpngproblem](https://cloud.githubusercontent.com/assets/16719964/13827082/0935b802-ebbb-11e5-961c-c2bf3e9d1eba.png)

**Expected behavior:**

The two mirrors should look the same, since the source PNGs look the same and the mask used is the same.

**Further notes about source PNGs**

The problem PNG is made using GIMP 2.8.16 on Win7x64, using new image with defaults (white background), then scribbling.

To fix it, I copied the problem one, opened it in Paint, and simply re-saved it.

Using TweakPNG to view the PNG headers, the only difference I could see between the two files was this: the original's header said only "truecolor", whereas the fixed one said "truecolor+alpha".  That was on my original art from my project.  You'll find some additional differences between the two files in the art used above, so I thought I should note that they're red herrings.

(I've also verified that re-saving using GIMP on compression level 0 or 1 still results in a broken image.  All of the settings in GIMP's export dialog are unchecked except the last one, "save color values from transparent pixels," which is also unchecked, but greyed out too, which makes sense since there aren't any transparent pixels in the picture.  With interlacing checked (comp 1), still broken.  With all options checked (comp 1), still broken.)

I tried starting again in GIMP but with a transparent background, and it works fine, no need to resave in Paint (which would destroy the transparency anyway, not that I cared in my original artwork because there was none, but still, thought I should note this as further evidence that it has to do with the absence of alpha.  Even though it's a bit counter-intuitive because one would assume that Paint, which doesn't bother with alpha, would not put out a PNG with an alpha channel.  Apparently it does, it just has all alpha=1 pixels, I guess.)

**Comment by Gama11** [comment]
`problem.png` doesn't have an alpha channel. This is reflected in the `transparent` properties of the `BitmapData` instances:

```haxe
trace(Assets.getBitmapData(AssetPaths.fixed__png).transparent); // true
trace(Assets.getBitmapData(AssetPaths.problem__png).transparent); // false
```

`alphaMaskFlxSprite()` is just a thin wrapper around Flash API (`BitmapData#copyChannel()`), so this can't really be a Flixel issue. Besides, I think this is the expected behavior anyway - `BitmapDataChannel.ALPHA` is used there, which doesn't exist in the "problem file".

**Comment by GimmickyApps** [comment]
Thanks for confirming that it was the alpha channel.  I disagree about expected behaviour though (even if that means I disagree with the Flash API): I had a simple graphic, and I wanted to copy part of it using a mask.  The mask has an alpha channel, naturally, and the result would too, but I would argue that it should not matter whether the source does.  I mean, look at the two graphics above, could you tell that one should work and the other not?  And if you used PhotoShop or GIMP, would you expect that you could create masks for only some images, but others not?  I would propose either that HF works around this limitation internally (perhaps by creating an all-0xFF alpha channel if none exists in the source), or at the very least, plaster a big warning in the docs.  Combined with the other bug I reported I lost several hours with the resulting strange behaviour trying to accomplish something relatively simple.  But I am open to being further enlightened about this :)

**Comment by Gama11** [comment]
I added a note to the docs, can't really hurt. I don't like the idea of messing with the source `BitmapData` though.

**Comment by GimmickyApps** [comment]
It's not really messing with it, I would say: it's just adding data that has no visual effect whatsoever, in any context.  But thanks for noting it in the docs, at least, I hope that saves someone else time.  IMO it should "just work" in this context though, this is quite the surprise.
