### ISSUE TITLE
Debugger doesn't show BitmapLog information by default

### ISSUE THREAD

**Issue by thegoodideaco** [HaxeFlixel/flixel#1778]
- **Flixel version:** 4.0.0
- **OpenFL version:** 3.6.0
- **Lime version:** 2.9.0
- **Affected targets:**
ALL

**Code snippet is irrelevant. to reproduce**:

1. Show Debugger
2. Click BitmapLog Brush Icon at the top
3. BitmapLog will show 0 bitmaps
4. Type **viewCache** in the debugger console

**Comment by Gama11** [comment]
Is this supposed to be a bug report? If so, this is the intended behavior, viewing the cache is not the only purpose of the BitmapLog window - you can view arbitrary `BitmapData` instances there.

Or are you suggesting to change this behavior?

**Comment by thegoodideaco** [comment]
My apologies. I was unaware, it seemed like a bug from my perspective. This can be tossed out
