### ISSUE TITLE
FlxSprite.animation doc and function a bit misleading

### ISSUE THREAD

**Issue by GimmickyApps** [HaxeFlixel/flixel#1780]
- **Flixel version:** dev
- **Affected targets:** all

> 	 * @param	Frames		An array of numbers indicating what frames to play in what order (e.g. 1, 2, 3).

This is just my personal experience, but when I saw the one-based example, I then thought that the frame numbers were 1-based (there could be several reasons for this) when in fact they're zero-based.  I always thought my particular animations looked a bit funny but never slowed them down with a really obvious example to find out that, in fact, they were completely missing a frame.  But also there's no warning or crash or anything trying to use a frame that's beyond the end of the loaded frames.  A warning in debug output would make sense to me.

Also, I haven't yet come across an example showing (or, IIRC, doc saying) that you can, in fact, use non-linear sprite sheets (e.g. one laid out in a 2x2 pattern instead of 1x4 or 4x1).  This is definitely a handy feature, because with big sprites, you might easily go beyond your texture size limit if you lay them out 1xX or Xx1...I think it's worth mentioning it in the function doc.

**Comment by gamedevsam** [comment]
Good point, care to make a Pull Request?

**Comment by GimmickyApps** [comment]
Thanks, I had put this on the post-project todo along with the other doc improvement request.  I still intend to do the other one.
