### ISSUE TITLE
Interfaces do not always contain public variables

### ISSUE THREAD

**Issue by GimmickyApps** [HaxeFlixel/flixel#1783]
- **Flixel version:** dev

`interface IFlxSprite` does not expose all the public variables of `FlxSprite`.  Shouldn't it?

My use case is that I have an interface that extends IFlxSprite (I can't use a class in this context, because Haxe doesn't have multiple inheritance).  A class that uses this interface then needs to access `flipX` and `flipY`.  I went to add those two and make a PR, but then thought, wait, doesn't this apply to all public variables?  And before doing all of them (for IFlxSprite, anyway), I thought I should ask.

Secondary question, if the above is OK: I would also need `width` and `height`, but those are inherited from `FlxObject`, and `IFlxSprite` directly extends `IFlxBasic`.  Should I make an `IFlxObject` that exposes `width` and `height`, and have `IFlxSprite` extend that instead?  Or can I just add `width` and `height` to `IFlxSprite` directly?  I would think the former is the proper way to do things (if the premise of the first part is true.)

Alternatively, maybe your goal is to not include more in the interface than is needed internally by flixel, in which case I should just add the variables I need to my own interface and not touch `IFlxSprite` at all.

**Comment by Gama11** [comment]
Yeah, `IFlxSprite` seems a bit unfinished...

I think flixel-ui uses it somewhere, so adding any properties would probably break some code there. In general, adding properties would be a breaking change. :/

**Comment by GimmickyApps** [comment]
OK, fair enough.  Thanks for the heads-up.
