### ISSUE TITLE
Cumulative errors in FlxSpriteGroup positions when scrolling

### ISSUE THREAD

**Issue by IBwWG** [HaxeFlixel/flixel#1785]
- **Flixel version:** dev
- **OpenFL version:** 3.6.0
- **Lime version:** 2.9.0
- **Affected targets:** flash, probably others

As mentioned in [this old comment](https://github.com/HaxeFlixel/flixel/issues/1315#issuecomment-57887896).

**Observed behavior:** over time, positions of FlxSprites with 0 scrollFactor drift (to the right?)
**Expected behavior:** they shouldn't drift

**Comment by Gama11** [comment]
Considering that issue didn't have any code, a code snippet to repro would be helpful. Also to make sure it's really the same issue.

**Comment by GimmickyApps** [comment]
Since nobody asked for code there, it sounded like it was universally acknowledged.  Well, I'll have to make an example up at some point, but I'm getting close to a deadline.  My workaround for now was to reset the position on every draw() call.

**Comment by IBwWG** [comment]
I think I was mistaken, in the end.  In my case it seems not related to `FlxSpriteGroup` after all.
