### ISSUE TITLE
What I'm missing? | flixel tpl command weird error 

### ISSUE THREAD

**Issue by Lomejook** [HaxeFlixel/flixel#1791]
![image](https://cloud.githubusercontent.com/assets/8918952/14071819/28d53d48-f46e-11e5-9ab9-8ba811ed89db.png)

![image](https://cloud.githubusercontent.com/assets/8918952/14071873/9dc35b94-f46e-11e5-833a-f37507d19442.png)

![image](https://cloud.githubusercontent.com/assets/8918952/14071895/c4d10ae2-f46e-11e5-8b85-440313d11801.png)

![image](https://cloud.githubusercontent.com/assets/8918952/14071909/ed3c2732-f46e-11e5-8b75-cf7ed7470acd.png)

- **Flixel version:** 4.0.1
- **OpenFL version:** 3.6.0
- **Lime version:** 2.9.0
- **Affected targets:** Windows CMD

**Comment by dstrekelj** [comment]
Looks like you're using a custom build script (`haxe -cp source -main Test -debug`). If this is how your project was configured after running `flixel tpl -n "Test"` and opening the generated FlashDevelop / HaxeDevelop project file, then that's definitely a bit strange.

If, however, you have tried configuring your project yourself - know that the lime / OpenFL build system goes beyond Haxe's. This simply won't work the way you intend it to. You will have to run `openfl test neko` or `lime test neko` from the directory containing the `Project.xml` file instead.

I have tried to reproduce your issue a couple of times without success. Have you made any changes to the generated project? Have you opened the generated project file, or have you imported the project files into an existing / freshly created FlashDevelop or HaxeDevelop Haxe project?

It would help if you could flesh your story out a bit. As it stands it looks more like human error to me than an actual issue.

**Comment by Lomejook** [comment]
Thanks for the response

This error appear just before I tried to update haxeflixel, because I had an old version. 

First I run on cmd `haxelib update flixel` and then `haxelib upgrade`. After a lot of downloading everything completes just fine. But then I run `flixel tpl` that blank message on cmd appears

When I run `openfl test neko` the project opens on a window and runs correctly. but if I run the project on FlashDevelop, the Output shows that error on the image

(sorry for my bad english)

**Comment by dstrekelj** [comment]
Have you configured flixel-tools? It could be that something went wrong during the setup process. Try running `flixel setup` or `haxelib run flixel-tools setup`, and then try creating a new project again.

P.S. Your English is fine :)

**Comment by Gama11** [comment]
That seems to be a pretty old FlashDevelop version - what version exactly? Can you try updating FlashDevelop?

**Comment by Lomejook** [comment]
Yeah @dstrekelj, I already configured flixel just like that 

This is the FlashDevelop that I have:
- **FlashDevelop**: 4.5.2.5

Updating FlashDevelop do the trick.

Thanks!
