### ISSUE TITLE
FlxSound: implement a setter for time

### ISSUE THREAD

**Issue by Gama11** [HaxeFlixel/flixel#1792]

**Comment by MSGhero** [comment]
Should this actually start playing the sound at that time if the sound is paused or stopped?

**Comment by Gama11** [comment]
Hmm, very good question. I suspect that could be counter-intuitive, yet easier to implement.

**Comment by MSGhero** [comment]
In that case, you would have a private `_time`, and `set_time()` would just call `startSound()`. Otherwise, set `_time`, and the user calls `resume()` to start the sound at that time.

Confusion might occur if users try to `play()` instead of `resume()` with `play`'s time parameter.
