### ISSUE TITLE
Asset size limit?

### ISSUE THREAD

**Issue by GimmickyApps** [HaxeFlixel/flixel#1795]
Hi folks, hoping you can help with this as I near a deadline and am finally getting real assets in!

- **Flixel version:** Mar 28 dev
- **OpenFL version:** 3.6.0
- **Lime version:** 2.9.0
- **Affected targets:** flash/debug (always reproducible), windows/release (not isolated yet), possibly others

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxState;

class PlayState extends FlxState
{
	override public function create():Void
	{
		// no code needed
	}
}
```
Take roughly 167 MB+ of asset files and put them in your assets directory.  (Not sure the precise limit, but 120 MB is OK, and 167 MB breaks it.)

________________________________

**Observed behavior:**

On flash/debug:

```
Called from ? line 1
Called from CommandLineTools.hx line 1400
Called from CommandLineTools.hx line 25
Called from CommandLineTools.hx line 126
Called from CommandLineTools.hx line 619
Called from lime/project/PlatformTarget.hx line 70
Called from lime/tools/platforms/FlashPlatform.hx line 260
Called from lime/tools/helpers/FlashHelper.hx line 872
Called from lime/tools/helpers/FlashHelper.hx line 685
Called from format/swf/Writer.hx line 60
Called from format/swf/Writer.hx line 1425
Called from format/tools/Deflate.hx line 33
Called from /usr/lib/haxe/std/neko/_std/haxe/zip/Compress.hx line 48
Called from /usr/lib/haxe/std/haxe/io/Bytes.hx line 457
Uncaught exception - alloc.c(177) : max_string_size reached
Build halted with errors.
```

Note: google "Uncaught exception - alloc.c(177) : max_string_size reached" and you'll find people talking about Stencyl suggesting that a particular image is too large.  This is *not* the case, because I can compile fine with 120 MB of assets, and then simply duplicate a subfolder, and have it break.  Therefore no single image is too big, because I haven't introduced any new image data, just copies of data that don't otherwise break compilation.

Also note that it's not to do with the number of files, since I only have a few hundred, and I did a test where I added 1,000 small files to a new project and it compiled fine.  (I had thought maybe we were hitting a class size limit for AssetPaths or something.  Not so.)

On windows/release (only in my project, haven't isolated yet, but I think it's related...compiles fine if I delete a bunch of assets):

```
include\AssetPaths.h(538): error C2238: unexpected token(s) preceding ';'
include\AssetPaths.h(539): error C2059: syntax error: 'user-defined literal'
(x100)
include\AssetPaths.h(539): fatal error C1003: error count exceeds 100; stopping compilation
```

If you have any suggestions for how to isolate the windows/release trouble I'm all ears.

**Expected behavior:** Normal compilation.

**Comment by Gama11** [comment]
Regarding the flash problem, it's a fairly well-known Lime limitation (though I don't know the exact size limit). See http://community.openfl.org/t/solved-project-not-compiling-on-flash/1221/2 for example. I can easily reproduce this by including a large amount of assets in a pure OpenFL project. There's not much Flixel can do about this.

@larsiusprime might know a bit more about this, he has the same issue when compiling DQ1 to Flash.

I doubt the windows problem is related, sounds like more of an issue with `AssetPaths` (which is totolly optional to including assets). Feel free to open a separate issue for that once you have it isolated.

**Comment by GimmickyApps** [comment]
Thanks for the quick response.  Are you sure it's the same thing?  The last line of my compiler error output is different than mentioned there (and on SO, linked to from there.)

**Comment by Gama11** [comment]
I linked that mostly because of Joshua's response:

>There is a known memory limit right now when writing for the Flash target, it's a lot better than it was before, but it could be pushed further with some work

The actual issue posted there might be something different. But like I mentioned, I can repro this exact stacktrace in a pure OpenFL project.

**Comment by GimmickyApps** [comment]
I wasn't sure if you meant "this" as in what was in the thread you linked to, or what I posted.  Sorry...

As for the Windows thing you're right, it's unrelated.  But also a bug, will open separately.
