### ISSUE TITLE
Crash on Windows pressing 0, +, or - keys

### ISSUE THREAD

**Issue by GimmickyApps** [HaxeFlixel/flixel#1797]
- **Flixel version:** Mar 28 dev
- **OpenFL version:** 3.6.0
- **Lime version:** 2.9.0
- **Affected targets:** windows/debug and /release

________________________________

**Code snippet reproducing the issue**:

I haven't isolated this yet, unfortunately.  I only report anyways because 0, +, and - are flixel sound control built-ins.  Pressing other keys works fine and my game otherwise functions normally.

________________________________

**Observed behavior:** Sound control interface overlay does not appear.  Instead, immediately a tiny popup window comes up:

Error
=
> Custom([file_write,stderr])
> 
> OK   

Clicking OK immediately closes the game.

On /debug, nothing is mentioned in console output.  With the in-game debugger open, nothing is mentioned in the log.

Also, if I uncomment `<haxedef name="FLX_NO_SOUND_TRAY" />` from Project.xml, the problem goes away (well, so does sound control via hotkeys.  But at least it doesn't crash.)

**Expected behavior:** Sound control.

**Comment by Gama11** [comment]
I can't reproduce that. Does this happen with a freshly generated Flixel project?

**Comment by GimmickyApps** [comment]
No, it doesn't, hence I couldn't isolate it so easily.

It might be related to some other sound problem I'm having with my project, which I just noticed and also haven't isolated.  Some sounds work and others don't (among WAV files) and the ones that don't also never complete their play() callbacks, which in some cases makes the game unplayable.  Looking into it...

**Comment by Gama11** [comment]
Issue reports without a way to reproduce aren't too useful. ;)

**Comment by GimmickyApps** [comment]
I know, I know.  As I said I wouldn't report it except that it's very flixel-specific...

**Comment by GimmickyApps** [comment]
Although, that Sound.hx error is OpenFL.

**Comment by GimmickyApps** [comment]
Compiling for OpenFL next (never tried this before) makes both problems go away: sounds play normally, and 0/+/- work instead of crashing the game.

**Comment by Gama11** [comment]
Seems like we can safely assume that this is an OpenFL issue then (anything else would surprise me anyway, `FlxSound` is just a light wrapper around OpenFL's sound API).

**Comment by GimmickyApps** [comment]
Except that it affects flixel's sound tray, no?  Like I said, you disable the sound tray, everything works.  No doubt it's also an openfl issue, but I think flixel shouldn't break because of it...

**Comment by Gama11** [comment]
There's not much Flixel can do if playing a sound through OpenFL's API causes a crash.

**Comment by GimmickyApps** [comment]
That's not how it is.  Before the point that the sound even plays, hitting 0/+/- causes the crash.  I just postulated that it might be related to other general sound issues on my project--among which are sounds mysteriously not playing suddenly when they worked before--because I couldn't reproduce the issue.

**Comment by Gama11** [comment]
Flixel itself plays a sound too when the volume controls are used.

**Comment by GimmickyApps** [comment]
Ohhh, that's what you mean.  However, the sound playing (mine or flixel's) does not cause a crash.  ONLY the flixel tray hotkeys cause a crash.  My sounds only cause a weird error in the output (which the flixel blip sound does not.)

**Comment by Gama11** [comment]
Either way, not much I can do here without a way to reproduce.

**Comment by GimmickyApps** [comment]
I'm working on it.

**Comment by GimmickyApps** [comment]
Hmm, seems related actually to music, although in the reproduction I have here it's crashing without first giving an error popup.  In fact, I'm not sure it's even a crash, since I don't get the normal windows crash dialog.  It just exits immediately.  Which is what it was doing before, but with an error popup first.

**Comment by GimmickyApps** [comment]
Ah, yes, I had a mistake in my VLC converter batch file.  Instead of mux=raw I needed mux=ogg.  Created files of a reasonable size but that would not play even in VLC itself.

So: the bug is, if you playMusic() on a bad file, subsequently your game will auto-exit (possibly with a popup error first) if you press 0, +, or -.
