### ISSUE TITLE
Console: improve completion robustness

### ISSUE THREAD

**Issue by Gama11** [HaxeFlixel/flixel#1798]
The debugger console's completion doesn't work properly when the caret isn't at the end of the String right now because of some assumptions the logic makes. Would be nice if that was more robust and worked no matter the current position.

**Comment by GimmickyApps** [comment]
It also behaves differently on windows native than on flash.  E.g. an ENTER keypress jumps the caret to the end on flash (IIRC) but not on windows, where it stays put and you have to move it yourself.

**Comment by Gama11** [comment]
That's a bug in the OpenFL TextField implementation we can't do much about. I think it works on OpenFL Next.

**Comment by GimmickyApps** [comment]
Ah, good to know.  Thanks.

**Comment by IBwWG** [comment]
As a possible workaround you could fire an openfl keypress of the End key, maybe?
