### ISSUE TITLE
Implement OpenFL Next's Tilemap API

### ISSUE THREAD

**Issue by Gama11** [HaxeFlixel/flixel#1800]
OpenFL Next has a new rendering API called `Tilemap`, which is supposedly faster than `drawTiles` (but does not support scaling or rotation at this point, so implementing it at this point would only be experimental).

An example implementation can be found in OpenFL's BunnyMark sample: https://github.com/openfl/openfl-samples/blob/master/demos/BunnyMark/Source/Main.hx
##

**Comment by larsiusprime** [comment]
I think if we start working on this it will motivate OpenFL to get it finished. Very excited about this. Will this improve our shader capabilities too?

**Comment by Gama11** [comment]
¯\_(ツ)_/¯

**Comment by Beeblerox** [comment]
@larsiusprime i don't think so. since shaders works per openfl.display.DisplayObject.
But we'll need it, since Tilesheet will be deprecated (as far as i know)

**Comment by larsiusprime** [comment]
At the risk of being off topic, what would we need to do to our renderer to add shader support on a per flxsprite level?

**Comment by Tiago-Ling** [comment]
Hey guys, i'm working on the isometric tilemap again and this current
implementation is somewhat closer to the Tilemap API.

I just finished an initial port to HaxeFlixel (i was working with pure
OpenFL + Tilesheet) and i think it'll be easy to implement the new renderer
and experiment with it. Could be a nice test bed for implementing this for
the official FlxTilemap.

There's still a lot to do, but i put up a repo with a sample (windows /
neko only ftm): https://github.com/Tiago-Ling/FlxIsoTilemap

What do you guys think?

Tiago Ling Alexandre
Tel: +55 41 8819-3191


2016-04-03 16:23 GMT-03:00 Lars Doucet <notifications@github.com>:

**Comment by Beeblerox** [comment]
@larsiusprime we'll need to write pure opengl renderer then, so we'll have total control over it.

**Comment by Beeblerox** [comment]
i think it's possible to create custom Tilemap implementation which will support more features for canvas ang opengl rendering than current version, but flash will be very limited, since bitmapdata's draw() method can't draw transformed image regions (there is stage3d rendering as well which can have more features)

**Comment by larsiusprime** [comment]
@beeblerox: I think at this point it's okay to just let flash stick with the regular blitting logic for now. I mean a stage3d renderer would be "nice to have" but it's hardly a priority, I'd rather put that into native & webgl.

**Comment by Beeblerox** [comment]
@larsiusprime ok, let's neglect flash then for this issue (not forever, but for a while)

**Comment by Beeblerox** [comment]
@larsiusprime on the second thought there is shader argument in drawTiles() method, so individual shaders should be possible already. this just needs to be tested, and i expect some help from you (just running test demos), since i have problems with my setup.

**Comment by larsiusprime** [comment]
@Beeblerox sure happy to help. It will be interesting to see if the shader applies to the whole tilesheet batch or is isolatable to just one element. Either way, once we figure out how it works we can figure out ways to use it in a more customizable way.

**Comment by Beeblerox** [comment]
@larsiusprime i've made initial commit for shader support here: https://github.com/HaxeFlixel/flixel/tree/shaders
and here is the demo for it: https://github.com/HaxeFlixel/flixel-demos/tree/shaders/Effects/SpriteShaders

**Comment by Gama11** [comment]
Wow, that's pretty awesome. :+1: 

The demo doesn't showcase it very well though, I think it's more impressive when there are a lot of sprites that are _overlapping each other_ (since otherwise, you could just do this with a regular camera shader). I've added it to FlxBunnyMark locally for testing:

![](http://i.imgur.com/Dy6Hy62.png)

You said "initial support" - what's still missing? Seems to be working pretty well already.

**Comment by larsiusprime** [comment]
Trying to rig this up to play with now

**Comment by larsiusprime** [comment]
Looks cool! :clap:

**Comment by Tembac** [comment]
Hello Everyone,

I encountered an issue with openFl and the SWF library. https://github.com/openfl/swf/issues/64

@jgranick seems to have fixed it on the new openfl but it is incompatible with current HaxeFlixel. Do you have any estimate on when will this be available?

**Comment by MSGhero** [comment]
I'll look at it this weekend if no one else gets to it by then. That's assuming I can compile a test project to cpp+opengl because I *still* can't in my main game.

**Comment by Beeblerox** [comment]
@MSGhero you can try this. but currently Tilemap is very limited. I think it's far from completion.
I'm starting work on custom DisplayObject which will reimplement drawTiles feature in openfl. Hope i'll show you something next week

**Comment by MSGhero** [comment]
But don't we *have* to switch to tile map now since tile sheet was removed? Or will your display object be the new tile rendering backend?

**Comment by Tembac** [comment]
Where does the decision to make the new tilesheet for openfl take place? Is there a Slack for openfl or secret forum?
I would like to know more about the roadmap of openfl and why we needed big changes now.

**Comment by MSGhero** [comment]
@Tembac `Math.random() < .5`

There is an OpenFL slack I think, but it seems like he just kinda did it. It ends up being faster/better than the tile sheet approach, and that was probably most of the justification. But idk, I'm not in that slack group.

**Comment by Tiago-Ling** [comment]
AFAIK Tilesheet will remain in the framework for the time being isn't it?

It'll likely be deprecated before being completely removed. Tilemap is very
experimental at the moment, it'll probably change a lot before being the
'default way'.

Tiago Ling Alexandre
Tel: +55 41 8819-3191


2016-06-01 20:27 GMT-03:00 Nick <notifications@github.com>:

**Comment by MSGhero** [comment]
@Tiago-Ling it was straight up removed from dev. Like, flixel will never again compile to dev openfl until this is resolved. But that's like once a month these days

**Comment by larsiusprime** [comment]
Joshua created a new dev branch that keeps it
https://github.com/openfl/openfl/tree/openfl3

On Wed, Jun 1, 2016 at 7:01 PM, Nick <notifications@github.com> wrote:

> @Tiago-Ling <https://github.com/Tiago-Ling> it was straight up removed
> from dev. Like, flixel will never again compile to dev openfl until this is
> resolved. But that's like once a month these days
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/HaxeFlixel/flixel/issues/1800#issuecomment-223160413>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-NeIxx7Hb4CI-3ZfeCVqDoCGeaiVks5qHh1SgaJpZM4H-Cud>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by Tiago-Ling** [comment]
Even with this branch it seems the new rendering api will have to be implemented asap - it relies on DisplayObject now (more inflexible imho), so i think HaxeFlixel will have to change a lot of stuff for it to work.

**Comment by Tembac** [comment]
@larsiusprime Where do you get that info about openfl? Twitter and the blog don't seem to be very active.

@jgranick,
I'm admin on a big community of latinoamerican game devs. Several of us are using HF and more only Openfl. The most common complain I hear is that Openfl is almost always broken in some way. For example, right now Lime 2.9.1 crashes on most platforms if you use textfields. I think that these kind of things are very damaging to the community that likes these tools or want to try something different. I hear strong complains every time Openfl is mentioned. 
I know that making these tools is very hard work and I appreciate and thank for it but we need to have more stable releases or the community will fade. Openfl and Lime needs to be tested more before every release. I think several of us can help with this even if we don't have the technical knowledge to fix the issues ourselves. I would like that you reach more to us as a community for help. Let us know how we can help you more and what do you need. 
Your work helps a lot of people, let us help you.

**Comment by larsiusprime** [comment]
@tembac

I'm a bit of an insider to be sure, the Slack channel is where a lot of
this discussion happens. I think you bring up some valid points; I think we
need to focus a lot on regression tests prior to any future releases.


On Wed, Jun 1, 2016 at 8:46 PM, Tembac <notifications@github.com> wrote:

> @larsiusprime <https://github.com/larsiusprime> Where do you get that
> info about openfl? Twitter and the blog don't seem to be very active.
>
> @jgranick <https://github.com/jgranick>,
> I'm admin on a big community of latinoamerican game devs. Several of us
> are using HF and more only Openfl. The most common complain I hear is that
> Openfl is almost always broken in some way. For example, right now Lime
> 2.9.1 crashes on most platforms if you use textfields. I think that these
> kind of things are very damaging to the community that likes these tools or
> want to try something different. I hear strong complains every time Openfl
> is mentioned.
> I know that making these tools is very hard work and I appreciate and
> thank for it but we need to have more stable releases or the community will
> fade. Openfl and Lime needs to be tested more before every release. I think
> several of us can help with this even if we don't have the technical
> knowledge to fix the issues ourselves. I would like that you reach more to
> us as a community for help. Let us know how we can help you more and what
> do you need.
> Your work helps a lot of people, let us help you.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/HaxeFlixel/flixel/issues/1800#issuecomment-223174469>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-K1IEReW2DgPihg3cqWmlhiCI1tkks5qHjXpgaJpZM4H-Cud>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by jgranick** [comment]
@MSGhero @Tembac 

Yes, we have a Slack account -- this is meant to be a secret society, but due to the nature of Slack accounts, it is invite only. I'm open to alternatives :wink:

I'm hearing two different things from you guys, either we make OpenFL more stable, or we keep `Tilesheet` -- these are not both possible, unfortunately. The design of `tilesheet.drawTiles` makes it unreasonable to support in most of OpenFL's renderers. It is broken on almost on every renderer, and is incompatible with many other OpenFL features -- including almost every other `sprite.graphics` API. `drawTiles` is a hold over from NME that by its design can never work well. We need to avoid making promises we cannot keep, and `drawTiles` is simply one of those.

We have improved the `Graphics` API fidelity incredibly over the last year, and have been able to make strides in improving other features that were broken, such as `scrollRect`. We are on a good path for driving further quality and stability improvements into the core of OpenFL, and are focused on one code path for most functionality in OpenFL. Fixing once for all platforms is an awesome workflow. With the single, unified OpenFL the code is 100% Haxe code, making it much simpler to maintain and for external collaborators to get involved. It keeps getting better.

We are not being flippant about removing APIs, but we are being deliberate about pruning OpenFL into a library we can maintain, improve and invest into for long stability. Some non-standard APIs (such as `drawTiles`) just aren't compatible with this goal. We're approaching a major version release, so this is the time to make breaking changes if we need to, and in this case, we do.

We've gotten 230% better performance out of `Tilemap` than `Tilesheet` (depending on the GPU), so I think that moving away from `drawTiles` and Flixel gaining its own custom renderer here could have huge benefits long-term.

**Comment by Tiago-Ling** [comment]
@jgranick Seems like OpenFL 4 will be a huge improvement for all targets! And from what you just told i completely agree that these breaking changes are worth it.

I think people miss more communication about these changes though - this is the first time i hear about version 4, and if i'm not mistaken there is no official roadmap in the site.

I know these are time-consuming tasks and the focus has always been on the code and api improvements, but as the community grows larger it appears these non-programming tasks are becoming even more essential.

**Comment by larsiusprime** [comment]
"this is meant to be a secret society,"

The "but" right after that makes me think you meant "*not* meant" ? :P

On Thu, Jun 2, 2016 at 9:24 AM, Tiago Ling Alexandre <
notifications@github.com> wrote:

> @jgranick <https://github.com/jgranick> Seems like OpenFL 4 will be a
> huge improvement for all targets! And from what you just told i completely
> agree that these breaking changes are worth it.
>
> I think people miss more communication about these changes though - this
> is the first time i hear about version 4, and if i'm not mistaken there is
> no official roadmap in the site.
>
> I know these are time-consuming tasks and the focus has always been on the
> code and api improvements, but as the community grows larger it appears
> these non-programming tasks are becoming even more essential.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/HaxeFlixel/flixel/issues/1800#issuecomment-223307630>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-Kb_SmaGsL7wj5a83cNiobt-UbWSks5qHueVgaJpZM4H-Cud>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by jgranick** [comment]
@larsiusprime Yeah, this went out by email notification before I added the (very necessary) "not" that I originally meant

**Comment by Tembac** [comment]
Thanks for your answer @jgranick ! 
I personally trust on your decision on these maters but it is great to know them now. Is as @Tiago-Ling says, most of us don't know why these changes are made and it gives the wrong image of an erratic development. It will be great if you post on the openfl Blog this explanation so more people know what the plans are for openfl 4. I think the new things will make a lot of people happy.

I know that maybe writing blog posts or roadmaps take time but they are important for the community. Maybe a quick way to solve it can be to post the logs from the slack chat when something important is discussed?

**Comment by larsiusprime** [comment]
Something I've been thinking of is something like this:
http://www.fortressofdoors.com/automated-transparent-development/

That's what I did while I was developing my latest game -- I don't always
have time to write blog posts, but providing some public, and
*automatically updated* "proof of life", with links to where the activity
is happening, might be a good solution because otherwise what inevitably
happens is you intend to write a bunch of stuff, then you don't, and then
there's nothing on the site and people are wondering what's going on.

This would have to be redesigned for OpenFL which is a very different
project, but we're creative folks, we can come up with something.

Then maybe add a blurb that the Slack Chat exists (most don't even know!)
and then a button to request an invite? Right now it's very haphazard and I
think a lot of people don't know how to get an invite.

That's just my random thoughts, dunno if it's a good idea.

On Thu, Jun 2, 2016 at 12:57 PM, Tembac <notifications@github.com> wrote:

> Thanks for your answer @jgranick <https://github.com/jgranick> !
> I personally trust on your decision on these maters but it is great to
> know them now. Is as @Tiago-Ling <https://github.com/Tiago-Ling> says,
> most of us don't know why these changes are made and it gives the wrong
> image of an erratic development. It will be great if you post on the openfl
> Blog this explanation so more people know what the plans are for openfl 4.
> I think the new things will make a lot of people happy.
>
> I know that maybe writing blog posts or roadmaps take time but they are
> important for the community. Maybe a quick way to solve it can be to post
> the logs from the slack chat when something important is discussed?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/HaxeFlixel/flixel/issues/1800#issuecomment-223371097>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAtG-KduYmo_HegTzuGOt7YTvceqcHWJks5qHxmXgaJpZM4H-Cud>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by jgranick** [comment]
I am working on making our chat public, I just found a way to integrate with Fleep, enabling two-way communication to/from Slack in a public URL:

[openfl] General: https://fleep.io/chat?cid=gEdNbSUoSLqHv_Avpr8ErQ
[openfl] Help: https://fleep.io/chat?cid=OVtBNlGgRhOcy2B9-vXMLA
[openfl] Contributors: https://fleep.io/chat?cid=5frjNw9eQAq2cUbWxgPF2w

This might be a half-step toward better communication. We just need to decide how we change openfl.org to bring visibility to this, also interested in feedback on whether this works well?

**Comment by Tembac** [comment]
Made an account on Fleep. I think that having to make an account to see the conversation is some kind of wall but let's see on the following days if it improves the visibility of the development plan.

**Comment by man2** [comment]
How's the update on this? is the new Tilemap API implemented yet?

**Comment by Beeblerox** [comment]
i'm working currently on making flixel work with openfl 4, but not relying on Tilemap.
Current state can be seen here: https://github.com/Beeblerox/flixel/tree/Separate-render (this fork uses latest dev version openfl right now, because @jgranick made great improvements in the way how shaders are working, in comparison to the latest official release on haxelib)

**Comment by Tembac** [comment]
Would it be good for performance to not rely on tilemaps? I tough Tilemaps where for improving performance.

**Comment by Gama11** [comment]
@Tembac Are you talking about `FlxTilemap`? OpenFL's Tilemap API mentioned here has nothing to do with that.

**Comment by Tembac** [comment]
Yes, I know that. I already had that confusion before :D

I'm asking if not using openfl's tilemap api can be bad for performance.  Especially maybe for html5 targets.

**Comment by Gama11** [comment]
That's sort of irrelevant, because it doesn't support all the features Flixel needs from what I understand.

**Comment by Beeblerox** [comment]
Gama11 is right: Tilemap doesn't support tile tinting, color offsets and per tile shaders. Plus it's very hard to have multiple camera support with it.

**Comment by Tembac** [comment]
Thanks for your clarifications! 

Where can I learn about flixel rendering?

**Comment by MSGhero** [comment]
Is this still a relevant issue, or is it superseded by #2068?

**Comment by Gama11** [comment]
We're not gonna use the Tilemap API, so superseded I guess.
