### ISSUE TITLE
FlxTilemap buffers are not updated on camera resize or replacement

### ISSUE THREAD

**Issue by Gama11** [HaxeFlixel/flixel#1801]
Nicely demonstrated by a sample project from @jscott1989: https://github.com/jscott1989/camera-test

**Comment by buckle2000** [comment]
true. [strange behavior](https://github.com/buckle2000/camera-test/blob/master/source/MenuState.hx)

**Comment by buckle2000** [comment]
I think there is not a easy solution but call `tilemap.updateBuffers()` on changing cameras.

Because `FlxBasic` is not notified when its main camera changed:
```
private function get_camera():FlxCamera
	{
		return (_cameras == null || _cameras.length == 0) ? FlxCamera.defaultCameras[0] : _cameras[0];
	}
```

**Comment by Gama11** [comment]
I mostly solved this locally, it involves adding a few new `FlxSignal`s for certain "camera events". I struggled with adding proper unit tests for this though..

**Comment by Gama11** [comment]
Eh, I didn't mean to close this just yet.
