### ISSUE TITLE
flixel.FlxSprite has no field drawRoundRectComplex on windows (but it does on flash)

### ISSUE THREAD

**Issue by GimmickyApps** [HaxeFlixel/flixel#1802]
- **Flixel version:** dev
- **OpenFL version:** 3.6.0
- **Lime version:** 2.9.0
- **Affected targets:** windows

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxState;
import flixel.FlxSprite;
import flixel.util.FlxColor;
using flixel.util.FlxSpriteUtil;

class PlayState extends FlxState
{
	override public function create():Void
	{
	        var background:FlxSprite;
		background = cast add(new FlxSprite(0, 0));
		background.makeGraphic(100, 200, 0x0, true);
		var radius = background.height * 0.4;
		background.drawRoundRectComplex(0, 0, background.width, background.height, 0, 0, radius, radius, 0x0, { thickness: 2, color: FlxColor.WHITE });
	}
}
```

________________________________

**Observed behavior:** Compiler error `flixel.FlxSprite has no field drawRoundRectComplex`
**Expected behavior:** Working like on flash target

**Comment by Gama11** [comment]
OpenFL [does not implement](https://github.com/openfl/openfl/blob/3.6.1/openfl/display/Graphics.hx#L468) `Graphics#drawRoundRectComplex()`, so `FlxSpriteUtil`'s wrapper is only available on Flash.

**Comment by GimmickyApps** [comment]
I have a question about workflow...if a developer typically works with a flash target for faster testing, and then compiles for native and finds things are missing...doesn't this sort of negate the cross-platform-ness that's a selling point of HaxeFlixel / OpenFL in the first place?  If so, how does one avoid this type of thing?  Maybe there could be some LOWEST_COMMON_DENOMINATOR compiler flag or something, if one wants to keep in the realm of the truly cross-platform while developing?

**Comment by Gama11** [comment]
I think providing a target dropdown like api.haxe.org has to show what API is available on what platform could help (https://github.com/HaxeFlixel/flixel-docs/issues/132). Then you get these "available on [platforms]" texts you can see here for example: http://api.haxe.org/haxe/macro/Compiler.html

**Comment by GimmickyApps** [comment]
OK thanks.
