### ISSUE TITLE
Preloader doesn't compile against HTML5

### ISSUE THREAD

**Issue by ashes999** [HaxeFlixel/flixel#1803]
- **Flixel version:** 4.0.1
- **OpenFL version:** 3.6.1-LQBZc4
- **Lime version:** 2.9.1
- **Affected targets:** HTML5

________________________________

**Code snippet reproducing the issue**: from [this GitHub repo file](https://github.com/deengames/owlicious/blob/master/source/deengames/abook/boot/Preloader.hx)

```haxe
// Adapted from http://gamepopper.co.uk/2014/08/26/haxeflixel-making-a-custom-preloader/
// Pre-loads assets. Used for Android and Flash.
// Delegates to StartupScreen.
package deengames.abook.boot;

import flash.Lib;
import flash.display.Bitmap;
import flash.display.BitmapData;
import flixel.system.FlxPreloader;
import openfl.display.Sprite;

@:bitmap("assets/images/preloader-logo.png") class LogoImage extends BitmapData { }

class Preloader extends FlxPreloader
{
	var logo:Sprite = new Sprite();
	private static inline var FADE_FROM_PERCENT = 0.75;

	public function new(minDisplayTime:Float = 0, ?allowedUrls:Array<String>)
	{
		super(minDisplayTime, allowedUrls);
	}

	override private function create():Void
	{
		this._width = Lib.current.stage.stageWidth;
		this._height = Lib.current.stage.stageHeight;

		var bitmap = new Bitmap(new LogoImage(0,0));
		// Rotate around origin
		bitmap.x = -bitmap.width / 2;
		bitmap.y = -bitmap.height / 2;

		//Sets the graphic of the sprite to a Bitmap object,
		// which uses our embedded BitmapData class.
		logo.addChild(bitmap);
		logo.x = (this._width - logo.width) / 2;
		logo.y = (this._height - logo.height) / 2;

		// account for negative-coordinates origin
		logo.x += -bitmap.x;
		logo.y += -bitmap.y;
		addChild(logo); //Adds the graphic to the preloader's buffer.
	}

	override public function update(percent:Float):Void
	{
		// 60 FPS, two rotations per second
		logo.rotation += 12;
		// 0-90% = 1.0 alpha
		// 91-100% = 1.0 => 0
		if (percent >= FADE_FROM_PERCENT) {
			logo.alpha = 1 - (percent - FADE_FROM_PERCENT) * (1 / (1 - FADE_FROM_PERCENT));
		}
	}
}
```

________________________________

**Observed behavior:** Several compiler errors:
```
Preloader.hx:21: characters 8-22 : Too many arguments
Preloader.hx:19: lines 19-22 : Missing super constructor call
Preloader.hx:26: characters 2-44 : Int should be openfl.display.DisplayObject
Preloader.hx:27: characters 2-46 : Int should be openfl.display.DisplayObject
Preloader.hx:37: characters 12-23 : openfl.display.DisplayObject should be Int
Preloader.hx:38: characters 12-24 : openfl.display.DisplayObject should be Int
Preloader.hx:24: lines 24-44 : Field create is declared 'override' but doesn't override any field
Preloader.hx:46: lines 46-55 : Field update is declared 'override' but doesn't override any field
```

**Expected behavior:** It should compile fine, as it does with Neko and Flash.

**Comment by Gama11** [comment]
`FlxPreloader` currently doesn't work on HTML5, which is why the entire class body is guarded with `#if !js` to make sure OpenFL's default preloader is still being used.

We can make sure that the `FlxPreloader` methods are still available as stubs on HTML5 by moving the conditionals inside them to make things compile. The Preloader still wouldn't actually work though.

**Comment by ashes999** [comment]
Sorry, I don't understand.

I see that you moved the `#if js ... #end` blocks into the methods themselves, which makes the code apparently compile, but the pre-loader isn't used...

I'm not very experienced with HTML5. I thought we still need pre-loaders on that platform (load bootstrap JS + a few pre-loader images first, then load everything else).

Are there plans to eventually get the `FlxPreloader` to work with HTML5/js?

**Comment by Gama11** [comment]
Yes, HTML5 does have preloaders (like I said, the methods in `FlxPreloader` are empty so that the default preloader is used).

I'm not sure how much work it'd be to get `FlxPreloader` to work nicely on HTML5 - I suspect at least the blend modes that are used would cause some trouble. Haven't really looked into it though.

Feel free to open a separate issue for that.

**Comment by ashes999** [comment]
Sure, I can do that.
