### ISSUE TITLE
`FlxPreloader` doesn't work in HTML5.

### ISSUE THREAD

**Issue by ashes999** [HaxeFlixel/flixel#1804]
As mentioned in #1803, `FlxPreloader` should (but doesn't) work in HTML5.

I'm not sure what specific issues need to be fixed (probably at least blend modes).

**Comment by Nallebeorn** [comment]
I've been working on this over the weekend (without even knowing about this issue), and it's mostly functional now. Blend modes indeed won't work in HTML5, but that's a non-fatal issue (and not really related to the preloader). There are some other quirks though, which require somewhat ugly workarounds... But it works.

**Comment by ashes999** [comment]
@Nallebeorn it would be great if you can open a PR for this.

**Comment by Nallebeorn** [comment]
I will, of course :)
