### ISSUE TITLE
FlxSpriteUtil.alphaMask() should use FlxGraphicAsset

### ISSUE THREAD

**Issue by Gama11** [HaxeFlixel/flixel#1806]
Currently uses `Dynamic` and implements the type checking itself instead of using `FlxAssets.resolveBitmapData()` .

**Comment by buckle2000** [comment]
We can declare `FlxGraphicAsset` as abtract type of `OneOfThree<...>`, and then add `@:to toBitmapData` or something. So we can do implicit cast on the go.
Is that practicable?

**Comment by Gama11** [comment]
Not sure why the `@:to toBitmapData` would be necessary here?

**Comment by buckle2000** [comment]
Never mind. I think it would just be a more natural way, since if someone want to convert `FlxGraphicAsset` to `BitmapData`, one may never check `FlxAssets`.
