### ISSUE TITLE
New feature: SVG support in FlxSpriteUtil

### ISSUE THREAD

**Issue by buckle2000** [HaxeFlixel/flixel#1809]
add 2 functions named `loadGraphicsFromSVG` and `drawSVG`, accept filepath and .svg data (as a string)

problem: need to change dependency, add a optional haxelib `svg` just like `hscript` now.
- if there is no way to force **import** statement affected by DCE, at least I don't know

does it worth to do that?

**Comment by Gama11** [comment]
What's preventing you from just using the svg lib right now?

**Comment by buckle2000** [comment]
Nothing. I was just asking is it good to add a function to draw svg thing onto `FlxSprite`.

**Comment by ashes999** [comment]
SVG support hails from OpenFL's SVG support, which has a lot of issues. I would be hesitant to add this to Flixel without fixing a whole slew of SVG library issues.

Rendering to an SVG is pretty easy, so for now, I would recommend just writing some helper/wrapper code to take care of this for you.
