### ISSUE TITLE
Compiler error on windows/debug using openfl legacy

### ISSUE THREAD

**Issue by IBwWG** [HaxeFlixel/flixel#1819]
- **Flixel version:** freshly updated dev
- **OpenFL version:** 3.6.0
- **Lime version:** 2.9.0
- **Affected targets:** windows/debug only, with openfl legacy

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxState;

class PlayState extends FlxState
{
	override public function create():Void
	{
              super.create();
	}
}
```

________________________________

**Observed behavior:**

```
cmd: "C:\HaxeToolkit\haxe/haxelib" run lime build "Project.xml" windows -debug -Dfdb
C:/HaxeToolkit/haxe/lib/flixel/git/flixel/system/debug/watch/EditableTextField.hx:76: characters 18-24 : Unknown identifier : length
C:/HaxeToolkit/haxe/lib/flixel/git/flixel/system/debug/watch/EditableTextField.hx:76: characters 26-32 : Unknown identifier : length
Build halted with errors.
Done(1)
```

**Expected behavior:**  successful compilation

**Comment by Gama11** [comment]
Damn, that's a pretty huge blindspot in our CI...

**Comment by Gama11** [comment]
Wow, this is funny. CI would have catched this (phew), if OpenFL 3.6.0 was still the most recent haxelib release. It seems like `TextField#length` was implemented only quite recently on legacy and is in the 3.6.1 release:

**Comment by IBwWG** [comment]
Thanks!
