### ISSUE TITLE
Key input not working on next + debug

### ISSUE THREAD

**Issue by Gama11** [HaxeFlixel/flixel#1827]
Apparently, this commit: https://github.com/HaxeFlixel/flixel/commit/df981da19f9bf1f74e673d20c88a961c48a0016c broke keyboard input on native targets with OpenFL next in debug mode. It seems that `FlxG.keys.enabled` is false for some reason in that case since that commit.

I'm not sure how the preloader could have any impact on that, considering it shouldn't even be used on native targets.

**Comment by starry-abyss** [comment]
It narrows down  to this FlxBasePreloader function (reverted to fix keyboard input on neko and windows):

```
	override public function onLoaded() 
	{
		//#if flash
		_loaded = true;
		_percent = 1;
		//#else
		//super.onLoaded();
		//#end
	}
```

**Comment by Gama11** [comment]
Wow, I wonder why that happens. Thanks for isolating!

**Comment by Gama11** [comment]
Apparently the preloader is actually used on native targets. The more you know!
