### ISSUE TITLE
Pre/Post Update and Draw signals should include elapsed

### ISSUE THREAD

**Issue by JoeCreates** [HaxeFlixel/flixel#1836]
Pre/Post Update and Draw signals should include elapsed. This time will always be calculated by the time the calls are required, and this information is useful in many cases, such as doing late updates to physics.

It seems FlxG.elapsed could be used in most cases, but not in the case of preUpdate because elapsed isn't calculated until after preUpdate is dispatched.

If the value is passed instead, it would also make the listeners more flexible.
##

**Comment by Gama11** [comment]
Hm, this is unfortunately a breaking change...

I think we had those signals before there was an `elapsed` argument in `update()`.

**Comment by JoeCreates** [comment]
As an intermiary non-breaking improvement, the dispatch of the preupdate could be moved to after calculation of FlxG.elapsed, so that at least preUpdate listeners could use that.

**Comment by Gama11** [comment]
That seems reasonable.

**Comment by MSGhero** [comment]
@Gama11 can you think of any reason these lines can't be moved up to the beginning of the function, after the early exit? https://github.com/HaxeFlixel/flixel/blob/dev/flixel/FlxGame.hx#L725-L736

It's breaking if someone needed to use last frame's `elapsed` in this frame's `preUpdate`, but no one has probably ever thought about that before. I don't see coming before `switchState` being a problem.

**Comment by Gama11** [comment]
Why do you need `elapsed` during `switchState()` / what's wrong with Joe's suggestion?

**Comment by MSGhero** [comment]
If you can't come up with a reason why, then Joe's suggestion is good and I can make a quick PR. I wanted to make sure I wasn't overlooking anything.

**Comment by Gama11** [comment]
Go ahead.

**Comment by Geokureli** [comment]
Clearing out 5.0.0 tasks, was this completed? I see preUpdate is called after FlxG.elapsed is set, we don't pass elapsed in draw calls, but do we want to pass it on pre/post update signals? I could go either way, honestly

**Comment by Geokureli** [comment]
Gonna close this out, for pre/post update they can just use FlxG.elapsed, and draw calls shouldn't use elapsed to begin with
