### ISSUE TITLE
FlxMouseEventManager doesn't respect scale for FlxExtendedSprite

### ISSUE THREAD

**Issue by ashes999** [HaxeFlixel/flixel#1837]
- **Flixel version:** 4.0.0
- **OpenFL version:** 3.6.0
- **Lime version:** 2.9.0
- **Affected targets:** Neko (didn't test others)

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxG;
import flixel.FlxSprite;
import flixel.FlxState;
import flixel.text.FlxText;
import flixel.ui.FlxButton;
import flixel.math.FlxMath;
import flixel.input.mouse.FlxMouseEventManager;
import flixel.addons.display.FlxExtendedSprite;
import flixel.FlxObject;

class MenuState extends FlxState
{
	override public function create():Void
	{
		super.create();
        
        var s = new FlxExtendedSprite();
        s.loadGraphic('assets/images/bush.png');
        add(s);
        s.setGraphicSize(32, 32);
        s.updateHitbox();
        
        FlxMouseEventManager.add(s, clickHandler);
	}
    
    public function clickHandler(e:FlxObject)
    {
        trace("CLICK!");
    }

	override public function update(elapsed:Float):Void
	{
		super.update(elapsed);
	}
}
```

________________________________

**Observed behavior:** Even though the sprite is shrunk to 32x32, clicking anywhere in a 64x64 area traces `CLICK!`
**Expected behavior:** Clicks shouldn't fire outside of the scaled-down, 32x32 area

Note: `bush.png` is 64x64 pixels

Git repo: https://github.com/ashes999/flixel-scale-bug

**Comment by Gama11** [comment]
Not sure how this is specific to `FlxExtendedSprite`, I get the same behavior with `FlxSprite`.

Either way, this behavior is expected: by default, `FlxMouseEventManager` uses pixel-perfect overlap checks with the graphic, which don't take scaling into account. You can set the `PixelPerfect` param of `add()` to `false` to use the hitbox instead.

**Comment by ashes999** [comment]
Yeah, I didn't test it with `FlxSprite` (or with `scale` instead of `updateHitbox`). It seems to be working as expected now. Thanks!

**Comment by al-arz** [comment]
(Another person here who lost some time figuring out what's wrong with MEM)

IMO, this behaviour is 'expected' only if you actually know how things work internally. From the user's perspective, why would you want to check if something pixel-perfectly overlaps initial graphics and not the actually displayed pixels? 

And to point to the root issue: #1464
