### ISSUE TITLE
Rotated sprite not displaying correctly in Flash when game size is larger than the double of the actual window

### ISSUE THREAD

**Issue by caiopsouza** [HaxeFlixel/flixel#1838]
- **Flixel version:** 4.0.1
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:** Flash

________________________________

I created an empty HaxeFlixel project on HaxeDevelop and made the following changes.

Main.hx

```haxe
package;

import flixel.FlxGame;
import openfl.display.Sprite;

class Main extends Sprite
{
	public function new()
	{
		super();
		
		// Doubles the default width and height.
		// Some values larger than those will trigger the bug, but not all.
		// Smaller values seems to work properly
		addChild(new FlxGame(2 * 640, 2 * 480, MenuState));
	}
}
```

MenuState.hx
```haxe
package;

import flixel.FlxSprite;
import flixel.FlxState;

class MenuState extends FlxState
{
	override public function create():Void
	{
		super.create();
		
		var sprite = new FlxSprite();
		sprite.makeGraphic(200, 200, 0xffffffff);
		add(sprite);
		
		// Very small values make the bug unnoticeable
		// You can also change the y value to achieve similar results
		// if the position is big enough, the sprite will be completely hidden
		sprite.x = 30;
		
		// Rotating by any angle triggers the bug
		sprite.angle += 1;
	}

	override public function update(elapsed:Float):Void
	{
		super.update(elapsed);
	}
}

```

I made no changes in Project.xml, so the window size is the default 640x480 pixels.

________________________________

**Observed behavior:** The sprite rotates, but it's truncated or disappear. If you resize the window, making it bigger, the sprite will display correctly.
**Expected behavior:** The sprite is displayed rotated.

**Comment by Beeblerox** [comment]
This isn't a bug. this is how flixel renderer works (how origin of sprite is handled). Here is screenshot of rotated sprite on neko and flash targets:
![sprite-rotation](https://cloud.githubusercontent.com/assets/857406/14965275/25f11fee-10b5-11e6-8f8a-c2d56986e81b.png)

If you want your sprite not to be truncated then you should set its origin to (0, 0):
```
sprite.origin.set(0, 0);
```

**Comment by philipes** [comment]
Here is a screenshot on how it behaves for me. Right is Neko, working as it should. Left is Flash.

![sprite-bug-ss](https://cloud.githubusercontent.com/assets/1131681/14965525/4c504dee-1084-11e6-9131-3ee53b3fcb96.png)

**Comment by Gama11** [comment]
@Beeblerox Any clue what's going on here?

**Comment by Beeblerox** [comment]
@Gama11 i have no clue about this. Will try to experiment one more time, but i suspect it could be flash bug (don't want it to be so)

**Comment by Gama11** [comment]
@Beeblerox Did you get a chance to check this again?

**Comment by Beeblerox** [comment]
@Gama11 i think i've check it a long time ago, but didn't find the source of the issue. Will try again this week

**Comment by Beeblerox** [comment]
i trully believe now that this is a flash runtime bug with bitmapdata.draw() method.
This happens in FlxCamera's `drawPixels()` method.
If i change the line:
```
buffer.draw(pixels, matrix, null, blend, null, (smoothing || antialiasing));
```
with
```
bitmap.bitmapData = pixels;
buffer.draw(bitmap, matrix, null, blend, null, (smoothing || antialiasing));
```
where `bitmap` is a helper `Bitmap` instance then everything draws correctly without clipping graphic.
I need to make perfomance checks before including this "fix" or we could add this as a hack, because this happens only in very specific cases

**Comment by Beeblerox** [comment]
ok, i've checked perfomance with FlxBunnyMark test and haven't noticed perfomance changes with applied fix. So PR is on the way :)

**Comment by Gama11** [comment]
>i trully believe now that this is a flash runtime bug with bitmapdata.draw() method

Wow, crazy.

**Comment by Gama11** [comment]
The fix for this broke the FlxBloom demo: #1979

**Comment by Gama11** [comment]
I had to revert the fix for this, but I don't think there's much of a point in reopening this: the only workaround causes other features to break. So this is a "wontfix" I guess.

**Comment by MSGhero** [comment]
If you made this purely AS3/OpenFL->SWF, does the same thing happen? You can compile to swf in try.haxe.org, but I'm not sure what the minimal case boils down to.

**Comment by MSGhero** [comment]
Like... what exactly is the problem?
![image](https://cloud.githubusercontent.com/assets/5033927/19280187/b3f8c55e-8fb2-11e6-9a2d-88f9ee73f550.png)
```haxe
public function new() {
    var buffer = new flash.display.BitmapData(640, 480, false, 0x0);
    var bm = new flash.display.Bitmap(buffer);
    flash.Lib.current.stage.addChild(bm);
    
    var matrix = new flash.geom.Matrix(1, 0, 0, 1);
    matrix.rotate(1);
    matrix.translate(100, 100);
    
    var bmd = new flash.display.BitmapData(100, 100, false, 0x00ff00);
    
    buffer.draw(bmd, matrix);
}
```
