### ISSUE TITLE
Cannot open fullscreen

### ISSUE THREAD

**Issue by buckle2000** [HaxeFlixel/flixel#1851]
- **Flixel version:** 4.0.1
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:** all

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxGame;
import openfl.display.Sprite;

class Main extends Sprite
{
	public function new()
	{
		super();
		addChild(new FlxGame(0, 0, MenuState, 1, 60, 60, true, true)); // this line
	}
}
```

________________________________

**Observed behavior:** .../haxe/lib/flixel/4,0,1/flixel/FlxGame.hx:248: characters 23-47 : openfl._legacy.display.Stage has no field window
**Expected behavior:** No compile-time error

**Comment by buckle2000** [comment]
Also, I created this project using `flixel tpl -n abc`.

**Comment by buckle2000** [comment]
Oh that was really weird. I could not even compile a newly created project.

**Comment by Gama11** [comment]
I can't reproduce this, could you provide more infos? Is that the complete error message?

>that **was** really weird

Does that mean you managed to solve it?

**Comment by buckle2000** [comment]
That is the complete error message.
However I solved it by completely removing `openfl` and `flixel` and reinstall them.
But I don't know why.
Just forget it.
Thank @Gama11 for trying to help.

**Comment by Gama11** [comment]
Fyi, you can close your own issues if you managed to solve them. :)
