### ISSUE TITLE
FlxBitmapFont with fonts on multiple lines seems to crash on Neko

### ISSUE THREAD

**Issue by xerosugar** [HaxeFlixel/flixel#1857]
- **Flixel version:** git
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:** Neko

**Observed behavior:** When placing fonts/characters on more than one line (inside the font image) the game crashes on Neko target; it works on Windows target.

**Comment by Beeblerox** [comment]
will look into this tomorrow night

**Comment by Beeblerox** [comment]
@xerosugar sorry, but i cannot reproduce it bitmap font demo https://github.com/HaxeFlixel/flixel-demos/tree/dev/UserInterface/FlxBitmapText
i'll need code that can reproduce this issue. Maybe the problem caused by the font

**Comment by xerosugar** [comment]
hm, that's odd... I'll see if I can reproduce it w/ a new project. I'll get back to you.

**Comment by xerosugar** [comment]
I found the problem. When providing the FlxBitmapFont with the character string and the multi-lined .png with the font gfx, I had some empty spaces at the end of the png-file that fooled the parser into thinking that there were more characters there than what I'd provided inside the string.

So, character-string length was shorter than number of spaces in the png-file and this led to it crashing.

**Comment by Beeblerox** [comment]
that's strange. There is check for that in FlxBitmapFont: https://github.com/HaxeFlixel/flixel/blob/dev/flixel/graphics/frames/FlxBitmapFont.hx#L535

Can you provide your font, so i could fix this ussue?

**Comment by xerosugar** [comment]
![font](https://cloud.githubusercontent.com/assets/5557471/15323409/30c03160-1c42-11e6-9f8a-7376ade10eb6.png)

```
package;

import flixel.FlxState;
import flixel.graphics.frames.FlxBitmapFont;
import flixel.math.FlxPoint;
import flixel.text.FlxBitmapText;

class MenuState extends FlxState
{
	override public function create():Void
	{
		var letters:String = "ABCaå";
		var font:FlxBitmapFont = FlxBitmapFont.fromMonospace("assets/images/font.png", letters, FlxPoint.weak(6, 12));
		var bmTxt:FlxBitmapText = new FlxBitmapText(font);
		bmTxt.text = "ABC";
		bmTxt.setPosition(50, 50);
		add(bmTxt);
	}
}
```

**Comment by xerosugar** [comment]
when I change the 'å' to an 'a' it works. but "å" has length == 2 if not you're not using utf8.length() so I'm guessing that's the problem. he tries to parse 6 letters, when there's only 5. 
```
trace(letters.length);
trace(Utf8.length(letters));
```

**Comment by Beeblerox** [comment]
So the problem is with utf8 encoding. i think that this line causes this issue:
https://github.com/HaxeFlixel/flixel/blob/dev/flixel/graphics/frames/FlxBitmapFont.hx#L524
which should be changed to 
`var numLetters:Int = Utf8.length(letters);`

**Comment by xerosugar** [comment]
yeah, that should do it

**Comment by Beeblerox** [comment]
could it be closed now?

**Comment by xerosugar** [comment]
yep, seems to be working now, thanks!!
