### ISSUE TITLE
FlxAtlas with powerOfTwo=true in constructor crash

### ISSUE THREAD

**Issue by starry-abyss** [HaxeFlixel/flixel#1858]
- **Flixel version:** dev, 868b405
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:** neko, flash

________________________________

**Code snippet reproducing the issue**:

Add second argument to FlxAtlas constructor in FlxAtlas demo like this:
```haxe
var atlas:FlxAtlas = new FlxAtlas("myAtlas", true);
```

________________________________

**Observed behavior:**
Crash

**Expected behavior:**
No crash

**Comment by Beeblerox** [comment]
will look into this issue tomorrow

**Comment by starry-abyss** [comment]
Thanks, seems to work!
