### ISSUE TITLE
BlendMode doesn't work on Neko and CPP on Flixel dev, but works on 4.0.1

### ISSUE THREAD

**Issue by thecocce** [HaxeFlixel/flixel#1859]
- **Flixel version:** dev
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:** CPP, Neko ,Windows. Android

________________________________

Hi the blandmode works only on flash target.
![blendmodes demo](https://cloud.githubusercontent.com/assets/3259703/15556615/098b3732-22cf-11e6-9596-457c67c0b2d0.jpg)

**Observed behavior:**
**Expected behavior:**

**Comment by Gama11** [comment]
Blend modes are handled by OpenFL, not Flixel. Nothing we can do about it.

That said, didn't at least some of them used to work? @larsiusprime

**Comment by thecocce** [comment]
OK, but, Flixel 4.0.1 works propertly. Is just the dev branch.

**Comment by Gama11** [comment]
Wow, you're right. Looks like it broke with 9406295. Any ideas @Beeblerox?

**Comment by larsiusprime** [comment]
Blend modes are ultimately implemented by shaders, so likely with that commit some sort of default shader logic was overwritten or suppressed, would be my guess.

**Comment by Gama11** [comment]
Much simpler than that, I accidentally removed `flags |= blending;` -.-

**Comment by Poobslag** [comment]
I'm still seeing this behavior in Flixel 4.3.0. Has this bug been reintroduced?
