### ISSUE TITLE
-Dnext causes other cameras to not draw

### ISSUE THREAD

**Issue by AaronShea** [HaxeFlixel/flixel#1866]
- **Flixel version:** 4.0.1
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:** Windows (only tested this so far)

________________________________

**Code snippet reproducing the issue**:

Build the FlxCamera example project `haxelib run lime-tools create FlxCamera` with `lime test windows -Dnext`

________________________________

**Observed behavior:** Overlay camera does not draw at all
**Expected behavior:** It should draw, just like in legacy

### Without `-Dnext`
![Without -Dnext](https://puut-aaronshea.rhcloud.com/get/57578a6079606fb89801cc77)

### With `-Dnext`
![With -Dnext](https://puut-aaronshea.rhcloud.com/get/57578b0079606fb89801cc79)

**Comment by Gama11** [comment]
This is a bit more subtle than "additional cameras don't work in Next" - the cameras in Mode work just fine.

**Comment by Gama11** [comment]
Seems to be related to the transparent background color. Any idea @Beeblerox? OpenFL bug?

**Comment by JoeCreates** [comment]
I think this was just this issue: https://github.com/HaxeFlixel/flixel/issues/1793

@Gama11  Can probably close, now?

**Comment by Gama11** [comment]
Yep - thanks for the reminder. :)
