### ISSUE TITLE
Suggestion: Per-camera scrollfactor (or visibility?)

### ISSUE THREAD

**Issue by IBwWG** [HaxeFlixel/flixel#1867]
The more I think about how `.scrollfactor` works on multiple cameras, the more I wonder what use case there is for using `.scrollfactor.set(0)` in a multi-camera context the way flixel currently works.  I can't think of why you'd want a UI element (the typical use case for 0-SF) to be duplicated on every camera, although maybe there is a case.  OTOH, I can think of lots of cases where you *wouldn't* want it duplicated on every camera.  For starters, if you're using `FlxMouseEventManager`, it won't respond to events on SF-0'd objects on cameras besides the main one, so all your SF-0'd UI objects are visually duplicated but N-minus-one of them are broken.

I have a proposed solution that would be backward-compatible but more flexible:  Add `.scrollfactors:Array<FlxPoint>` whose indices correspond to `.cameras`' indices, and then make `.scrollfactor` be an alias for `.scrollfactors[0]`.  If an object doesn't have a scrollfactor for a given camera, it uses the value of `.scrollfactors[0]`.  So behaviour would not change, but you would have the added flexibility of saying, I want object X not to move on camera Y, but to move on all other cameras.  Object X would typically be an off-world/off-screen object so that the result would be it simply wouldn't show on the other cameras.

Alternatively, if my use case is the only one this would be useful for, it would probably be clearer and more efficient to scrap the above idea and instead make `.hiddenOnCamera:Array<Bool>` (or maybe `Map<Int, Bool>`?).  A quick check in the camera code can have it short-circuit if it comes across an object where that value is defined and true for its index.  It would take precedence over `.visible`.

Feedback appreciated before I try to write it myself...

**Comment by Gama11** [comment]
You can change what cameras a sprite is rendererd on via its `cameras` property.

**Comment by IBwWG** [comment]
Hooray!  I must've seen that a jillion times.  Not sure how it came loose from my memory.  Glad it's already implemented!
