### ISSUE TITLE
Tween chain never completes

### ISSUE THREAD

**Issue by IBwWG** [HaxeFlixel/flixel#1871]
- **Flixel version:** 4.0.0
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:** windows/debug

________________________________

**Code snippet reproducing the issue**:

```haxe
package;
import flixel.FlxState;
import flixel.tweens.FlxTween;

class PlayState extends FlxState
{
	override public function create():Void 
	{
		var fakeThing = { a: 0, b: 0 };
		
		FlxTween.tween(fakeThing, { a: 1 }).then(FlxTween.num(0,1).then(FlxTween.num(0,1))).onComplete = function (dummy:FlxTween)
		{
			trace("done A");
		};
		FlxTween.tween(fakeThing, { b: 1 }).then(FlxTween.num(0,1).then(FlxTween.num(0,1,1, {onComplete: function (dummy:FlxTween)
		{
			trace("done B");
		}})));
	}
}
```

________________________________

**Observed behavior:** `done B` not traced
**Expected behavior:** `done B` should be traced

I realize the two things are not semantically equivalent, but they should both call their completion functions, shouldn't they?  The first one should tween, trace, num, num (tracing after 1 second); the second should tween, num, num, trace (tracing after 3 seconds).  But the second one never traces.  (And of course, this is the one you'd expect from a general concept of chaining.)

Take out a num tween, or take away the tween tween, and they both trace as expected.

**Comment by IBwWG** [comment]
One workaround:
```haxe
		FlxTween.tween(fakeThing, { c: 1 }, 1, { onComplete:function (dummy:FlxTween) {
			FlxTween.num(0, 1).then(FlxTween.num(0, 1, 1, { onComplete: function (dummy:FlxTween) {
				trace("done C");
			}}));
		}});
```

**Comment by Gama11** [comment]
Chaining simply didn't account for nested chains... I hope it works as expected now.

Writing the unit tests for this one was fun. :D

**Comment by IBwWG** [comment]
Huh...I'll have to try it out, but that's interesting, because in the above example, it does work with nested chains, just not 3 levels, for some reason...2 worked fine.

But I also wonder, do I have the chaining syntax incorrect?  Is it supposed to be .then(tween).then() instead of .then(tween.then()) in normal usage?  For some reason I thought I had either tried that or traced it and thought it needed to be nested to work.  I thought because .then() returned the original tween, so originalTween.then(tweenA).then(tweenB) would start A and B simultaneously after original finished.

**Comment by Gama11** [comment]
The `.then(tween).then() ` seems more common to me.

`originalTween.then(tweenA).then(tweenB)` shouldn't start A and B at the same time, it should run originalTween, A and then B.

**Comment by IBwWG** [comment]
You're right!  I could've sworn I tried that.  Maybe I got confused because I was trying to finish with `.onComplete = ...` at the same time, which isn't possible with chained tweens because it applies to the first tween rather than the last.  Thanks for the sanity check!
