### ISSUE TITLE
Debugger's VCR load icon doesn't respond to clicks

### ISSUE THREAD

**Issue by IBwWG** [HaxeFlixel/flixel#1872]
- **Flixel version:** 4.0.0
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:**
windows/debug
________________________________
________________________________

**Observed behavior:** button doesn't respond, despite docs' "The button with the folder icon right allows loading record files and replaying them."
**Expected behavior:** open file dialog to pick a save file to replay

**Comment by Gama11** [comment]
There's not really a way to have a file dialog without additional dependencies on Lime legacy, which I'd like to avoid. Maybe the button should be disabled or removed.

On Next, we could potentially use `lime.ui.FileDialog`.

**Comment by IBwWG** [comment]
Yeah, I would vote to disable it in the cases where it's not able to function...
