### ISSUE TITLE
Build fails on windows, neko is fine

### ISSUE THREAD

**Issue by ManlyChicken** [HaxeFlixel/flixel#1873]
Hi,
I recently got a new pc and I'm trying to get flashdevelop and haxeflixel running on it.
I install haxe, openfl, flixel, visual studio, everything seems to be installed correctly, I can build my game in Neko, but not for Windows.
I have the most recent flashdevelop, haxe, neko, haxeflixel, I have JRE and Visual Studio 2015 installed. I uninstalled everything and reinstalled, restarted, etc.
It was working on my crummy laptop, and both seem to have the same thing installed.
This is the build output I get:

Building Game
Running Pre-Build Command Line...
cmd: "C:\HaxeToolkit\haxe/haxelib" run lime build "project.xml" windows -release -Dfdb
export/windows/cpp/haxe/ApplicationMain.hx:80: characters 47-65 : Warning : Use programPath instead
Creating C:/Users/User/Desktop/game/export/windows/cpp/obj/obj/msvc-ncxp/_pch/haxe/hxcpp.pch...
'cl.exe' is not recognized as an internal or external command,
operable program or batch file.
Error: error running cl.exe -Iinclude -nologo -DHX_WINDOWS -D_USING_V140_SDK71 -GR -O2 -Oy- -c -EHs -GS- -arch:SSE "-IC:/Users/User/flixel/hxcpp/3,3,49/include" -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=330 -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -wd4996 -MT -Ychxcpp.h -Yllinkb0f64e3ab5344c0106202e359c708b18 "C:/Users/User/Desktop/game/export/windows/cpp/obj/obj/msvc-ncxp/__pch/haxe/hxcpp.cpp" "/FpC:/Users/User/Desktop/game/export/windows/cpp/obj/obj/msvc-ncxp/__pch/haxe/hxcpp.pch" "-FoC:/Users/User/Desktop/game/export/windows/cpp/obj/obj/msvc-ncxp/__pch/haxe/hxcpp.obj"
Build halted with errors.

Thanks

**Comment by ManlyChicken** [comment]
How would I go about doing that?
(Couldn't find it on google)

**Comment by Gama11** [comment]
You need to find the folder that contains `cl.exe` (something like `C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin`) and [add it to your PATH](http://www.howtogeek.com/118594/how-to-edit-your-system-path-for-easy-command-line-access/).

**Comment by ManlyChicken** [comment]
Thanks, I'll try it when I get home from work.

**Comment by ManlyChicken** [comment]
Fixed it, didn't realize you had to specify to install c++ compiling tools for new versions of visual studio. That did the trick. Thanks for the help though.
