### ISSUE TITLE
FlxBitmapText alpha not displaying as intended

### ISSUE THREAD

**Issue by KnotUntied** [HaxeFlixel/flixel#1877]
- **Flixel version:** 4.0.1
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:** Noted on Flash, so far

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxState;

class PlayState extends FlxState
{
	override public function create():Void
	{
		var test1 = new FlxBitmapText(gmfont);
		test1.text = "WORLD";
		test1.x = 50;
		test1.y = 200;
		test1.alpha = 0;
		add(test1);

		var test2 = new FlxBitmapText(gmfont);
		test2.text = "WORLD";
		test2.x = 100;
		test2.y = 200;
		test2.alpha = 0.1;
		add(test2);

		var test3 = new FlxBitmapText(gmfont);
		test3.text = "WORLD";
		test3.x = 150;
		test3.y = 200;
		test3.alpha = 1;
		add(test3);
	}
}
```

________________________________

**Observed behavior:**
test1 displays as expected, zero alpha, invisible. test3 also, one alpha, opaque. test2, however, is opaque, despite having an alpha of 0.1. (The same happens with values 0<x<1.)
**Expected behavior:**
Aforementioned bitmap texts should display with their respective alphas.

I will provide more details if inquired.

**Comment by Gama11** [comment]
Looks like I can reproduce this in the `FlxBitmapText` demo.

**Comment by KnotUntied** [comment]
Found the fix. Only reason I didn't bother doing a pull request is because it's a one-liner.
```haxe
override private function set_alpha(value:Float):Float
{
	super.set_alpha(value); // This was forgotten, apparently.
	alpha = value;
	if (FlxG.renderBlit)
	{
		pendingTextBitmapChange = true;
	}
	return value;
}
```

**Comment by JoeCreates** [comment]
Any idea why the original alpha = value wasnt working?

**Comment by Gama11** [comment]
I think the assignment was working, it's probably more about the `updateColorTransform();` call in super.
