### ISSUE TITLE
accelerateTowardsMouse doesn't work well

### ISSUE THREAD

**Issue by DleanJeans** [HaxeFlixel/flixel#1878]
- **Flixel version:** **4.0.x** & **dev**
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:** All

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxSprite;
import flixel.FlxState;
import flixel.math.FlxVelocity;

class MenuState extends FlxState {
	var sprite:FlxSprite;
	
	override public function create() {
		sprite = new FlxSprite();
		sprite.makeGraphic(10, 10);
		sprite.screenCenter();
		add(sprite);
	}

	override public function update(elapsed:Float) {
		FlxVelocity.accelerateTowardsMouse(sprite, 100, 500);
		super.update(elapsed);
	}
}
```

________________________________

**Observed behavior:** Sprite moves only a few pixels per second. Happens in dev when mouse is in any direction. In 4.0.x, sprite only accelerates normally when mouse is on the left and above.
**Expected behavior:** Sprite accelerates to mouse normally

**Comment by MSGhero** [comment]
There was a bug in master that was fixed.

I'm on my phone, but can you trace sprite.acceleration and velocity and tell us what those numbers are? Seems like you should do that line after super.update as well, but idk if that's the problem.

**Comment by MSGhero** [comment]
Ok I was able to look it over. The issue is here:

`ResetVelocity	Whether to reset the FlxSprite velocity to 0 each time` in `FlxVelocity`

So then `accelerateTowardsMouse` should look like:
```haxe
public static function accelerateTowardsMouse(Source:FlxSprite, Acceleration:Float, MaxSpeed:Float):Void
{
	var a:Float = FlxAngle.angleBetweenMouse(Source);
	accelerateFromAngle(Source, a, Acceleration, MaxSpeed, false);
}
```

**Comment by DleanJeans** [comment]
Setting that to `false` even yields worse behavior. Those must be totally broken.

**Comment by MSGhero** [comment]
What exactly is worse behavior? It works fine for me.

**Comment by DleanJeans** [comment]
I think it only happen in 4.0.1 not the dev version.

**Comment by SeiferTim** [comment]
@DleanJeans the problem is that you're calling this function in your `update` - you only want to call it once, which will set your sprite's velocity to 0 and acceleration to whatever it needs to be to move towards the mouse. 

I'm not sure what functionality you're expecting, or how you're trying to use it, but this function is working as intended.

**Comment by MSGhero** [comment]
@SeiferTim he wants it to follow the mouse over time, not shoot toward where the mouse is initially

**Comment by SeiferTim** [comment]
You wouldn't want to use this function for that.

**Comment by MSGhero** [comment]
=/

**Comment by DleanJeans** [comment]
I was just using it for some minimum camera test with some in the main cam. So this isn't a big deal for me. It's all up to you if you wanna fix it or not.

**Comment by SeiferTim** [comment]
I think you misunderstood me... the function name/usage is a little vague, but it was never meant to be used the way you seem to be trying to use it... You might try some of the others, or make your own.

**Comment by MSGhero** [comment]
Imo it seems pretty useless to use this once. Then again, this function uses trig which is way more expensive than just doing math, so it's bad in that regard too.

**Comment by Gama11** [comment]
@SeiferTim is right, the function wasn't intended to be used this way.
