### ISSUE TITLE
Tweens cleared on FlxState switch (possibly by design?)

### ISSUE THREAD

**Issue by tbrosman** [HaxeFlixel/flixel#1883]
- **Flixel version:** 4.0.1

________________________________

**Code snippet reproducing the issue**:

```haxe
FlxG.sound.music.fadeOut(4.0, 0.0);
```

________________________________

**Observed behavior:** No fade out occurs (tweens are not getting updated because plugins are not getting updated).
**Expected behavior:** Plugins should be updating.

FlxG.plugins is populated correctly but never updated. Since the FlxTweenManager is a plugin, for it to correctly update the PluginFrontEnd containing it needs to be updated. I would expect this update to get called somewhere like FlxGame.onEnterFrame.

**Comment by MSGhero** [comment]
https://github.com/HaxeFlixel/flixel/blob/dev/flixel/FlxGame.hx#L499
https://github.com/HaxeFlixel/flixel/blob/dev/flixel/FlxGame.hx#L743

??? Try updating flixel? I don't think this line has been changed in a while, though. What target are you on?

**Comment by tbrosman** [comment]
Ah, somehow I missed that. 4.0.1 definitely does call update on that line. My tween still isn't getting updated (more accurately, it's never finishing). I think I know why now: when the state switches, the tweens are killed. I'm assuming this is by-design...?

**Comment by MSGhero** [comment]
Yes, that's correct and I've had that issue before haha. Kinda annoying

**Comment by tbrosman** [comment]
It would be nice if plugins were per-FlxState (or could be) somehow. That way you could show that the plugin's transient state is actually scoped to the FlxState. The only issue with this is then you'd have two types of plugins (unless all plugins were FlxState-level, which I don't think is possible).

**Comment by MSGhero** [comment]
I manually control a finite state machine so I don't have to worry about any of that 😄
