### ISSUE TITLE
No way to modify animation frames (without instantiating new animation)

### ISSUE THREAD

**Issue by JoeCreates** [HaxeFlixel/flixel#1888]
```FlxAnimation._frames``` is private, meaning we cannot edit the frames of an animation after it has already been instantiated. ```FlxAnimationController``` provides methods append frames to an animation, but there is no way to remove or change the frames.

The reason I wish to do this is that I have pooled objects that may require slightly different animations once recycled. Simply using add, however, will be constantly instantiating new ```FlxAnimation``` objects, so I would prefer to avoid this.

Should ```FlxAnimation._frames``` be public, or perhaps we could add a new method to ```FlxAnimationController``` to set the frames of an existing animation?

**Comment by IBwWG** [comment]
I'd also find this handy for read access.
