### ISSUE TITLE
Next crashes when debugger disabled

### ISSUE THREAD

**Issue by SeiferTim** [HaxeFlixel/flixel#1890]
- **Flixel version:** dev
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:** windows, neko (cpp)

________________________________

This is a weird one. To reproduce:

Grab the mode demo.
`lime test neko|windows -Dnext -debug` will work with no problem.
`lime test neko|windows -Dnext` will HARD crash with no stacktrace message at all: gc.dll for neko, ntdll.dll for windows, right after the FlxSplash finishes.
Go into `Project.xml`, and set `FLX_NO_DEBUG` to be true (remove the `unless="debug")
`lime test neko|windows -Dnext -debug` will crash in the same place as before.
Does not matter if you have the splash or not.

I tried to narrow this down as much as I possibly could...
In mode, it seems to die when trying to load all the particles in the `_gib` FlxEmitter in `MenuState` - it loads about 45 out of 650 of the particles before it blows up.

Comment out everything having to do with that emitter, and it dies when it called `_title1.width` (when it's trying to create `_title2`) You can also add a `trace(_title1.width)` somewhere after `_title1` has been created to get it to die right there - it dies in `FlxText.regenGraphic()` when it tries to access `textField.width` (and `textField` is not null or anything...)

It's a moving target - comment out or change things and it dies somewhere else, seemingly randomly, but, re-enable the debugger, and everything is fine.

You can roll back to OpenFL: 3.5.3 and Lime: 2.8.2 and this stops happening...

**Comment by starry-abyss** [comment]
I had similar crashes at startup due to broken sound playback (game was crashing mostly on splash sound, or on debugger console beep). Was fixed by upgrading OpenFl to openfl3 branch, but in that version I had another issues: http://forum.haxeflixel.com/topic/98/issues-migrating-to-next

**Comment by Gama11** [comment]
I don't think there's much we can do here since it appears to be an OpenFL issue.
