### ISSUE TITLE
Calling revive on FlxSpriteGroup won't set children to alive.

### ISSUE THREAD

**Issue by caiopsouza** [HaxeFlixel/flixel#1891]
- **Flixel version:** 4.1.0
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:** All

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxSprite;
import flixel.FlxState;
import flixel.group.FlxSpriteGroup;

class MenuState extends FlxState
{
	override public function create():Void
	{
		super.create();
		
		var group = new FlxSpriteGroup();
		var amount = 10;
		
		for (_ in 0...amount) group.add(new FlxSprite());
		trace(group.length, group.countLiving(), group.countDead());
		
		group.kill();
		trace(group.length, group.countLiving(), group.countDead());
		
		group.revive();
		trace(group.length, group.countLiving(), group.countDead());
	}
}
```
________________________________

**Observed behavior:** Last line printed is "10,0,10"
**Expected behavior:** Last line should be "10,10,0"
________________________________
This happens because FlxSpriteGroup.set_alive [will check if the object "exists"](https://github.com/HaxeFlixel/flixel/blob/5ccd9b0e908adc789a542574b27c250f2b586427/flixel/group/FlxSpriteGroup.hx#L626) before changing its value. A quick fix would be to swap [those two line in FlxBasic](https://github.com/HaxeFlixel/flixel/blob/42bcf8859d07517fa89d483f0522fb0a4f2bc0e6/flixel/FlxBasic.hx#L90-L91) so "exists" will be true when it tries too change the value of "alive".

Using FlxSpriteGroup for FlxGroup the result is as expected.

**Comment by thegoodideaco** [comment]
can this be fixed? I'm running into issues because of this, and it seems like a very easy fix, it's been an issue for about a month now.

**Comment by Gama11** [comment]
>A quick fix would be to swap those two line in FlxBasic so "exists" will be true when it tries too change the value of "alive".

Sounds like a hack to me. I see no good reason why `set_alive()` needs to check for `exists` in the first place.
