### ISSUE TITLE
Rotated objects appear misplaced when drawing FlxG.camera.canvas (or FlxG.stage) into a BitmapData object [CPP/Neko]

### ISSUE THREAD

**Issue by yuigoto** [HaxeFlixel/flixel#1893]
- **Flixel version:** 4.1.0
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:** CPP, Neko

________________________________

**Code snippet reproducing the issue**:

```haxe
// Creating BitmapData object
var BITMAP:BitmapData = new BitmapData( FlxG.width, FlxG.height, true, 0x0 );
// Draw canvas
BITMAP.draw( FlxG.camera.canvas ); // FlxG.stage can also be used
// New FlxSprite
var SCREEN:FlxSprite = new FlxSprite();
// Loading the bitmap into the sprite
SCREEN.loadGraphic( BITMAP, false ); // Sorry, I wrote SCREEN, instead of BITMAP here
// Add the sprite
add( SCREEN );
```

________________________________

**Observed behavior:**
Whenever I have a rotated sprite/object on screen (angle != 0, 180, 360 or multiples of the latter two), the code snippet above will capture that object rotated, but misplaced and with the wrong rotation.

I tested it with both `FlxText` and `FlxSprite` objects and both give the same output.

Using `FlxScreenGrab` also gives the same results, using the same method on HaxeFlixel Tutorial's *[Polish](http://haxeflixel.com/documentation/polish/)* chapter, to capture the screen, renders the same output.

________________________________

**Expected behavior:**
The object should be capture in its designed place, with the right rotation.

The screenshot below exemplifies the expected/observed behavior:
![rendering-problem](https://cloud.githubusercontent.com/assets/346572/17238431/fa34800a-5531-11e6-8cb8-5a9e903a03bc.jpg)

Also, if I set this variable on the create event on the State I've placed the object being rotated, the "observed" behavior happens naturally:
```haxe
FlxG.camera.canvas.cacheAsBitmap = true;
```

**Comment by Gama11** [comment]
Unfortunately, I don't think there's much we can do about this issue on Flixel's side. This is similar to the discussion here: https://github.com/HaxeFlixel/flixel-addons/issues/82

**Comment by yuigoto** [comment]
Don't worry, and thanks! :smile:

Who knows, in the future things might get solved :wink:

I tried some other things, ended up using something more simple than what I had in mind.

Thanks again for looking at this!
