### ISSUE TITLE
Updated ArtifactFix for HaxeFlixel 4.0

### ISSUE THREAD

**Issue by diegosolo** [HaxeFlixel/flixel#1894]
Hi! I've been struggling for some hours with the issues described in #911 #1514 #434 and #1288 (among others I suppose). The main problem I encountered was that the solution proposed by @Ohmnivore wasn't working in HF4 anymore. So, I replaced the old types with the new ones and made some other necessary changes. I also used some variables to make it more flexible in case of need. Yet, the most important change was making the safe column to be applied to all four sides of the tile, as the fix wasn't working for me with just right and bottom. So here it is: [ArtifactFix](https://github.com/diegosolo/ArtifactFix/blob/master/ArtifactFix).

Now, what I'd really like to put to discussion is the possibility of adding this directly to the core, maybe optionally, like the useScaleHack thing. I'm almost sure (?) everybody using HF for the first time (for native targets) encounters this issue. And the solutions aren't easy to find nor to apply. Besides, I think that's the reason why people choose to develop in a framework, because it solves problems for you. So, do you think it would be possible/useful?

**Comment by starry-abyss** [comment]
Hi, do you mean this http://forum.haxeflixel.com/topic/39/tilemap-tearing-desktop-targets ?

**Comment by diegosolo** [comment]
Jesus, really?? So many hours reinventing the wheel...

Yet, I just couldn't find this information after a pretty big amount of time invested in it. Isn't it a good idea to make HF use it internally by default in native targets? And if not, shouldn't it be present as a warning in the API or something like that?

**Comment by starry-abyss** [comment]
I believe one day it will be fixed altogether, with no need to workaround. Also you may want to read this https://github.com/HaxeFlixel/flixel/issues/1861

**Comment by diegosolo** [comment]
Good. I must admit that I don't quite understand the discussion over there, but I assume the vector flooring thing will fix all tearing problems and there will be no need for fixes/hacks.

So, I'll start testing with -Dnext and see if everything works fine. I remember having issues with next, specifically with input fields.

Thank you!
