### ISSUE TITLE
OGG doesn't play on Ubuntu/Neko

### ISSUE THREAD

**Issue by ashes999** [HaxeFlixel/flixel#1896]
- **Flixel version:** 4.0.0
- **OpenFL version:** 3.6.0
- **Lime version:** 2.9.0
- **Affected targets:** Neko

________________________________

**Code snippet reproducing the issue**:

```haxe
FlxG.sound.load('assets/sounds/bullet-gun.ogg').play();
```

________________________________

**Observed behavior:** No audio.
**Expected behavior:** The audio should play.

________________________________

This occurrs in a Linux/Ubuntu VM on a Windows 8.1 host. What's strange about this is that, on the same machine, with the same audio files, the following all work fine:
- Neko on Windows (host)
- Flash on Ubuntu (if converted to MP3)
- Playing the sound effects in Ubuntu itself (RhythmBox)

However, Neko on Linux doesn't play the sound. In fact, I think HaxeFlixel thinks the sound *is* playing, because the onComplete event handler fires in roughly the right amount of time.

You can reproduce the issue by cloning [this repository at this changelist](https://github.com/ashes999/haxeteroids/tree/39f077f188850b50ee90dae5b2586a7d03fc13d6).

All the sounds seem affected, but I only tested `bullet-gun.ogg` and `powerup.ogg`.

I'm sorry if this is something obvious and stupid :) I spent the last six months developing my previous game on this exact VM, with the same versions of everything, and audio worked fine; I must be doing something wrong.

**Comment by MSGhero** [comment]
Is it a codec issue? Your Linux might not have ffmpeg or whatever installed.

Not every target (or even every browser) can play oggs. Converting them to MP3 doesn't change the fact that you might not be able to even play oggs to begin with. Idk what rhythm box is, but it might contain the codec internally while your OS doesn't.

I would investigate that first.

**Comment by ashes999** [comment]
I'm going to close this as a non-issue. My other Ubuntu VM works fine. (Original response below)

___________________________

I don't think it's a codec issue, because:

- I can play the `.ogg` file in RhythmBox. It's like Ubuntu's "Windows Media Player."
- I developed my last project almost exclusively with Neko on Linux, on the same box. Nothing significant changed in the last month or two.

Neko certainly can play OGG files, as can all other platforms except for Flash. Flash requires MP3s.
