### ISSUE TITLE
PixelPerfect check on a tilemap with FlxMouseEventManager dies in html5, but not in flash

### ISSUE THREAD

**Issue by IBwWG** [HaxeFlixel/flixel#1898]
- **Flixel version:** 4.1.1
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:** html5/debug, html5/release

________________________________

**Code snippet reproducing the issue**:

```haxe
package;
import flixel.FlxG;
import flixel.FlxState;
import flixel.input.mouse.FlxMouseEventManager;
import flixel.tile.FlxTilemap;
import openfl.display.BitmapData;
class PlayState extends FlxState
{
	override public function create():Void 
	{
		FlxG.plugins.add(new FlxMouseEventManager());
		
		var tm:FlxTilemap = cast add(new FlxTilemap());
		tm.loadMapFrom2DArray([[0]], new BitmapData(100, 100), 0, 0, null, 0, 0, 0);
		
		var pixelPerfect = true; // with true, html5 gives an error on the first update()
		FlxMouseEventManager.add(tm, mouseDown, null, null, null, false, true, pixelPerfect);
	}
	
	function mouseDown(tm:FlxTilemap)
	{
		trace(tm);
	}
}
```

________________________________

**Observed behavior:**
```
TypeError: this._tileObjects[this._data[this.getTileIndexByCoords(...)]] is undefined

flixel_tile_FlxBaseTilemap.prototype<.overlapsPoint()
flixel_input_mouse_FlxMouseEventManager.prototype<.checkOverlapWithPoint()
flixel_input_mouse_FlxMouseEventManager.prototype<.checkOverlap()
flixel_input_mouse_FlxMouseEventManager.prototype<.update()
flixel_system_frontEnds_PluginFrontEnd.prototype.update()
flixel_FlxGame.prototype<.update()
flixel_FlxGame.prototype<.step()
```

**Expected behavior:**

As on flash: a black window with a white square that traces when you click it.

I know that it says "only works with FlxSprites"--but it should behave consistently across platforms, no?  And since FlxMouseEventManager.add() takes more general objects than FlxSprites, maybe the default for the PixelPerfect flag should be false?

Depending on the answers to these questions, maybe an appropriate fix would simply be to change this part of FlxMouseEventManager.add():

```haxe
		if (Std.is(Object, FlxSprite))
		{
			newReg.sprite = cast Object;
		}
```

to have just after it:

```haxe
		else
		{
			PixelPerfect = false;
		}
```

**Comment by IBwWG** [comment]
As an aside, I'm a bit confused by the use of collision flags here at all, since you're not looking for a collision, but for a click.  This makes it so you couldn't use the system to check for mouse clicks on non-colliding map tiles...what's the rationale behind that?

**Comment by Gama11** [comment]
I can't reproduce this error with your test code on Chrome (neither on 4.1.1 nor latest dev), what browser are you using?

**Comment by IBwWG** [comment]
Latest firefox at the time...

**Comment by IBwWG** [comment]
Any comment on the collision/clickability nomenclature?

**Comment by Gama11** [comment]
>I'm a bit confused by the use of collision flags here at all

What exactly do you mean by "collision flags"?

**Comment by IBwWG** [comment]
The use of things like "allowCollisions" throughout FlxBaseTilemap.hx does not suggest it has to do with clickability, yet, it does.

**Comment by Gama11** [comment]
What does allowCollisions have to do with FlxMouseEventManager?

**Comment by IBwWG** [comment]
I think it's also used in there...but that's why I said "as an aside"...just a comment from going through the tilemap source

**Comment by Gama11** [comment]
I don't think it is.

**Comment by IBwWG** [comment]
OK, purely an aside, then :)

**Comment by Gama11** [comment]
Still can't reproduce this, neither in Chrome nor Firefox.
