### ISSUE TITLE
FlxSprite.makeGraphic key says "trumps unique flag"...but doesn't actually?

### ISSUE THREAD

**Issue by IBwWG** [HaxeFlixel/flixel#1899]
- **Flixel version:** 4.1.1
- **OpenFL version:** n/a
- **Lime version:** n/a
- **Affected targets:** all

________________________________

If you follow makeGraphic's code, it pass the unique flag all the way to `generateKey()` (where `key` is sent as `userKey`), which does this:

```haxe
	public function generateKey(systemKey:String, userKey:String, unique:Bool = false):String
	{
		var key:String = userKey;
		if (key == null)
			key = systemKey;
		
		if (unique || key == null)
			key = getUniqueKey(key);
		
		return key;
	}
```

Assume `userKey` and `systemKey` are non-null (the latter is non-null in the context of makeGraphic because the call to generateKey is preceded by creating an explicit systemKey).

If `unique` is false, you get the original `key` sent to makeGraphic.  If it's true, you instead get the results of `getUniqueKey(key)` which are guaranteed to be different because of the `while` loop it uses.

Maybe it's just a language thing, but to me, "trumps" means "takes precedence over and makes irrelevant."  (If we're playing a card game and my card is a trump card, it doesn't matter what your card is, my card wins.)  But that's not what happens here: the `unique` flag still matters quite a bit!  Barring any jokes about current American politics, I think this description is just plain inaccurate and should be removed, but maybe I'm missing something about the intended meaning here...

**Comment by Beeblerox** [comment]
my english isn't very good, so i'd rather propose this description for `Key` parameter:
```
Optional parameter - specify a string key to identify this graphic in the cache. If `Unique` flag is true and there is already graphic object with the same name in the cache, then it will generate new name, which will use provided name as the basis (for example, you passed "canvas" as the Key, then it will generate unique name like "canvas9001" or so). If you won't provide any name then size and color of the graphic will be used for the name generation (like "100x200:0").
```

Maybe someone will edit it or make better description

**Comment by Gama11** [comment]
I think that's a bit too much documentation for a single parameter. Maybe something simpler would do:

```
An optional `String` key to identify this graphic in the cache.
If `null`, the key is determined by `Width`, `Height` and `Color`.
If `Unique` is `true` and a graphic with this `Key` already exists,
it is used as a prefix to find a new unique name like `"Key3"`.
```

Still a bit long, but I guess it kind of has to be.

**Comment by Beeblerox** [comment]
@Gama11 yes, it better describes parameter's role
