### ISSUE TITLE
Mac mouse cursor (flixel one, not system) invisible on html5

### ISSUE THREAD

**Issue by IBwWG** [HaxeFlixel/flixel#1900]
- **Flixel version:** 4.1.1
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:**
  html5/release, running on up-to-date Safari on a less-than-year-old mac
  ________________________________

**Code snippet reproducing the issue**:

(This is direct from my project, just because it occurs on all states and I don't have any funky mouse-cursor-specific stuff anywhere in the game.  Edit: I had switched the order but not recompiled yet, now it's how it was originally.))

``` haxe
class Main extends Sprite
{
    public static var tongue:FireTongueEx;

    public function new()
    {
        super();
        addChild(new FlxGame(1024, 600, State_Title, 1, 30, 30, true));
        FlxG.scaleMode = new StageSizeScaleMode();
    }
}
```

---

**Observed behavior:** when mouse enters window, there's no cursor seen; however, it works as if the cursor was there--moving it around, you can see buttons highlight, and then clicking them functions fine; it's a bit hard to play a game this way though when the interface is mainly mouse-based (unless you have a touch-screen, I guess)
**Expected behavior:** to function the same as on Windows/Firefox, seeing the HaxeFlixel grey triangle mouse cursor

I'm going to try `FlxG.mouse.useSystemCursor = true;` and see if this fixes anything (this is a user report, I don't have direct access to the machine.)
##

**Comment by Gama11** [comment]
This is only an issue on Mac? If so, I have no way of testing this.

Did `useSystemCursor = true` anything?

**Comment by IBwWG** [comment]
Yes, only on Mac, and the system cursor works fine.

**Comment by Gama11** [comment]
@Tiago-Ling You have a Mac right? Can you take a look at this?

**Comment by Gama11** [comment]
There's a pretty good chance this is fixed with OpenFL 8. If not, let us know.
