### ISSUE TITLE
drawDebugOnCamera not called for FlxSpriteGroup

### ISSUE THREAD

**Issue by IBwWG** [HaxeFlixel/flixel#1905]
- **Flixel version:** 4.1.1
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:**
all
________________________________

**Code snippet reproducing the issue**:

```haxe
// (within a FlxSpriteGroup)
	#if debug
	override public function draw():Void //without adding this, drawDebugOnCamera() is never called
	{
		#if FLX_DEBUG
		super.draw();
		if (FlxG.debugger.drawDebug)
			drawDebug();
		#end
	}
	override public function drawDebugOnCamera(camera:FlxCamera):Void 
	{
		super.drawDebugOnCamera(camera);
		var gfx:Graphics = beginDrawDebug(camera);
		gfx.lineStyle(1, FlxColor.WHITE, 0.5);
		gfx.drawRect(FlxG.mouse.x,FlxG.mouse.y,500,500);
		endDrawDebug(camera);
	}
	#end
```

________________________________

**Observed behavior:** overridding drawDebugOnCamera() doesn't have an effect like it does with a FlxSprite
**Expected behavior:** I would think it would have an effect...is there any reason (possible side-effects I'm ignorant of?) why the drawDebug() call is left out in FlxSpriteGroup's draw(), or can it be added there so that overriding drawDebugOnCamera works out-of-the-box like it does in other places?

**Comment by Gama11** [comment]
I think this is simply an oversight. There is this weird `_isDrawnDebug` helper variable that is unused though, which might suggest that someone didn't finish the implementation.
