### ISSUE TITLE
Feature request: allow setting sound looping end point as well

### ISSUE THREAD

**Issue by IBwWG** [HaxeFlixel/flixel#1906]
FlxSound.loopTime presumes you want to loop from point X until the end of the track.  What if you want to loop from the start of the track to point X?  Or from point X to point Y?  If it's possible, I think it'd be much more flexible to have a loopEndTime as well.

**Comment by Gama11** [comment]
Seems reasonable enough.

**Comment by Gama11** [comment]
Are you working on implementing this?

**Comment by IBwWG** [comment]
Not at the moment...I had already manually split my tracks into start/loop/end parts before coming across loopTime.
