### ISSUE TITLE
Feature request: Per-camera Shaders

### ISSUE THREAD

**Issue by AaronShea** [HaxeFlixel/flixel#1912]
I've been toying with the newer feature of per-sprite shaders. It's working quite well.
However I'm still searching around for a solution to apply a shader to a specific camera.
As a possible use case: A frame graphic of a CRT monitor, the frame is not post-processed, however the text and images inside the screen should have something like a scanline shader (something like this: https://www.shadertoy.com/view/XsjSzR)

When applying a simple Invert to all of the items in an FlxGroup the result is something like this:

![2016-08-21 22_43_39-command prompt - lime test windows -dnext -debug](https://cloud.githubusercontent.com/assets/1334174/17842434/f4d73518-67f0-11e6-9841-2ca2f5a31e8b.png)

This makes sense of course, as the shaders are applied per sprite. Making applying a shader across a large rectangle of sprites difficult. I'm still researching a solution locally.

My first idea was to have the screen items drawn on another camera separate from the frame's camera. I was thinking the bitmap buffer could be drawn to another FlxSprite and the shader applied to that. However the draw tiles method used by Flixel does not use the bitmap buffer (duh, hardware acceleration!) so I'm currently at a dead end.

**Comment by Gama11** [comment]
This has been supported for a while longer than per-sprite shaders actually, see the Filters demo / `FlxG.camera.setFilters()` https://github.com/HaxeFlixel/flixel-demos/tree/dev/Effects/Filters

Note that the demo currently doesn't do a particularly great job of showcasing that the feature is per-camera, considering there's only one.

**Comment by AaronShea** [comment]
Thanks for the source link!
Don't know how I missed that. I blame lack of sleep, was trying to hunt around in the docs before.

**Comment by Gama11** [comment]
It is a bit hidden admittedly. :)

**Comment by Tiago-Ling** [comment]
Can somebody confirm that PostProcess is working (also please include lib
versions)?

Thanks!

Tiago Ling Alexandre
Tel: +55 41 8819-3191


2016-08-22 8:57 GMT-03:00 Gama11 <notifications@github.com>:

**Comment by Gama11** [comment]
PostProcess is a different demo.

**Comment by Tiago-Ling** [comment]
Oh, gonna try it instead of PostProcess (which does not seem to be working
here currently - OpenFL 3.6.1 (next), Lime 2.9.1, Hxcpp 3.2.205, Flixel
4.0.1)

Thanks!

Tiago Ling Alexandre
Tel: +55 41 8819-3191


2016-08-22 9:37 GMT-03:00 Gama11 <notifications@github.com>:

**Comment by Gama11** [comment]
PostProcess requires OpenFL legacy IIRC.
