### ISSUE TITLE
FlxTouch - touchPointID returns unexpected Int

### ISSUE THREAD

**Issue by Joffcom** [HaxeFlixel/flixel#1913]
- **Flixel version:** 4.1.0
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:** iOS

________________________________

**Code snippet reproducing the issue**:

```haxe
    override public function update(elapsed:Float):Void
    {
        super.update(elapsed);
        for (touch in FlxG.touches.list) {
            if (touch.pressed) trace(touch.touchPointID);
        }
    }
```

________________________________

**Observed behavior:** When running on iOS you get crazy numbers like 2041847584, 2041858400 and 2083644688. It changes for every touch.

**Expected behavior:** Documentation and testing on Android has me thinking the first touch should return 0 and the second 1 and so on which makes it a bit harder on iOS to base something on the first and second touch IDs.

**Comment by Gama11** [comment]
I think this is outside of Flixel's control, unless we introduce some crazy hacks. The touch API is a wrapper around OpenFL's, which in turn probably just passes on whatever value it gets from Lime / SDL.

>**Documentation** and testing on Android has me thinking the first touch should return 0 

Which documentation are you referring to?

**Comment by Joffcom** [comment]
I have been following this one: http://api.haxeflixel.com/flixel/input/touch/FlxTouch.html

When it didn't work I had a quick look in the code and found the same deal in the comments but there looks to be very little that could go wrong.

```haxe
/**
	 * The unique ID of this touch. Example: if there are 3 concurrently active touches 
	 * (and the device supports that many), they will have the IDs 0, 1 and 2.
	 */
public var touchPointID(get, never):Int;
```
I have managed to cobble together a work around for my project by doing some ugly things with a couple of temp vars and some if magic, I did wonder if it was something else causing the problem and OpenFL would make sense.

**Comment by Gama11** [comment]
I see, the docs there definitely seem misleading.

It looks like this behavior is unlikely to change on OpenFL level: https://github.com/openfl/openfl/issues/745#issuecomment-124175143

>I believe the touchpoint ID is given by SDL (from the operating system?) and is not intended to be used as anything other than a unique ID. It may or may not have some order to it.

So I think we just need to adjust the documentation here accordingly.

**Comment by Joffcom** [comment]
You are the man :smile:

**Comment by Gama11** [comment]
Thanks for pointing it out - I hope the new docs are much less amibigous. :)
