### ISSUE TITLE
FlxRandom.shuffleArray should use Fisher-Yates shuffle

### ISSUE THREAD

**Issue by ttencate** [HaxeFlixel/flixel#1914]
[This](https://github.com/HaxeFlixel/flixel/blob/854e0de557e9b68071895bcf394fb834493c89bc/flixel/math/FlxRandom.hx#L307) is not a proper shuffle algorithm. It is both slower than a standard [Fisher-Yates shuffle](https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle), and produces lower quality output.

I would send a PR, but unfortunately, simply swapping out the implementation either breaks the API or leaves us with an unused `HowManyTimes` parameter. An alternative would be to add a second method, say `shuffle` (the "array" bit is sort of implied anyway), and deprecating the old, but that is more hassle and more bloat. What is the HaxeFlixel policy on such matters?

**Comment by Gama11** [comment]
Deja-Vu. :) https://github.com/HaxeFlixel/flixel/pull/1860

As I explained in that PR, I think we need to keep the old method for now.

**Comment by ttencate** [comment]
Sorry, should have searched first. I'll close this in favour of #1860. Could you please add the milestone there too?

**Comment by Gama11** [comment]
Well, #1860 is closed, so I'd actually like to keep this one open. :)

**Comment by Gama11** [comment]
Is anybody working on this? @ttencate, @JoeCreates or @16th-earl?

**Comment by ttencate** [comment]
I'm not, and am not booted into the right OS to roll a PR right now. But here's what I would add:

	/**
	 * Shuffles the entries in an array into a new pseudorandom order.
         * Uses the standard Fisher-Yates shuffling algorithm, so every ordering is equally likely.
	 * 
	 * @param   array          An array to shuffle.
	 */
	@:generic
	public function shuffle<T>(array:Array<T>):Void
	{
		for (i in 0...array.length - 1)
		{
			var j = int(i, array.length - 1);
			var tmp = array[i];
			array[i] = array[j];
			array[j] = tmp;
		}
		return array;
	}

Plus add this to `shuffleArray`:

         * @deprecated Unless you rely on the particular results of this function, you should use shuffle() instead. It is faster and higher quality.

**Comment by Gama11** [comment]
Thanks - I can wait for a propert pull request. :)

Note that Haxe has a special `@:deprecated` metadata that outputs compiler warnings, which is what we should probably use here. See here for example:

https://github.com/HaxeFoundation/haxe/blob/6c29743078019dbe90998788022f895b385b0501/std/Sys.hx#L119
