### ISSUE TITLE
Code style change proposoal: get rid of the private keyword

### ISSUE THREAD

**Issue by Gama11** [HaxeFlixel/flixel#1916]
I'd like to propose getting rid of the `private` keyword (at least in the core library) again (#853). It's superfluous, since Haxe only has `private` and `public` and fields are `private` by default.

@impaler @Beeblerox @gamedevsam Did any of your opinions on this matter change?

@larsiusprime What do you think?

Any opinions are welcome here - @HaxeFlixel/active-contributors, @HaxeFlixel/contributors, or anybody else.

The change itself is trivial, and the style is enforcable with CodeClimate / haxe-checkstyle I think.

I guess we can vote with :+1: / :-1: reactions? :)
##

**Comment by Tiago-Ling** [comment]
+1 to get rid of the `private` keyword. I've been using it like this for some time and prefer it much more.

**Comment by elsassph** [comment]
Death to `private` is my middle name.

**Comment by sruloart** [comment]
As long as the [exceptions](https://haxe.org/manual/class-field-visibility.html) are kept, I for one welcome our new no-private overlords.

**Comment by Gama11** [comment]
@sruloart I'm not sure what you mean? We can't change Haxe's default visibilities.

**Comment by sruloart** [comment]
Just this (please do ignore me if that's obvious and irrelevant :| ):
>Omitting the visibility modifier usually defaults the visibility to private, but there are exceptions where it becomes public instead:
   
> If the class is declared as extern.
    If the field is declared on an interface.
    If the field overrides a public field.

**Comment by MSGhero** [comment]
Externs and interfaces have to be public to make sense, and I'm pretty sure an error gets thrown if you mess with the modifiers of an override. We don't have to worry about any of that here 😄

**Comment by adireddy** [comment]
👍 personally I prefer not specifying default access modifiers. `private` in classes & `public` in interfaces and externs.

**Comment by alihassan0** [comment]
IMO .. that may cause some confusion to those starting to read the flixel classes. since I think most people don't know that all fields are private by default.

**Comment by impaler** [comment]
I am still no particular fan of having to write private, people should be able to remember a default :)

**Comment by JoeCreates** [comment]
I don't care either way.

**Comment by Tiago-Ling** [comment]
Since we're in the subject, i really do like to omit `Void` returns too - what do you think about it?

**Comment by Gama11** [comment]
Same, but I'm not sure we should discuss that here.

**Comment by Beeblerox** [comment]
if majority agrees about getting rid of these keyword then i won't be arguing abbout it.
So maybe polling or something?

**Comment by Gama11** [comment]
There already is a "poll" with GitHub reactions: 13 thumbs up, 1 thumbs down (see the first post in this issue).

I think this change should be made after #1940 to avoid merge conflicts.

**Comment by Beeblerox** [comment]
ok, i need to speed up work on this PR then :)

**Comment by Gama11** [comment]
Eh, it's not like this is urgent.

**Comment by nachoverdon** [comment]
@sruloart Actually, there's only one thing that we should worry about, and that's `override`.

There are no `extern` classes nor `@:publicFields` in the code base, so we are good here.
Regarding interfaces, we can't omit it. We can omit `public` there, though. Or not, since there aren't too many interfaces...

**As for `override`**, there should be a rule to **always declare its visibility**, even if Haxe allows you to omit it, because there's no way to tell if the field is `public` or `private` without looking it up.

**Comment by MSGhero** [comment]
Couldn’t we declare `public override` and `override` to distinguish between public and private, while still removing all privates?

**Comment by nachoverdon** [comment]
Yes, but `public override` must be declared to avoid confusion.

**Comment by MSGhero** [comment]
Yeah definitely, maybe I misunderstood.

**Comment by nachoverdon** [comment]
It was my bad. I didn't specify.
