### ISSUE TITLE
Flixel Fundraiser Credits

### ISSUE THREAD

**Issue by larsiusprime** [HaxeFlixel/flixel#1919]
- [ ] Create a list of backers from the fundraiser
- [ ] Include it in flixel core somehow 
- [ ] Make it 100% opt-in, hidden behind a define  (`FLX_BACKERS` ?)
- [ ] Make it simple, easily formattable, & configurable by the developer
- [ ] Optionally create a FlxCredits demo, and/or FlxCredits class for flixel-addons

Here's a rough sketch of what the implementation might look like:

``` haxe
Class FlxBackers
{
   public var listSansHeaders(get, null):Array<String>;    //just names, no headers
   public var listWithHeaders(get, null):Array<String>;    //names & headers
   public var headers(get, null):Array<String>;            //just headers, no names
   public function getList(headers:Bool):Array<String>;    //function that does the work of getting the names
   public function getSection(name:String):Array<String>;  //function that gets just one section by header name
}
```

The data itself would look something like this:

With headers:

``` haxe
["#Super Funders","John","Jane","#Funders","Alice","Bob"]
```

Sans headers:

``` haxe
["John","Jane","Alice","Bob"]
```

Just one section ("Super Funders"):

``` haxe
["John","Jane"]
```
##

**Comment by larsiusprime** [comment]
Here's the current credits list:

https://gist.github.com/larsiusprime/27257c67f736758344ce0f4ba7ea0116

**Comment by Tembac** [comment]
Shouldn't it include the HaxeFlixel team and Openfl team credits in case we wanted to include you in our games? Is there any other way to give the tools teams credit?

**Comment by Gama11** [comment]
That's a bit tricky actually, who do you consider to be part of the HaxeFlixel team? The members of the GitHub organization?
There are people who contributed a lot, but aren't part of that. However, you probably wouldn't want to include [all 92 contributors](https://github.com/HaxeFlixel/flixel/graphs/contributors) (not to mention other repos) either...

**Comment by Tembac** [comment]
I think that the top 10 or 20 contributors deserves credit. You are the people doing almost all the work here.

**Comment by Gama11** [comment]
That's the problem though - where's the cut-off point? There will always be some contributor who just barely didn't make the list and might be upset about that.

**Comment by Tembac** [comment]
Why wouldn't you want to include the 92? 
If we are going to include all the backers, 92 contributors is not that different.

**Comment by MSGhero** [comment]
I don't think any contributors should be published. That seems weird, I wouldn't want my +- 1400 in the credits of someone's game.

**Comment by Gama11** [comment]
A bit late for this now...
