### ISSUE TITLE
Static text object graphic missing after state switch

### ISSUE THREAD

**Issue by DleanJeans** [HaxeFlixel/flixel#1922]
- **Flixel version:** dev ahead of 4.1.1
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:** Neko/CPP

________________________________

**Code snippet reproducing the issue**:
https://gist.github.com/DleanJeans/5f71159386f8b0ddfc862bea92b48407

**Instructions**:
First state (MenuState) creates a FlxText
Second state (PlayState) add the FlxText and remove it before switching back to MenuState (to prevent FlxText destruction)

SPACE to switch between states
In PlayState.hx:
Press 1 to switch alignment
Press 2 to switch fieldWidth
Press 3 to switch font
Press ENTER to FlxText drawFrame() (does nothing tho)
________________________________

**Observed behavior:**
On Neko, (probably same on cpp)
At first you can press switch state (SPACE) as many time you want and the text still shows.
But if you change either fieldWidth (Key 2) or font (Key 3), the text will disappear if you switch back to PlayState and only shows up again if you change them again.
On Flash, (probably same on html5)
work as expected like below.
**Expected behavior:** No matter platform or settings, the text should appear on switch state

**Comment by Gama11** [comment]
This might be a Flixel bug, but I have to look into it more closely. It's strange that it only happens on RENDER_TILE, but not RENDER_BLIT targets.

**Comment by Beeblerox** [comment]
with my PR you don't need to set `text.graphic.persist = true;` now, because bitmap cache is being cleared after state is destroyed, and `FlxG.bitmap.clearCache()` removes only unused graphic now. 
But if you remove object from the state before swithing the state then state destroy won't change use count of object's graphic use count, so object's graphic will stay in the cache

**Comment by Gama11** [comment]
>But if you remove object from the state before swithing the state then state destroy won't change use count of object's graphic use count, so object's graphic will stay in the cache

This sounds like it could lead to memory leaks?

**Comment by Beeblerox** [comment]
in most cases you won't remove object from state, you just kill object. So there won't be leaks.
But if you remove the object and want to completely get rid of it then you'll need to also call object.destroy() which should clean memory out of all links, including graphic, so object's graphic use count also will be changed thus will allow to dispose it as well

**Comment by Beeblerox** [comment]
and coder always can find the way how to cause memory leak :)

**Comment by Gama11** [comment]
I guess that's fair.
