### ISSUE TITLE
NUMPAD keys not working on html5

### ISSUE THREAD

**Issue by jsanjuan83** [HaxeFlixel/flixel#1927]
- **Flixel version: 4.0.1
- **OpenFL version: 3.6.1
- **Lime version: 2.9.1
- **Affected targets: HTML5

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxState;

class PlayState extends FlxState
{
	override public function update(elapsed:Float):Void
	{
		if (FlxG.keys.justPressed.NUMPADONE)
{
*****
}
	}
}
```

________________________________

**Observed behavior:** 
I get no response on pressing numpad keys.
**Expected behavior:**
Capture numpad keys pressings

**Comment by larsiusprime** [comment]
Sorry if this sounds dumb, but just to be sure -- you've confirmed it's not an issue with NUMLOCK being on or off?

**Comment by jsanjuan83** [comment]
Yes, I made sure of that. Moreover, it's something only happening on html5. I checked it on flash and neko and it worked.

**Comment by Beeblerox** [comment]
i believe that this is an openfl or lime issue, since Keyboard event keyCodes for:
"a" and NUMPAD_3 is 65,
"b" and NUMPAD_2 is 66,
 "c" and NUMPAD_3 is 67, etc.

**Comment by Gama11** [comment]
In that case, we should isolate this and report it to either Lime or OpenFL.

**Comment by Beeblerox** [comment]
@Gama11 i'll try to do it tonight then. But at this moment i think that this is lime issue.

**Comment by Gama11** [comment]
This is indeed a Lime issue, reported at https://github.com/openfl/lime/issues/818.

**Comment by Gama11** [comment]
It had already been fixed on the Lime dev branch, so it will be part of the next Lime release I guess. #1940 needs to be finished before we can benefit from that though.
