### ISSUE TITLE
Screenshake behavior during pause

### ISSUE THREAD

**Issue by MSGhero** [HaxeFlixel/flixel#1929]
- **Flixel version:** latest
- Flash target, maybe others

________________________________

When you screenshake, pause, and step the game forward one frame, the display starts moving (and doesn't stop) in the random direction that was chosen by `updateShake`. This is because of the 3rd linked snippet below, where `draw()` gets called from FlxGame's enterframe despite things being paused. Shake is updated during the draw phase in the 1st linked snippet, which moves the display.

I'm not sure what other FX there are, but they are probably affected too. This is just an issue while paused, as the display will snap back to normal on the next frame.

https://github.com/HaxeFlixel/flixel/blob/dev/flixel/FlxCamera.hx#L1409-L1413
https://github.com/HaxeFlixel/flixel/blob/dev/flixel/FlxGame.hx#L899
https://github.com/HaxeFlixel/flixel/blob/dev/flixel/FlxGame.hx#L540

**Comment by Beeblerox** [comment]
i think that other effects (fade and flash) shouldn't be affected.
the easiest way to fix this issue is to change this line https://github.com/HaxeFlixel/flixel/blob/dev/flixel/FlxCamera.hx#L1409 to something like
```
if (((_fxShakeOffset.x != 0) || (_fxShakeOffset.y != 0)) && FlxG.state.active)
```
But i don't like it.

**Comment by bendmorris** [comment]
HaxePunk used to have this issue for particles, the fix is simply to not do state modification in the draw method, but move it into update methods. In this case you could modify flashSprite.x/y in updateShake instead of in draw. Easy fix, PR incoming.

**Comment by Beeblerox** [comment]
or move this block of code https://github.com/HaxeFlixel/flixel/blob/dev/flixel/FlxCamera.hx#L1409-L1413 into `updateShake()` method, which is not completely right too, since this method can be called few times per frame (update rate can be higher than draw rate)

**Comment by bendmorris** [comment]
>update rate can be higher than draw rate

If that's the case it's not really a problem, right? If flashSprite gets recentered and moved to a random offset multiple times before drawing, the end result is the same, it's offset by some random amount.

**Comment by Beeblerox** [comment]
yes, right!

**Comment by MSGhero** [comment]
Thanks @bendmorris
