### ISSUE TITLE
DebugDraw box size doesn't update after playing animation with bigger frame size

### ISSUE THREAD

**Issue by IBwWG** [HaxeFlixel/flixel#1936]
- **Flixel version:** 4.1.1
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:**
flash, windows

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flash.display.BitmapData;
import flash.geom.Matrix;
import flash.geom.Point;
import flash.geom.Rectangle;
import flixel.FlxG;
import flixel.FlxSprite;
import flixel.FlxState;
import flixel.graphics.frames.FlxAtlasFrames;
import flixel.util.FlxCollision;
import flixel.util.FlxColor;

class PlayState extends FlxState{
	override public function create():Void {
		FlxG.debugger.drawDebug = true;
        var sprite:FlxSprite = cast add(new FlxSprite(30, 0));
		sprite.makeGraphic(100, 100, FlxColor.WHITE, true);
        var sourceSprite = new FlxSprite();
		sourceSprite.makeGraphic(100, 100, FlxColor.RED, true);
		var animatedSprite:FlxSprite = cast add(new FlxSprite());
		// load animations with varying frame sizes
		animatedSprite.frames = FlxAtlasFrames.fromLibGdx(sourceSprite.pixels, '
test.png
size: 100,100
format: RGBA8888
filter: Nearest,Nearest
repeat: none
a/0
  rotate: false
  xy: 0, 0
  size: 10, 10
  orig: 10, 10
  offset: 0, 0
  index: -1
b/0
  rotate: false
  xy: 90, 90
  size: 20, 20
  orig: 50, 50
  offset: 30, 0
  index: -1
');
		// add animations
		for (name in ["a","b"])
			animatedSprite.animation.addByPrefix(name, name);
		// play smaller-framed anim
		animatedSprite.animation.play("a");
		// play larger-framed anim
		animatedSprite.animation.play("b");
    }
	
	

}
```

________________________________

**Observed behavior:**
![hf-debugdraw](https://cloud.githubusercontent.com/assets/16719964/18346018/7927562e-75be-11e6-9ff5-d1f4a4d920e3.png)

**Expected behavior:**

The 10x10 red box in the upper-left corner should have become 50x50.

**Comment by Gama11** [comment]
I don't think this can really be considered a bug. drawDebug draws the sprite's hitbox, not its graphic dimensions. The hitbox happens to be initialized to the graphic's size during `loadGraphic()` once, but Flixel doesn't really touch it afterwards. This is similar to how flixel doesn't update the hitbox automatically after changing `scale`.

Changing this behavior (as in, update the hitbox when the current animation frame is changed) would be a breaking change and apart from that potentially quite annoying for some use cases.

**Comment by IBwWG** [comment]
I also found the behaviour with scale surprising when I first encountered it.  Maybe what we need is something indicating whether the hitbox is needed, so that if it is, it can be updated automatically in this case.  Perhaps checking the `solid` property?

This wouldn't solve the scale case, though.

**Comment by Gama11** [comment]
Even if it's "needed", the user may want to do something different with it than have it be auto-updated by Flixel. Often times, you'll want to adjust the hitbox slightly after loading a graphic, make it slightly smaller, offset it, etc... Wouldn't want those changes to be overriden just because an animation is played.

**Comment by Gama11** [comment]
My point is: I don't want to make too many assumptions about use cases. :)

**Comment by IBwWG** [comment]
Indeed, I just read about this in Discover HaxeFlixel.  I hadn't even used custom hitboxes myself, but now I see the use case.
