### ISSUE TITLE
FlxCamera bug w/ transparent background

### ISSUE THREAD

**Issue by xerosugar** [HaxeFlixel/flixel#1949]
- **Flixel version:** 4.1.1 (from git)
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:**
tested on: html5, neko, win, flash
________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxState;

class PlayState extends FlxState
{
	override public function create():Void
	{
		var sprite = new FlxSprite();
		sprite.makeGraphic(100, 100, FlxColor.RED);
		
		var sprite2 = new FlxSprite(100);
		sprite2.makeGraphic(100, 100, FlxColor.BLUE);
		
		add(sprite);
		add(sprite2);
		
		var cam1:FlxCamera = new FlxCamera(0, 0, FlxG.width, FlxG.height, 1);
		var cam2:FlxCamera = new FlxCamera(0, 0, FlxG.width, FlxG.height, 1);
		
		FlxG.cameras.add(cam2);
		
		sprite2.cameras = [cam2];
		cam2.bgColor = FlxColor.TRANSPARENT;
	}
}
```

________________________________

**Observed behavior:** The blue sprite becomes invisible when compiling the project on OpenFl Next
**Expected behavior:** Both sprites should be visible even if the camera's bgColor is transparent.

**Comment by JoeCreates** [comment]
Are you using -dnext and do you have the commit https://github.com/HaxeFlixel/flixel/commit/45762e5f30fa82a1caa430ccd829ec23d91bd6aa? It contains a workaround for an openfl next issue that was causing this effect. If you haven;t pulled in the last week I would suggest doing so and seeing if it fixes the issue.

**Comment by xerosugar** [comment]
I have this in project.xml:
```
<set name="next"/>
```

Haven't pulled in a while now so I could do that and see what happens.

**Comment by Gama11** [comment]
Just checked, and as @JoeCreates pointed out, this is fixed by 45762e5.

**Comment by xerosugar** [comment]
It seems to work with the latest git version, thanks! But now my other (bigger) app instantly crashes after compiling for neko and doesn't respect the scrollboundsRect on windows, hm... ah well, I guess this particular issue is fixed.

**Comment by Gama11** [comment]
Did you find out what was causing your scrollboundsRect issue on Windows?

**Comment by xerosugar** [comment]
didn't really feel like digging into it that time, so I simply replaced the updated method (that calculates the scrollbounds) with the older version and then it worked again.

**Comment by Gama11** [comment]
I kind of want to find out if there is an issue or not before 4.2.0...

**Comment by xerosugar** [comment]
I made a small test that demonstrates it. can I send the project as a zip somewhere?

**Comment by Gama11** [comment]
Slack?

Check the changelog: https://github.com/HaxeFlixel/flixel/blob/dev/CHANGELOG.md
