### ISSUE TITLE
FlxEmitter emitParticle should return the emitted particle

### ISSUE THREAD

**Issue by JoeCreates** [HaxeFlixel/flixel#1957]
I'm presently trying to override emitParticle so that I can extend the existing behaviour. However, emitParticle does not return the particle it just emitted, so there is no way to do more things to said particple by overriding emitParticle and calling `super.emitParticle()`.

**Comment by Gama11** [comment]
PR?

**Comment by JoeCreates** [comment]
Will do. I'm just working on a strange branch of flixel right now which I can't do the PR from.
