### ISSUE TITLE
FlxTimer Not Recognizing Loops

### ISSUE THREAD

**Issue by xhunterko** [HaxeFlixel/flixel#1960]
- **Flixel version:** 4.1.1
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets: Flash**

________________________________

**Code snippet reproducing the issue**: 

new FlxTimer().start(4, onVictory, 1);

Also this:
new FlxTimer().start(4, LoadLevel(ScreenNumber), 1);

**Observed behavior:** 
source/PlayState.hx:343: characters 3-40 : Cannot skip non-nullable argument Loops
Build halted with errors (haxelib.exe).

**Expected behavior:** That the timer would go to the function or that it would acknowledge the loop.

**Comment by Gama11** [comment]
This is a Haxe compiler error / not a Flixel issue. Most likely, your `onVictory` callback function has an incorrect type.

It should be:

`function onVictory(t:FlxTimer)`

or

`function onVictory(_)`

It is however quite a misleading error message (which has been fixed on Haxe dev afaik).

**Comment by xhunterko** [comment]
All righty thanks.
