### ISSUE TITLE
A quality of life change - Native layer (Z axis) support

### ISSUE THREAD

**Issue by Jarrio** [HaxeFlixel/flixel#1969]
It seems a odd how haxeflixel has no native layering support, adding a value such as layer or Z would go a long way.

**Comment by MSGhero** [comment]
What do you mean? You can rearrange the order of added sprites by accessing the `members` property of whatever group you're looking at.

**Comment by Jarrio** [comment]
I'm not referring to grouping specifically more in general. So right now the way haxeflixel handles layering is - last added is on top. I'm requesting that `FlxBasic` adds a field "layer" or "z", which can directly change the layering of the object.

`add(background);`
`add(player);`

That would be interpreted as the player sprite being on top of the background as expected. What I'm requesting is the following change:

`// create sprite...`
`public function new() {`
      `    this.layer = 5;`
`}`

So that when the game starts rendering it will take into account the layer value and sort via that value. So that if someone were to do:

`add(player); // .layer = 5;`
`add(background); // .layer = 0;`

The player would still render on top of the background. This is a very basic use case but it really does add a nice feature to the engine.

**Comment by Beeblerox** [comment]
it's possible to implement only for hardware opengl renderer, which is in the works.
but i'm not sure that i will implement it in the near future

**Comment by Gama11** [comment]
I don't think it's really an option to support to support a feature like this only on some platforms. If it's implemented, it should work everywhere.
