### ISSUE TITLE
Addition of a tile tool to FlxG.debugger.interaction

### ISSUE THREAD

**Issue by Dovyski** [HaxeFlixel/flixel#1970]
Before opening any pull requests, I would like some feedback regarding a tile tool to be added to `FlxG.debugger.interaction`. This is what I have so far:

![haxeflixel-interaction-tile-tool](https://cloud.githubusercontent.com/assets/512405/19016775/5dea8020-8824-11e6-9744-bf7d2fa54a05.gif)

When the tool (called "tile pen") is clicked, two windows show up: one ("Tilemap") allows the user to select which tilemap to work on, the other ("Tile palette") shows which tiles are available in the currently selected tilemap.

I plan to add a "Tile pointer" tool as well, which allows the user to select tiles and move them around. Such tool will also require a way for the user to select which tilemap to work on, so that's why I decided to go with multiple windows. All tile tools will share the "Tilemap" window to allow the user to select a tilemap.

The implementation is available [here](https://github.com/Dovyski/haxeflixel/tree/interaction-tile-tool).
##

**Comment by Eiyeron** [comment]
I just saw it on Twitter and I can't deny it looks pretty rad. I wonder if you could save/load maps on the fly though. I suppose it'd depend too much on specific conditions to be flexible enough for save/loading in most cases?

**Comment by Dovyski** [comment]
Thanks! Yeah, saving/loading is a key part. I think the best solution is to keep it very simple and allow save/load of CSV files for each tilemap, which is already supported by HaxeFlixel. Anything beyond that is too specific.

**Comment by Beeblerox** [comment]
i agree, that you can get data from modified tilemap and save it yourself

**Comment by Gama11** [comment]
Wow, that .gif is quite impressive!

This does raise some interesting questions though. So far, the debugger overlay has always been for... well, debugging. I don't see this being very useful as a debugging feature, it's more of an actual _editor_. I think people will generally prefer dedicated tools for that like Tiled.
However, it might not necessarily be a bad idea to have this as a simple option / alternative. But it can always only be very limited. Where do you think this fits in?

Another thing is that space is starting to run out with all the available debugger windows (depending on the game's size). I've been wodering if we could have the debugger in a second window on cpp / neko with multi-window support being a thing in OpenFL / Lime Next...

**Comment by starry-abyss** [comment]
I don't like Tiled workflow when game-jamming. Parsing CSV or bitmap for levels is faster, but comes at a price of not having several layers. For example, in top-down game: layer for ground, layer for wall parts that are above objects, layer for ones below objects, layer for objects' initial positions.

Does this thing have support for several tilemaps one over another like Tiled layers?

**Comment by Dovyski** [comment]
> Wow, that .gif is quite impressive!

Thanks!
 
> I think people will generally prefer dedicated tools for that like Tiled. However, it might not necessarily be a bad idea to have this as a simple option / alternative. But it can always only be very limited. 

I like the idea of having built-in tools able to allow developers to quickly prototype games, or even as production tools. An in-engine solution is always faster and more convenient than external tools. I honestly don't think Tiled is more powerful than in-game editing (e.g. selecting, dragging, pausing, resuming while the game is running).

Maybe people prefer Tiled now because they don't have any in-engine alternative.   

> Does this thing have support for several tilemaps one over another like Tiled layers?

Yes, but you have to create and add the tilemap objects to the state yourself first (via code). After that, the tile tool will automatically recognize them during runtime and treat each tilemap as a layer.

> Where do you think this fits in?

I think the interaction tools could enhance the developer experience/workflow. However I understand your point regarding things starting to look like an actual *editor*. In that case, if this initiative becomes out of the scope of the core, I could branch it into a separate project similar to `flixel-ui`. How about `flixel-editor` ? :smile:

**Comment by starry-abyss** [comment]
BTW, I'm using my own clunky in-game editor for one of the projects. The reason is because I need an editor for players to use. So it's the same tool for developer and player. Flixel debugger is not very suitable for my use-case though

**Comment by Ohmnivore** [comment]
I think this is really cool. Excellent for prototyping, for example making sure you can reach that platform with a jump, checking other kinds of spacing, and more.

It seems pretty much complete, so it definitely won't hurt to include it imo. I think it belongs in the main flixel repo :)

**Comment by Ohmnivore** [comment]
I think this is really cool. Excellent for prototyping, for example making sure you can reach that platform with a jump, checking other kinds of spacing, and more.

It seems pretty much complete, so it definitely won't hurt to include it imo. I think it belongs in the main flixel repo :)

**Comment by Dovyski** [comment]
As @Gama11 suggested, this feature might be a bit too much for Flixel core. I'm moving its development (and the development of many similar features) to the [Flixel Studio addon](https://github.com/Dovyski/flixel-studio).

Thanks for all the discussion and feedback, guys!
