### ISSUE TITLE
FlxMouseEventManager doesn't play nice with substates

### ISSUE THREAD

**Issue by Gama11** [HaxeFlixel/flixel#1972]
This is essentially the same issue as #1087 (which was resolved in #1934) but for `FlxMouseEventManager`.

A fix was proposed in #1961, but in my opinion it breaks too much code to be considered before a major version (5.0.0). Maybe there's a way of fixing this without breaking much code though?
##

**Comment by Geokureli** [comment]
this isn't a class I use very much, but I have some ideas after applying these changes to a local branch (this branch is outdated, so I made the changes manually).

With this proposed changes existing game will need to change all refs such as FlxMouseEventManager.add(obj, onDown, null, onOver, onOut) to FlxMouseEventManager.globalManager.add(obj, onDown, null, onOver, onOut). and while it works with surprsingly minimal changes to all HF libs, that's pretty verbose and cumbersome for devs. for cleaner code, what if we rename [ObjectMouseData](https://github.com/HaxeFlixel/flixel/blob/dev/flixel/input/mouse/FlxMouseEventManager.hx#L720) to FlxMouseEvent (or FlxTypedMouseEvent<T> and a typedef) and change the standard utilization to new FlxMouseEvent(obj, onDown, null, onOver, onOut) or FlxMouseEvent.manage(obj, onDown, null, onOver, onOut) and add a final manager arg, which defaults to the global manager.

This is based on how FlxTween and FlxTimer work

**Comment by Geokureli** [comment]
I've made my proposed changes in #2482 2540
