### ISSUE TITLE
An updated Spine runtime

### ISSUE THREAD

**Issue by jeremyfa** [HaxeFlixel/flixel#1973]
Hello team,

I am currently using Flixel to develop a game that uses Spine animations. My first attempt was to try to use [spinehaxe](https://github.com/bendmorris/spinehaxe) with the related FlxSpine class and example, but I quickly ran into problems: the spine runtime is a bit outdated compared to the official runtimes, thus I could not read all animations properly (no shear, for instance).

Spine and some of its latest features being a requirement for the game, I checked if it would be easy to improve the current spinehaxe repo, but at the end, the quickest and most efficient option was simply to make a new port based on the official AS3 runtime. The result and complete explanation can be found here:

https://github.com/jeremyfa/spine-hx

The idea is to stay as close as possible to the official AS3 implementation, in order to make updates easy when the official runtime will be improved.

Then, I edited FlxSpine class (and related) to use this new runtime. The code can be found here, along with the updated example from flixel demos:

https://github.com/jeremyfa/flixel-spine-hx

I also slightly changed how the animations are drawn when using quads: some 2d transformations could not be expressed by just changing rotation/scale of FlxSprite objects, so I added an FlxTransformableSprite that can use a custom matrix for drawing. So, the drawing of each sprite is simply done by getting the matrix values provided by the runtime (Note that this FlxTransformableSprite is completely independant from FlxSpine/Spine and can be used for other purposes).

The code is pretty recent, but so far, all the animations I tested work as expected, even when using latest Spine features. Feel free to give it a try!

**Comment by Gama11** [comment]
Looks great!

However, could you reopen this [on flixel-addons](https://github.com/HaxeFlixel/flixel-addons/issues)? That's where we keep the spine implementation, so all issues related to that should go there.
