### ISSUE TITLE
FlxG.random.shuffle should be non-destructive

### ISSUE THREAD

**Issue by SeiferTim** [HaxeFlixel/flixel#1975]
- **Flixel version:** dev
________________________________

`FlxG.random.shuffleArray` now gives a warning suggesting users switch to `FlxG.random.shuffle`, but `shuffle` changes the array itself, while `shuffleArray` does not.

`shuffleArray` works great if you want to grab a random item out of an array, without actually changing the order of the array (in the case that the order matters of other parts of the code)

I suggest changing `shuffle` to work in a similar way, it should return an Array instead of Void, and clone the array to be shuffled.

**Comment by Gama11** [comment]
You're mistaken, `shuffleArray()` modifies the array in place as well:

```haxe
var array = [1, 2, 3, 4, 5, 6];
FlxG.random.shuffleArray(array, 10);
trace(array); // [2,1,6,5,3,4]
```

**Comment by JoeCreates** [comment]
@SeiferTim You can clone any array manually and shuffle that, if that's the behaviour you require. Forcing the array to be a copy could be a burden on resources for user's that don't need it.
