### ISSUE TITLE
FlxCamera.updateScroll does not work if Zoom > 1

### ISSUE THREAD

**Issue by SeiferTim** [HaxeFlixel/flixel#1976]
- **Flixel version:** dev

________________________________

It looks like `FlxCamera.updateScroll` was changed a few months ago to better handle when zoom < 1, however, this new logic breaks the scrollBounds logic if zoom > 1.

I'm able to 'fix' the problem by using `if (zoom <= 1)` for the new code, but there might be a more elegant solution available.

```haxe
	/**
	 * Updates (bounds) the camera scroll.
	 * Called every frame by camera's update() method.
	 */
	public function updateScroll():Void
	{
		if (zoom <= 1)
		{
			// Adjust bounds to account for zoom
			var minX:Null<Float> = minScrollX == null ? null : minScrollX - (zoom - 1) * width / (2 * zoom);
			var maxX:Null<Float> = maxScrollX == null ? null : maxScrollX + (zoom - 1) * width / (2 * zoom);
			var minY:Null<Float> = minScrollY == null ? null : minScrollY - (zoom - 1) * height / (2 * zoom);
			var maxY:Null<Float> = maxScrollY == null ? null : maxScrollY + (zoom - 1) * height / (2 * zoom);
			
			// Make sure we didn't go outside the camera's bounds
			scroll.x = FlxMath.bound(scroll.x, minX, (maxX != null) ? maxX - width : null);
			scroll.y = FlxMath.bound(scroll.y, minY, (maxY != null) ? maxY - height : null);
		} 
		else
		{
			scroll.x = FlxMath.bound(scroll.x, minScrollX, (maxScrollX != null) ? maxScrollX - width : null);
			scroll.y = FlxMath.bound(scroll.y, minScrollY, (maxScrollY != null) ? maxScrollY - height : null);
		}
		
	}
```

**Comment by Gama11** [comment]
The new code was not for fixing cases with zoom < 0, it was for zoom in general. For some reason it seems like it doesn't play nice with the `Zoom` parameter of `FlxGame#new()` though (@JoeCreates looked into this on Slack). Can you try changing that to 1 if it's > 0?

**Comment by JoeCreates** [comment]
I've opened a new issue which better reflects the cause of this. Short term I can make updateScrollBounds take account of FlxGame zoom values (which I can do in the coming weeks following a deadline), while long term I would consider removing the zoom parameter if it doesn't have any practical use.

**Comment by Gama11** [comment]
That sounds reasonable.

No reason to keep both issues open I guess.
