### ISSUE TITLE
FlxTween.quadMotion (and may be another tweens) works incorrectly.

### ISSUE THREAD

**Issue by extremalex** [HaxeFlixel/flixel#1978]
- **Flixel version:** 4.2.0 (dev)
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:** desktop (windows)
________________________________
- **Code example** (simplest):

FlxTween.quadMotion(_token, _token.x, _token.y, (_token.x + _x_end) / 2, mid_y, _x_end, _y_end, 1.0, true, { type: FlxTween.ONESHOT, ease: FlxEase.sineInOut, onComplete: cast function() {trace ('something');} } );

The behavior of an object in motion is wrong, it is very different from all Flixel versions earlier than September's 4.2.0 and any latest versions. Also, the **onComplete** method does not run at the end of the tween.

**Comment by Gama11** [comment]
Thanks for reporting, looks like the FlxTween demo indeed has some issues...

**Comment by Gama11** [comment]
Bisected to #1934 / 9ac2de5. (cc @JoeCreates).

**Comment by Gama11** [comment]
This only seems to affect `QuadMotion` from what I can tell...
