### ISSUE TITLE
FlxBloom demo broken

### ISSUE THREAD

**Issue by Gama11** [HaxeFlixel/flixel#1979]
As of 71c6811 / #1974, the FlxBloom demo looks like this:

![](http://i.imgur.com/ONjdRgG.png)

It's supposed to look like this:

![](http://i.imgur.com/J1Uo5ox.png)

We may need to revert the fix for #1838.

**Comment by Beeblerox** [comment]
i have no idea how to fix it.
i've tried to change stage.quality before drawing but no luck.
the only way is to revert changes for flxcamera
