### ISSUE TITLE
FlxBitmapText does not permit negative line spacing

### ISSUE THREAD

**Issue by seraku24** [HaxeFlixel/flixel#1984]
- **Flixel version:** 4.2.0
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:** flash, and (possibly) all others

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxG;
import flixel.FlxState;
import flixel.text.FlxBitmapText;

class PlayState extends FlxState
{
	override public function create():Void {
		var bitmapText = new FlxBitmapText();
		var desiredLineSpacing = -5;
		bitmapText.lineSpacing = desiredLineSpacing;
		if (bitmapText.lineSpacing != desiredLineSpacing) {
			FlxG.log.error("FlxBitmapText.lineSpacing is not desired value.");
		}
	}
}
```

________________________________

**Observed behavior:**
The `lineSpacing` property becomes a positive value, specifically the absolute value.

**Expected behavior:**
The `lineSpacing` property allows a negative value to be set.

NOTE: Near as I can tell, the text layout code in `FlxBitmapText` is already written properly to support a negative value for `lineSpacing` which would result in condensed spacing.  The issue, then, lies within the property setter enforcing a positive-only value.

**Comment by Gama11** [comment]
This seems familiar. :) https://github.com/HaxeFlixel/flixel/pull/1603
