### ISSUE TITLE
Default loader leaks textures on WebGL

### ISSUE THREAD

**Issue by ttencate** [HaxeFlixel/flixel#1991]
- **Flixel version:** 4.2.0
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:** webgl

---

It seems that the default HaxeFlixel loader screen does not delete its textures on WebGL after loading is done. To see this, install [WebGL Inspector](https://chrome.google.com/webstore/detail/webgl-inspector/ogkcjmbhnfmlnielkjhedpcjomeaghda) in Chrome and open e.g. [this game](http://frozenfractal.itch.io/shenzhen-solitaire) (you'll need to liberate it from its iframe in order for the WebGL Inspector to work). For each (?) new percentage increase of the preloader, a new text is generated but the old one is not deleted, even after loading is complete:

![preloader](https://cloud.githubusercontent.com/assets/90930/19836244/57985a12-9e9a-11e6-87d1-bff15dbfdfa8.png)

I think all the other loader textures could also be deleted (logo, stripes, background etc.), but the percentage text seems the worst offender, as it'll eat more texture memory when more assets are being loaded, or when loading is slower.
##

**Comment by Gama11** [comment]
Could you try again with Flixel 4.4.0+ OpenFL 8? WebGL is now the default renderer there, and I wonder if the situation has improved. I had some trouble getting the WebGL inspector plugin you linked to getting to work on my end.

**Comment by ttencate** [comment]
The WebGL inspector stopped working for me as well. Pity. I don't know how to mimic its behaviour with browser console commands easily, and I'm not going to spend hours trying right now, sorry.

**Comment by Gama11** [comment]
No worries, I understand. Thanks for confirming that it's not just some setup issue on my end at least!

**Comment by Gama11** [comment]
I guess it's best to close this for now then, as there's a good chance OpenFL 8 has improved in this regard and I don't want to invest a lot of time into getting the plugin to work either. :) If it turns out that's it's still an issue, let me know!
