### ISSUE TITLE
Refactor logic for item removal (e.g. mouse events)

### ISSUE THREAD

**Issue by seraku24** [HaxeFlixel/flixel#1992]
- **Flixel version:** 4.2.0, dev
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:** all

---

Moving discussion from #1990 to its own issue for tracking:

> This might fall under the category of refactoring, but there is potential for a cleaner and faster solution here.
> 
> Having `removeAll()` defer to `remove()` is slow, specifically O(_n_²), due to the need to iterate the collection per each element.  Since all items are going to be removed, the array can be cleared directly instead of removing elements one at a time.  To avoid duplication of code, the existing "null"ing logic currently within `remove()` should be in a `destroy()` method that belongs to `ObjectMouseData<T>`.  This would enable both `remove()` and `removeAll()` to share this cleanup logic without depending on each other.
> 
> _(Some hastily written and untested code for clarity.)_
> 
> ``` haxe
> public function remove<T:FlxObject>(Object:T):T {
>     if (_registeredObjects == null || _registeredObjects.length == 0) { return Object; }
>     for (reg in _registeredObjects) {
>         if (reg.object == Object) {
>             reg.destroy();
>             _registeredObjects.remove(reg);
>             break;
>         }
>     }
>     return Object;
> }
> 
> public function removeAll():Void {
>     if (_registeredObjects == null || _registeredObjects.length == 0) { return; }
>     for (reg in _registeredObjects) { reg.destroy(); }
>     _registeredObjects = [];
> }
> 
> // . . .
> 
> public function destroy():Void {
>     object = null; sprite = null;
>     onMouseDown = onMouseUp = onMouseOver = onMouseOut = null;
> }
> ```
> 
> Just something to consider.  Although, it sounds like there might be other parts of the project that could be improved with the same refactoring, which would be beyond the scope of the issue you are fixing.
> 
> **Edit:** Added a `break` to the `remove()` function in my example.  After all, it is Bad™ to continue iteration on a collection that has been modified.  Plus, there's no need to continue iteration once we've found the element we want to remove.

**Comment by Beeblerox** [comment]
i'll work on this logic this week.
Thank you for noticing this :)

**Comment by MSGhero** [comment]
I want to add, Joshua said that `array = array.splice(0, array.length)` does not allocate versus `array = []` on non-flash targets. Flash allocates either way.

**Comment by Beeblerox** [comment]
@MSGhero thanks for the tip

**Comment by MSGhero** [comment]
Maybe it was just `array.splice()` and no `array = array.splice()`. I'll check openfl later.

**Comment by Beeblerox** [comment]
@MSGhero i believe that it should be just `array.splice()`, because it returns an array of removed elements of original array - see http://api.haxe.org/Array.html#splice
Anyway, i've already made these changes here: https://github.com/HaxeFlixel/flixel/pull/2005
