### ISSUE TITLE
FlxBar ignores value, stays empty

### ISSUE THREAD

**Issue by Ohmnivore** [HaxeFlixel/flixel#2000]
- **Flixel version:** 4.2.0
- **OpenFL version:** 4.4.1
- **Lime version:** 3.4.1
- **Affected targets:** Windows, others not tested

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxState;
import flixel.ui.FlxBar;

class PlayState extends FlxState
{
        private var health:Float;

	override public function create():Void
	{
		health = 100;
		healthBar = new FlxBar(0, 0, null, 32, 5);
		healthBar.setRange(0, 100);
		healthBar.createFilledBar(0xff005100, 0xff00F400, true, 0xff000000);
                healthBar.value = health;
	}

        override public function update(elapsed:Float):Void
        {
                 healthBar.value = health;
        }
}
```

________________________________

**Observed behavior:** The FlxBar stays always empty, regardless of value
**Expected behavior:** The FlxBar should grow/shrink according to value

I tried setting the value on each update, and also the other setParent method. Nothing worked. I traced the FlxBar at runtime and it displays the right value, but remains empty.

**Comment by DleanJeans** [comment]
Try
```
healthBar = new FlxBar(0, 0, null, 32, 5, this, "health");
```

**Comment by Ohmnivore** [comment]
Already have, still the same behavior.

**Comment by DleanJeans** [comment]
Nothing wrong here on Flash, Windows, Neko
HaxeFlixel: 4.2.0
OpenFl: 3.6.1
Lime; 2.9.1

How do you make HaxeFlixel work with OpenFl 4?
Is HaxeFlixel compatible with it now?

**Comment by Beeblerox** [comment]
@Ohmnivore HaxeFlixel: 4.2.0 doesn't work with OpenFL version: 4.x
are you sure that you're using these versions of the libs?
And as @DleanJeans said FlxBar is working as expected with HaxeFlixel: 4.2.0, OpenFl: 3.6.1 and Lime: 2.9.1
So could you provide more details?

**Comment by Gama11** [comment]
No followup.
