### ISSUE TITLE
[question] can i tween member variables?

### ISSUE THREAD

**Issue by 0xFireball** [HaxeFlixel/flixel#2001]
i want to tween a point inside a sprite.
for example, my sprite has a `scale` property, and i want to tween `scale.x` from its current value to `3`.
is there any way to do this?
i tried a couple things but i got: "unsupported operation"

**Comment by Gama11** [comment]
You need to pass `sprite.scale` as the tweened object and use `"x"` as the property to be tweened, rather than tweening `"scale.x"` on `sprite`.

The issue tracker is not really intended for questions - we have a [forum](http://forum.haxeflixel.com/) for that.
