### ISSUE TITLE
Using group.length after removing an element yields a null reference due to not updating the internal value

### ISSUE THREAD

**Issue by Jarrio** [HaxeFlixel/flixel#2010]
- **Flixel version:** 4.2.0
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:** All of them
________________________________

**Code snippet reproducing the issue**:

```haxe
import flixel.FlxSprite;
import flixel.FlxG;
import flixel.FlxState;
import flixel.group.FlxSpriteGroup;

class TestState extends FlxState {
    public var group:FlxSpriteGroup = new FlxSpriteGroup();
    override public function create():Void {
        super.create();

        for (i in 0...10) {
            group.add(new FlxSprite(i * 10, 10));            
        }

        add(group);
        group.remove(group.members[0], true);

        
        for (i in 0...group.length) {
            trace(group.members[i].x);
        }
        
    }
}
```

________________________________

**Observed behavior:**
Error is on the final trace
**Expected behavior:**
The `group.length` value should match the new `group.members.length` value
Temporary fix is to just use the `group.members.length` value

**Comment by Gama11** [comment]
Nice catch. Looks like there originally [used to be](https://github.com/AdamAtomic/flixel/blob/master/org/flixel/FlxGroup.as#L282) a `length--` there, but it went missing between these two commits:

https://github.com/HaxeFlixel/flixel/commit/2ddde969cc52c723c07555177e2d10e26fb55134#diff-0a33dc2c18b9746c9928ecafde442aa2L344
https://github.com/HaxeFlixel/flixel/commit/e353f0789ae78a63a717060fc4774c9039017bd8#diff-0a33dc2c18b9746c9928ecafde442aa2R343

**Comment by MSGhero** [comment]
#1887 though?

**Comment by Gama11** [comment]
That's not really the same thing. That PR would've made it so that `length` is always decreased in `remove()`, even with `Splice = false`.

**Comment by MSGhero** [comment]
I meant more that you said you were wary of changing it bc people relied on the current behavior, and it's a breaking change.

But it's more correct now so...

**Comment by Gama11** [comment]
Ah. I mean, this really just restores the original / "correct" behavior. We couldn't fix any bugs if we always fear somebody [relies on the buggy behavior](http://xkcd.com/1172/). :)

That PR you linked went in a different direction / changed the behavior, it wasn't a bugfix.
