### ISSUE TITLE
FlxState/FlxSubState bgColor doesn't work on HTML5 (renderBlit(?))

### ISSUE THREAD

**Issue by DleanJeans** [HaxeFlixel/flixel#2014]
- **Flixel version:** 4.3.0 git
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:** HTML5 and maybe Android IIRC

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxState;
import flixel.FlxSubState;
import flixel.util.FlxColor;

class PlayState extends FlxState
{
	override public function create():Void
	{
		// 2 seperate tests:
		
		// FlxState bgColor test
		var bgColor = FlxColor.WHITE;
		bgColor.alphaFloat = 0.5;
		this.bgColor = bgColor;

		// FlxSubState bgColor test
		bgColor = FlxColor.WHITE;
		var substate = new FlxSubState();
		substate.bgColor = FlxColor.BLACK;
		substate.bgColor.alphaFloat = 0.5;
		openSubState(substate);
	}
}
```

________________________________

**Observed behavior:** White background
**Expected behavior:** Grayish background

**Comment by ashes999** [comment]
I saw this today on HTML5. Setting `this.bgColor` to anything other than white leaves the background as black. This can be simply reproduced by generating the template and setting `this.bgColor` in `create`.

If it helps, I tried several methods of changing/generating the `FlxColor` object, including `fromRGB` and `setRGB`.

**Comment by ashes999** [comment]
Any chance you can look into this @Gama11 ?

**Comment by Beeblerox** [comment]
i'll look into it tomorrow

**Comment by Beeblerox** [comment]
it's not that easy issue to fix as i thought. I've spent whole evening and part of morning with no luck.
Will need some more time to investigate this issue

**Comment by ashes999** [comment]
Thanks for spending time on it. I'm not in a rush personally (I can work around this).

**Comment by Gama11** [comment]
This seems to be working correctly with OpenFL 8.
