### ISSUE TITLE
Black window on legacy after maximize-minimize-restore

### ISSUE THREAD

**Issue by starry-abyss** [HaxeFlixel/flixel#2018]
- **Flixel version:** dev 58c1d1a
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:** windows, neko

________________________________

Only in legacy mode.

Steps to reproduce:
- run FlxBunnyMark demo;
- maximize the game window;
- minimize the game window;
- restore the game window.

________________________________

**Observed behavior:**
The game is all black until un-maximizing the window.

**Expected behavior:**
Proper game visuals right after restoring the window.

**Comment by Gama11** [comment]
This no longer reproduces with OpenFL 8.

Note: I could still reproduce with Legacy, but instead of a black window it just "got stuck".
