### ISSUE TITLE
Game permanently paused when losing focus.

### ISSUE THREAD

**Issue by MintPaw** [HaxeFlixel/flixel#2022]
- **Flixel version:** dev@58c1d1a (most recent)
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:** HTML5

________________________________

Compile the Mode demo targeting html5, on the main menu and click the Windows taskbar to lose focus. Then click back on the game, the game will not unpause, although the paused overlay will go away. You can still open the debugger, but the game is "paused" meaning update() does not run. You can click in the console textfield then back on the game to unpause it. Text is still selectable and the performance graphs still update while paused, I'd imagine this is an html focus issue. The behaviour seems exactly like when you have your cursor in the console and the game is "frozen" pending you typing a command.

`FlxG.autoPause = false;` and `<haxedef name="FLX_NO_FOCUS_LOST_SCREEN" />` don't seem to change anything except you can purposely lose focus and the game will unpause. This suggests that maybe the bool for focus that is being flipped is losing synchronization with actual focus? Although that's just a guess.

This was tested with Chrome and Firefox on Windows 8.1 x64.

**Comment by starry-abyss** [comment]
Maybe the same as my issue here (no fix yet): https://github.com/HaxeFlixel/flixel/issues/2008

**Comment by Gama11** [comment]
Closing as a duplicate.

**Comment by JeremiahIsKing** [comment]
Search `function update()` and put it on here!!
