### ISSUE TITLE
FlxColor compilation error

### ISSUE THREAD

**Issue by raould** [HaxeFlixel/flixel#2028]
(in the bug template, why doesn't it ask for the Haxe version??????????????? and OS?)

- **Haxe version:** 3.2.1
- **OS:** Ubuntu 14.04 LTS intel/amd 64 bit
- **Flixel version:** 4.2.0
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:** neko

________________________________

```
 FlxColor.blue
```

________________________________

**Observed behavior:**
/usr/share/haxelib/flixel/4,2,0/flixel/util/FlxColor.hx:584: lines 584-587 : Invalid abstract implementation function

**Expected behavior:**
no compilation error

**Comment by Gama11** [comment]
You're probably looking for `FlxColor.BLUE`? `blue` is a non-static property which can't be accessed via the class name. Haxe's error message here is quite confusing though...

**Comment by Gama11** [comment]
Opened a Haxe issue: https://github.com/HaxeFoundation/haxe/issues/5940

**Comment by raould** [comment]
oh ha ha I misread the docs saying "BLUE" as "Blue" and then the compiler told me I probably meant "blue" so that's how i ended up there I guess.

thank you for the help!
