### ISSUE TITLE
Document how FLX_defines work i.e. #if FLX_SOUND_SYSTEM

### ISSUE THREAD

**Issue by raould** [HaxeFlixel/flixel#2030]
- **Flixel version:** 4.2.0
- **OpenFL version:** 3.6.1
- **Lime version:** 3.5.2
- **Haxe version:** 3.2.1
- **OS**: ubuntu 14.04 lts 64 bit intel
- **Affected targets:** neko, html5, linux

________________________________

When I try to use 
```
new FlxG.sound.load( K.Path_music_m1, 1 );
```
it gives me
```
source/com/x/z/Tracker.hx:19: characters 24-29 : Unexpected sound
source/com/x/z/Tracker.hx:19: characters 24-34 : flixel.system.FlxSound has no field load
```
and when I look at FlxG.sound I see 
```
    #if FLX_SOUND_SYSTEM
    /**                                                                                                                             
     * Contains a list of all sounds and other things to manage or play() sounds.                                                   
     */
    public static var sound(default, null):SoundFrontEnd;
    #end
```
which makes me think I need to turn on FLX_SOUND_SYSTEM somewhere somehow? I haven't turned up anything explaining it anywhere yet.

**Comment by MSGhero** [comment]
https://github.com/HaxeFlixel/flixel-demos/blob/dev/Arcade/Flappybalt/Project.xml

This is the default flixel project template, plus some stuff specific to this demo. So you would leave "disable sound management code" commented out so that it's actually enabled. 

I don't remember, but I think this gets generated when you create a new project from a template. That would be described on the website, but I myself have never done it that way.

**Comment by raould** [comment]
Thank you for the thought. I haven't changed anything in the Project.xml and when I use
```
#if FLX_SOUND_SYSTEM
#error
#end
```
in my code then that does give me an error, so I think the sound system is turned on but somehow the code is not compiling right. Why does FlxG.sound not turn out to be the right thing?
```
source/com/x/z/Tracker.hx:19: characters 24-34 : flixel.system.FlxSound has no field load
```

**Comment by MSGhero** [comment]
Well, `FlxSound` doesn't actually have a `load` property or function. There's `loadEmbedded`, `loadStream` and `loadByteArray`.

Maybe that was the case in an old version of flixel, and you've updated recently?

**Comment by MSGhero** [comment]
Oh wait I see. You're calling `FlxG.sound.load()` and it's giving you that error? Can you try `dev` flixel and see if that works?

**Comment by Gama11** [comment]
>```haxe
>new FlxG.sound.load( K.Path_music_m1, 1 );
>```

There shouldn't be a `new` there.

**Comment by raould** [comment]
yes! (as in aigh, nooooo!) thank you.
