### ISSUE TITLE
flixel tpl has "snap to grid" horizontal mouse movement (vertical is fine) on neko/cpp on Linux (only 64-bit, not 32)

### ISSUE THREAD

**Issue by IBwWG** [HaxeFlixel/flixel#2035]
Haxe 3.4.0.

- **Flixel version:** 4.0.0, 4.2.0
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:**
linux (release mode) for both neko and cpp on all the above flixel versions
________________________________

**Code snippet reproducing the issue**:

```
$ flixel tpl -n "HelloWorld"
Created template at:
.../HelloWorld
 
$ cd HelloWorld/
$ lime test neko
```

________________________________

**Observed behavior:**

![flixel helloworld neko](https://cloud.githubusercontent.com/assets/16719964/22507643/cd23c6f0-e886-11e6-86d6-9042b28e29e2.gif)

Hopefully despite it being a gif you can tell the stark difference in feeling between the vertical and horizontal mouse movement.  Compare with horizontal outside the window, where it's smooth again.  Inside it visually resembles "snap to grid" except that the grid has irregular spacing (wider at the right than at the left part of the window.)

**Expected behavior:**

Smooth mouse movement on both axes.

**Comment by IBwWG** [comment]
OK a less branchy example, TurnBasedRPG from flixel-demos 2.3.0, with flixel 4.0.0, does not have this problem on the following:

1. flixel 4.0.0, neko
1. flixel 4.2.0, neko

did not test yet:

1. flixel 4.2.0, cpp
1. flixel 4.0.0, cpp

**Comment by IBwWG** [comment]
I just confirmed that with flixel 4.2.0, haxe 3.4.0, neko, all else the same, this does not happen on Windows 7x64, at least my box.

**Comment by IBwWG** [comment]
Something interesting (and another reason I think this at least *affects* flixel-templates, even if it's not *only* about that--it could also result in a documentation improvement to flixel, but I'm trying to show you what a newcomer would see) is that `FlxG.mouse` reports (0,0) no matter where the cursor is, and added sprite objects do not appear in the window.  You can see what I mean if you replace the template's MenuState.hx with this:

```
package;

import flixel.FlxG;
import flixel.FlxSprite;
import flixel.FlxState;
import flixel.text.FlxText;
import flixel.ui.FlxButton;
import flixel.math.FlxMath;
import flixel.util.FlxColor;

class MenuState extends FlxState
{
	var whiteBox:FlxSprite = null;
	override public function create():Void
	{
		super.create();
		whiteBox = new FlxSprite();
		whiteBox.makeGraphic(100, 100, FlxColor.WHITE);
		add(whiteBox);
	}

	override public function update(elapsed:Float):Void
	{
		trace(FlxG.mouse);
		whiteBox.setPosition(FlxG.mouse.x, FlxG.mouse.y);
		super.update(elapsed);
	}
}
```

Now, if you replace Main.hx with this:

```
package;

import openfl.display.Sprite;
import openfl.events.Event;
import openfl.Lib;
import flixel.FlxGame;

class Main extends Sprite 
{
	static public function main():Void
	{	
		Lib.current.addChild(new Main());
	}
	
	public function new() 
	{
		super();
		
		if (stage != null) 
		{
			init();
		}
		else 
		{
			addEventListener(Event.ADDED_TO_STAGE, init);
		}
	}
	
	private function init(?E:Event):Void 
	{
		if (hasEventListener(Event.ADDED_TO_STAGE))
		{
			removeEventListener(Event.ADDED_TO_STAGE, init);
		}
		
		addChild(new FlxGame(640, 480, MenuState, 1, 60, 60, true));
	}
}
```

Then both of those problems go away: you see the mouse position correctly traced, and a white box follows the cursor around.  Furthermore, the problem of the OP goes away.

So, the template needs fixing.  And maybe the docs need updating.  This is what newcomers will experience when trying to start out on their own, if they elect not to take someone else's project and modify it, which I hope is considered an equally legitimate way of learning.  It's step 3 on http://haxeflixel.com/documentation/hello-world-command-line/ and HaxeFlixel markets itself as cross-platform.

**Comment by IBwWG** [comment]
I can also confirm that with haxe 3.2.1 on Linux Mint 17.1 MATE (32-bit), this issue is not present.

**Comment by Gama11** [comment]
>is that FlxG.mouse reports (0,0) no matter where the cursor is

The reason for that is that the docs weren't updated after changing the template to default to the PlayState (https://github.com/HaxeFlixel/flixel-templates/pull/30/files).

**Comment by IBwWG** [comment]
I don't think that's true:

1. flixel-templates' latest release was September and that PR is from October
1. a trace statement wouldn't report anything whatsoever if I weren't in the right state; likewise, changing Main *in such a way that it still points to **Menu**State* would not fix anything

**Comment by Gama11** [comment]
Maybe you're talking about a different issue then, one I can't reproduce. Is that one Linux-specific too?

**Comment by IBwWG** [comment]
I'm having three issues with the template, only on 64-bit Linux (of the three machines I've tried), which all go away when I fix Main.hx as above.  They are:

1. strange mouse movement (OP)
1. FlxG.mouse reporting 0,0 no matter where the flixel cursor is rendered
1. FlxSprite added is not visible

I don't care to investigate them separately, personally.  To me, because the fix is to use the Main.hx template that everybody else uses already, that should be the official template given, until such time as it's not required for such simple things as the above three to work correctly out of the box on all supported platforms.  It's not like the workarounds in the Main.hx above are new and I don't think we need to look at every screw side-effect that occurs when not using them.  Any one of the above three should be enough reason.  I just put them there because the latter two are a bit more concrete, in case they appear e.g. on 32-bit Linux but not the first symptom.

**Comment by IBwWG** [comment]
BTW your wording suggestions you *can* reproduce the first issue @Gama11 , is that correct?

**Comment by Gama11** [comment]
>is that correct?

No, I haven't checked that yet. Not sure if the results in a Virtual Machine would be indicative of much anyway, they tend to be laggy to start with. I don't have a dedicated linux machine.

>which all go away when I fix Main.hx as above.

We removed all this extra `Event.ADDED_TO_STAGE` logic from `Main.hx` because according to @jgranick it's not necessary. OpenFL templates look the same: https://github.com/openfl/openfl-samples/blob/master/features/display/DisplayingABitmap/Source/Main.hx

**Comment by IBwWG** [comment]
Sorry the gif is not great, I should move the mouse slower.  It's not lag.  The mouse snaps to X coordinates that are spaced maybe 80px apart on the left half of the window, and maybe 160px apart on the right--I'm sure you could tell the effect even with lag, were it present for you.

Then he's mistaken, at least on my box.  I can try DisplayingABitmap to be sure, though.  I have compiled that recently and did not notice this bug, but I also wasn't looking.

**Comment by IBwWG** [comment]
Just confirmed, on the box having the flixel issue, DisplayingABitmap (with the same openfl+lime version) does **not** have this bug.  So it's, so far, specific to flixel on 64-bit Linux with haxe 3.4.0.

**Comment by Gama11** [comment]
Well, DisplayingABitmap uses the system cursor, not a Sprite as a cursor like Flixel does. Or are you talking about the other issue?

**Comment by IBwWG** [comment]
The other issues (2 and 3) involving FlxG.mouse coordinates and FlxSprites?  No, not them.  Just the cursor.

So, clearly an issue with flixel that requires a workaround still.  At least on my box...again, feel free to verify (issues 2 and 3 should be very plainly visible, even if you are not convinced you'll notice issue 1 because of lag.)

**Comment by IBwWG** [comment]
Just confirmed, this also happens with neko 2.1.0.  (I hadn't realized haxe 3.4.0 bumped the neko compatibility version.)

**Comment by IBwWG** [comment]
Just confirmed, haxe 3.4.0 + neko 2.1.0 on linux32 (specifically Mint 17.1 MATE) does **not** have any of the above issues.

So it's very specific to neko+cpp on flixel on linux64, although I haven't tried os x.

**Comment by Gama11** [comment]
You said TurnBasedRPG does not have the issue, but it doesn't have the `Event.ADDED_TO_STAGE` logic either: https://github.com/HaxeFlixel/flixel-demos/blob/2.3.0/Tutorials/TurnBasedRPG/source/Main.hx

It just happens to have some other code in there, but I don't see how that could in any way be related...

**Comment by IBwWG** [comment]
Very good catch!  The plot thickens...

OK, I'll try paring down TBRPG and see if I can get it to fail.

**Comment by Gama11** [comment]
So, I just tried reproducing these issues in my Ubuntu 14.04 / 64 bit VM:

- There's no noticable difference between horizonal and vertical mouse movement with the default Main.hx.
- There's no noticable difference in mouse movement between the default Main.hx and the one with Event.ADDED_TO_STAGE either.
- In general, mouse movement is pretty laggy, but that's no surprise when using a non-system cursor in a VM.
- Moving the white box around / tracing the mouse pos works as expected as well: http://i.imgur.com/oUWH4Io.gifv (note: movement is much smoother than the gif might suggest)

This was all tested on Neko.

**Comment by IBwWG** [comment]
Thanks @Gama11 I appreciate your testing efforts.  (Sometimes I feel like a bad tech magnet.  This laptop was given to me fairly new, and I've only installed Linux on it two weeks ago, and tried to go with a fairly popular distro.)  I guess there are two main possibilities:

1. it's specific to my software environment somehow (e.g. 64-bit Mint 18.1 specific?)
1. it's specific to my hardware

...or a combination of the two...

**Comment by IBwWG** [comment]
Wow, this is a doozy.  It's now behaving intermittently.

1. HelloWorld exhibits the problem
1. RPG doesn't, so I modify it, try it, modify it, try it, until as far as Main.hx and MenuState.hx are concerned, they are now identical to HelloWorld, but RPG is still not messing up.  Good, right?  It must be something in the Project.xml or the like, except...
1. Now HelloWorld doesn't exhibit the problem, even though I haven't changed any of its files.

This sequence is pretty bewildering to me.

**Comment by IBwWG** [comment]
Furthermore, now `lime test linux` won't compile HelloWorld anymore:

```
...
 - src/haxe/_Unserializer/DefaultResolver.cpp 
 - src/haxe/Timer.cpp 
Error: ./src/haxe/Unserializer.cpp: In member function ‘Dynamic haxe::Unserializer_obj::unserialize()’:
./src/haxe/Unserializer.cpp:329:79: error: ‘_hx_reslove_virtual_array’ was not declared in this scope
 HXLINE( 281)     return (this->cache->set(cachePos,_hx_reslove_virtual_array(a)));
```

**Comment by Gama11** [comment]
That seems to be the same error as https://github.com/HaxeFoundation/haxe/issues/5983. Is your hxcpp up to date?

**Comment by IBwWG** [comment]
Huh, no--it was 3.4.43.  I had recently updated, but not recently enough.

OK now cpp is not showing this issue anymore...

**Comment by IBwWG** [comment]
OK, cpp shows it for Lars' actions__ branch.  Let's see, maybe cpp is more version-limited.  Or maybe it's just being intermittent again.

**Comment by IBwWG** [comment]
It's interesting that originally I had seen it on 4.0.0 and 4.2.0.  Now it seems to be consistently showing the bug on 4.0.0 and actions__, and not showing it on 4.2.0.

**Comment by Gama11** [comment]
My guess is that the Flixel version is completely unrelated.

**Comment by IBwWG** [comment]
Doesn't seem to be...cpp is now also showing this pattern (although it takes a lot longer to test...)

**Comment by Gama11** [comment]
Are you doing clean builds? If not, you're bound to get weird results after switching versions a lot.

**Comment by IBwWG** [comment]
Nope.  OK, will start to again.

**Comment by IBwWG** [comment]
Although, it does stand to reason, this new pattern, if you look at https://github.com/HaxeFlixel/flixel/releases and https://github.com/larsiusprime/haxeflixel/commits/actions__ .  I.e. you would expect that if it were something that were fixed by 4.2.0 but still broken as of 4.0.0, that actions__ would also have it broken.

**Comment by IBwWG** [comment]
I am now testing with lines like this, on stock `flixel tpl -n "HelloWorld"` from the flixel-templates version before your new release today, 2.1.0:

```
$ haxelib set flixel 4.2.0 && rm -rf export && lime test linux
```
So far, 4.0.0 has the bug.

**Comment by Gama11** [comment]
Fyi, `lime test linux -clean` should to the trick too.

**Comment by IBwWG** [comment]
I know...although I got out of the habit of doing that because on Windows it used to cause FlashDevelop to get stuck once in a while with a file lock on the directory, so to build again I would have to restart FlashDevelop and use LockHunter to clear the file lock, which was annoying.
