### ISSUE TITLE
New haxe version 3.4.0 broke Windows export

### ISSUE THREAD

**Issue by OpmSaitama** [HaxeFlixel/flixel#2036]
- **Flixel version:** 4.1.1
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets: Windows

Haxe 3.4.0 Broke windows export, giving me 9milion errors for some reason: http://pastebin.com/gVAk5Dyp

**Comment by Gama11** [comment]
Please provide more details. How do I reproduce this? Does it happen with a regular Flixel demo or just your project?

Is your hxcpp version up to date?

**Comment by Gama11** [comment]
Taking a closer look at the errors, some of the paths reveal what hcxpp version you're using: `hxcpp/3,3,49/`. 

That version will not be compatible with Haxe 3.4.0, you need to update to the latest version (3.**4**.49).
