### ISSUE TITLE
Feature request for FlxCamera

### ISSUE THREAD

**Issue by xerosugar** [HaxeFlixel/flixel#2038]
I tested the Defold engine a few weeks back and came across this camera shake effect where the shake intensity diminish over time. It looked nice and I thought that this is something that HxFlixel should have as well!

Example: http://britzl.github.io/publicexamples/screen_shake/index.html
Src: https://github.com/britzl/publicexamples/blob/master/examples/screen_shake/baturinsky_shake.script

**Comment by Gama11** [comment]
I think this should be covered by https://github.com/HaxeFlixel/flixel/issues/1030?

**Comment by xerosugar** [comment]
Yeah, that should do it.
