### ISSUE TITLE
Music playback & looping broken when using pause()/resume() on Next

### ISSUE THREAD

**Issue by nospoone** [HaxeFlixel/flixel#2040]
- **Flixel version:** _4.2.0_
- **OpenFL version:** _3.6.1 Next_
- **Lime version:** _2.9.1_
- **Affected targets:** _CPP_ & _Neko_

Wasn't able to test Flash or HTML5.

________________________________

**Code snippet reproducing the issue**:
[The FlxSound demo](https://github.com/HaxeFlixel/flixel-demos/tree/dev/Features/FlxSound).
________________________________

**Observed behavior:**
Start playing music (looping or not) and pause it. The music will cut short and stop (or start its next loop) earlier than expected.

**Expected behavior:**
Pausing/Unpausing shouldn't make the music cut early.

**Comment by Gama11** [comment]
This no longer reproduces with OpenFL 8.
