### ISSUE TITLE
Seg Fault on Ubuntu 16.04 -- Hello World Example

### ISSUE THREAD

**Issue by mgmarlow** [HaxeFlixel/flixel#2042]
- **Haxe version:** 3.4.0
- **Flixel version:** 4.2.0
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Linux version**: Ubuntu 16.04
- **Affected targets:**
Neko, Flash, HTML5
________________________________

I am having trouble running the "Hello World" example provided in the haxeflixel getting started docs.

Configured `flixel-tools` with vscode default. Running through the "Hello World" example (http://haxeflixel.com/documentation/hello-world-command-line/) results in a `segmentation fault (core dumped)` when testing with lime.

Additionally, I tried the example with different versions of the libraries. I downgraded Flixel to 4.0.1, as well as upgraded lime and openfl to their newest versions (even though I know they aren't supported). Nothing solved the issue.

Identical installation process (apart from `apt-get` for Haxe) on Windows 10 resulted in no issues.

Perhaps this issue is related to the package I installed through `apt-get`. I followed the installation instructions, fetching the latest Haxe release (3.4.0) from `ppa:haxe/releases`.

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxG;
import flixel.FlxSprite;
import flixel.FlxState;
import flixel.text.FlxText;
import flixel.ui.FlxButton;
import flixel.math.FlxMath;

class PlayState extends FlxState
{
	override public function create():Void
	{
		super.create();
		add(new FlxText(0, 0, 0, "Hello World!"));
	}

	override public function update(elapsed:Float):Void
	{
		super.update(elapsed);
	}
}

```

```
lime test neko
lime test flash
lime test html5
```
________________________________

**Observed behavior:**
`segmentation fault (core dumped)`

**Expected behavior:**
Window with "Hello World" in the title bar.

**Comment by Gama11** [comment]
Have you tried running one of the OpenFL samples? I mentioned the command needed for that in the forum thread:

http://forum.haxeflixel.com/topic/455/hello-world-seg-fault-on-linux/8

**Comment by mgmarlow** [comment]
@Gama11  Interestingly, running with `openfl test neko` results in the following errors:

```
/usr/lib/haxe/std/haxe/macro/Compiler.hx:312: characters 10-103 : Primitive not found macro@add_global_metadata:5
/usr/lib/haxe/std/haxe/macro/Compiler.hx:293: characters 3-59 : Called from
--macro:1: character 0 : Called from
Aborted
```

`openfl test flash` results in similar errors.

**Comment by Gama11** [comment]
That error seems somewhat familiar... Anyway, to me it suggests that something is wrong with your Haxe install.

**Comment by mgmarlow** [comment]
@Gama11 I downgraded Haxe to `3.2.1` and I can now run the example without issue with flixel `4.2.0`. However, once working, I upgraded Haxe to `3.4.0` to check if there was an installation problem earlier, but I get the same error.

I think you're right about it being a Haxe issue but I wonder if it is specific to the `3.4.0` release. I did some research on the open Haxe issues and perhaps this is related: [haxe 3.4.0 compilation freezing](https://github.com/HaxeFoundation/haxe/issues/5918)? I suppose this particular issue may belong in the Haxe repo instead.

**Comment by Gama11** [comment]
I don't think that particular issue is related, the compiler isn't freezing in your case.

You said you used apt-get for installing Haxe - what if you use the binaries from here? http://haxe.org/download/

**Comment by Gama11** [comment]
Did you have a Haxe installation _before_ installing Haxe 3.4.0? It might not have been removed properly when installing the new Haxe version over it (I recall some issue like that that were fixed by using the install scripts OpenFL provides for Haxe). Leftover standard library files could cause an error like this, for instance.

**Comment by mgmarlow** [comment]
That is very likely, the OpenFL installation scripts were exactly what I used for installing previous versions of Haxe. How would I clear those out/where are the lib files located?

**Comment by Gama11** [comment]
According to the OpenFL install scripts (assuming they use the same location as the ppa install):

/usr/lib/haxe
/usr/lib/neko

You can keep your haxelibs at `/usr/lib/haxe/lib`.

**Comment by mgmarlow** [comment]
Found the solution. This issue was indeed caused by leftover environment variables or files from the OpenFL installation script. Uninstall haxe and ensure that all requisite packages are removed (`sudo apt-get autoremove`). Then reinstall haxe via `apt-get install haxe` with the most up-to-date release from `ppa:haxe/releases`. The sample project now compiles when testing neko with flixel `4.2.0`.
