### ISSUE TITLE
Audio Support in HTML5?

### ISSUE THREAD

**Issue by ashes999** [HaxeFlixel/flixel#2044]
TL;DR: playing `ogg` files doesn't work in HTML5. After reading [this issue](https://github.com/HaxeFlixel/flixel/issues/1597) and [this issue](https://github.com/HaxeFlixel/flixel/pull/1789) about spotty m4a, wav, and OpenFL audio support, I'm even more confused.

What audio file format works consistently against HTML5?

I'm on Flixel 4.2.0 if that matters (upgrading to 4.2.1 now ...)

Update: I can import `openfl.Assets` and use `Assets.getSound('...').play()`. That works fine, on 4.2.1, with `ogg` files. That suffices for me as a work-around.

**Comment by Gama11** [comment]
>That suffices for me as a work-around.

Ok, I'll close here then.

Flixel doesn't really have control over this, this is OpenFL / Lime's job (and I guess for the most part, they too depend on what browsers support in the first place).

**Comment by ashes999** [comment]
@Gama11 I'm not sure why you closed this; FlxSound is broken in HTML5 with `ogg` files. If I can get it working by using OpenFL directly, that means it's not about browsers or OpenFL support -- OpenFL supports it.

Unfortunately, it's very challenging in OpenFL to figure out when a file is finished playing. I really need that functionality, and I don't want to duplicate what Flixel does. It would be really great if someone can fix this.

**Comment by Gama11** [comment]
>If I can get it working by using OpenFL directly [...]

Ah, sorry, wasn't clear to me that it works for you with OpenFL but not Flixel.

**Comment by ashes999** [comment]
Sorry about that.

I did some preliminary investigation and my findings are below.

I normally load sounds by using `FlxG.sound.load("assets/audio/giggle.ogg").play()`. With the HTML5 back-end, that didn't work. `openfl.Assets.getSound(...).play()` works fine.

So I traced from `FlxG.sound` => `SoundFrontEnd.loadEmbedded` => `FlxSound.loadEmbedded` and looked at the method. It very clearly uses `Assets.getSound(...)` when the input parameter is a string.

I can only assume there's something about the `play` function (it calls `startSound`) that's causing this to apparently not work. There is a `FlxSound` sample (#42 at present) which we can probably use to reproduce this minimally.

I hope this helps.

**Comment by Gama11** [comment]
>There is a FlxSound sample (#42 at present) [,,,]

I guess you didn't mean to link to issue 42 there?

**Comment by ashes999** [comment]
Sorry, that's right. I meant the fourty-second template listed under `flixel create`.

**Comment by ashes999** [comment]
@Gama11  I need some help with my PR if you please.

I tracked this down to a difference in `SoundFrontEnd.hx`. In both neko (working) and html5 (broken). With HTML5, `muted` is set to `true` instead of `false`.

In both, there's a call in the private constructor to `loadSavePrefs` in `SoundFrontEnd.hx`.

When I print out the contents of `FlxG.save.data`, I see a difference.  The Neko one is empty (`{}`), while the HTML5 one is `{mute: true, volume: 1}`. This `mute=true` cascades and causes there to be no sound later in `FlxSound` when I try to play.

This is where I get lost; I can see `FLxG.save.data` being assigned to `_sharedObject.data` in `FlxSave.hx`, which is coming from `SharedObject.getLocal(name)`. But I can't understand where this data is actually coming from.

Can you please suggest how I might fix this?

**Comment by ashes999** [comment]
Ugh, I didn't realize this is coming from Local Storage. I deleted my browser stuff (cookies, local storage, etc.) for `localhost` and audio now works fine.

I probably pressed `0` or `m` or something without realizing at some point (maybe for this game, maybe for another one) and didn't realize. The value persists, but I don't know if that's something "fixable."

If someone can verify that they can create a simple HTML5 game which plays an ogg sound and it works fine, I'm good with closing this issue as "user error."

**Comment by Gama11** [comment]
>If someone can verify that they can create a simple HTML5 game which plays an ogg sound and it works fine, I'm good with closing this issue as "user error."

The FlxSound demo plays sound fine for me on HTML5 in Chrome.
