### ISSUE TITLE
Open, close and open persistent FlxSubState from another FlxSubState causes a crash

### ISSUE THREAD

**Issue by guifes** [HaxeFlixel/flixel#2046]
- **Haxe version:** 3.3.0
- **Flixel version:** 2.4.1
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:**: all

**Comment by Gama11** [comment]
Please provide a code example to reproduce.

**Comment by guifes** [comment]
[default.zip](https://github.com/HaxeFlixel/flixel/files/858247/default.zip)

To reproduce, just click the screen to open and close and open the substate again.

**Comment by Gama11** [comment]
Very interesting, Flash doesn't seem to be affected. On neko, it crashes with this stacktrace:

>Invalid field access : draw
Called from flixel.FlxSubState::draw line 70
Called from flixel.FlxState::draw line 73
Called from flixel.FlxSubState::draw line 74
Called from flixel.FlxState::draw line 73
Called from flixel.FlxGame::draw line 854
Called from flixel.FlxGame::onEnterFrame line 551
Called from openfl._legacy.events.EventDispatcher::dispatchEvent line 98
Called from openfl._legacy.display.DisplayObject::__dispatchEvent line 182
Called from openfl._legacy.display.DisplayObject::__broadcast line 161
Called from openfl._legacy.display.DisplayObjectContainer::__broadcast line 286
Called from openfl._legacy.display.Stage::__render line 1103
Called from openfl._legacy.display.Stage::__checkRender line 351
Called from openfl._legacy.display.Stage::__pollTimers line 1084
Called from openfl._legacy.display.Stage::__doProcessStageEvent line 430

Here's the code from the .zip reduced to one module:

```haxe
import flixel.FlxState;
import flixel.FlxSubState;
import flixel.util.FlxColor;
import flixel.FlxG;

class PlayState extends FlxState
{
	override public function create():Void
	{
		openSubState(new SubState(FlxColor.RED));
	}
}

class SubState extends FlxSubState
{
	var state2:SubSubState;

	override public function create():Void
	{
		state2 = new SubSubState(FlxColor.BLUE);
	}
	
	override public function update(elapsed:Float):Void
	{
		super.update(elapsed);
		if (FlxG.mouse.justReleased) openSubState(state2);
	}
}

class SubSubState extends FlxSubState
{
	override public function update(elapsed:Float):Void
	{
		super.update(elapsed);
		if (FlxG.mouse.justReleased) close();
	}
}
```

**Comment by guifes** [comment]
Digging a little deeper I found out that it happens even without the subsubstate:

```haxe
import flixel.FlxState;
import flixel.FlxSubState;
import flixel.util.FlxColor;
import flixel.FlxG;

class PlayState extends FlxState
{
	var state:SubState = new SubState(FlxColor.RED);

	override public function update(elapsed:Float):Void
	{
		super.update(elapsed);
		if (FlxG.mouse.justReleased) openSubState(state);
	}
}

class SubState extends FlxSubState
{	
	override public function update(elapsed:Float):Void
	{
		super.update(elapsed);
		if (FlxG.mouse.justReleased) close();
	}
}
```
What I'm trying to understand now is what is the difference between this code here and the SubState demo in haxeflixel demos... @Gama11 can you check if this case crashes with you as well?

**Comment by guifes** [comment]
Geez, I think I found out. Seems like I need this?

`destroySubStates = false;`

If this is so, you can close the issue, and please explain why is this necessary if you can: :)

**Comment by Gama11** [comment]
Ah, yeah... By default, substates behave the same way as regular states: they are not reused / destroyed when they're closed.

**Comment by guifes** [comment]
Should be interesting to update the api to warn about it:

> destroySubStates:Bool = true
If substates get destroyed when they are closed, setting this to false might reduce state creation time, at greater memory cost.

Could add a warning like, set this to false if you use persistent substates, idk...

**Comment by Gama11** [comment]
I'm not sure if adding a warning to `destroySubStates` really helps, the problem is more finding the flag in the first place, right? :)
