### ISSUE TITLE
FlxG.mouse.overlaps inconsistent with FlxSprite with changing color

### ISSUE THREAD

**Issue by buckle2000** [HaxeFlixel/flixel#2048]
- **Haxe version:** 3.4.2
- **Flixel version:** 4.2.1
- **OpenFL version:** 4.2.0
- **Lime version:** 2.9.1
- **Affected targets:** Flash, Neko, Windows

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxG;
import flixel.FlxSprite;
import flixel.FlxState;
import flixel.util.FlxColor;

class PlayState extends FlxState
{
	var square: FlxSprite;
	
	var iter = FlxColor.colorLookup.iterator();
	
	override public function create():Void
	{
		square = new FlxSprite(0, 0);
		square.makeGraphic(40, 40, FlxColor.TRANSPARENT);
		add(square);
		super.create();
	}

	override public function update(elapsed:Float):Void
	{
		super.update(elapsed);
		
		if (FlxG.mouse.justPressed && FlxG.mouse.overlaps(square)) {
			square.makeGraphic(40, 40, iter.next());
		}
	}
}
```
________________________________

**Observed behavior:**
In windows and neko builds, if you click on the transparent square, it will turn to differrent colors after each click.
However, in flash build, it will only turn white.

**Expected behavior:**
This API should behave the same on different platforms.

**Comment by buckle2000** [comment]
Sorry, I've updated the snippet.

**Comment by Gama11** [comment]
Okay, I can reproduce it now. It's not an issue with `FlxG.mouse.justPressed` or `FlxG.mouse.overlaps()` though, it enters the `if`-condition on each click (easy to see if you add a `trace()` there).

**Comment by buckle2000** [comment]
Eh, I don't know how to see trace message in flash.

**Comment by Gama11** [comment]
You may need to launch the swf with a debugger (not sure what IDE you're using), or just redirect the traces to Flixel's debugger overlay (`FlxG.log.redirectTraces = true`).

Btw, your example also works on Flash if you call `hasNext()` first:

```haxe
if (FlxG.mouse.justPressed && FlxG.mouse.overlaps(square) && iter.hasNext()) {
	square.makeGraphic(40, 40, iter.next());
}
```

Not sure how exactly iterators are specified in Haxe / whether a call to `hasNext()` is mandatory.

**Comment by buckle2000** [comment]
Ha, it's Haxe's fault.

---
On flash platform:
```
FlxG.log.redirectTraces = true;
var map:Map<String, Int> = ["one" => 1, "two" => 5];
var iter = map.iterator();
trace(iter.next()); // 1
trace(iter.next()); // 1
trace(iter.next()); // 1
trace(iter.next()); // 1
```

---
Yet they promise 
> On the other hand, iterators should not require a call to hasNext() before the first call to next() if an element is available.

http://api.haxe.org/Iterator.html
