### ISSUE TITLE
window dimension scaling on high-density screens

### ISSUE THREAD

**Issue by nictaylr** [HaxeFlixel/flixel#2049]
i have surface pro 4, but i have problem with window size scaling

with other tool and framework window size of 1000 will scale to be same size on my screen, actually larger than 1000 but will automatically scale to fit size. kha haxe framework scale correct, much good quality. but with flixel (is openfl problem ? can send me issue, how to resolve ?) window is not scaling and is normal pixel size.

i use [prefer external manifest hack](https://appuals.com/disable-display-scaling-on-high-dpi-devices-in-windows-10/) and it fix scale on the `CPp` build of my project, but can't fix neko, i use for develop game, 

please help thank very much time help!

**Comment by Gama11** [comment]
Yeah, this sort of thing is much more likely to be an OpenFL / Lime issue than one with Flixel.

- Same issue without Flixel? (try testing with one of the openfl-samples projects)
- What about with the most recent OpenFL / Lime versions? (Flixel is stuck on some older ones right now, but perhaps High-DPI support has been improved in the meantime).

**Comment by Tiago-Ling** [comment]
We're having similar problems here, i think it's same problem described: http://community.openfl.org/t/ios-is-there-a-way-to-have-stage-size-in-rendered-pixels-instead-of-points/8899

Basically we can't get the real high-dpi screen size in iPhone and the screen ends up with 667x375 size.

**Comment by Gama11** [comment]
I guess this can be closed, since there is an issue on the OpenFL repo: https://github.com/openfl/openfl/issues/1540

**Comment by nictaylr** [comment]
not to ask too much or give pressure ( after all this open source ), but when is planned flixel work with new openfl? otherwise fix only go to new openfl and we cannot use' i want scaling work better

**Comment by Gama11** [comment]
OpenFL 4 support is a work-in-progress (see #2032), but there's no ETA.

**Comment by 0xFireball** [comment]
For those that are interested, I have a workaround (confirmed to work with CPP on OpenFL legacy and next):

Put this in a file called `YourGame.exe.manifest`, where you replace `YourGame` with your game's executable name, and place this file in the same directory as your CPP build:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0" xmlns:asmv3="urn:schemas-microsoft-com:asm.v3">

<dependency>
  <dependentAssembly>
    <assemblyIdentity
      type="win32"
      name="Microsoft.Windows.Common-Controls"
      version="6.0.0.0" processorArchitecture="*"
      publicKeyToken="6595b64144ccf1df"
      language="*">
    </assemblyIdentity>
  </dependentAssembly>
</dependency>

<dependency>
  <dependentAssembly>
    <assemblyIdentity
      type="win32"
      name="Microsoft.VC90.CRT"
      version="9.0.21022.8"
      processorArchitecture="amd64"
      publicKeyToken="1fc8b3b9a1e18e3b">
    </assemblyIdentity>
  </dependentAssembly>
</dependency>

<trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
  <security>
    <requestedPrivileges>
      <requestedExecutionLevel
        level="asInvoker"
        uiAccess="false"/>
    </requestedPrivileges>
  </security>
</trustInfo>

<asmv3:application>
  <asmv3:windowsSettings xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">
    <ms_windowsSettings:dpiAware xmlns:ms_windowsSettings="http://schemas.microsoft.com/SMI/2005/WindowsSettings">false</ms_windowsSettings:dpiAware>
  </asmv3:windowsSettings>
</asmv3:application>

</assembly>
```
