### ISSUE TITLE
emitter does not emit in sprite

### ISSUE THREAD

**Issue by nictaylr** [HaxeFlixel/flixel#2054]
HF Version: 4.2.1

```haxe
package;

import flixel.*;
import flixel.util.*;
import flixel.effects.particles.*;

class Blob extends FlxSprite {
    private var emitter:FlxEmitter;

    public function new(?X:Float = 0, ?Y:Float = 0) {
        super(X, Y);

        makeGraphic(15, 15, FlxColor.RED);

        emitter = new FlxEmitter();
        emitter.scale.set(2, 2, 8, 8, 12, 12, 12, 12);
		emitter.lifespan.set(0.6, 1.6);
		emitter.color.set(FlxColor.fromRGBFloat(0.0, 0.4, 0.6), FlxColor.fromRGBFloat(0.4, 0.8, 1.0));
		emitter.makeParticles(8, 8, FlxColor.WHITE, 200);
    }

    override public function draw():Void {
		// draw spray below
		emitter.draw();

		super.draw();
	}

    override public function update(elapsed:Float) {
        emitter.x = x + width / 2;
		emitter.y = y + height / 2;

        if (!emitter.emitting) {
            emitter.start(false, 0.01);
        }

        super.update(elapsed);
    }
}
```

I make sprite, then add to simple state, but particles not render at all!

![image](https://cloud.githubusercontent.com/assets/22607541/25366512/fee2b44c-2924-11e7-8308-d7873661edb3.png)

**Comment by seraku24** [comment]
@nictaylr Does adding `emitter.update();` to your `update()` method above make a difference?  In all of the examples I have seen, the `FlxEmitter` object is created and `add()`ed to the `FlxState` object.  As a child of the state, an object will automatically be updated by the game loop.  However, your emitter object is just a private member of the sprite and would most likely need an explicit call for updating.

**Comment by Gama11** [comment]
Yep, emitters need to be updated. Rather than manually doing that, you should probably just call `FlxG.state.add(emitter)`.

**Comment by nictaylr** [comment]
@seraku24 thank you, that solved the problem
