### ISSUE TITLE
FlxPreloader sitelock not triggering anymore

### ISSUE THREAD

**Issue by Gama11** [HaxeFlixel/flixel#2055]
I was trying to force the sitelock failure message to show up to test #1994. The following code should have triggered it, since I was testing locally, and only `foo.com` is allowed:

```xml
<app preloader="CustomPreloader" />
```

```haxe
import flixel.system.FlxBasePreloader;

class CustomPreloader extends FlxBasePreloader {
	public function new() {
		super();
		allowedURLs = ["www.foo.com"];
	}
}
```

I bisected this to 57dc460, before that commit it worked as expected. @seraku24 could you look into this?

**Comment by seraku24** [comment]
@Gama11 Okay, I adjusted the regex so that URL fragments like `www.foo.com` are parsed correctly.  That should permit the usage above.

**Comment by Gama11** [comment]
Ah, so it was just about the missing `http://`? I didn't realize. :)
