### ISSUE TITLE
FlxBasePreloader sitelock link not working without http://

### ISSUE THREAD

**Issue by Gama11** [HaxeFlixel/flixel#2057]
Same code as in #2055, but not a regression this time (at least not compared to 4.2.1).

```haxe
import flixel.system.FlxBasePreloader;

class CustomPreloader extends FlxBasePreloader {
	public function new() {
		super();
		allowedURLs = ["www.foo.com"];
	}
}
```

Clicking the link on the sitelock screen in the standalone Flash Player opens a `file://` URL:

```
file:///<path-to-swf>/www.foo.com
```

The solution is probably to prepend `http://` in this case. @seraku24 thoughts? :)

On HTML5, it's not clickable to begin with, but it's probably OpenFL that's to blame there.

**Comment by seraku24** [comment]
We could probably prepend a missing protocol, though it might be tricky to know what to use.  I'd opt for `https://` these days but we'd not really know if secure transport is valid for the URL.  As such, it might be best to simply document that while URL fragments can be supplied for validating a site, the link that gets displayed will need to be a full URL in order for it to work properly.

**Comment by Gama11** [comment]
It seems there isn't really an elegant solution here, let's just leave it as-is.
