### ISSUE TITLE
Can't compile to native targets: Could not create directory:AppData

### ISSUE THREAD

**Issue by Jarrio** [HaxeFlixel/flixel#2058]
- **Haxe version:** 3.4.2
- **Flixel version:** 4.2.1
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:** [Neko, CPP, I'm assuming all other native targets as well]

________________________________

**Code snippet reproducing the issue**: This happens in a completely blank project `flixel tpl -n "Test"`
________________________________

**Observed behavior:** Compiling to neko or cpp causes the following error message (from first compile)
`Link: ApplicationMain-debug.exe
Creating library ApplicationMain-debug.lib and object ApplicationMain-debug.exp
Could not create directory:AppData
Called from ApplicationMain.main (ApplicationMain.hx line 119)
Called from Type.createInstance (P:\Development\HaxeToolkit\haxe\std/cpp/_std/Type.hx line 83)
Called from DocumentClass.new (ApplicationMain.hx line 217)
Called from Main.new (Main.hx line 10)
Called from openfl._legacy.display.DisplayObjectContainer.addChild (openfl/_legacy/display/DisplayObject
Container.hx line 31)
Called from openfl._legacy.display.DisplayObject.__setParent (openfl/_legacy/display/DisplayObject.hx li
ne 423)
Called from openfl._legacy.display.DisplayObjectContainer.__onAdded (openfl/_legacy/display/DisplayObjec
tContainer.hx line 379)
Called from openfl._legacy.display.DisplayObject.__onAdded (openfl/_legacy/display/DisplayObject.hx line
 362)
Called from openfl._legacy.display.DisplayObject.dispatchEvent (openfl/_legacy/display/DisplayObject.hx
line 70)
Called from openfl._legacy.display.DisplayObject.__dispatchEvent (openfl/_legacy/display/DisplayObject.h
x line 182)
Called from openfl._legacy.events.EventDispatcher.dispatchEvent (openfl/_legacy/events/EventDispatcher.h
x line 98)
Called from flixel.FlxGame.create (flixel/FlxGame.hx line 321)
Called from flixel.system.debug.FlxDebugger.new (flixel/system/debug/FlxDebugger.hx line 141)
Called from flixel.system.debug.log.Log.new (flixel/system/debug/log/Log.hx line 24)
Called from flixel.system.debug.Window.new (flixel/system/debug/Window.hx line 149)
Called from flixel.system.debug.Window.loadSaveData (flixel/system/debug/Window.hx line 287)
Called from flixel.system.debug.Window.initSaveData (flixel/system/debug/Window.hx line 300)
Called from flixel.util.FlxSave.flush (flixel/util/FlxSave.hx line 108)`

I have checked the `AppData` folder at `C:\Users\Me\AppData` and I have full folder permissions (windows 10) and don't have any issues with any other application. I have tried reinstalling haxe (upgraded from 3.4.1 -> 3.4.2) with no difference. Reinstalled hxcpp and flixel with no change as well.

**Comment by Gama11** [comment]
`Called from flixel.system.debug.FlxDebugger.new` - so does release mode work?

**Comment by Gama11** [comment]
Btw, line 108 in `FlxSave` is already wrapped in a try-catch - perhaps we need a catch-all there (`Dynamic` instead of `Error`)?  Can you check if that helps to at least prevent the crash?

https://github.com/HaxeFlixel/flixel/blob/4.2.1/flixel/util/FlxSave.hx#L108

**Comment by Jarrio** [comment]
Release mode compiles fine. However changing that line to `Dynamic` made no difference

**Comment by Gama11** [comment]
I guess the exception can't be caught then? Does OpenFL Next have the same problem?

**Comment by Jarrio** [comment]
Oh nice! I can compile to debug mode for openfl next on both of the platforms. This will serve as a nice solution for me, although I'm still not sure what's the root cause of the problem

**Comment by Jarrio** [comment]
Okay I think I might have figured out a clue to this issue. I just tried to run a compiled exe sent to me in haxeflixel and when I went to open it I got the following error: 
![image](https://cloud.githubusercontent.com/assets/748557/25549588/a6382928-2c6a-11e7-87fc-f937a763b4d1.png)

This is odd to me because I have a symbolic link setup from the default `C:\Users\Me\AppData` and it works for my other programs. Why is flixel having an issue with it here?

**Comment by Gama11** [comment]
The issue is probably with OpenFL's SharedObject, not Flixel.

**Comment by Jarrio** [comment]
This issue seems to be due to using symbolic links on the `AppData` directory. A workaround for this in the meantime is to compile to `-Dnext` once to get haxeflixel to create the save directory and file in the AppData folder and then you can go back to compiling to regular haxeflixel if you don't need/want to compile to -Dnext

**Comment by Gama11** [comment]
Considering this worked with `-Dnext`, this is very likely no longer an issue with OpenFL 8 either.
