### ISSUE TITLE
FlxEmitter very broken when lifespan = 0

### ISSUE THREAD

**Issue by JoeCreates** [HaxeFlixel/flixel#2072]
Presently `FlxEmitter` breaks if you set the lifespan of the emitter to 0, which is meant to be allowed for custom means of killing particles (e.g. when they move outside of some bounds).

To reproduce, make a square emitter, set lifespan to 0, set the velocity range to something...
```haxe
var emitter = new FlxEmitter();
emitter.lifespan.set(0);
emitter.launchMode = FlxEmitterMode.SQUARE;
emitter.velocity.set(-30, 100, -20, 150);
emitter.start(false, 0.1);
add(emitter);
```

This is an issue for any range property of an emitter, not just velocity. If you wish to randomise the velocity starts, the emitters velocity must be active. If it is active, both the start and the end of the particles range and randomised. Because the end is different to the start, this sets the particles velocitRange.active to true. This in turn means update tries to interpolate in this range based on `life / lifespan` or `dt / lifespan`. When lifespan is 0, this results in lots of unwanted NaNs.

**Comment by Beeblerox** [comment]
@JoeCreates your changes seems ok to me. would you create PR then?

**Comment by JoeCreates** [comment]
@beeblerox Oops, sorry. I thought I already had. xD

**Comment by Gama11** [comment]
Some unit tests would be nice.
