### ISSUE TITLE
HL Target Support?

### ISSUE THREAD

**Issue by ashes999** [HaxeFlixel/flixel#2077]
Hi,

Are there any plans to support the new(ish) HL target with Lime?  

From what I can gather, this is an improved replacement for Neko, which is still much faster than building against HTML5. (I asked a similar question for OpenFL [here](https://github.com/openfl/openfl/issues/1588).

**Comment by Gama11** [comment]
We depend on Lime for this, see https://github.com/openfl/lime/issues/979.
