### ISSUE TITLE
Error: process_run with eval

### ISSUE THREAD

**Issue by DleanJeans** [HaxeFlixel/flixel#2078]
- **Haxe version:** [614b588](https://github.com/HaxeFoundation/haxe/commit/614b588ea102339d4df47dbf9738e09a44d7daba)
- **Flixel version:** 4.2.1
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:** all (?)
________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxState;

class PlayState extends FlxState
{
	override public function create():Void
	{
		// insert your code here
	}
}
```
Yep, a template project
________________________________

**Observed behavior:** `Error: process_run`

**Expected behavior:** buildable just like other Haxe and OpenFl projects

**Comment by Gama11** [comment]
Travis builds Haxe dev just fine: https://travis-ci.org/HaxeFlixel/flixel/builds/239339404 I also can't reproduce this locally (even if I switch from Flixel dev to 4.2.1).

What command are you running exactly? Fails on e.g. just `lime build neko`? Or at runtime (`lime test neko`)?

**Comment by Gama11** [comment]
Hm, I think I now what's going on.. You don't have `git` in your path (which `FlxGitSHA` tries to run)... I guess this is not try-catchable in eval atm.

**Comment by Gama11** [comment]
Reported to Haxe: https://github.com/HaxeFoundation/haxe/issues/6333
