### ISSUE TITLE
Game Shutdown Event - Beyond Mobile Only

### ISSUE THREAD

**Issue by ashes999** [HaxeFlixel/flixel#2081]
I [asked a while back](https://github.com/HaxeFlixel/flixel/issues/1408) about a global shutdown event that I can use to "plug in" analytics stop/shutdown events. `onFocusLost` works well on Flash and mobile, but apparently not on `neko` (and I worry about the `cpp` target) and maybe not html5 either.

Is there any other event or method I can use to trap shutdown and execute some code on desktop platforms, and `neko`?

I also tried overriding `destroy` on my `FlxState` instance, but that didn't work either.

**Comment by Gama11** [comment]
This seems lower-level than Flixel, if there is anything, it's probably somewhere in OpenFL or Lime.

**Comment by Gama11** [comment]
Seems like this was answered here: http://community.openfl.org/t/game-shutdown-event/9223

**Comment by ashes999** [comment]
@Gama11 is this something worth exposing on HaxeFlixel somewhere as an event to hook into?

**Comment by Gama11** [comment]
There's nothing to "expose" really, you can access the event just like you normally would if you were only using Lime or OpenFL. You can access the `stage` instance via `FlxG.stage`.

**Comment by ashes999** [comment]
I would like to consider re-opening this issue. As mentioned on that thread, the suggested solution only works with recent-ish versions of OpenFL; HaxeFlixel uses 3.6.1, which doesn't support `application.onExit`.  Hence, I ask: can we update the version of OpenFL we use in HaxeFlixel?

**Comment by Gama11** [comment]
No, not until #2068 is finished.

**Comment by Tiago-Ling** [comment]
@ashes999 Did you try `Event.DEACTIVATE` ? It's a long shot, but it's available in 3.6.1 and may help / solve your problem?

**Comment by ashes999** [comment]
@Tiago-Ling that works on Neko but not on HTML5. Thanks, that at least fixes part of my problem.

**Comment by Tiago-Ling** [comment]
@ashes999 Take a look at `openfl.events.Event`, there might be another one which works for HTML5.

Quickly looking through the list, some obvious candidates would be `Event.CLOSE` and `Event.UNLOAD`. Not sure if they are gonna work though. Good luck!

**Comment by ashes999** [comment]
@Tiago-Ling that's a great suggestion.

I just tried pretty much all the events and none of them seem to work on HTML5 when you close your tab/window in Chrome. That makes sense; the browser probably just terminates processes/threads and moves on.

I will work around this by doing things on a timer interval. It's not ideal, but it'll do.  Thanks for your suggestion.

**Comment by Tiago-Ling** [comment]
You can also check how it's done in newer versions of OpenFL and manually implement in your local copy of the library. I've had to do that some times in my current projects, for cases in which the functionality wasn't implemented yet (Lib.getURL on mobile being the latest).
