### ISSUE TITLE
Proper CLICK event (and more?)

### ISSUE THREAD

**Issue by MSGhero** [HaxeFlixel/flixel#2085]
`FlxMouseEventManager` handles `DOWN`, `UP`, `OVER`, and `OUT`, but not `CLICK` and its variants or `MOVE`. Should it have callbacks for these others too? `CLICK` is probably a `DOWN` and `UP` on the same object, and `MOVE` is maybe `OVER` + move.

Then what about all the variants of `MIDDLE` and `RIGHT` having callbacks? I personally think no.

Main use case is haxeui expecting `CLICK`, `MOVE`, and `WHEEL` to be handled. I've been overloading `UP`'s handler with `CLICK`, but I'm not sure how good of a solution that is in general.

**Comment by SeiferTim** [comment]
Typically, you handle "click" with `justReleased`...
I don't think there's a need for a unique 'click'...

**Comment by MSGhero** [comment]
If you need a `CLICK` callback to interface with another library, `justReleased` won't help you. `justReleased` is also only `UP` and not `CLICK` and doesn't give you any information about what was just released.

**Comment by MSGhero** [comment]
Jotting down notes for whenever:

`CLICK`: Will need to add `_mouseDownObjects` array that gets populated in the `DOWN` section if a `CLICK` handler exists. The moment the mouse button is released, no matter where on the screen (see if offscreen release is detected), `_mouseDownObjects` should be cleared. Multiple mouse buttons screws that up, but as long as we're only interested in LMB clicks, MMB and RMB can just be ignored. Then on `UP` if `CLICK` exists, see if the object has a register in `_mouseDownObjects`, and if so, handle `CLICK`.

`MOVE`: for each register in `_mouseOverObjects` if `MOVE` exists and if the mouse moved, handle `MOVE`. Maybe put `justMoved:Bool` in `FlxMouse/Pointer` or maybe it already exists, idk.

`WHEEL`: for each register in `_mouseOverObjects` if `WHEEL` exists and if `cursor.wheel` is nonzero, handle `WHEEL`.
