### ISSUE TITLE
Zoom <= 0?

### ISSUE THREAD

**Issue by ashes999** [HaxeFlixel/flixel#2088]
Hi,

I just wasted a day yesterday trying to figure out why nothing appears on screen. Turns out in my zeal to turn off the HaxeFlixel splash screen, I accidentally entered a zoom value of `0`.

And just nothing renders.

Checking other issues, it looks like zooms that are less than one are meaningful. But what about a zoom of zero or less? Doesn't it make sense to throw an exception here? (Is there a reason HaxeFlixel doesn't already do this?)

**Comment by JoeCreates** [comment]
Er... what is a zoom less than 0 supposed to mean? Perhaps you saw somebody refer to negative zoom which actually refers to something between 0 and 1. That is, you are scaling down rather than up.

**Comment by Gama11** [comment]
I don't think we should arbitrarily disallow this. For instance, you might want to tween the camera's `zoom` to 0 as a state transition effect (zooming out until nothing shows anymore).

**Comment by ashes999** [comment]
What about not allowing zero in the `FlxGame` constructor?

If this is a valid use case (eg. zoom in to start your game ... ?), maybe we can allow zooms of `0.000001` or something like that, so we know for sure the user didn't make an error?

**Comment by Gama11** [comment]
So suddenly we're forcing people to use weird hacks (zoom values of 0.000001) just because we think it might prevent some errors? I really doubt this would help as much as you think...

**Comment by ashes999** [comment]
Okay, no problem. Thanks for the feedback.

**Comment by ashes999** [comment]
Final suggestion: can we move the "disable haxeflixel splash" parameter before the zoom parameter in FlxGame's constructor?

**Comment by Gama11** [comment]
No, changing the paramter order would break a lot of code for no good reason...

**Comment by ashes999** [comment]
@Gama11 let's agree to disagree. Again, my goal was to remove the HaxeFlixel splash screen; in doing so, you can say I made a noob mistake (setting zoom to zero). I wasted about an hour, flailing about, until I figured it out.

I see options to prevent others from going through this:

- Disallow a zoom of zero in the FlxGame constructor
- Shuffle the parameters so that zoom is after the one to disable the HaxeFlixel splash screen
- Disable the splash screen by default

I understand that you find none of these suitable. No problem.
