### ISSUE TITLE
Possible `FlxTilemapExt` Slope Fix

### ISSUE THREAD

**Issue by SeiferTim** [HaxeFlixel/flixel#2091]
**Issue:**

While working with `FlxTilemapExt` and slopes for a 2-D platformer, I encountered an issue where my objects would not 'stick' to the slopes properly. While moving horizontally, if I encountered an upward slope, the object would 'stutter' and 'catch' on the sides of the slope instead of moving smoothly up it.
And, if it encountered a downward slope, it would overshoot, fly over the slope, and land further down.

![slopes](https://user-images.githubusercontent.com/141478/28219849-0b87a354-6883-11e7-9878-849e9f7aa2cd.gif)

Digging into `FlxTilemapExt`, I found a solution that works for me, and, I'm not sure if it's a fix that would help everyone else, as well.

There are two functions that handle checking floor slopes: `solveCollisionSlopeNorthwest` and `solveCollisionSlopeNortheast`

They do a bunch of stuff like: check if the colliding object is actually inside a slope, what kind of slope, and, given the colliding point on the object, what y position would that object be colliding at, etc.
But, at the end of the function it does something like this:

```
if (_objPoint.x > Slope.x + _snapping && _objPoint.x < Slope.x + _tileWidth + Object.width + _snapping && _objPoint.y >= _slopePoint.y && _objPoint.y <= Slope.y + _tileHeight)
{
	// Call the collide function for the floor slope
	onCollideFloorSlope(Slope, Object);
}
```
Which basically says: If the object is actually inside where the slope would be, then trigger `onCollideFloorSlope`, which moves the object to the correct y position, and sets the `touching` flag, etc.

It seems like this check not only causes the excessive 'stuttering' when moving up the slope, but also does nothing for the object that is 'overshooting' the slope - it won't pull it down to snap to the slope.

The fix, I changed the `if` statement to just see if the object's velocity.y is positive:

```
if (Object.velocity.y > 0)
{
	onCollideFloorSlope(Slope, Object);
}
```

This means that anytime the object overlaps a slope at all, unless they are jumping of otherwise trying to move away from the slope, we adjust the object's y position to 'snap' to the slope.

**Comment by SeiferTim** [comment]
This is what I get with the fix:

![slopes-3](https://user-images.githubusercontent.com/141478/28220232-5327852a-6884-11e7-9ea5-4630b0ab1194.gif)

**Comment by Gama11** [comment]
Wrong repo, `FlxTilemapExt` is in flixel-addons.

**Comment by RichardBray** [comment]
@SeiferTim Is there a way to implement this fix without adjusting Flixel source code?
