### ISSUE TITLE
Tasks.Json needs update for latest VScode release

### ISSUE THREAD

**Issue by dumasymptote** [HaxeFlixel/flixel#2092]
- **Haxe version:** ?.?.?
- **Flixel version:** 4.2.1
- **OpenFL version:** ?.?.?
- **Lime version:** ?.?.?
- **Affected targets:**
visual studio code
________________________________
/*old style 
{
			"taskName": "html5 debug",
			"suppressTaskName": true,
			"args": ["test", "html5", "-debug"],
			"isBuildCommand": true,
			"problemMatcher": "$haxe"
		}
*/

isBuildCommand has been deprecated in the VScode tasks setup. It should be replaced with a group property as such (I think...)
            "group": {
                "kind": "build",
                "isDefault": true
            }

This is from the recent 1.14 update of vscode

https://code.visualstudio.com/updates/v1_14#_tasks

**Comment by Gama11** [comment]
Yep, this has been on my Todo-list.. Thanks for the reminder though!

Btw, for the future, the correct place to report is https://github.com/HaxeFlixel/flixel-templates.

**Comment by Gama11** [comment]
Alright, flixel-templates 2.4.3 fixes this: https://github.com/HaxeFlixel/flixel-templates/commit/0393e48e0ca8977bc66e189c903c2b2791f07ccf

**Comment by dumasymptote** [comment]
Sorry for putting the report in the wrong place but thank you for the quick resolution!
