### ISSUE TITLE
Broken cameras in Mode since camera zoom fix

### ISSUE THREAD

**Issue by Gama11** [HaxeFlixel/flixel#2097]
Since https://github.com/HaxeFlixel/flixel/commit/cbc92690781aab49ac8804dd1f4c1ff020bdec07 / #2003, the cameras in the top left of Mode are broken on the HTML5 target:

![](http://i.imgur.com/j6cErrU.png)

What they should look like:

![](http://i.imgur.com/RgDfRfs.png)

@Beeblerox Any ideas?

**Comment by Beeblerox** [comment]
will look into this. But this is strange, why only on html5 target?!

**Comment by Gama11** [comment]
Actually, looks like it's Flash too. So a RENDER_BLIT issue I guess.

**Comment by Beeblerox** [comment]
that's make things simpler to investigate :)
