### ISSUE TITLE
Calling FlxObject.setPosition() causes invalid result from FlxG.overlap()

### ISSUE THREAD

**Issue by Poobslag** [HaxeFlixel/flixel#2100]
- **Haxe version:** 3.4.0
- **Flixel version:** 4.2.1
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
________________________________

**Code snippet reproducing the issue**:

```haxe
package;
import flixel.FlxG;
import flixel.FlxSprite;
import flixel.FlxState;

class WeirdThing extends FlxState
{
	override public function create():Void
	{
		var _rect = new FlxSprite(59, 3);
		_rect.makeGraphic(248, 426);
		
		var _dot:FlxSprite = new FlxSprite();
		_dot.makeGraphic(1, 1);
		_dot.setPosition(354, 186);
		
		trace("rect hitbox: " + _rect.getHitbox());
		trace("dot hitbox: " + _dot.getHitbox());
		trace("FlxG.overlap: " + FlxG.overlap(_dot, _rect));
	}
}
```

________________________________

**Observed behavior:**
WeirdThing.hx:17: rect hitbox: (x: 59 | y: 3 | w: 248 | h: 426)
WeirdThing.hx:18: dot hitbox: (x: 354 | y: 186 | w: 1 | h: 1)
WeirdThing.hx:19: FlxG.overlap: true

The two objects are incorrectly reported as overlapping. This is because calling FlxSprite.setPosition() does not update FlxObject's internal "last" coordinate, which is used for hit detection.

**Expected behavior:**
Objects should not be reported as overlapping.

**Comment by Gama11** [comment]
`setPosition()` is just a convenience method around `x` and `y`, so it won't update `last`.
