### ISSUE TITLE
Parent reference + ADDED_TO_STATE

### ISSUE THREAD

**Issue by MSGhero** [HaxeFlixel/flixel#2104]
Discussion.

I'm really needing an `ADDED_TO_STAGE` parallel for HaxeUI. Like an `addedToState` `FlxSignal` or something. I don't see a way of implementing that without giving sprites a `parent` reference.

### Implementation:
`private var parent(default, set):`
1. `FlxSpriteGroup` in FlxSprite.hx
2. `FlxGroup` in FlxBasic.hx
3. `FlxBasic` in FlxBasic.hx
4. `IFlxGroup` or abstract multitype `FlxParent` in FlxSprite.hx

### Notes
1. I don't like the idea of restricting `parent` to FSG only.
2. If the intended parent is a FSG, `parent` would actually be `fsg.group`.
3. I don't see a good reason to use the common superclass `FlxBasic`
4. ???

### Implications:
- Local/global relationship of child properties changes (solves #1353, adds breaking changes)
- A sprite can only have one parent, which is breaking
- `push`ing directly to the `members` array would not set the `parent` reference
- Acknowledging `FlxSpriteGroup` as something other than a hack 😜 

### My conclusions
For `ADDED_TO_STATE`, I don't really care what the type of `parent` is, as long as `this.parent.parent.parent...` eventually gives me `null` or a `FlxState`.

Another option is to just keep the `parent` reference but not do anything with it. So the local/global relationship of FSG and children isn't touched, except maybe when changing `alpha`. This is the least breaking option.

**Comment by Jarrio** [comment]
Could adding built in an internal `FlxSignal` for `addedToStage` not work for this?

**Comment by MSGhero** [comment]
Omg I didn't make that clear. I want `ADDED_TO_STATE` to be a `FlxSignal` 😀 But I think the only way of telling if an object has actually been added to the state (for the event to dispatch internally) is with a parent reference.

**Comment by Gama11** [comment]
I don't think parents are a thing you can really have in Flixel. You are supposed to be able to add sprites to multiple groups. Several demos use this "meta group" (groups that are never added) technique for collisions:

https://github.com/HaxeFlixel/flixel-demos/blob/7494abc20b7de1bddb1fdbeb76c8934b111e1f4e/Platformers/Mode/source/PlayState.hx#L119-L131

**Comment by MSGhero** [comment]
So I think that's a good reason for `parent` to just be a reference and not actually do anything. Each sprite could only have one `parent`, but it could still be added to multiple groups. It wouldn't be like Flash where `parent.removeChild()` gets called when you try to double add. 

Can you think of any alternatives where `addedToState` could be dispatched? I'm not attached to the `parent` idea.

**Comment by JoeCreates** [comment]
It should be dispatched in FlxState#add, surely? I see no reason why parent
would be required.

**Comment by MSGhero** [comment]
@JoeCreates Subchildren of the FlxState's children should also dispatch the event, the same as Flash's `ADDED_TO_STAGE`.

**Comment by MSGhero** [comment]
Another reasonable option for HaxeUI would be to give FlxSprite an `onAdded(parent:FSG)` empty function that could be overridden. That's less complete but more reasonable of a change I think.

**Comment by Gama11** [comment]
I don't really like the idea of `FlxSprite` knowing about `FlxSpriteGroup`...

**Comment by Jarrio** [comment]
What about having a signal dispatched in all `add()` calls which can then be typed as `FlxTypedSignal<FlxTypedGroup<T>>` and you could even pass the sprite with that? Eg: `FlxTypedSignal<FlxTypedGroup<T>>,  T>`.

**Comment by MSGhero** [comment]
@Gama11 What about if it was typed FlxGroup instead?

The main issue I'm trying to solve is that the UI needs to know when it's been added to the UI container. So `myFSG.add(theWholeUI);` should tell the UI it's been added. It'd be nice if it also knew `myFSG` was added to the current state, but that's not suuuper essential.

Right now, it knows it's been added if `draw()` gets called, but there's the time between `add` and `draw` that the UI hasn't been validated. Any property access in that time will give incorrect values.

**Comment by Jarrio** [comment]
@MSGhero For this to not require any custom states from the users it would need to be an internal event.

**Comment by MSGhero** [comment]
@Jarrio ok, I looked over signals some more. I like the idea of `FlxTypedSignal<FlxTypedGroup<T>, T>`, and I guess it would have to be `addedToGroup` instead of `addedToState`.

When you say "internal event," do you mean that the user would not be able to register callbacks to it? Or do you mean that it could be `public var addedToGroup(default, null):FlxTypedSignal<FlxTypedGroup<T>, T>` in FlxTypedGroup? And `removedFromGroup` for parity, I guess.

**Comment by MSGhero** [comment]
@Gama11 if I did make a PR, would an `addedToGroup` signal be best in FSG or FlxGroup?

**Comment by Gama11** [comment]
I guess that depends on what that brings with it - parent references or whatnot...

**Comment by MSGhero** [comment]
Let's say no parent references since they're largely incompatible with the rest of flixel.

**Comment by MSGhero** [comment]
I have changes but no wifi, so I'll leave a note here so I don't forget to bring it up...

Should signals be dispatched in
- `recycle` when `revive` is called
- `clear`, and before or after actually deleting members
- `set_maxSize` when shrinking the max size

?

**Comment by Gama11** [comment]
Weren't we talking about an `added` signal? Since you're talking about deleting members / shrinking groups, would there be a `removed` signal as well?

**Comment by MSGhero** [comment]
Oh yeah, I decided to add `removedFromGroup` just to have both there.

**Comment by MSGhero** [comment]
I'm gonna close this since it's largely at odds with flixel's structure. I got what I needed to make HaxeUI work out of the add and remove signals.
