### ISSUE TITLE
visible viewport area

### ISSUE THREAD

**Issue by man2** [HaxeFlixel/flixel#2105]
- **Haxe version:** 3.4.2
- **Flixel version:** 4.3.0
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets: all

________________________________

**Code snippet reproducing the issue**:

```haxe
var visibleSize:Point = new Point();
	visibleSize.x = FlxG.camera.width * FlxG.camera.totalScaleX;
	visibleSize.y = FlxG.camera.height * FlxG.camera.totalScaleY;

	var visibleOrigin:Point = new Point();
	visibleOrigin.x = (Math.abs(visibleSize.x - Lib.current.stage.stageWidth ) / 2) / FlxG.camera.totalScaleX;
	visibleOrigin.y = (Math.abs(visibleSize.y - Lib.current.stage.stageHeight ) / 2) / FlxG.camera.totalScaleY;
```

________________________________

This is the code to add visible area for scaled viewport using ScaleMode  RATIO_FILL_SCREEN and FILL

**Comment by Gama11** [comment]
I'm not sure what you're reporting here... Do you want this to be added to Flixel?

**Comment by man2** [comment]
yes, sorry, I don't know if it's going to be useful for anyone. maybe I will just close this

**Comment by Gama11** [comment]
Just wasn't totally clear to me that this was a feature suggestion, as it looks more like a bug report with the issue template. ;)

**Comment by man2** [comment]
yes, apologies for not being clear on this :) But I would find this very nice feature to have for mobile development.
