### ISSUE TITLE
'system': not available on iOS with XCode 9.0

### ISSUE THREAD

**Issue by besserwisser** [HaxeFlixel/flixel#2112]
- **Haxe version:** 3.4.2
- **Flixel version:** 4.3.0
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:** iOS

________________________________

**Command line message**:

When running "lime build ios"

```
Error: /usr/local/lib/haxe/lib/hxcpp/3,4,64/src/hx/libs/std/Sys.cpp:271:17: error: call to unavailable function 'system': not available on iOS
   int result = system(cmd.__s);
                ^~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk/usr/include/stdlib.h:195:6: note: candidate function has been explicitly made unavailable
int      system(const char *) __DARWIN_ALIAS_C(system);
         ^
1 error generated.
make: *** [build-haxe-armv7] Error 1

** BUILD FAILED **


The following build commands failed:
        ExternalBuildToolExecution Build\ Haxe
(1 failure)                   
```

________________________________

**Observed behavior:**

I cannot compile to iOS anymore after deleting the export folder and updating XCode to Version 9.0. I was able to compile it before I deleted the export folder, when I remember correctly. 

**Expected behavior:**

Compilation works without errors like it did before.

**Comment by alanlanglois** [comment]
Have the same pb. I could compile before I updated XCode (and MacOS) to its last version. 
Is there anything new on this?

**Comment by besserwisser** [comment]
@alanlanglois I downgraded to XCode 8 for this project. But my colleague suggested, that you should backup the iPhoneOS10.3.sdk folder as long as XCode 8 is installed. Then install XCode 9 and copy the folder back to the XCode folder. I have not tried that though. You find the folder I am speaking of, when you click right on the Xcode.app and then on "Show package contents". Then navigate to Contents -> Developer -> Platforms -> iPhoneOS.platform -> Developer -> SDKs

**Comment by alanlanglois** [comment]
@besserwisser thx!
There is actually a proper way to fix it (in my case it worked)
http://community.openfl.org/t/solved-system-not-available-on-ios-with-xcode-9-0/9683/2

**Comment by Tembac** [comment]
Maybe this is related to the problem I'm having to build for Mac ?

http://forum.haxeflixel.com/topic/672/mac-os-builds-are-crashing

**Comment by besserwisser** [comment]
Okay, I hat to update to XCode 9, because I updated my iPhone to iOS11. The fix I proposed (Copying the Xcode Libraries from 8 to 9) did not work. 

@alanlanglois Your fix worked for me! Thank you very much. Would be nice, if flixel would use the current hxcpp version, in which the fix is included
