### ISSUE TITLE
Tinting on WebGL does not work correctly

### ISSUE THREAD

**Issue by besserwisser** [HaxeFlixel/flixel#2113]
- **Haxe version:** 3.4.2
- **Flixel version:** 4.3.0
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:** html5

________________________________

**Command line**:

```
lime build html5 -Dwebgl              
```

**Code**
```
el.color = FlxColor.fromString("#e1071a");;
```
________________________________

**Observed behavior:**

It tints the white Bitmap Font to a blue:
http://fs5.directupload.net/images/170929/6neusjj2.png

**Expected behavior:**

Tinting it to a red color like here, when I run "lime build html5" with the webgl flag. But the webgl flag is essential for performance...:
http://fs5.directupload.net/images/170929/e66b9ols.png

**Comment by MSGhero** [comment]
This seems like something that has been fixed already on the OpenFL/Lime side, as it doesn't seem like a flixel issue. Try following #2068 using later versions of the libraries and see if the issue goes away.

**Comment by Gama11** [comment]
What @MSGhero said. We should have OpenFL 8 support soon via #2136.
