### ISSUE TITLE
FlxPreRotated animation: if Value is NaN, triggers major performance issue

### ISSUE THREAD

**Issue by larsiusprime** [HaxeFlixel/flixel#2115]
https://github.com/HaxeFlixel/flixel/blob/29a545d47410bda82a7e4e0e3c55c807e0da549d/flixel/animation/FlxPrerotatedAnimation.hx#L27

See also:
https://twitter.com/larsiusprime/status/922579427208388614

Basically, if a NaN value gets fed in somehow, it will get hard cast to an integer value of -2147483648, and then it will add 360 to that until it's greater than 0, which will take about 6 million iterations to complete.

Just to make sure, I tested this by throwing in a Math.isNaN() check on Value and then clamping it to something like 0 if true but I expect we need a cleaner solution for production.

**Comment by MSGhero** [comment]
Should it throw an error? Acknowledging NaN means that we're saying it's a valid input to this setter.

Then again, `atan()` has funky returns and could easily be used with this setter. Theoretically, if `NEG_INFINITY` wasn't handled by the internal algebra, it would go on "forever."

**Comment by larsiusprime** [comment]
Yeah I'm not sure, At the very least should be a warning in the doc header maybe?

That's also exactly how I got this -- I was feeding it data from atan().

**Comment by larsiusprime** [comment]
Is there any cost associated with Math.isNaN() ? And even if not, is it wise to shunt NaN to zero in all cases? Is there some edge case we're not thinking of? I think you're right that it's invalid input and we should maybe put this on the user to be careful of. If checking for isNaN() is cheap, then I would rather throw an error than silently "fix" it -- if some part of the user's pipeline is feeding NaN into this function, that could cause other problems, and they should know about it as soon as possible.

**Comment by MSGhero** [comment]
We should make atan() illegal. Infinity and neg infinity are valid inputs to atan, so I think only weird inputs give you weird outputs, ie 0/0 or NaN or whatever inf/inf equals. Only 0/0 is practical for the kinds of angle-of-a-point stuff atan is used for. 

My instinct is to say there’s no performance cost, but that should be checked for sure.

**Comment by Gama11** [comment]
Interestingly, this only seems to be an issue on CPP targets, but not Neko. Anyway, nice catch, it's now throwing an exception:

```haxe
package;

import flixel.FlxState;
import flixel.FlxSprite;
import flixel.animation.FlxPrerotatedAnimation;

class PlayState extends FlxState
{
    override public function create():Void
    {
        var sprite = new FlxSprite();
        var animation = new FlxPrerotatedAnimation(sprite.animation, 10);
        animation.angle = Math.NaN;
    }
}
```

```
angle must not be NaN
Called from ApplicationMain.main (ApplicationMain.hx line 119)
Called from Type.createInstance (C:\HaxeToolkit\haxe\std/cpp/_std/Type.hx line 83)
Called from DocumentClass.new (ApplicationMain.hx line 217)
Called from Main.new (Main.hx line 11)
Called from openfl._legacy.display.DisplayObjectContainer.addChild (openfl/_legacy/display/DisplayObjectContainer.hx line 31)
Called from openfl._legacy.display.DisplayObject.__setParent (openfl/_legacy/display/DisplayObject.hx line 423)
Called from openfl._legacy.display.DisplayObjectContainer.__onAdded (openfl/_legacy/display/DisplayObjectContainer.hx line 379)
Called from openfl._legacy.display.DisplayObject.__onAdded (openfl/_legacy/display/DisplayObject.hx line 362)
Called from openfl._legacy.display.DisplayObject.dispatchEvent (openfl/_legacy/display/DisplayObject.hx line 70)
Called from openfl._legacy.display.DisplayObject.__dispatchEvent (openfl/_legacy/display/DisplayObject.hx line 182)
Called from openfl._legacy.events.EventDispatcher.dispatchEvent (openfl/_legacy/events/EventDispatcher.hx line 98)
Called from flixel.FlxGame.create (flixel/FlxGame.hx line 352)
Called from flixel.FlxGame.switchState (flixel/FlxGame.hx line 627)
Called from PlayState.create (PlayState.hx line 13)
Called from flixel.animation.FlxPrerotatedAnimation.set_angle (flixel/animation/FlxPrerotatedAnimation.hx line 27)
```
