### ISSUE TITLE
FlxButton mouseup no longer needed?

### ISSUE THREAD

**Issue by MSGhero** [HaxeFlixel/flixel#2118]
I have a feeling that FlxButton's explicit `MOUSE_UP` to handle clicks is no longer necessary with the `CLICK` callback from FlxMEM. `playback()` in FlxMouse would probably change too.

**Comment by Gama11** [comment]
The event listener is necessary for security restrictions on Flash, see https://github.com/HaxeFlixel/flixel/issues/866 or http://www.adobe.com/devnet/flashplayer/articles/fplayer10_uia_requirements.html.

**Comment by MSGhero** [comment]
Oh that’s right. A quick note about that would be good in `setMouseClickCallback()`.

**Comment by MSGhero** [comment]
... or maybe flixel’s click should dispatch an event too (#if flash?)

**Comment by Gama11** [comment]
Maybe... so far nobody has complained about it though. :D
