### ISSUE TITLE
Destroyed FlxSounds remain in FlxSoundGroup, adjusting group volume causes exception.

### ISSUE THREAD

**Issue by lcheeseboy** [HaxeFlixel/flixel#2124]
- **Haxe version:** 3.4.2
- **Flixel version:** 4.3.0
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:**
cpp, neko, html5 [presumably all]
________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxG;
import flixel.FlxState;
import flixel.system.FlxAssets;

class PlayState extends FlxState
{
	override public function create():Void
	{
		// Play a sound
		var sound = FlxG.sound.load(FlxAssets.getSound("flixel/sounds/flixel")).play();
		sound.onComplete = destroyTest;
	}

	function destroyTest() {
		// Destroy all non-persisted sounds [normally called on state switch]
		FlxG.sound.destroy();
		// Crashes because defaultSoundGroup contains a sound that was destroyed
		FlxG.sound.defaultSoundGroup.volume = 0.5;
	}
}
```

________________________________

**Observed behavior:**
Application crashes:
> Null Object Reference
> Called from openfl._legacy.display.Stage.__pollTimers (openfl/_legacy/display/Stage.hx line 1074)
> Called from openfl._legacy.media.SoundChannel.__pollComplete (openfl/_legacy/media/SoundChannel.hx line 233)
> Called from openfl._legacy.media.SoundChannel.__checkComplete (openfl/_legacy/media/SoundChannel.hx line 175)
> Called from openfl._legacy.media.SoundChannel.__runCheckComplete (openfl/_legacy/media/SoundChannel.hx line 258)
> Called from openfl._legacy.events.EventDispatcher.dispatchEvent (openfl/_legacy/events/EventDispatcher.hx line 98)
> Called from flixel.system.FlxSound.stopped (flixel/system/FlxSound.hx line 583)
> Called from PlayState.destroyTest (PlayState.hx line 19)
> Called from flixel.system.FlxSoundGroup.set_volume (flixel/system/FlxSoundGroup.hx line 83)
> Called from flixel.system.FlxSound.updateTransform (flixel/system/FlxSound.hx line 539)

This happens because FlxSoundGroup still has a reference to the destroyed sound.  Since (non-persisting) sounds are destroyed on state switch and recycled, this will happen any time a state that plays less sounds than any previous state tries to adjust the defaultSoundGroup volume.

**Expected behavior:**
The defaultSoundGroup's volume is changed.

**Comment by JoeCreates** [comment]
Should be a simple fix. Will have a look if I get time this week.

**Comment by Gama11** [comment]
Sounds are now removed from the default groups when they're destroyed. Note that your code example still crashes because it calls `destroy()` manually, which shouldn't be done under normal circumstances. Here's an example that crashed before, but now no longer does:

```haxe
package;

import flixel.FlxG;
import flixel.FlxState;
import flixel.system.FlxAssets;

class PlayState extends FlxState
{
    static var i = 0;

    override public function create():Void
    {
        switch (i) {
            case 0:
                var sound = FlxG.sound.load(FlxAssets.getSound("flixel/sounds/flixel")).play();
                sound.onComplete = function() FlxG.switchState(new PlayState());
            case 1:
                FlxG.sound.defaultSoundGroup.volume = 0.5;
        }
        
        i++;
    }
}
```
