### ISSUE TITLE
FlxMath.roundDecimal gives negative result for large(ish) positive inputs

### ISSUE THREAD

**Issue by ttencate** [HaxeFlixel/flixel#2126]
- **Haxe version:** 3.4.4
- **Flixel version:** 4.1.0
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:** neko, probably more

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxState;
import flixel.math.FlxMath;

class PlayState extends FlxState
{
	override public function create():Void
	{
		trace(FlxMath.roundDecimal(Sys.time(), 3));
	}
}
```

(I haven't actually run this exact code, but you get the idea.)

________________________________

**Observed behavior:** a negative value is printed, like `-2147483.648`.

**Expected behavior:** the current Unix time rounded to three decimals, like `1516282651.202`.

This is most likely due to overflow, because the [`roundDecimal` implementation](https://github.com/HaxeFlixel/flixel/blob/e56837f31239649e278910f26b49c7be5232590a/flixel/math/FlxMath.hx#L58) multiplies its argument by 10 repeatedly.

**Comment by Epono** [comment]
Hi,

The problem is actually that the function returns an int (FlxMath.round is for ints, FlxMath.fround for floats).
I submitted a PR.

**Comment by ttencate** [comment]
I think you meant `Math#round` and `Math#fround`, but yes, this makes sense. Floats don't overflow when multiplied by just a few orders of magnitude. And if they do overflow, I think they just become ∞ instead of wrapping.

**Comment by Epono** [comment]
Yup, my bad

**Comment by ttencate** [comment]
For the record, this bug would also cause NaN values to be printed as e.g. `-2147483.648`. Very misleading, because `roundDecimal` is used for printing `FlxPoint`s!

**Comment by Gama11** [comment]
This is fixed in recent versions now though, right? I guess you're still on an older one?

**Comment by ttencate** [comment]
Yes, I know, that's why I wrote "would". Thank you for the fix! I was just adding this info in case someone else stumbles into this.

(We're still on 4.1.0 due to other bugs we encountered when upgrading. Those are possibly also fixed now, but it's made us a bit more cautious.)

**Comment by Gama11** [comment]
Hm.. I'd love to know what exactly the issue was there, would be good if you could try again with latest flixel (4.4.1). Note that you can use that even with older OpenFL, so you don't have to risk upgrading that.

**Comment by ttencate** [comment]
Don't worry, we'll try again some day and file proper bug reports. It just takes time to test everything and narrow down the causes. From memory (it was over a year ago): there was a crash involving `FlxTimer` (even before the new non-singleton timer manager stuff landed), and some semi-advanced bitmap operations worked differently.
