### ISSUE TITLE
using next on mobile doesn't resize the screen when the game is on focus again.

### ISSUE THREAD

**Issue by Tembac** [HaxeFlixel/flixel#2128]
- **Haxe version:** 3.4.0
- **Flixel version:** 4.3.0
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:**
Android
________________________________

**Observed behavior:**

The first time the game starts on android it fits the screen perfectly. 
![screenshot_20180128-231337](https://user-images.githubusercontent.com/2808285/35537014-795f5318-0527-11e8-92f9-84bedde6aa3b.png)

If you go to another app and then come back to the game black bars appears around the game.
![screenshot_20180129-103714](https://user-images.githubusercontent.com/2808285/35537013-793d0182-0527-11e8-9635-bd4dd10fca6e.png)

This only happens using next.

**Expected behavior:**
The game is fullscreen when the app is on focus again.

**Comment by Tembac** [comment]
I need to use "next" because I'm using the clipboard and it only works with that version of openfl. 

I found this issue and I think it is related: https://github.com/openfl/openfl/issues/1325

**Comment by Tembac** [comment]
The optional solution seems to be to disable fullscreen.

**Comment by Gama11** [comment]
Can you try with #2136?

**Comment by Tembac** [comment]
It works fine with #2136

**Comment by Gama11** [comment]
Awesome! I'll go ahead and close this then. :)
