### ISSUE TITLE
FlxDestroyUtil should use macros

### ISSUE THREAD

**Issue by JoeCreates** [HaxeFlixel/flixel#2130]
The destroy/put methods should blatantly be macros.
```
// Without FlxDestroyUtil
if (myVar != null) {myVar.destroy(); myVar = null;}

// Current FlxDestroyUtil usage
myVar = FlxDestroyUtil.destroy(myVar);

// Better FlxDestroyUtil usage
FlxDestroyUtil.destroy(myVar);

// Even better FlxDestroyUtil!
FlxDestroyUtil.destroy(myVar, anotherVar, allTheVars, etc);
```

Note that if the macro returns the expression in a block, all existing uses of FlxDestroyUtil.destroy will still work because the code would become:
```
myVar = {if (myVar != null) myVar.destroy(); myVar = null;}
```

I've never liked FlxDestroyUtil because it barely saves any code at all, but perhaps now I could. :)

**Comment by Gama11** [comment]
It would be slightly shorter code, sure, but I'm concerned about the impact such a macro would have on compilation and especially completion performance...

**Comment by Gama11** [comment]
Considering the impact that such a macro might have on compilation / completion performance, I'm not sure it's worth it for such a small improvement.

**Comment by Tiago-Ling** [comment]
+1 for not increasing autocomplete time!

Tiago Ling Alexandre
Tel: +55 41 8819-3191


2018-03-22 11:20 GMT-03:00 Jens Fischer <notifications@github.com>:
