### ISSUE TITLE
FlxTilemap.overlapsPoint() produces null object reference

### ISSUE THREAD

**Issue by 01010111** [HaxeFlixel/flixel#2135]
- **Haxe version:** 3.4.7
- **Flixel version:** 4.3.0
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:** All

________________________________

When loading maps from certain editors that use "-1" to represent "no tile" FlxTilemap.overlapsPoint() gives a null object reference.

If I change:
```haxe
	private function tileAtPointAllowsCollisions(point:FlxPoint):Bool
	{
		var tileIndex = getTileIndexByCoords(point);
		if (tileIndex < 0 || tileIndex >= _data.length)
			return false;
		return _tileObjects[_data[tileIndex]].allowCollisions > 0;
	}
```
to:
```haxe
	private function tileAtPointAllowsCollisions(point:FlxPoint):Bool
	{
		var tileIndex = getTileIndexByCoords(point);
		if (tileIndex < 0 || tileIndex >= _data.length || _data[tileIndex] < 0)
			return false;
		return _tileObjects[_data[tileIndex]].allowCollisions > 0;
	}
```
It doesn't throw the error.

(that code snippet is here: [FlxBaseTilemap.1253](https://github.com/HaxeFlixel/flixel/blob/master/flixel/tile/FlxBaseTilemap.hx#L1253))

**Comment by Gama11** [comment]
That doesn't seem like a proper fix, negative indices should never get past the loading stage. There was a fix for this a while back, but it only applied to loading maps from CSV: https://github.com/HaxeFlixel/flixel/commit/94859ebb0cffc18a4e392133a2d961e43205ec7f#diff-b41363a89c67b2e86081b4ae16166048

How are you loading your maps / what editor are you using?

**Comment by 01010111** [comment]
I'm using Ogmo, so it's stored as CSV data inside an XML, but I'm turning that data into a 2D Array before using it to create my tilemaps.

**Comment by Gama11** [comment]
The fix originally was for Ogmo as well, which is mostly why it was specific to loading maps from CSV I guess... Any particular reason for the 2D-Array-conversion?

**Comment by 01010111** [comment]
Hm I think it was some legacy thing from generating minimaps. I can switch back to using the CSV, but in the long run this is a little wonky because it presumes that every tileset will include a blank tile at index 0 (which mine do not, but if I need to change them it's no biggie)

**Comment by Gama11** [comment]
That's kind of the assumption when using FlxTilemap think. Even the `loadMapFromCSV()` which has the Ogmo fix sets those tiles < 0 to 0. Back in AS3 Flixel, it even used a unsigned integers for tile types.

The docs for `MapData` state:

>An array containing the tile indices

or

>A 2D array containing the tile indices

"Indices" already suggests that -1 wouldn't be allowed, as that's not really a valid index. We could make it more explicit however, for instance by adding "must be positive".

**Comment by Gama11** [comment]
I added a clarification to the docs.
