### ISSUE TITLE
Error building against Android: libstd-v7.so does not exist

### ISSUE THREAD

**Issue by nightblade9** [HaxeFlixel/flixel#2140]
- **Haxe version:** 3.4.7
- **Flixel version:** 4.3.0
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:** Android

________________________________

I used to be able to build against the Android target. Today, when I run `lime build android`, I get this error: `Error: Source path "D:\Haxetoolkit\haxelib\hxcpp/3,4,188/bin/Android/libstd-v7.so" does not exist`. This is regardless of what the project code looks like.

I tried uninstalling and reinstalling `hxcpp`, both from `lime` and from `haxelib` (even though they install the same version). As a final option, I completely removed all related libraries (`openfl`, `lime`, `flixel`, `flixel-*`) from haxelib and reistalled everything; I still get this error.

Any idea how I can fix this? (Sorry if this is the wrong repo to open the issue against.)

**Comment by Gama11** [comment]
Try installing an older hxcpp version. This should be the same issue as http://forum.haxeflixel.com/topic/671/windows-build-issues.

```
haxelib set hxcpp 3.4.64
```

**Comment by nightblade9** [comment]
`3.4.64` seems to work. Thanks for the quick turn-around on this.
