### ISSUE TITLE
Y-axis fix #2138 creates new sticking collision problem on object corners

### ISSUE THREAD

**Issue by cervanky** [HaxeFlixel/flixel#2141]
Although #2138 solved the issue for getting stuck on the y-axis against multiple objects, this has created another problem for me when colliding with the very edge of another object. 

In the examples below, I'm constantly holding the right key to move the player right, except for in the "after" example when I release the key to "unstick" the player and escape the collision. 

# Before #2138 fix:
![before](https://user-images.githubusercontent.com/8077416/38900479-90b6e39e-4269-11e8-861d-99392c64eaa2.gif)

# After #2138 fix:
![after](https://user-images.githubusercontent.com/8077416/38900483-92c7b762-4269-11e8-9c0c-c7d6dfae24ef.gif)

**Comment by Gama11** [comment]
Hm, that doesn't look good, we might have to revert the fix. :( Any chance you could provide a small code snippet that reproduces it?

Thanks for reporting!

**Comment by cervanky** [comment]
Sure! Test it out for yourself using this code I took from #1566, with the addition of two platforms to test corner collision. Just jump on the upper platform and keep holding right - you'll fall and get stuck on the corner of the second platform.
```
package;

import flixel.FlxG;
import flixel.FlxObject;
import flixel.FlxSprite;
import flixel.FlxState;
import flixel.group.FlxGroup.FlxTypedGroup;

class PlayState extends FlxState
{
    var boxes:FlxTypedGroup<FlxSprite>;
    var player:FlxSprite;

    override public function create():Void
    {
        add(boxes = new FlxTypedGroup<FlxSprite>());

        for (i in 0...15)
        {
            var b = new FlxSprite(0, i * 50);
            b.makeGraphic(50, 50, 0xFF000000 + Std.random(0xFFFFFF));
            b.immovable = true;
            b.solid = true;
            boxes.add(b);
        }

        for (i in 0...15)
        {
            var b = new FlxSprite(i*50+50, FlxG.height- 50);
            b.makeGraphic(50, 50, 0xFF000000 + Std.random(0xFFFFFF));
            b.immovable = true;
            b.solid = true;
            boxes.add(b);
        }

		var c = new FlxSprite(300,350);
		c.makeGraphic(100,50,0xFFFFFFFF);
		c.immovable = true;
		c.solid = true;
		boxes.add(c);

		var d = new FlxSprite(117,250);
		d.makeGraphic(100,50,0xFFFFFFFF);
		d.immovable = true;
		d.solid = true;
		boxes.add(d);

        player = new FlxSprite(50, 0);
        player.makeGraphic(20, 20);
        player.acceleration.y = 500;
        add(player);
    }

    override public function update(elapsed:Float):Void
    {
        FlxG.collide(player, boxes);

        player.velocity.x = 0;

        if (FlxG.keys.pressed.LEFT)
            player.velocity.x = -100;
        if (FlxG.keys.pressed.RIGHT)
            player.velocity.x = 100;
        if (FlxG.keys.justPressed.UP && player.isTouching(FlxObject.DOWN))
            player.velocity.y = -650;

        super.update(elapsed);
    }
}
```

**Comment by Gama11** [comment]
Thanks, that perfectly reproduces it... definitely will have to revert the other fix for now.
