### ISSUE TITLE
Transparent sprite created with makeGraphic() results in corruption when drawn to the display

### ISSUE THREAD

**Issue by grayhaze** [HaxeFlixel/flixel#2142]
- **Haxe version:** 3.4.4
- **Flixel version:** git (e659eafcde472c8d44f039f5b994844e24360cf3)
- **OpenFL version:** git (1a9e0ec52c505f14faed5a14a3185c89447db077)
- **Lime version:** git (8b6ea9bff5fc4a6a3dcc1e36a2a8192c99d9eb45)
- **Affected targets:** mac/cpp

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxState;
import flixel.FlxSprite;
import flixel.FlxG;

class PlayState extends FlxState
{
	var mySprite:FlxSprite;
	override public function create():Void
	{
		super.create();
		mySprite = new FlxSprite();
		mySprite.makeGraphic(FlxG.width, FlxG.height, 0x00000000, true);
		add(mySprite);
	}
	override public function update(elapsed:Float):Void
	{
		super.update(elapsed);
	}
}
```

________________________________

**Observed behavior:** Transparent sprite created with `makeGraphic()` results in corruption when drawn to the display:

![acidtrip](https://user-images.githubusercontent.com/1177813/39040993-069a6366-4480-11e8-8cd3-92a8312846d7.gif)

**Expected behavior:** The sprite should be completely transparent.

**Comment by grayhaze** [comment]
I suspect this is down to a recent commit in #2136 before the branch was merged to `dev`, as this wasn't happening with an earlier version of that branch. I'll try to pinpoint the exact change that caused the issue.

**Comment by Gama11** [comment]
>I'll try to pinpoint the exact change that caused the issue.

That would be helpful, since I can't reproduce this. Note that it could well have been a change in OpenFL or Lime as well.

**Comment by Gama11** [comment]
Could you narrow it down further? Was it one of the changes to `FlxGraphicsShader`?

**Comment by grayhaze** [comment]
Unfortunately I can't checkout any individual SHAs after that point from your repo, as I just get a `fatal: reference is not a tree` error. I suspect it would have been one of the two `FlxGraphicsShader` changes though.

**Comment by Gama11** [comment]
Oh, perhaps I shouldn't have deleted that branch just yet. I've pushed it again, try again after a fetch.

What graphics card do you have? Does the same issue occur on HTML5, and if so, is there anything interesting in the dev console? Sometimes GLSL error reporting is better there than on native targets.

**Comment by Gama11** [comment]
Looking at that diff you linked, I just spotted a stupid mistake that might or might not have been the culprit. Can you try again with latest dev?

**Comment by grayhaze** [comment]
Yes, that seems to have fixed the issue! Thanks for sorting this out so quickly @Gama11, and good work on getting us up and running on OpenFL 8. It's nice to be up to date finally. 😀
