### ISSUE TITLE
Setting FlxSpriteGroup.camera should work like FlxSpriteGroup.cameras

### ISSUE THREAD

**Issue by puggsoy** [HaxeFlixel/flixel#2144]
When setting the `cameras` property of a `FlxSpriteGroup` it also sets the `cameras` for all its children, as it should. However this doesn't happen with `camera`. Because the `camera` property is simply a way to set/get the first element of `cameras`, I think it makes sense to implement this functionality for `FlxSpriteGroup`. It's both convenient, and what I would consider to be the expected behaviour.

**Comment by Gama11** [comment]
Feel free to create a pull request! :)
