### ISSUE TITLE
updateTransform called on FlxSoundGroup.remove throws null reference exception

### ISSUE THREAD

**Issue by tbrosman** [HaxeFlixel/flixel#2149]
- **Haxe version:** 3.4.2
- **Flixel version:** 4.4.0
- **OpenFL version:** 8.0.0
- **Lime version:** 6.3.0
- **Affected targets:** Flash, Windows, Android
________________________________

** Stack trace **
```
Called from flixel.FlxGame::step flixel/FlxGame.hx line 665
Called from flixel.FlxGame::update flixel/FlxGame.hx line 712
Called from flixel.FlxGame::switchState flixel/FlxGame.hx line 606
Called from flixel.system.frontEnds.SoundFrontEnd::destroy flixel/system/frontEnds/SoundFrontEnd.hx line 271
Called from flixel.system.frontEnds.SoundFrontEnd::destroySound flixel/system/frontEnds/SoundFrontEnd.hx line 279
Called from flixel.system.FlxSoundGroup::remove flixel/system/FlxSoundGroup.hx line 52
Called from flixel.system.FlxSound::set_group flixel/system/FlxSound.hx line 672
Called from flixel.system.FlxSound::updateTransform flixel/system/FlxSound.hx line 543
```

________________________________

Sounds (looping, in this case) that have been destroyed are not removed from their FlxSoundGroups (I think this is by-design). When the SoundFrontEnd goes to destroy the built-in FlxSoundGroups, they set the group to null. However, setting the group also causes updateTransform to run.

This worked fine on Flixel 4.1.1 (the last version I used). Note that I'm calling "destroy" to kill looping sounds instead of "stop". Is this not the correct way to do this?

**Comment by Gama11** [comment]
Do you have some code to reproduce this?

**Comment by tbrosman** [comment]
@Gama11 Sure thing

```haxe
package;
import flixel.FlxG;
import flixel.FlxState;
import flixel.system.FlxSound;
import flixel.ui.FlxButton;


class MenuState extends FlxState
{
    private var soundInstance:FlxSound;
    
    public override function create():Void
	{
		super.create();
		
		var playSound:FlxButton = new FlxButton(
            0, 0, "Play sound", function() { soundInstance = FlxG.sound.play("assets/sounds/music.mp3", 1, true); } );
        add(playSound);
        
        var destroySound:FlxButton = new FlxButton(
            0, 100, "Destroy sound", function() { soundInstance.destroy(); } );
        add(destroySound);
        
        var changeState:FlxButton = new FlxButton(
            200, 0, "Change State", function() { FlxG.switchState(new OtherState()); } );
        add(changeState);
	}
}

class OtherState extends FlxState
{
    public function new()
    {
        super();
    }
}
```

**Comment by Gama11** [comment]
I think this is expected, you shouldn't normally call `destroy()` on things outside of `destroy()` / until states are switched. Either `stop()` or `kill()` seems like the way to go.

Note that sounds played through `FlxG.sound` are actually added to `FlxG.sound.list`, and it tries to recycle killed sounds.

**Comment by tbrosman** [comment]
@Gama11 Works for me. Thanks for clarifying!

Btw, is there an "object lifetime" section sitting around in the Flixel documentation somewhere? I think it would be useful for situations like this.

**Comment by Gama11** [comment]
Not sure what you mean by "object lifetime" exactly?
