### ISSUE TITLE
Runtime Error using Lime 7.0.0

### ISSUE THREAD

**Issue by RNanoware** [HaxeFlixel/flixel#2163]
- **Haxe version:** 3.4.7
- **Flixel version:** 4.5.0
- **OpenFL version:** 8.4.0
- **Lime version:** 7.0.0
- **Affected targets:** Flash (but HTML5 seems broken too)

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxState;

class PlayState extends FlxState
{
	override public function create():Void
	{
		// Nothing needs to be added: A blank project throws the error
	}
}
```

________________________________

**Observed behavior:**

After running the following commands in Powershell on Windows 10:

```
haxelib install flixel 4.5.0
haxelib install flixel-tools 1.4.2
haxelib install openfl 8.4.0
haxelib install lime 7.0.0
haxelib run lime setup
haxelib run lime setup flixel
haxelib run flixel-tools setup
flixel tpl -n "Empty"
cd Empty
lime test flash
```

A flash player opens, and the HaxeFlixel splash animation displays, but the following error immediately pops up:

```
ArgumentError: Error #2025: The supplied DisplayObject must be a child of the caller.
	at flash.display::DisplayObjectContainer/removeChild()
	at flixel.system.frontEnds::CameraFrontEnd/remove()
	at flixel.system.frontEnds::CameraFrontEnd/reset()
	at flixel::FlxGame/switchState()
	at flixel::FlxGame/create()
	at flash.display::DisplayObjectContainer/addChild()
	at Main()
	at DocumentClass()
	at ApplicationMain$/start()
	at MethodInfo-98()
	at lime.app::_Event_Void_Void/dispatch()
	at openfl.display::Preloader/start()
	at lime.utils::Preloader/updateProgress()
	at lime.utils::Preloader/current_onEnter()
```

Hitting "Continue" on the error message, the next error that displays is:

```
ArgumentError: Error #2015: Invalid BitmapData.
	at flash.display::BitmapData/get width()
	at flixel::FlxCamera/checkResize()
	at flixel::FlxGame/draw()
	at flixel::FlxGame/onEnterFrame()
```

...and it repeats indefinitely.

However, if I run the following (reverting to lime 6.4.0):

```
haxelib install lime 6.4.0
haxelib set lime 6.4.0
lime test flash
```

The expected behavior occurs (no error).

**Expected behavior:**

I expect a Flash player to open, display the HaxeFlixel splash screen, then go black, without showing any errors.

**Comment by Gama11** [comment]
This is probably the same issue as http://community.openfl.org/t/bug-openfl-8-4-0-making-multiple-instances-of-main-hx-in-flash/10834/. Try updating to OpenFL dev to get the fix mentioned in that thread.

**Comment by RNanoware** [comment]
@Gama11 Using the latest code from OpenFL develop seemed to do the trick! Thank you for the triage. Is there anything that I/anyone can do to help others avoid running into this hiccup while we wait for the OpenFL fix to arrive in a release?

(In my case, the Ludum Dare 48-hour game design competition is underway, and this issue has cost me quite a bit of time, unfortunately!)
