### ISSUE TITLE
drawLine is missing color

### ISSUE THREAD

**Issue by Arcnor** [HaxeFlixel/flixel#2165]
- **Flixel version:** 4.5.0

Unless I'm missing something, `FlxSpriteUtils.drawLine()` doesn't take a color (although the docs say otherwise), and the relevant line on said function (unless I'm mistaken) seems to be:

```
beginDraw(0x0, lineStyle);
```

Isn't `0x0` supposed to be `color` (and `color` needs to be a new function parameter, of course)?

**Comment by Gama11** [comment]
The line `color` is specified in `LineStyle`. What's passed to `beginDraw()` is the _fill_ color, and lines don't really have that.

**Comment by Arcnor** [comment]
I see, thanks for the information. The docs don't seem to be helpful in this case (they say "This function draws a line on a FlxSprite from position X1,Y1 to position X2,Y2 with the specified color.", but it's probably not really color, but all the attributes).

That said, the docs (or at least the Cheatsheet) seem to be using some `FlxSprite.drawLine` that doesn't seem to exist?

In any case, this doesn't seem to be a bug, sorry about the noise.

**Comment by Gama11** [comment]
This the the only mention of `drawLine` on the cheat sheet - looks correct to me?

![](https://i.imgur.com/ERtreLU.png)

**Comment by Arcnor** [comment]
That's exactly what I was trying to do, but (and I'm probably on the wrong here) `canvas` is a `FlxSprite`, and going to the `FlxSprite` docs don't mention anything about `drawLine` or similar (and so the compiler said as well).

Unless you're telling me of course that if I import `FlxSpriteUtils` Haxe will be smart enough to add extension methods to `FlxSprite` automagically.

**Comment by Gama11** [comment]
Sort of - you need `using` instead of `import`. See also this section on the cheat sheet a few lines. ;)

![](https://i.imgur.com/s2FrfqJ.png)

**Comment by Arcnor** [comment]
Ah, that will explain it then, thank you very much and sorry for the noise
