### ISSUE TITLE
FlxTileFrames documentation issue

### ISSUE THREAD

**Issue by ProjectPatatoe** [HaxeFlixel/flixel#2179]
Documentation generated for FlxTileFrams looks messed up. Tested Chrome and Firefox

![image](https://user-images.githubusercontent.com/27925441/46383449-45368e80-c665-11e8-8e72-c6c0ade9045b.png)

https://api.haxeflixel.com/flixel/graphics/frames/FlxTileFrames.html

**Comment by Gama11** [comment]
Looks like dox (the tool we use to generate API docs) doesn't like code snippets after `@return`...
