### ISSUE TITLE
killTweensOf

### ISSUE THREAD

**Issue by Geokureli** [HaxeFlixel/flixel#2180]
Continuing off of #1458. This is a pretty common feature of tween libraries and can be done relatively easily.

I'm a huge fan of Greensock's flash tween library which looked like:
```as3
/**
 * @param target    Object whose tweens should be killed immediately or selector 
 *     text to feed the selector engine to find the target(s). You may also pass in an 
 *     array of targets.
 * @param vars      (default = null) - To kill only specific properties, use a generic
 *      object containing enumerable properties corresponding to the ones that 
 *     should be killed like {x:true, y:true}. The values assigned to each property
 *     don’t matter – the sole purpose of the object is for iteration over the named 
 *     properties (in this case, x and y). If no object (or null) is defined, all matched 
 *     tweens will be killed in their entirety.
 * @param complete  (default = false) - Determines whether or not the
 *     tweens/delayedCalls/timelines should be forced to completion before being killed.
**/
static public function killTweensOf(target:Object, vars:Object = null, complete:Boolean = false):void
```
I don't think FlxTween has the capability to complete() a tween early, so lets ignore that property

I've made a [mockup of the feature](https://github.com/HaxeFlixel/flixel/compare/dev...Geokureli:killTweensOf) (untested, as of now, but ready for feedback). Yes there's better, more optimized ways of doing this than looking through the whole list each time, but I feel like this will address the common use cases.

**Comment by Geokureli** [comment]
Could you elaborate on what's strange? the idea is so that you can tweens of certain properties but keep others. for instance:
```haxe
FlxTween.killTweensOf(mySprite, ["x", "y", "angle"]);
```
this would kill position tweens of mysprite as well as angle tweens, whether they were created via
```haxe
FlxTween.angle(mySprite, mySprite.angle, 180 ...
```
or
```haxe
FlxTween.tween(mySprite, { angle: 180 } ...
```
Side note: I forgot to do the same for the motion tweens

**Comment by MSGhero** [comment]
It looks like it works for just canceling all tweens of an object, which is all I'd want in this feature, even if grabbing specific properties exists. Also I literally do not remember making #1458

**Comment by Gama11** [comment]
Hm, I see... Still feels quite "stringly typed". :) Then again, so is `VarTween` with its use of reflection.

**Comment by Geokureli** [comment]
I'm fine using `{ x:null, y:true, angle:false }` since it matches

**Comment by Gama11** [comment]
That doesn't seem any different - in fact, an array of Strings is probably preferable. I don't really understand why it's an object in that Greensock API, it even states "the values assigned to each property don’t matter", which makes it rather redundant / unnecessarily verbose. Unless I'm missing something?

**Comment by Geokureli** [comment]
FYI @Gama11, I'm planning on updating this branch and submitting for approval since I keep wishing I had this feature. I still don't know of a better solution than `Array<String>` to specify which tween args to kill, so if you know a better implementation, or if you know that you would likely block a change using that implementation, let me know.
