### ISSUE TITLE
Suggestion: multiple FlxVector changes

### ISSUE THREAD

**Issue by Geokureli** [HaxeFlixel/flixel#2185]
This started out as a single suggestion but has grown to cover multiple requests:
- [ ] Add FlxVector.weak and call putWeak() on operations
- [ ] Make FlxVector an abstract class so converting FlxPoints to FlxVectors is trivial and FlxVector operations can take FlxPoints
- [ ] 'override' all FlxPoint methods in FlxVector and use covariance to return FlxVectors. **Note**: this won't be necessary if the [polymorphic 'this' types proposal](https://github.com/HaxeFoundation/haxe-evolution/pull/36) is accepted

**Original message:**
FlxPoint.weak is such a great tool, I'd love to see it on FlxVector as well. Right now FlxPoint will call `putWeak()` on Vectors, but they are never weak. I'm not seeing any obvious drawbacks to adding a static `weak()` method and calling `putWeak` on FlxVector methods that handle other vectors

**Comment by Geokureli** [comment]
tangential suggestion, make FlxVector an abstract of FlxPoint. 
```haxe
class Point {
	
	static var _pool:Array<Point> = [];
	
	public var x:Float;
	public var y:Float;
    
	var _weak:Bool = false;
	
	public function new (x = 0.0, y = 0.0) { set(x, y); }
	
	inline public function set(x = 0.0, y = 0.0):Point {
        
		this.x = x;
		this.y = y;
		return this;
	}
	
	inline function setWeak():Point {
        	
		_weak = true;
		return this;
	}
	
	inline public function put():Void { _pool.push(this); }
	
	inline public function putWeak():Void { if (_weak) put(); }
	
	inline static public function get(x = 0.0, y = 0.0):Point {
		
		return (_pool.length == 0 ? new Point() : _pool.shift()).set(x, y);
	}
    
	inline static public function weak(x = 0.0, y = 0.0):Point {
		
		return Point.get(x, y).setWeak();
	}
}

@:forward
abstract Vector(Point) from Point to Point {
	
	public var length(get, never):Float;
	
	inline public function new (x = 0.0, y = 0.0) { this = Point.get(x, y); }
	
	inline function get_lengthSquared():Float { return this.x * this.x + this.y * this.y; }
	
	inline static public function get(x = 0.0, y = 0.0):Vector { return cast Point.get(x, y); }
	
	inline static public function weak(x = 0.0, y = 0.0):Vector { return cast Point.weak(x, y); }
}

class Test {
	
	static function main() {
		
		Point.weak().putWeak();
		
		trace(Vector.get(4, 3).lengthSquared);
	}
}
```

**Comment by MSGhero** [comment]
Could have internal `__add`, where external `add` does the putWeaking. Not the worst since it (may) all get inlined.

**Comment by Geokureli** [comment]
I would probably have to do the same with FlxPoint's methods and give access to FlxVector on all of them, since abstracts can't access private fields on the underlying type.

what's neat about this is we could have:

```haxe
inline function __add(v:FlxVector, put:Bool = true):FlxVector
{
    x += v.x;
    y += v.y;
    if (put) v.putWeak();
}
```
and DCE will remove the `if` when the put arg is a literal false, as shown [here](https://try.haxe.org/#5161d)
