### ISSUE TITLE
HaxeFlixel not detecting arrow key presses

### ISSUE THREAD

**Issue by Joncom** [HaxeFlixel/flixel#2190]
- **Haxe version:** 3.4.7
- **Flixel version:** 4.5.1
- **OpenFL version:** 8.6.2
- **Lime version:** 7.1.1
- **Affected targets:** HTML5

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import openfl.display.Sprite;
import flixel.FlxG;
import flixel.FlxGame;
import flixel.FlxState;
import flash.events.KeyboardEvent;

enum Mode {
	Broken;  // Most keys detected, but NOT arrow keys
	Working; // All keys detected, including arrow keys
}

class Main extends Sprite
{
	public static var mode : Mode = Mode.Broken;

	public function new()
	{
		super();

		if(mode == Mode.Working) {
			addListener();
		} else {
			addChild(new FlxGame(0, 0, PlayState));
		}
	}

	public static function addListener()
	{
		FlxG.stage.addEventListener(KeyboardEvent.KEY_DOWN, Main.keydown);
	}

	public static function keydown(event:KeyboardEvent)
	{
		if([37, 38, 39, 40].indexOf(event.keyCode) >= 0) {
			trace("Arrow key pressed");
		} else {
			trace("Other key pressed");
		}
	}
}

class PlayState extends FlxState
{
	override public function create():Void
	{
		super.create();
		Main.addListener();
	}
}
```

________________________________

**Observed behavior:** Key presses like A, B, C, Shift, etc. will trigger a message to console, but arrow keys will not. No `KeyboardEvent` fires for arrow keys.

**Expected behavior:**

Arrow key presses should trigger a console message, just like the other keys do.

**Comment by JoeCreates** [comment]
This also breaks arrow keys in the debug console, so this is a straight up flixel issue on HTML5. Arrow keys are need, for example, to navigate the autocomplete menu.

**Comment by Gama11** [comment]
>I'm not sure why the stop(Immediate)Propagation would be useful

Somebody would have to check whether or not that's necessary on Android or HTML5. I suspect it may have been needed on at least one of those with OpenFL legacy (which we technically still support...).

**Comment by JoeCreates** [comment]
Why would they even be necessary on any platform? By this point they are
just events in openfl. Essentially it's just saying nothing else in openfl
can use this event now, isn't it?

If there really is something which needs to be disabled to prevent some
default openfl behavior then I would expect a better way of disabling them
specfically for that reason without consuming the event entirely.
