### ISSUE TITLE
Color transform offsets not working correctly, also issues with colortransform alpha

### ISSUE THREAD

**Issue by larsiusprime** [HaxeFlixel/flixel#2192]
- **Haxe version:** 3.4.7
- **Flixel version:** latest dev version from github
- **OpenFL version:** latest develop branch version from github
- **Lime version:** 7.1.1
- **Affected targets:** windows (presumably neko as well)

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxG;
import flixel.FlxSprite;
import flixel.FlxState;
import flixel.util.FlxColor;
import openfl.Assets;
import openfl.display.BitmapData;
import openfl.geom.ColorTransform;
import openfl.display.Bitmap;

class PlayState extends FlxState
{
	var sprite:FlxSprite;
	var sprite2:FlxSprite;
	var bmp:BitmapData;
	var toggle = false;

	var oflBitmap:Bitmap;
	
	override public function create():Void
	{
		makeCheckerBoard();

		sprite = new FlxSprite();
		sprite2 = new FlxSprite();
		sprite.makeGraphic(64,64,FlxColor.GRAY);
		sprite2.makeGraphic(64,64,FlxColor.GRAY);
		bmp = new BitmapData(64,64,false,FlxColor.GRAY);
		sprite.x = Std.int((FlxG.width-sprite.width)/2) - sprite.width;
		sprite.y = Std.int((FlxG.height-sprite.height)/2);

		oflBitmap = new Bitmap(new BitmapData(64,64,false,FlxColor.GRAY));
		oflBitmap.x = Std.int(sprite.x + sprite.width);
		oflBitmap.y = sprite.y;
		FlxG.stage.addChild(oflBitmap);
		
		sprite2.x = sprite.x + sprite.width + sprite2.width;
		sprite2.y = sprite.y;
		add(sprite);
		add(sprite2);
	}
	
	private function makeCheckerBoard():Void
	{
		var tileW = Math.round(FlxG.height / 10);
		var tileH = tileW;

		var tilesWide = Math.round(FlxG.width/tileW);
		var tilesTall = Math.round(FlxG.height/tileH);

		for(iy in 0...tilesTall){
			for(ix in 0...tilesWide){
				var tileColor = (iy + ix) % 2 == 0 ? FlxColor.BLACK : FlxColor.WHITE;
				var tile = new FlxSprite().makeGraphic(tileW,tileH,tileColor);
				tile.x = ix * tileW;
				tile.y = iy * tileH;
				add(tile);
			}
		}
	}

	
	override public function update(elapsed:Float):Void
	{
		super.update(elapsed);

		if(FlxG.keys.justPressed.SPACE)
		{
			toggle = !toggle;
			if(toggle)
			{
				var r = rand(-255,255)/255;
				var g = rand(-255,255)/255;
				var b = rand(-255,255)/255;
				var a = 1.0;//rand(0,255)/255;
				var ra = rand(-255,255);
				var ga = rand(-255,255);
				var ba = rand(-255,255);
				var aa = 0;//rand(-255,255);
				sprite.setColorTransform(r,g,b,a,ra,ga,ba,aa);
				sprite2.graphic.bitmap.draw(bmp, null, new ColorTransform(r,g,b,a,ra,ga,ba,aa));
				oflBitmap.transform.colorTransform = new ColorTransform(r,g,b,a,ra,ga,ba,aa);
			}
			else
			{
				sprite.setColorTransform(1,1,1,1,0,0,0,0);
				sprite2.graphic.bitmap.draw(bmp, null, new ColorTransform(1,1,1,1,0,0,0,0));
				oflBitmap.transform.colorTransform = new ColorTransform(1,1,1,1,0,0,0,0);
				sprite.alpha = 1.0;
			}
		}
	}

	private function rand(min:Int, max:Int):Int
	{
		var range = (max-min)+1;
		return Std.int(Math.random() * range) + min;
	}
}
```

________________________________

**Observed behavior:**
This little test creates three squares and puts them in the scene, then applies color in one of three ways:
- A regular FlxSprite, with a colorTransform applied directly to it (left)
- A regular FlxSprite, whose pixels are directly set by a BitmapData.draw() command with a color transform supplied -- e.g. software rendering (middle)
- An openfl Bitmap object applied directly to FlxG.stage, with a colorTransform applied directly to it (right)
- The three squares are directly touching each other so that subtle color errors are easier to notice.

Press spacebar to toggle between default color transform values (1,1,1,1,0,0,0,0) and randomized ones.

- Alpha transforms are commented out in this sample as it's hard to notice the color errors with them in the mix, but there appears to be a bug with them too. 
- Color multipliers don't appear correct -- they're a bit too dark.
- Using color offsets cause the FlxSprite to disappear entirely, unless alpha offset is 255. Even then, the result is too dark.
- Alpha multiplier appears to yield the correct alpha, and interestingly enough the color matches too! *But only when the alpha multiplier is not 1.0*, otherwise the color is too dark.
- Alpha offset is broken as mentioned above -- sprite entirely invisible when color offsets used unless alpha offset is set to 255. When no color multiplier or offsets are set (and no alpha multiplier either, just alpha offset), then the result we get is the wrong alpha value for the basic gray square.

**Expected behavior:**
- The basic color of all three squares should match when the transforms are applied.
- The alphas for the upper left (flixel w/ transform) and the one on the bottom (openfl w/ transform) should match.
- The alpha of the upper right one is not expected to change as BitmapData.draw() doesn't apply that operation.

**Comment by JoeCreates** [comment]
In the test code,

```sprite.makeGraphic(64,64,FlxColor.GRAY);
sprite2.makeGraphic(64,64,FlxColor.GRAY);```

should be 

```sprite.makeGraphic(64,64,FlxColor.GRAY, true);
sprite2.makeGraphic(64,64,FlxColor.GRAY, true);```

After a couple of confusing hours, I noticed that the transform was simply being applied twice for flixel. Nothing wrong with the shader. :P
