### ISSUE TITLE
Camera Filters not working correctly when scrolling

### ISSUE THREAD

**Issue by MiniBobbo** [HaxeFlixel/flixel#2194]
Haxe version: 3.4.7
Flixel version: 4.5.1 (first noticed on 4.4.1)
OpenFL version: 8.5.0 (first noticed on 8.1.0)
Lime version: 7.1.1 (first noticed on 6.3.1)
Affected targets: HTML5, CPP, maybe others

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxState;

class PlayState extends FlxState
{
	override public function create():Void
	{
		super.create();
		var s = new FlxSprite();
		s.makeGraphic(100, 100, FlxColor.RED);
		add(s);
		FlxTween.tween(FlxG.camera.scroll, {y:100}, 1, {type:FlxTweenType.PINGPONG});
		FlxG.camera.bgColor = FlxColor.GRAY;
		FlxG.camera.setFilters([new BlurFilter()]);
		
	}
}
```

________________________________

**Observed behavior:**
When a filter is applied to the camera and the camera scrolls, the top of the camera are not rendering correctly.  I've never seen the problem on the left and right.  

![haxeerror](https://user-images.githubusercontent.com/5286906/49317471-9676c900-f4c2-11e8-95ad-25340b597e36.gif)

Strangely, this only happens when a sprite is scrolling off the screen.  If you remove the sprite the background renders fine.

**Expected behavior:**

![haxeerror2](https://user-images.githubusercontent.com/5286906/49317592-1735c500-f4c3-11e8-8739-026f84d8a591.gif)

**Comment by JoeCreates** [comment]
This is an openfl issue https://github.com/openfl/openfl/issues/2107

**Comment by JoeCreates** [comment]
This is now fixed in openfl and can be closed.
