### ISSUE TITLE
Blend modes don't currently work in OpenFL 8

### ISSUE THREAD

**Issue by larsiusprime** [HaxeFlixel/flixel#2196]
- **Haxe version:** 3.4.7
- **Flixel version:** latest dev version from github
- **OpenFL version:** latest develop branch version from github
- **Lime version:** 7.1.1
- **Affected targets:** windows (presumably neko as well)

________________________________

**Code snippet reproducing the issue**:

The [BlendModes demo](http://haxeflixel.com/demos/BlendModes/) reproduces the issue very clearly and comprehensively.
________________________________

**Observed behavior:**

It looks like this:
![2018-12-04 16_56_30-blendmodes](https://user-images.githubusercontent.com/739064/49478510-8ffb9080-f7e5-11e8-8ab7-dfb61d84a86c.png)

**Expected behavior:**

It should looks something like this:
![2018-12-04 16_55_59-blendmodes _ haxeflixel 2d game engine](https://user-images.githubusercontent.com/739064/49478493-840fce80-f7e5-11e8-86e3-66db7d83bda2.png)

(flash results)

------------------

I know this is a known issue, that is technically OpenFL's "fault" in that the drawQuads API doesn't currently expose a functioning blend mode parameter, but I think we should seriously look into doing this on our own just by using a custom shader that implements BlendModes. That will necessitate the custom shader fed into drawQuads being able to sample the background, and may also require a multi-pass solution.

I've been talking to @JoeCreates and @jgranick about this, and I think it's possible. I still need to investigate more to see if it's possible to do without having to change OpenFL's api. But I think doing it in our own shader is valuable because a) it doesn't put an additional support/implementation/maintenance burden for Yet Another Feature in the OpenFL drawQuads API, and it opens the door for all sorts of effects, particularly if we figure out a multi-pass solution with background sampling, that's apply-able per-FlxSprite.

If this seems like a reasonably good approach, then I'll also make this LarsBounty #5 and put $50 USD on it.

**Comment by JoeCreates** [comment]
So the openfl side of this may require some work (presuming it is a sensible addition) to get into release, but here are some openfl/flixel branches with working native blend modes, in case anyone else needs this.

https://github.com/openfl/openfl/pull/2090
https://github.com/JoeCreates/flixel/commit/a54347512fef589a635050c8e9f343a79e8db875

**Comment by larsiusprime** [comment]
I believe this is fixed and merged into mainline OpenFL now:
https://github.com/openfl/openfl/commit/da3080406402f6dbd25b68496293b627d517e985

If someone wants to double verify this before closing, I think we're done here!

**Comment by JoeCreates** [comment]
Not quite, the flixel side will now need a little tweak and merging also. On it, now.
