### ISSUE TITLE
Can't build android app: libc.so not found

### ISSUE THREAD

**Issue by nightblade9** [HaxeFlixel/flixel#2213]
I tried several combinations of environments, hence multiple versions listed.

- **Haxe version:** 3.4.4, 3.4.7
- **Flixel version:** 4.5.1, 4.6.0
- **OpenFL version:** 8.6.4
- **Lime version:** 7.1.1, 7.2.1
- **Affected targets:** Android

________________________________

**Code snippet reproducing the issue**: TurnBasedRPG sample from `flixel create`

________________________________

**Observed behavior:** 
![image](https://user-images.githubusercontent.com/31222662/53699435-37249f80-3db6-11e9-9ae3-9df38aef3b1e.png)

**Expected behavior:** App runs fine.

---

I destroyed and rebuilt my HaxeFlixel environment, installing the latest everything: Flixel 4.6.0, OpenFL 8.6.4, Lime 7.1.1, hxcpp 3.4.49. (4.0.8 is the latest but doesn't compile against the rest of the stack.)

When I run `lime test android`, I get exactly this error from this Lime issue: https://github.com/openfl/lime/issues/685

The stated fix is to use a recent version of lime (greater than ~5.0.0 from what I can tell) along with the Android NDK > 12. I tried this with both Android NDK 8 and with the latest (19).

I can't get my app to build either (same error). What am I missing?

**Comment by Gama11** [comment]
HXCPP is not compatible with anything more recent than NDK r15c, try that one (although a newer one should lead to a different error). And HXCPP 4.0.8 should work just fine, but probably doesn't matter much for this.

Either way, this is not an issue with Flixel, but Lime/OpenFL (you can almost certainly reproduce this with one of their samples).

**Comment by nightblade9** [comment]
Okay. I will try downgrading my NDK. Since this is not a HaxeFlixel issue, I will close it.

I don't recall what error I got with HXCPP 4.0.8. Every rebuild of my app builds something under `/src/haxe` in what looks to me like the Haxe standard library. Some of those files fail with various compiler errors.
