### ISSUE TITLE
Text on button displayed twice on HashLink

### ISSUE THREAD

**Issue by MatusBako** [HaxeFlixel/flixel#2215]
- **Haxe version:** 4.0.0-rc.2
- **Flixel version:** 4.6.1
- **OpenFL version:** 8.9.0
- **Lime version:** 7.3.0
- **HashLink:** 1.9.0
- **Platform:** Linux
________________________________

**Observed behavior:** When I try to run example game [TurnBasedRPG](https://github.com/HaxeFlixel/flixel-demos/tree/dev/Tutorials/TurnBasedRPG) from flixel demos, the text on the buttons is displayed twice, as shown in the picture:

![hl](https://user-images.githubusercontent.com/24631113/56082648-87623900-5e1b-11e9-8aff-0b9097c90b20.png)

**Expected behavior:** The white text should not be there. The demo works fine when launched as C++ binary or under neko.

**Comment by Gama11** [comment]
Would be good if somebody could test try to reproduce this on Linux, as it works fine for me on Windows.

**Comment by AlexHaxe** [comment]
can confirm with latest Haxe and hashlink versions on Ubuntu 18.04 with Intel graphics

**Comment by Gama11** [comment]
@MatusBako Can you try this again with the new Lime 7.5.0 and OpenFL 8.9.1 releases? There were some HL-related fixes.

**Comment by MatusBako** [comment]
Works properly with the new updates.

**Comment by Gama11** [comment]
Awesome! 🎉
