### ISSUE TITLE
makeGraphic() not displaying sprite in Hashlink

### ISSUE THREAD

**Issue by MatusBako** [HaxeFlixel/flixel#2216]
- **Haxe version:** 4.0.0-rc.2
- **Flixel version:** 4.6.1
- **OpenFL version:** 8.9.0
- **Lime version:** 7.3.0
- **HashLink:** 1.9.0
- **Affected targets:** HashLink
- **Platform:** Linux (Mint 19)

________________________________

**Code snippet reproducing the issue**:
```haxe
class Player extends FlxSprite
{ 
   
    public function new(?X:Float=0, ?Y:Float=0)
    {
        super(X, Y);
        //loadGraphic(AssetPaths.player__png, true, 16, 16);
        makeGraphic(16, 16, FlxColor.BLUE);
        ...
    }
```

________________________________

**Observed behavior:** In [TurnBasedRPG](https://github.com/HaxeFlixel/flixel-demos/tree/dev/Tutorials/TurnBasedRPG) example in Player.hx, if you substitute loading player model with makeGraphic() call as shown above, nothing is displayed as the player model. The player can still move and interact with enviroment, but is basically invisible.

**Expected behavior:** 16*16px blue square should be displayed as player model.

**Comment by Gama11** [comment]
Can you try this again with the new Lime 7.5.0 and OpenFL 8.9.1 releases? There were some HL-related fixes.

**Comment by MatusBako** [comment]
Now it works as intended. Sprite is displayed properly.
