### ISSUE TITLE
Android Input Keys - BACK and MENU buttons

### ISSUE THREAD

**Issue by DrDerico** [HaxeFlixel/flixel#2218]
- **Haxe version:** 3.4.7
- **Flixel version:** 4.6.1
- **OpenFL version:** 8.9.0
- **Lime version:** 7.3.0
- **Affected targets:** Android

________________________________

**1.** 
Finally I moved from OpenFL 3.6.1 and Flixel 3.3.5 to the latest versions. And BANG! On Android the BACK button stops to work the way as it worked before.

I used FlxG.android.preventDefaultKeys(27) in my code.

So, after a big investigation I found where the problem was. In Lime 7.3.0 (and in the earlier versions) android codes for BACK button are changed from "27" (decimal) to "var APP_CONTROL_BACK = 0x4000010E;" and code of MENU button from "16777234" (decimal) to "var APP_CONTROL_SEARCH = 0x4000010C; ".

I made changes on my side in [flixel/input/android/FlxAndroidKeys.hx](flixel/input/android/FlxAndroidKeys.hx) and [flixel/input/android/FlxAndroidKey.hx](flixel/input/android/FlxAndroidKey.hx) by replacing old values to the new ones and it starts to work!

**2.**
I found that in 
[https://github.com/HaxeFlixel/flixel/blob/984124c41720ddb7b55ce4ed0a52978fd3c6ad2e/flixel/input/FlxKeyManager.hx#L278](https://github.com/HaxeFlixel/flixel/blob/984124c41720ddb7b55ce4ed0a52978fd3c6ad2e/flixel/input/FlxKeyManager.hx#L278) preventDefault is used only for #html5 target. But why???? Where is #android???

I suggest to add #android also, because whithout that BACK button event doesn't prevented on Android.

**Code snippet**:

```haxe
#if (html5 || android)
	event.preventDefault();
#end
```

________________________________

Sorry for English

**Comment by DrDerico** [comment]
Thank you!

**Comment by Tw1ddle** [comment]
Thanks, perhaps @JoeCreates or someone could commit the fix to Flixel itself :smile:

**Comment by Gama11** [comment]
@Tw1ddle Why not just open a PR yourself? ;)

I think we want to have conditionals for old OpenFL versions / the old values though, we haven't dropped OpenFL 3.6.1 support yet.

**Comment by Gama11** [comment]
Thanks for the investigation!
