### ISSUE TITLE
Cube button from debugger is not working on windows target

### ISSUE THREAD

**Issue by Tembac** [HaxeFlixel/flixel#2224]
- **Haxe version:** 3.4.7
- **Flixel version:** 4.6.2
- **OpenFL version:** 8.9.1
- **Lime version:** 7.5.0
- **Affected targets:**
Windows. 
Also tested HTML5 and it works fine.

________________________________

Press this button:
![image](https://user-images.githubusercontent.com/2808285/61145218-437be000-a4ad-11e9-9787-ab8f21ae8237.png)
________________________________

**Observed behavior:**

Everything slows down and the border lines for the sprites are not shown.

**Expected behavior:**

That it shows the borders for every sprite on the screen.

**Comment by Gama11** [comment]
Seems to work fine for me in the Mode demo on Neko. Does it reproduce there for you as well?

**Comment by Tembac** [comment]
This is strange but I tested Mode and it works fine. Later, I tested my project again and it is also working. I'm not sure what happened. Maybe my computer needed a weekend off, jaja.
