### ISSUE TITLE
FlxGroup camera issues caused by #2222

### ISSUE THREAD

**Issue by JoeCreates** [HaxeFlixel/flixel#2229]
#2222 did not account for mouse position on objects inside a group with a camera. It only implemented drawing to the gruops camera by default.

Fixing this could be a bit messy due to the existing position check logic being potentially scattered around.

**Comment by Gama11** [comment]
Does it make sense to revert the change for now?

**Comment by JoeCreates** [comment]
Yeah, revert it for now. I think the best solution would hit both rendering and update at the same time.

**Comment by JoeCreates** [comment]
Oh... I think I do actually have an easy solution. We could just do everything that was in this PR minus the changes to flxspritegroup.
