### ISSUE TITLE
[Suggestion] Change physics vars to FlxVector

### ISSUE THREAD

**Issue by Geokureli** [HaxeFlixel/flixel#2236]
Now that FlxVector is just an abstract of FlxPoint, and there's no runtime difference between the 2 types, I was wondering if it would be a good idea to convert flxSprite.velocity and acceleration to FlxVector. 

My assumption is that the only reason it's a FlxPoint right now is because these properties predate FlxVector and (until now) changing it would have broken some games(?). I find myself constantly casting velocity to a vector, and I think FlxVector isn't very well known to newer flixel users. This could increase visibility.

**Comment by AustinEast** [comment]
I'd like to suggest just deprecating `FlxPoint`, not sure why we even need both!

All of `FlxPoint`'s functionality could be moved into `FlxVector` and `FlxPoint` could become:
```
@:deprecated("FlxPoint is now FlxVector)
@:noCompletion
typedef Flxpoint = FlxVector;
```
And then in some future version of Flixel, `FlxPoint` could be removed altogether :)

**Comment by Geokureli** [comment]
I kinda like having the 2 separate classes. In a mathematical sense, points and vectors are different things, and flxpoint being lighter reduces bloat and noise in code completion

**Comment by AustinEast** [comment]
Yeah, in a mathematical sense they are different, but they really do represent the same data (X and Y).

In the end Flixel is a game framework that's supposed to be as simple and accessible as possible, and having both classes is making the flixel codebase more complex than it needs to be, especially to new users who may not understand how and why they need to cast. 

I can deal with a little bit of extra bloat in my autocomplete if it means the API in general is simpler 😉

**Comment by Geokureli** [comment]
case in point:
<img width="711" alt="Screen Shot 2019-10-07 at 5 08 49 PM" src="https://user-images.githubusercontent.com/2609513/66352528-4c057a80-e925-11e9-8549-46f88ca5e0bb.png">

**Comment by bhgsbatista** [comment]
@Gama11 any opinion on this? I am in favor of simplifying the code surface.

**Comment by bhgsbatista** [comment]
@Geokureli @AustinEast either of you interested in opening a PR for this?

**Comment by Gama11** [comment]
There already was one. https://github.com/HaxeFlixel/flixel/pull/2240

**Comment by Geokureli** [comment]
We could move FlxVector's methods into FlxPoint as @AustinEast suggested, that would prevent the v.x++ issue in 3.47, but we wouldn't be able to add operators to FlxVectors as suggested in #2239. 

I'm fine with this change if you guys are. We can keep a deprecated FlxVector to make this a non-breaking change

**Comment by radiatoryang** [comment]
Hello. Just bumping / +1'ing this issue. I'm a newcomer to HaxeFlixel and I was really confused why FlxPoint didn't have any vector math functions on it, and ended up kludging my own until I learned there was a FlxVector type and that I was supposed to cast FlxPoints into FlxVectors in order to do vector math? I know there are probably reasons for keeping FlxPoint around, but at least for me, coming from Unity C#, this was a weird distinction for me that felt unnecessary.

**Comment by Geokureli** [comment]
Time to revisit this, might merge FlxVector utils into FlxPoint

**Comment by Geokureli** [comment]
i did it
