### ISSUE TITLE
Unable to create new Projects

### ISSUE THREAD

**Issue by BronzeViper** [HaxeFlixel/flixel#2245]
- **Haxe version:** 4.0.2
- **Flixel version:** 4.6.3
- **OpenFL version:** 8.9.5
- **Lime version:** 7.6.3
![haxe](https://user-images.githubusercontent.com/55687227/70819409-31a3bd80-1dfc-11ea-9cb1-6e3e31f99106.png)

This error shows when i try to create new projects. The path somehow got mixed and I have no idea how to fix it.

**Comment by Gama11** [comment]
You have already reported this. https://github.com/HaxeFlixel/flixel-tools/issues/72
