### ISSUE TITLE
FlxButton: right click not working

### ISSUE THREAD

**Issue by filipp8** [HaxeFlixel/flixel#2246]
- **Haxe version:** 4.0.5
- **Flixel version:** git
- **OpenFL version:** git
- **Lime version:** git
- **Affected targets:** Neko, Windows

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.input.mouse.FlxMouseButton.FlxMouseButtonID;
import flixel.ui.FlxButton;
import flixel.FlxState;

class PlayState extends FlxState
{
	override public function create():Void
	{
		super.create();
		var button = new FlxButton(0, 0, "Press me", () -> trace("Pressed"));
		button.screenCenter();
		button.mouseButtons = [FlxMouseButtonID.LEFT, FlxMouseButtonID.RIGHT];
		add(button);
	}
}
```

________________________________

**Observed behavior:**
left button correctly traces Pressed
right button does nothing
if I swap left and right position in the array, right button correctly interact with the button (the button shows the pressed status) but won't fires clicked callback, while left button does nothing

**Expected behavior:**
Right click should work

**Comment by Gama11** [comment]
Wow, this must have been broken for a long time.

**Comment by Gama11** [comment]
Should be better now. I just hope I didn't break anything else in the process.

**Comment by filipp8** [comment]
> Should be better now. I just hope I didn't break anything else in the process.

It seems working.
I'll test the feature and report if something is wrong.
Thank you
