### ISSUE TITLE
[Regression on Mobile] Wrong button click on defaultCameras

### ISSUE THREAD

**Issue by filipp8** [HaxeFlixel/flixel#2248]
- **Flixel version:** commit 1063137
- **Affected targets:** IOS/Android

Don't know why but this breaks on mobile, both android/ios, and seems to be working on desktop (tested only on neko).
I think it is something wrong with zoom level.
I have three buttons on the top of my screen acting as toolbar and I trigger those buttons while tapping very far from them.

I have a 3 camera setup: `bgCamera`, `fieldCamera` and `hudCamera`.
I add every camera to `FlxG.cameras` and then set `FlxCamera.defaultCameras = [Reg.hudCamera];`
The problem is only present on `hudCamera` as the buttons with wrong behavior are shown in this camera.

The commit before this is working fine.

**Comment by Gama11** [comment]
@JoeCreates Could you have a look at this when you get a chance?

**Comment by JoeCreates** [comment]
Could I get some example code please?

You must have actually set a group's camera at some point in order for this
to be an issue I think.
