### ISSUE TITLE
`FlxG.keys.anyJustPressed([ANY])` returns false when `FlxG.keys.justPressed.ANY` return true

### ISSUE THREAD

**Issue by Geokureli** [HaxeFlixel/flixel#2249]
```hx
if (FlxG.keys.anyJustPressed([ANY]) != FlxG.keys.justPressed.ANY)
    throw"error";
```

I need this to work because a weird use case I'm dealing with, so I don't mind looking into it later

**Comment by Gama11** [comment]
>so I don't mind looking into it later

How much later? :D

**Comment by Geokureli** [comment]
I can look into this after the NG jam
