### ISSUE TITLE
Blank FlxText characters after adding diacritics as a parameter on Windows build

### ISSUE THREAD

**Issue by JasonNumberThirteen** [HaxeFlixel/flixel#2264]
- **Haxe version:** 4.1.2
- **Flixel version:** 4.8.1
- **OpenFL version:** 8.9.7
- **Lime version:** 7.8.0
- **Affected targets:** Windows (including Debug and Final "types")

________________________________

**Code snippet reproducing the issue**:

"_Main_":

```haxe
package;

import flixel.FlxGame;
import flixel.system.FlxAssets;
import lime.utils.Assets;
import openfl.display.Sprite;

class Main extends Sprite
{
	public function new()
	{
		FlxAssets.FONT_DEFAULT = Assets.getFont("assets/fonts/pressStart2P.ttf").name;

		super();
		addChild(new FlxGame(0, 0, PlayState));
	}
}
```

"_PlayState_"

```haxe
package;

import flixel.FlxState;

class PlayState extends FlxState
{
	override public function create()
	{
		super.create();

		var text = new flixel.text.FlxText(0, 0, 0, "ąęóy!", 16);

		text.screenCenter();

		add(text);
	}

	override public function update(elapsed:Float)
	{
		super.update(elapsed);
	}
}
```

________________________________

**Observed behavior:**
![windows-build](https://user-images.githubusercontent.com/40078536/88209725-707fd880-cc53-11ea-8892-416425a1427a.png)

No characters at all! Eventually most of characters are "eaten". This occurs **even after adding a font supporting diacritics**! Windows build.

**Expected behavior:**
![neko-build](https://user-images.githubusercontent.com/40078536/88209745-75448c80-cc53-11ea-87ec-d9b6c65a5516.png)

Displaying all characters, especially diacritics. Checked on Neko and HTML5, both were OK. **Only Windows fails**.

**Comment by MSGhero** [comment]
Can you try the dev version of OpenFL? I think this is fixed already. Not a flixel issue at least

**Comment by JasonNumberThirteen** [comment]
Works like a charm. Thanks for your suggestion! BTW, what is a reason of this mess?

**Comment by MSGhero** [comment]
The way Lime and OpenFL handled UTF text worked on Haxe3 but not Haxe4. This fix was already merged into the main branch, but a lot of fixes were reverted for some reason and haven't been merged back in yet.

**Comment by JasonNumberThirteen** [comment]
Sounds logical. Thanks for explanation!
