### ISSUE TITLE
FlxG.keys.justPressed not being called as the key is "just pressed"

### ISSUE THREAD

**Issue by fabtjar** [HaxeFlixel/flixel#2270]
- **Haxe version:** 4.1.3
- **Flixel version:** 4.8.1
- **OpenFL version:** 9.0.2
- **Lime version:** 7.8.0
- **Affected targets:** Neko, Html5, (not tried others)

________________________________

**Code snippet reproducing the issue**:

```haxe
if (FlxG.keys.justPressed.R)
    FlxG.switchState(new PlayState(levelNumber));
```

________________________________

**Observed behavior:** The button is triggered constantly when holding down the key and loading the same state.

**Expected behavior:** The button should only be triggered on the frame it is pressed. So it shouldn't check for buttons held down before the state is initialised.

**Comment by Gama11** [comment]
Inputs are reset on state switches by default. `FlxG.inputs.resetOnStateSwitch = false;` should do the trick.

**Comment by fabtjar** [comment]
Cheers @Gama11! Didn't know about that 🥇
