### ISSUE TITLE
addFormat() does not respect end

### ISSUE THREAD

**Issue by mjedmonds** [HaxeFlixel/flixel#2275]
- **Haxe version:** 4.1.3
- **Flixel version:** 4.8.1
- **OpenFL version:** 9.0.2
- **Lime version:** 7.8.0
- **Affected targets:** html5

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxState;

class PlayState extends FlxState
{
	override public function create():Void
	{
		var text = new FlxText();
		text.text = "Hello, this is some text";
		text.addFormat(new FlxTextFormat(FlxColor.RED), 4, 8);
		add(text);
	}
}
```

________________________________

**Observed behavior:**

Format is added from the 4th character to the end of the string. I believe this also causes bugs in `applyMarkup()` and potentially other formatting functions.

**Expected behavior:**

Format is added from the 4th character to the 8th character.

**Comment by mjedmonds** [comment]
This bug is fixed in the develop branch, so I would think this will be corrected in the next release

**Comment by Gama11** [comment]
In the develop branch of OpenFL you mean?

**Comment by mjedmonds** [comment]
Yes, apologies, this is fixed in the develop branch of OpenFL
