### ISSUE TITLE
No signal for when subState has been opened / closed.

### ISSUE THREAD

**Issue by ianharrigan** [HaxeFlixel/flixel#2279]
Hi,

It would be advantageous to know when a subState has been opened/closed but not in the openCallback of the substate itself but from its parent FlxState - similar to `memberAdded`/`memberRemoved` - currently im working around this by using an `FlxInputManager` to know when the state has changed then (even though its a sub state) and "stealing" the openCallback, similar to this:

```haxe
class InputManager implements IFlxInputManager {
    public function reset():Void {
        if (FlxG.state != null && FlxG.state.subState != null) {
            var cachedSubStateOpenedCallback = FlxG.state.subState.openCallback;
            FlxG.state.subState.openCallback = function() {
                trace("substate opened");
                if (cachedSubStateOpenedCallback != null) {
                    cachedSubStateOpenedCallback();
                }
            }
        }
    }
}
```
This works, but feels a little hacky, moreover, this _doesnt_ work if the parent FlxState has `persistentUpdate = true` because of:

```haxe
            if (!persistentUpdate)
                FlxG.inputs.onStateSwitch();
```
In `FlxState`, which is fine as in my workaround im misusing the `IFlxInputManager::reset` to know when the sub state is about to be created (so i can inject my own code into the `openCallback`). 

Im happy to make a PR for this which would be a new signal on `FlxState`, `subStateOpened` / `subStateClosed` which would fire at the very end of when the sub state has been created and shown. 

Is this an acceptable solution and if it is, is there a reason why it doesnt already exist? Some kind of gotcha?

Cheers,
Ian

**Comment by Gama11** [comment]
I think the only thing to watch out for is to initialize the signals lazily since most people will not need them (as it's been done with `memberAdded` / `memberRemoved`).

**Comment by ianharrigan** [comment]
OK, great, ill get a PR together then? I'll basically copy the way `memberAdded` / `memberRemoved` works.

**Comment by ianharrigan** [comment]
(Added a PR)
