### ISSUE TITLE
FlxBitmapFont.fromXNA causes an infinite loop on Brave Browser

### ISSUE THREAD

**Issue by Geokureli** [HaxeFlixel/flixel#2285]
More info coming soon, but it's definitely getting stuck here:
https://github.com/HaxeFlixel/flixel/blob/dev/flixel/graphics/frames/FlxBitmapFont.hx#L384

**Comment by Geokureli** [comment]
Furthermore, I'm seeing this because the default font apparently uses fromXNA, considering it uses these automatic pixel detection methods, perhaps we should swap it to something that relies more on hand crafted data, since graphic tools can vary widely?

**Comment by Geokureli** [comment]
I should mention that I don't see this issue in Brave when testing locally, nor do I get this issue when I run in Brave with the shield disabled. No effin clue why that is.

**Comment by Geokureli** [comment]
PR branch was closed; I plan to make a new PR with this branch's infinite loop prevention, later. I still say that should go in, even if the farbling detection doesn't. longer term we may want to reconsider using `fromXNA` for the default font as well

**Comment by Gama11** [comment]
Yes, I'm much more open to that. The part I was uncomfortable with was mostly adding new public API for a niche browser.
