### ISSUE TITLE
HaxeFlixel not working with Haxe 4.2.0

### ISSUE THREAD

**Issue by Abdel-Fattah-Radwan** [HaxeFlixel/flixel#2294]
- **Haxe version:** 4.2.0
- **Flixel version:** 4.8.1
- **OpenFL version:** 9.0.2
- **Lime version:** 7.8.0
- **Affected targets:** All
________________________________

**Code snippet reproducing the issue**:

`lime test neko`

________________________________

**Observed behavior:**

C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1810: characters 22-28 : lime.utils.Float32Array should be 
lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1810: characters 22-28 : ... For function argument 'params'C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1815: characters 22-28 : lime.utils.Float32Array should be 
lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1815: characters 22-28 : ... For function argument 'params'C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1831: characters 24-30 : lime.utils.UInt32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1831: characters 24-30 : ... For function argument 'params'C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1836: characters 24-30 : lime.utils.Int32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1836: characters 24-30 : ... For function argument 'params'C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1841: characters 24-30 : lime.utils.Int32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1841: characters 24-30 : ... For function argument 'params'C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeWindow.hx:143: characters 5-23 : lime._internal.backend.native.NativeOpenGLRenderContext should be lime.graphics.OpenGLES2RenderContext
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeWindow.hx:144: characters 5-23 : lime._internal.backend.native.NativeOpenGLRenderContext should be lime.graphics.WebGLRenderContext
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeWindow.hx:150: characters 6-24 : lime._internal.backend.native.NativeOpenGLRenderContext should be lime.graphics.OpenGLES3RenderContext
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeWindow.hx:151: characters 6-25 : lime._internal.backend.native.NativeOpenGLRenderContext should be lime.graphics.WebGL2RenderContext
C:/HaxeToolkit/haxe/lib/openfl/9,0,2/packages/utils/src/openfl/utils/ByteArray.hx:750: characters 3-30 : openfl.utils.ByteArray should be lime.utils._Bytes.LimeBytes
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4740: characters 74-75 : lime.utils.Float32Array should be lime.utils.DataPointerC:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4740: characters 74-75 : ... For function argument 'v'
C:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/group/FlxGroup.hx:473: characters 80-91 : Type not found : ObjectClass
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/math/ColorMatrix.hx:117: characters 12-17 : lime.math.ColorMatrix should be Null<lime.utils.ArrayBufferView>     
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/math/ColorMatrix.hx:117: characters 12-17 : ... For optional function argument 'view'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:2313: characters 36-42 : lime.utils.Int32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:2313: characters 36-42 : ... For function argument 'params'C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:2319: characters 36-42 : lime.utils.Float32Array should be 
lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:2319: characters 36-42 : ... For function argument 'params'C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4617: characters 63-64 : lime.utils.Float32Array should be lime.utils.DataPointerC:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4617: characters 63-64 : ... For function argument 'v'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4631: characters 64-65 : lime.utils.Int32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4631: characters 64-65 : ... For function argument 'v'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4639: characters 66-67 : lime.utils.UInt32Array should be lime.utils.DataPointer 
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4639: characters 66-67 : ... For function argument 'v'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4655: characters 70-71 : lime.utils.Float32Array should be lime.utils.DataPointerC:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4655: characters 70-71 : ... For function argument 'v'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4669: characters 71-72 : lime.utils.Int32Array should be lime.utils.DataPointer  
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4669: characters 71-72 : ... For function argument 'v'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4678: characters 73-74 : lime.utils.UInt32Array should be lime.utils.DataPointer 
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4678: characters 73-74 : ... For function argument 'v'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4696: characters 80-81 : lime.utils.Float32Array should be lime.utils.DataPointerC:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4696: characters 80-81 : ... For function argument 'v'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4712: characters 81-82 : lime.utils.Int32Array should be lime.utils.DataPointer  
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4712: characters 81-82 : ... For function argument 'v'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4721: characters 83-84 : lime.utils.UInt32Array should be lime.utils.DataPointer 
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4721: characters 83-84 : ... For function argument 'v'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4757: characters 75-76 : lime.utils.Int32Array should be lime.utils.DataPointer  
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4757: characters 75-76 : ... For function argument 'v'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4767: characters 77-78 : lime.utils.UInt32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4767: characters 77-78 : ... For function argument 'v'
C:/HaxeToolkit/haxe/lib/openfl/9,0,2/packages/stage3d/src/openfl/display3D/VertexBuffer3D.hx:113: characters 41-45 : openfl.utils.ByteArray should be Null<Int>
C:/HaxeToolkit/haxe/lib/openfl/9,0,2/packages/stage3d/src/openfl/display3D/VertexBuffer3D.hx:113: characters 41-45 : ... For optional function argument 'elements'
C:/HaxeToolkit/haxe/lib/openfl/9,0,2/packages/stage3d/src/openfl/display3D/VertexBuffer3D.hx:113: characters 41-45 : ... For function argument 'data'        
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/math/Matrix4.hx:235: characters 12-17 : lime.math.Matrix4 should be Null<lime.utils.ArrayBufferView>
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/math/Matrix4.hx:235: characters 12-17 : ... For optional function argument 'view'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/media/OpenALAudioContext.hx:573: characters 3-40 : lime.media.openal.ALBuffer should be Int
C:/HaxeToolkit/haxe/lib/openfl/9,0,2/packages/sound/src/openfl/media/Sound.hx:591: characters 37-42 : openfl.utils.ByteArray should be Null<Int>
C:/HaxeToolkit/haxe/lib/openfl/9,0,2/packages/sound/src/openfl/media/Sound.hx:591: characters 37-42 : ... For optional function argument 'elements'
C:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/group/FlxGroup.hx:852: characters 19-30 : Type not found : ObjectClass
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/text/harfbuzz/HBBlob.hx:47: characters 3-48 : Float should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/text/harfbuzz/HBBlob.hx:56: characters 3-57 : Float should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/system/frontEnds/PluginFrontEnd.hx:47: characters 19-28 : Type not found : ClassType
C:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/system/frontEnds/PluginFrontEnd.hx:94: characters 20-29 : Type not found : ClassType
C:/HaxeToolkit/haxe/lib/openfl/9,0,2/packages/bitmapdata/src/openfl/display/BitmapData.hx:1885: characters 45-54 : openfl.utils.ByteArray should be lime.utils.BytePointer
C:/HaxeToolkit/haxe/lib/openfl/9,0,2/packages/bitmapdata/src/openfl/display/BitmapData.hx:1885: characters 45-54 : ... For function argument 'bytePointer'   
C:/HaxeToolkit/haxe/lib/openfl/9,0,2/packages/assets/src/openfl/utils/AssetLibrary.hx:47: characters 52-57 : openfl.utils.ByteArray should be lime.utils.Bytes
C:/HaxeToolkit/haxe/lib/openfl/9,0,2/packages/assets/src/openfl/utils/AssetLibrary.hx:47: characters 52-57 : ... For function argument 'bytes'
C:/HaxeToolkit/haxe/lib/openfl/9,0,2/packages/assets/src/openfl/utils/AssetLibrary.hx:293: characters 38-43 : openfl.utils.ByteArray should be lime.utils.Bytes
C:/HaxeToolkit/haxe/lib/openfl/9,0,2/packages/assets/src/openfl/utils/AssetLibrary.hx:293: characters 38-43 : ... For function argument 'bytes'

**Expected behavior:**

The `lime test neko` command should run without issues.

**Comment by Gama11** [comment]
Yes, but not much we can do about it other than waiting for OpenFL and Lime to be updated.

**Comment by Abdel-Fattah-Radwan** [comment]
> Yes, but not much we can do about it other than waiting for OpenFL and Lime to be updated.

Okay, thanks for your reply.

**Comment by Abdel-Fattah-Radwan** [comment]
Issue not directly related to HaxeFlixel.
