### ISSUE TITLE
Haxe 3.4.7 backwards compatibility

### ISSUE THREAD

**Issue by Geokureli** [HaxeFlixel/flixel#2297]
Made this issue because I wanted to understand more about Haxeflixel's support for haxe versions earlier than 4. We know that there are still a lot of devs that have not updated their projects to haxe 4, yet. I know a few HaxeFlixel devs still using it. What I don't know is if any of these people are using latest HF with 3.4.7.

I know that the Lime backend for Switch doesn't yet work for haxe 4, but I don't know if there is also a hard limit on the version of Lime, OpenFL or HaxeFlixel. Can @larsiusprime shed some light on that? I plan to eventually become a Switch Haxe developer, so I'm definitely curious about how that works

What other concerns does haxeflixel have regarding backwards compatibility? do We always assume that latest HF devs also have latest OpenFL/Lime? do we assume that 3.4.7 devs use a specific openfl/lime version?

@Gama11 brought up the idea of dropping 3.4.7 support so I was looking to understand more about it. ReadOnlyArrays would be pretty handy in flixel but I don't think it would make a huge difference, tbh.

**Comment by Geokureli** [comment]
@Gama11 no one seems to care, how do you feel about dropping 3.4.7 support?

**Comment by Gama11** [comment]
I don't really care either. 😄

**Comment by Geokureli** [comment]
I thought FlxDirections would require dropping 3.4.7, that's why I asked. but I was able to make it work. lets just wait until a new feature benefits from dropping 3.4.7, I guess

**Comment by Geokureli** [comment]
@Gama11 does this mean we've officially dropped 3.4.7?

**Comment by Gama11** [comment]
> if this was to prevent the CI issues

That was the plan, I had forgotten how recent isOfType is. But it seems about time to finally drop 3.4 support anyway.

As for fixing CI, ideally somebody creates a PR that fixes firetongue's backwards compatiblity.

**Comment by Geokureli** [comment]
> As for fixing CI, ideally somebody creates a PR that fixes firetongue's backwards compatiblity.

https://github.com/larsiusprime/firetongue/pull/47
Done
