### ISSUE TITLE
Falling Letters on the Flixel Debugger

### ISSUE THREAD

**Issue by TheHENOOB** [HaxeFlixel/flixel#2302]
- **Haxe version:** 4.2.1
- **Flixel version:** 4.9.0
- **OpenFL version:** 9.1.0
- **Lime version:** 7.9.0
- **Affected targets:** Neko and HTML5

I recently updated haxe and all the librarys to the most recent version but when i open the flixel debugger the letters falls on the screen
![image](https://user-images.githubusercontent.com/74883505/115479787-8d1b6200-a21f-11eb-8c41-d7c8cde663f1.png)
The only unaffected target was Flash that works correctly
![image](https://user-images.githubusercontent.com/74883505/115480180-5bef6180-a220-11eb-949b-d14987ff1805.png)

**Comment by Gama11** [comment]
That's an OpenFL bug. I think it's already fixed by https://github.com/openfl/openfl/pull/2487 but not released.

**Comment by TheHENOOB** [comment]
I will close issue then, not about HaxeFlixel
