### ISSUE TITLE
FlxSpriteGroup's revive() will never call revive() on its children (i.e. its group's members)

### ISSUE THREAD

**Issue by TripleSmeven** [HaxeFlixel/flixel#2306]
So I expected that calling `revive()` on an FlxSpriteGroup will also call `revive()` on all its children, just like calling `revive()` on FlxGroup does. But that's not the case.

See for yourself:

```
import flixel.FlxState;
import flixel.group.FlxSpriteGroup;

class PlayState2 extends FlxState
{
	override public function create()
	{
		var parent = new Parent();
		add(parent);
		parent.kill();
		parent.revive();
	}
}

class Parent extends FlxSpriteGroup
{
	public function new()
	{
		super();
		add(new Member());
	}

	override public function revive()
	{
		trace('revive in Parent');
		super.revive();
	}
}

class Member extends FlxSpriteGroup
{
	public function new()
	{
		super();
	}

	override public function revive()
	{
		trace('revive in Member');
		super.revive();
	}
}
```

If you run this, you'll see that "revive in Member" is never printed, meaning `member.revive()` was never called, even though `parent.revive()` was called.

Why does this happen? Let's look at FlxSpriteGroup's revive.
```
	override public function revive():Void
	{
		super.revive();
		group.revive();
	}
```
`super.revive()` ends up calling FlxSpriteGroup's set_exists, which actually sets the `exists` attribute on its children to `true`. So what happens when we call `group.revive()` immediately after? Let's look at FlxGroup's revive().
```
	override public function revive():Void
	{
		var i:Int = 0;
		var basic:FlxBasic = null;

		while (i < length)
		{
			basic = members[i++];

			if (basic != null && !basic.exists) // <---- see this check?
				basic.revive();
		}

		super.revive();
	}
```

As you can see, there's actually a check to see if the children exists before calling revive on it. But since FlxSpriteGroup's set_exists already made all its children exists, the children will fail this check inside the group's revive call. This means revive() will never be called on the children.

Is the intention of FlxSpriteGroup's revive to also call the revive on the children? It seems so, or else why call group.revive? But the set_exists (and the set_alive) setters already achieve the "revival" for the children, so it seems weird to still call group.revive. Because group.revive doesnt even call revive on the children anyways.

**Comment by Geokureli** [comment]
honestly, FlxSpriteGroup has a ton of caveats, particularly with exists flags. I always override it to remove some of them, like so:
```hx
class SpriteGroup extends FlxSpriteGroup
{
	public function new (x = 0.0, y = 0.0, maxSize = 0)
	{
		super(X, Y, maxSize);
		autoBounds = false;
	}
	
	// Don't set children's exist
	override function set_exists(Value:Bool):Bool
	{
		return exists = Value;
	}
	
	// similar to super but doesn't check exists
	override function set_x(Value:Float):Float
	{
		if (!_skipTransformChildren && x != Value)
		{
			var offset:Float = Value - x;
			transformChildren(xTransform, offset);
		}
		
		return x = Value;
	}
	
	// similar to super but doesn't check exists
	override function set_y(Value:Float):Float
	{
		if (!_skipTransformChildren && y != Value)
		{
			var offset:Float = Value - y;
			transformChildren(yTransform, offset);
		}
		
		return y = Value;
	}
}
```
