### ISSUE TITLE
Type not found: FlxG

### ISSUE THREAD

**Issue by bacc-studio** [HaxeFlixel/flixel#2307]
- **Haxe version:** 4.1.5
- **Flixel version:** 4.9.0
- **OpenFL version:** 9.1.0
- **Lime version:** 7.9.0
- **Affected targets:** I'm a noob at Haxe/HaxeFlixel so I don't know what this means

________________________________

**Code snippet reproducing the issue**:

```haxe
	override public function update(elapsed:Float)
	{
		super.update(elapsed);
        if (FlxG.keys.justPressed.F)
            FlxG.fullscreen = !FlxG.fullscreen;

	}
}
```

________________________________

**Observed behavior:** `source/PlayState.hx:19: characters 13-17 : Type not found : FlxG`

**Expected behavior:** (Runs fine)

**Comment by Gama11** [comment]
That's a problem with your setup, not with flixel. This sort of question is better suited for Discord (see link in our readme: https://discord.com/invite/rqEBAgF).
