### ISSUE TITLE
Move HaxeFlixel forums to Github Discussions

### ISSUE THREAD

**Issue by RichardBray** [HaxeFlixel/flixel#2308]
For those of you who regularly visit the [forums](http://forum.haxeflixel.com/) to help new HaxeFlixel devs with issues, you'll realise it's been down for months which isn't great :(

There's loads of good content out there which no one will be able to find unless they use wayback machine or something. It's pretty tough to rollout your own forum and keep supporting that as life happens so I suggest we use [GitHub Discussions](https://docs.github.com/en/discussions).

It's pretty easy to setup and we can start using it right away. The only risk is I don't know if it's possible to migrate existing threads from the old forum into Github Discussions, but I'm happy to look into it if we're happy to go ahead with this plan.

**Comment by Gama11** [comment]
I actually considered this as well. Doesn't seem like the worst idea, but not sure what to do about existing threads.

**Comment by RichardBray** [comment]
Yeah, I think that's the main issue with this. We'll need to look into some sort of way to export and import the data 🤔 
I'll do some digging.

**Comment by RichardBray** [comment]
So it doesn't look like there's an easy way to do it. There's a claim it might be able to be done with the Github desktop app but I'm a bit skeptical. I think if there's a way to export thing as a JSON file there might be a way to automatically add the threads with selenium or something, but the dates will be all wrong but I don't think it's worth it.

IMO having any forum is better than having no forum 🤷

**Comment by Gama11** [comment]
Alright, let's give it a try.

https://github.com/HaxeFlixel/flixel/discussions

I have to admit, I quite like that you can convert issues to discussions.

**Comment by RichardBray** [comment]
Nice, also I don't have to check the forums everyday to delete spambot accounts 😁
