### ISSUE TITLE
Add access instructions on all FlxG FrontEnd singletons

### ISSUE THREAD

**Issue by Geokureli** [HaxeFlixel/flixel#2310]
![image](https://user-images.githubusercontent.com/2609513/120711796-a5b0a600-c474-11eb-92bb-3b0c0aed9ed4.png)
Seen this question a number of times on forums and discord, and I myself have struggled with patterns like this on other libraries.

https://api.haxeflixel.com/flixel/system/frontEnds/SoundFrontEnd.html
I assume, if we add a doc comment to the class header it will show up at the top of this page, right? Let's make sure all the FlxG singletons specify how to globally access these instances.

**Comment by Gama11** [comment]
Makes sense.
