### ISSUE TITLE
Debugger Stats isn't displaying memory, update, and draw correctly

### ISSUE THREAD

**Issue by Tekkunsan** [HaxeFlixel/flixel#2366]
- **Haxe version:** 4.2.1
- **Flixel version:** 4.9.0
- **OpenFL version:** 9.1.0
- **Lime version:** 7.9.0
- **Affected targets:** Windows/Hashlink

________________________________

**Observed behavior:**
![haxeflixel-issue (2)](https://user-images.githubusercontent.com/35391378/127637050-d584b775-b306-4307-8135-fc72175ac0b6.jpg)

**Expected behavior:** Debugger Stats should be displaying the memory consumption, update, and draw

**Comment by Gama11** [comment]
See https://github.com/HaxeFlixel/flixel/issues/2302
