### ISSUE TITLE
updateHitbox() does not work for FlxBitmapText after scaling

### ISSUE THREAD

**Issue by brettchalupa** [HaxeFlixel/flixel#2413]
- **Haxe version:** 4.2.3
- **Flixel version:** 4.10.0
- **OpenFL version:** 9.1.0
- **Lime version:** 7.9.0
- **Affected targets:** web, neko, (all?)

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxG;
import flixel.FlxSprite;
import flixel.FlxState;
import flixel.text.FlxBitmapText;
import flixel.util.FlxColor;

class PlayState extends FlxState
{
	override public function create():Void
	{
		super.create();

		FlxG.camera.bgColor = FlxColor.WHITE;

		var bt = new FlxBitmapText();
		bt.setPosition(40, 40);
		bt.autoUpperCase = true;
		bt.text = "bitmap text rules!!!";
		bt.useTextColor = true;
		bt.textColor = 0xff000000;
		bt.scale.set(2, 2);
		bt.updateHitbox();
		FlxG.debugger.track(bt, "bt");
		add(bt);

		var sprite = new FlxSprite(40, 80).makeGraphic(32, 32, FlxColor.ORANGE);
		sprite.scale.set(2, 2);
		sprite.updateHitbox();
		FlxG.debugger.track(sprite, "sprite");
		add(sprite);
	}

	override public function update(elapsed:Float):Void
	{
		super.update(elapsed);
	}
}

```

________________________________

**Observed behavior:**

`updateHitbox()` does not update the hitbox (width, height, offset), it maintains the 1x value. The hitbox in the debugger is the 1x size, not 2x.

**Expected behavior:**

Width and height of the bitmap text to be doubled, like it does with sprite.

**More details:**

Screenshot of the behavior with the debugger open:

<img width="872" alt="FlxBitmapText Hitbox Bug" src="https://user-images.githubusercontent.com/928367/134558516-2c2355c0-3d7c-4ed7-94a7-0c09ec02c19a.png">

I'm not sure what's causing this. Any help would be appreciated! I've looked at the source, and I'd like to help fix it, but I'm not quite sure what to do. As you can see in the sample and screenshot, sprites scale fine and have their hitbox updated, so it seems potentially related to [`FlxBitmapText.hx`'s implementation](https://github.com/HaxeFlixel/flixel/blob/0a56aa1cb839ab692b7faab40804bfd5e302a78e/flixel/text/FlxBitmapText.hx).

*Edit to add more details on use case:* When using `FlxBitmapText`, I'd like to be able to scale the instances since there's not explicit text sizing control like there is with an embedded font. But without being able to have the height, width, and offset vals update, it's challenging to properly position the instances and layout other sprites based on the width and height of the scaled bitmap text.

Thanks!

**Comment by Geokureli** [comment]
Out of curiosity does it work as expected if you put the line: `bt.width = bt.width;` before `bt.updateHitbox();`?

**Comment by brettchalupa** [comment]
@Geokureli that sure does fix it, awesome! Happy to PR that change. Thank you!

**Comment by brettchalupa** [comment]
I applied the change to `FlxBitmapText`, like this:

``` haxe
override public function updateHitbox():Void
{
    computeTextSize();
    super.updateHitbox();
}
```

And that doesn't do the trick. This does though:

``` haxe
override public function updateHitbox():Void
{
    computeTextSize();
    width = width;
    super.updateHitbox();
}
```

That seems kinda weird though, so I won't PR it yet and will keep experimenting.

**Comment by Geokureli** [comment]
try `checkPendingChanges()` instead of `computeTextSize()`

**Comment by brettchalupa** [comment]
@Geokureli Thanks for the fix! 🙌
