### ISSUE TITLE
Changing the pitch of the music can unbalance the loop

### ISSUE THREAD

**Issue by Cheemsandfriends** [HaxeFlixel/flixel#2468]
- **Haxe version:** 4.2.4
- **Flixel version:** 4.10.0
- **OpenFL version:** 9.1.0
- **Lime version:** 7.9.0
- **Affected targets: (At least on what I tried) Hashlink and Windows

```haxe
package;

import flixel.FlxState;
import flixel.FlxG;
import lime.media.openal.AL;

class PlayState extends FlxState
{
        var pitch:Float = 1
	override public function create():Void
	{
		FlxG.sound.playMusic(AssetPaths.Music__ogg);
	}

        override public function update(elapsed:Float)
	{
		if (FlxG.keys.pressed.UP)
		{
			pitch += 0.05;
		}
		if (FlxG.keys.pressed.DOWN)
		{
			pitch -= 0.05;
		}
		@:privateAccess
		AL.sourcef(FlxG.sound.music._channel.__source.__backend.handle, AL.PITCH, pitch);
       }
}
```
If you change the pitch the length will remain the same, So if your pitch is high, your song finishes and the loop starts a few seconds later or if your pitch is low, the song will be interrupted at some point, and doesn't let the sound reproduce correctly.

What should be doing is that the length of the music may variate depending on the pitch.

**Comment by Geokureli** [comment]
There is no official support for pitch change in flixel, yet. Even the PR for openfl isn't ready, hence why you're using `@:privateAccess`

once openfl  supports it we can implement it with flixel's looping system

**Comment by Cheemsandfriends** [comment]
@Geokureli Oh, So it isn't a flixel-only problem but a openfl problem?
I'll close the issue since it doesn't make any sense to be here.

**Comment by Cheemsandfriends** [comment]
But my guess it's that the length of the sound should be looked tho.
The length of the sound will be always the same, no matter the Pitch.
But this is more like a duration change problem most of all

**Comment by Geokureli** [comment]
I mean it may be a problem we need to fix in flixel soon, but we won't touch it until openfl exposes pitch fields and that whole feature is completed and released

**Comment by Cheemsandfriends** [comment]
Maybe I should make this issue on openfl instead so that they can see what they could do maybe?

**Comment by Cheemsandfriends** [comment]
> I mean it may be a problem we need to fix in flixel soon, but we won't touch it until openfl exposes pitch fields and that whole feature is completed and released

Ok, So I made a Pull Request in the Native Backend making a rough Solution of the thing.

Maybe I should reopen this as `Bring Back the pitch function` because I saw a pitch function with openfl legacy, which idk what is it. Maybe it's the old versions of openfl lol
