### ISSUE TITLE
Make FlxRandom portable

### ISSUE THREAD

**Issue by NQNStudios** [HaxeFlixel/flixel#2469]
After some digging, it seems like `FlxRandom.hx` might be the best cross-platform RNG implementation in pure Haxe. I actually want to use it for projects that go beyond HaxeFlixel -- but this doesn't work currently because FlxRandom.hx references flash types (all indirectly, through FlxG, FlxSprite, etc.)

By editing the source directly in my haxelib folder, I was able to add just a few `#if flash` directives that made it possible for me to add `-lib flixel` to a non-flixel project and import FlxRandom for my purposes. Maybe this would be useful to others too? Would a PR be welcome for this?

**Comment by Geokureli** [comment]
I would just copy it into your project and manually remove the refs to other flixel classes. frankly I'm not a fan of FlxRandom compared to most proprietary RNG libs I've used

**Comment by Gama11** [comment]
>I would just copy it into your project and manually remove the refs to other flixel classes.

Agree with @Geokureli, that seems better.
