### ISSUE TITLE
Memory leak when updating a FlxText's text

### ISSUE THREAD

**Issue by Stilic** [HaxeFlixel/flixel#2505]
- **Haxe version:** 4.2.4
- **Flixel version:** 4.10.0
- **OpenFL version:** 9.1.0-LqBuHo
- **Lime version:** 7.9.0
- **Affected targets:** windows

________________________________

[**The file where there is the issue**](https://github.com/Stilic/Forever-Modding/blob/master/source/meta/state/ChartingState.hx)

________________________________

**Observed behavior:**
*Before:*
![image](https://user-images.githubusercontent.com/63605602/156229132-c121f434-cf20-4318-b62a-7596eec785f4.png)
*After:*
![image](https://user-images.githubusercontent.com/63605602/156230038-3ee4a892-f513-4a05-bc15-d244347a2268.png)

The memory is gradually filled for no reason when playing the current song.
I think this is related to the update of the FlxText used for display informations about the song.

**Comment by Geokureli** [comment]
Can you make a smaller reproduction of this issue? for all I know it's Funkin code causing the issue, and this is a Funkin issue and not a FlxText issue
