### ISSUE TITLE
Type not found : JoystickEvent and openfl.gl.GL

### ISSUE THREAD

**Issue by McJonnycat** [HaxeFlixel/flixel#2516]
- **Haxe version:** 4.2.4
- **Flixel version:** 4.11.0
- **OpenFL version:** 9.1.0
- **Lime version:** 7.9.0
- **Affected targets:**
 macos Monterey 
  
/usr/local/lib/haxe/lib/flixel/4,11,0/flixel/system/frontEnds/BitmapFrontEnd.hx:13: characters 8-20 : Type not found : openfl.gl.GL
/usr/local/lib/haxe/lib/flixel/4,11,0/flixel/input/gamepad/FlxGamepadManager.hx:10: characters 8-35 : Type not found : openfl.events.JoystickEvent
/usr/local/lib/haxe/lib/flixel/4,11,0/flixel/input/gamepad/FlxGamepadManager.hx:462: characters 39-52 : Type not found : JoystickEvent

**Comment by McJonnycat** [comment]
it was a friday night funkin  build

**Comment by Geokureli** [comment]
Sorry but all of your version info matches mine and I see nothing wrong, it must be something in your project.xml

Note that [the openfl.gl.GL import](https://github.com/HaxeFlixel/flixel/blob/dev/flixel/system/frontEnds/BitmapFrontEnd.hx#L13) is wrapped in `#if opengl_legacy` which is normally not enabled, but seems to be enabled in your project.

**Comment by McJonnycat** [comment]
thx
