### ISSUE TITLE
Nightly builds failing

### ISSUE THREAD

**Issue by Geokureli** [HaxeFlixel/flixel#2534]
started with recent PRs, unit tests and coverage tests are failing with the message:
```
  > haxelib run munit gen
  Warning: Repository requires reformatting. To reformat, run `haxelib fixrepo`.
  Massive Unit - Copyright 2022 Massive Interactive. Version 2.3.5
  Error: std@put_env
```
`haxelib fixrepo` may be a red herring. If anyone knows more about this please let me know

**Comment by tobil4sk** [comment]
The `haxelib fixrepo` is indeed a red herring in this situation, you can read more about it here: https://github.com/HaxeFoundation/haxelib/wiki/Reformatting-and-the-%22fixrepo%22-command

And for the issue itself, if you are running haxe nightly builds, you'll have to use neko nightly as well, as there was a patch to `std@put_env`.

**Comment by Geokureli** [comment]
is `Error: std@put_env` unrelated to the `haxelib run munit gen` command entirely? I see it's failing with the same error after `haxelib run flixel-tools bp html5 -dir haxeflixel-mechanics -Dno-deprecation-warnings` as well, even though all the tests run successfully, (link below)
https://github.com/HaxeFlixel/flixel/runs/6011947140?check_suite_focus=true

> you'll have to use neko nightly as well
I notice all targets are failing, not just neko, is neko used for all target tests?

**Comment by tobil4sk** [comment]
When `haxelib run` is executed, it sets environment variables, e.g. `HAXELIB_RUN_NAME` to the name of the library, which is why the error is happening after that command. And haxelib runs on neko, which is why it's failing everywhere.

After it finishes running, it tries to remove the variable by setting it to null, however, this fails with non nightly versions of neko due to a bug.

**Comment by Geokureli** [comment]
looks like I need to use the nightly neko version to test nightly haxe, thanks tobil4sk!
https://github.com/HaxeFlixel/setup-flixel/blob/master/src/Main.hx
