### ISSUE TITLE
FlxSave overhaul

### ISSUE THREAD

**Issue by Geokureli** [HaxeFlixel/flixel#2539]
> I think we could eliminate the most needs to rebind, or ever call bind in general by setting web's default binding to bind(appTitle, urlDomainName). It should also check bind("flixel", null) as well for backwards compatibility.
> 
> Right now FlxSave's intended use isn't very inutitive for web. I always call bind with custom args because of this and I assume it's the norm among web devs (at least the ones aware of this issue)

quote from #2396

## Breaking changes
Should be none, existing games that called `bind` with specific args will still work, and games that didn't should still check the old save path before copying over to the new default path

**Comment by Cheemsandfriends** [comment]
What I'm thinking is not needing to rebind the thing with adding the name of the game plus the name of the guy who made it, instead of doing it by title and url cos it might lose all shit if you try to change of url?

**Comment by Cheemsandfriends** [comment]
And if the game or the name company has any illegal characters, then change it to flx and inform the user about it in the log

**Comment by Geokureli** [comment]
I actually started working on this yesterday and came to the same conclusion, making:
```hx
var meta = stage.application.meta;
var company = meta["company"];
if (company == null)
	company == "HaxeFlixel";

var name = meta["name"];
if (name == null)
	name == meta["file"];

var invalidChars = ~/[ ~%&\\;:"',<>?#]/;
company = invalidChars.split(company).join("-");
name = invalidChars.split(name).join("-");

save.bind(company, name);
```

but I also want to load the old `save.bind("flixel")` data and merge that into the new data, to avoid causing lost data on old games

**Comment by Cheemsandfriends** [comment]
That's kinda tricky, cos the flixel save bind might be not only on one game, but on more than one

**Comment by Geokureli** [comment]
luckily the old save will never overwrite any data on the new one, so you may have some extra data then expected, but that would happen with the old saving, too

But yeah I hadn't considered that the flixel save is a mix of game saves

**Comment by Geokureli** [comment]
what suggestion?

**Comment by Geokureli** [comment]
what suggestion?

**Comment by Cheemsandfriends** [comment]
the instead of making url and shit, doing it by name and company
nvm, I guess I didn't understand the sentence ig lmao

**Comment by Geokureli** [comment]
we had the same idea. we are both geniuses, plain and simple

**Comment by Geokureli** [comment]
we had the same idea. we are both geniuses, plain and simple

**Comment by Cheemsandfriends** [comment]
Oh
😊
