### ISSUE TITLE
How destroy function works? FlxSave

### ISSUE THREAD

**Issue by fistiG** [HaxeFlixel/flixel#2567]
- **Haxe version:** 4.2.5
- **Flixel version:** 4.,11.0
- **OpenFL version:** 9.1.0
- **Lime version:** 7.9.0
- **Affected targets:** Windows

I want to delete my save like this:
```haxe
FlxG.save.destroy();
```
But it doesn't work. How to make it work? I'm just so dumb sorry ;(

P.S.
```haxe
FlxG.save.erase();
```
It doesn't work correctly for me

**Comment by Geokureli** [comment]
destroy clears the FlxSave instance but not the actual local saved data in long term memory. erase will delete the save. What do you mean by "it doesn't work correctly"?

**Comment by fistiG** [comment]
nvm I fixed my problem.

**Comment by Geokureli** [comment]
Can you share what the problem and solution was, for future people having the same issue?
