### ISSUE TITLE
How do I clear VRAM and RAM?

### ISSUE THREAD

**Issue by TheRealJake12** [HaxeFlixel/flixel#2598]
- **Haxe version:** 4.2.5
- **Flixel version:** 4.11.0
- **OpenFL version:** Latest?
- **Lime version:** 7.9.0
- **Affected targets:**
Windows
________________________________

What is the best way to clear VRAM. A project I work on uses 1.5GB and my GPU only has 2.0GB. It then crashes when the VRAM gets really high. `remove(asset);` doesnt clear the VRAM so any other fix?

________________________________

**Observed behavior:**
`remove(asset);` not removing things in VRAM or normal RAM.
**Expected behavior:**
`remove(asset);` clearing VRAM and RAM.

**Comment by ACrazyTown** [comment]
Did you try destroying the asset via `asset.destroy()`?

**Comment by TheRealJake12** [comment]
> Did you try destroying the asset via `asset.destroy()`?

yeah but Ill try again

**Comment by TheRealJake12** [comment]
it crashes

**Comment by ACrazyTown** [comment]
> it crashes

That may be because you reference or didn't remove it before destroying. Make sure nothing else references that asset when its destroyed and make sure to remove it before destroying.

**Comment by TheRealJake12** [comment]
> > it crashes
> 
> That may be because you reference or didn't remove it before destroying. Make sure nothing else references that asset when its destroyed and make sure to remove it before destroying.

the object is animated and plays animation every idk second. Is that why its crashing because its already removed

**Comment by TheRealJake12** [comment]
yeah I really need to find a way to get rid of things in VRAM. the destroy does nothing.

**Comment by Geokureli** [comment]
destroy removes references to data which will later get cleared by the garbage collector when it decides to run a GC sweep.  This means you shouldn't expect memory usage to drop immediately.

Plus, destroying things like FlxSprites likely won't help. FlxSprites are just game objects with references to FlxGraphics, and FlxGraphics are openfl bitmaps with frame slicing data. Destroying the FlxSprites doesn't free up the Bitmaps. Flixel will typically clear out all the bitmaps when FlxG.switchState is called.

It's really hard to give concise steps to help with memory issues without knowing a lot of details about your project. 2gb ram is the minimum for win 10 and most funkin mods take up around 1.5-2gb. I'm assuming this is for an FNF mod and you might just have to either get a better pc, or talk with FNF modders on how to reduce memory usage

**Comment by TheRealJake12** [comment]
> destroy() removes references to data which will later get cleared by the garbage collector when it decides to run a GC sweep. This means you shouldn't expect memory usage to drop immediately.
> 
> Plus, destroying things like FlxSprites likely won't help. FlxSprites are just game objects with references to FlxGraphics, and FlxGraphics are openfl bitmaps with frame slicing data. Destroying the FlxSprites doesn't free up the Bitmaps. Flixel will typically clear out all the bitmaps when FlxG.switchState is called.
> 
> It's really hard to give concise steps to help with memory issues without knowing a lot of details about your project. 2gb ram is the minimum for win 10 and most funkin mods take up around 1.5-2gb. I'm assuming this is for an FNF mod and you might just have to either get a better pc, or talk with FNF modders on how to reduce memory usage

ok damn your right. But the mod I'm fixing is a really GPU intense one. Specifically VRAM intense. I've made it run the garbage collector every time it goes to a new state. Fixing a memory leak. But it has a hard time removing all the VRAM things used. I'm pretty good at lowering normal RAM but VRAM is trickier.

**Comment by Geokureli** [comment]
You might have better luck in the [OpenFL forum](https://community.openfl.org/). Shaders arereally a lime/openfl feature that flixel just leverages.
