### ISSUE TITLE
FlxSprites/FlxSkewedSprites use the flash.geom package, how do I skew them as the ActionScript API documents it?

### ISSUE THREAD

**Issue by Itz-Miles** [HaxeFlixel/flixel#2604]
- **Haxe version:** 4.2.4
- **Flixel version:** 4.11.0
- **OpenFL version:** 9.1.0
- **Lime version:** 7.9.0

________________________________
**Issue:**
I can't figure out how to skew sprites in the way that both the pdf/html ActionScript references depict. I understand that this is for bug requests, but all other options I know about are exhausted through trial and error.
 ________________________________

**Observed behavior:**
(Extended FlxSkewedSprite, added over elements of another flxState) FlxSkewedSprites and other sprites with any skew-related affine transformations appear to be skewed starting from the middle, with the top half/bottom half skewed accordingly. This can't easily be changed, as far as I know.

https://user-images.githubusercontent.com/95124554/179393993-5ed6a2b6-1256-4c77-b4a9-b168db52da1c.mp4

**Expected behavior:**
Any sprite that has any skew-related transformations is depicted as being skewed from the top down, which can easily be changed/ offset via public methods. (`deltaTransformPoint()` for example, which I haven't found a way to work by itself since _matrix and _point are private vars for FlxSprites)

![Screenshot (99)](https://user-images.githubusercontent.com/95124554/179393145-950d00e8-c9c6-4d0c-800a-3f98f458adf8.png)

**Comment by Geokureli** [comment]
try setting the sprite's origin

**Comment by Itz-Miles** [comment]
Thanks, I can't thank you enough for reminding me! By extending FlxSkewedSprite to another class, I was able to set things like the matirx/point data, and the origin most importantly. Works as intended!
