### ISSUE TITLE
I want to be able to downgrade and actually update my version

### ISSUE THREAD

**Issue by PortilizenHub** [HaxeFlixel/flixel#2608]
- **Haxe version:** i dont even fucking know
________________________________

![image](https://user-images.githubusercontent.com/99573698/179780998-c4395925-5568-4e36-8989-73c437e04aa5.png)

Im using Haxe 4.2.5, I'm trying to make a Friday Night Funkin' Mod, **I CANT.**
You guys need to make something that makes it so we can downgrade our versions, I'm tired of this bullshit, I'm tired of the auto-update your extension does, I want to be able to make FNF mods without having to deal with this **BULLSHIT.**

And your thing doesn't update itself, I installed haxe 4.1.5, it says 4.0,2, but in vsc its 4.2.5? What the fuck is this.

**Comment by ItsyourboyJonnycat** [comment]
your on linux right? so do lime build linux

**Comment by ItsyourboyJonnycat** [comment]
or your trying to build for windows do a #if cpp then end it off with a #end
