### ISSUE TITLE
Commit 'd2f6fc0' breaks clipRects for sprite groups

### ISSUE THREAD

**Issue by ianharrigan** [HaxeFlixel/flixel#2631]
Hi!

This commit here seems to break clip rects for me on FlxGroups: https://github.com/HaxeFlixel/flixel/commit/d2f6fc007cdde61cdf18a0c5581e23165493e972

Before the commit: 
![image](https://user-images.githubusercontent.com/3024242/188849969-0da4f14f-8b3f-4d0c-afd2-2c0ed3694ec8.png)

After:
![image](https://user-images.githubusercontent.com/3024242/188850244-4e92fb11-461c-499d-b125-dc423710ecdf.png)

Unfortunately i dont really know enough about what its doing (or flixel in general really) to be able to provide more info / submit a PR... i can slowly start to add the previous commit back until i can work out what breaks? If that may help.

Cheers,
Ian

**Comment by Geokureli** [comment]
@ianharrigan is there a simple test project I can use to try and fix this?

**Comment by ianharrigan** [comment]
Ive only tried a haxeui project, ill see if i can knock up a minimal repro.

**Comment by ianharrigan** [comment]
if i remove the `_skipTransformChildren` from the 

```haxe
	public function transformChildren<V>(Function:T->V->Void, Value:V):Void
	{
		if (_skipTransformChildren || group == null)
			return;

		for (sprite in _sprites)
		{
			if (sprite != null)
				Function(cast sprite, Value);
		}
	}
```
then everything works again. Weirdly though, if comment out all the `_skipTransformChildren = true` and leave it in the check things still dont work (which i find verrrry strange)

**Comment by ianharrigan** [comment]
So, as you know, there was an ill conceived `_skipTransformChildren` in haxeui-flixel which was causing this. Ive removed this now as i cant see what it was trying to do, and if it was an attempt to do something, it was certainly the wrong way to do it. 

Ill close this.

Cheers,
Ian
