### ISSUE TITLE
Improve debug selection tool

### ISSUE THREAD

**Issue by Geokureli** [HaxeFlixel/flixel#2663]
As discussed in #2662 we should improve the selection tool:
- Clicking should always select the most top-drawn object overlapping the cursor.
- Shift-click to toggle the selection of the top-most object
Additionally, it would be a good idea to have a button to toggle `ignoreDrawDebug` on the selected object(s)

Pinging @ACrazyTown, if you don't end up getting to this, let me know

**Comment by ACrazyTown** [comment]
Just wondering, where would the button go?

**Comment by Geokureli** [comment]
The butt to toggle ignoreDrawDebug? Good question. Maybe with the selection and mover tool, but it might be hard to convey that use to people. Maybe this is something should be handled in [flixel-studio](https://github.com/Dovyski/flixel-studio). Moreso, the button might be best left as a separate issue

**Comment by ninjamuffin99** [comment]
fixed by #2964 ?

**Comment by Geokureli** [comment]
1 item still remains, ill have to move it to a new issue and close this when i get a chance
