### ISSUE TITLE
Compile issue on `FlxSound`.

### ISSUE THREAD

**Issue by MAJigsaw77** [HaxeFlixel/flixel#2677]
If i use a older version of `Lime`, this happens `/opt/hostedtoolcache/haxe/4.2.5/x64/lib/flixel/5,0,0/flixel/system/FlxSound.hx:753: characters 23-28 : lime.media.AudioSource has no field pitch`

**Comment by Geokureli** [comment]
@Cheemsandfriends would you be able to check this feature with lime 7, this isn't the only issue we've seen in this area. This fixes a compile issue that was reported in FlxDefines: https://github.com/HaxeFlixel/flixel/commit/ce453083600acb68c6bff47ea1c583d1ff467e91

@MAJigsaw77 try compiling with `-DFLX_NO_PITCH` or add `<haxedef name="FLX_NO_PITCH" /> to your project.xml

**Comment by MAJigsaw77** [comment]
Ok

**Comment by Geokureli** [comment]
@MAJigsaw77 what target are you building to and what lime version are you using?

**Comment by MAJigsaw77** [comment]
I'm using Lime 7.9.0 and I'm building android

**Comment by MAJigsaw77** [comment]
Also, the define worked.

**Comment by MAJigsaw77** [comment]
> I'm using Lime 7.9.0 and I'm building android

8.0.0 has some issues

**Comment by MAJigsaw77** [comment]
That's why

**Comment by Geokureli** [comment]
what issues, just curious?

**Comment by MAJigsaw77** [comment]
The svg icons have higher priority and this is issue shows only only on android.

**Comment by MAJigsaw77** [comment]
JNI in macro context crashes.

**Comment by MAJigsaw77** [comment]
> JNI in macro context crashes the compile.

If i use fields

**Comment by MAJigsaw77** [comment]
This issue won't get fixed until the next release?

**Comment by MAJigsaw77** [comment]
@Geokureli

**Comment by Geokureli** [comment]
> This issue won't get fixed until the next release?

Yes

**Comment by Cheemsandfriends** [comment]
@Geokureli the line that is giving issues is basically where the pitch is set.
I don't understand how os it giving errors since the functions (both get and set pitch) are wrapped in the target conditional FLX_PITCH
Unless that lime 8 for some reason removed the pitch, I can't explain how is it crashing.
Maybe I'm missing out something.

**Comment by Geokureli** [comment]
@Cheemsandfriends MAJigsaw77 is using 7.9.0, the problem is that lime 7.9.0 does not define a pitch property in Audiosource:
https://lib.haxe.org/p/lime/7.9.0/files/src/lime/media/AudioSource.hx

pitch was introduced in lime 8
https://lib.haxe.org/p/lime/8.0.0/files/src/lime/media/AudioSource.hx

**Comment by Cheemsandfriends** [comment]
@Geokureli Ik that it was introduced in lime 8, I just didn't understand for a second why it defined to FLX_PITCH if it was on lower versions
Now i think that this fixes it?

**Comment by Geokureli** [comment]
@MAJigsaw77 gonna release a patch sometime early tomorrow

**Comment by MAJigsaw77** [comment]
> @MAJigsaw77 gonna release a patch sometime early tomorrow

👍
