### ISSUE TITLE
Changes to FlxStrip break FlxTiledSprite

### ISSUE THREAD

**Issue by MasterEric** [HaxeFlixel/flixel#2694]
With the addition of changes made by @UncertainProd in #2671, FlxTiledSprite no longer renders properly. The tiled sprite is now stretched out instead of repeated over the sprite's width.

I considered posting this issue to `flixel-addons`, but no changes were made to FlxTiledSprite; rather, the code change to FlxStrip has caused an issue which potentially affects anything using FlxStrip.
________________________________

- **Haxe version:** 4.2.5
- **Flixel version:** git commit [e1fbdc4](https://github.com/HaxeFlixel/flixel/commit/e1fbdc40df8c9bfc9a73b0bdfbca4cc96da5485a)
- **OpenFL version:** 9.2.0
- **Lime version:** 8.0.0
- **Affected targets:** Windows and Linux native were both tested
________________________________

**Code snippet reproducing the issue**:

https://github.com/MasterEric/FlxTiledSprite-TestBench
________________________________

**Observed behavior:**

![incorrect](https://user-images.githubusercontent.com/4635334/206659253-c7bc28aa-91f7-4b72-8e8f-fb009dd2b1e6.png)

**Expected behavior:**

![correct](https://user-images.githubusercontent.com/4635334/206659281-a56f229a-5f8b-4730-a6fd-d4221bb6da7c.png)

**Comment by Geokureli** [comment]
Gonna do some testing, soon, but ill likely revert the breaking PR around monday. Sorry about this

**Comment by UncertainProd** [comment]
I think this is due to the fact that `beginShaderFill` doesn't have an option to repeat the texture that its filling with, like how `beginBitmapFill` does. I guess we can add an if check before choosing whether to use `beginShaderFill` or `beginBitmapFill`.
I think adding a boolean field called `repeat` to `FlxDrawTrianglesItem` and then doing something like this can work:
```haxe
if (!repeat && shader != null)
	camera.canvas.graphics.beginShaderFill(shader);
else
	camera.canvas.graphics.beginBitmapFill(graphics.bitmap, null, repeat, (camera.antialiasing || antialiasing));
```
It only has the downside that only one of `FlxStrip.repeat` and `FlxStrip.shader` can work at a time (aka setting FlxStrip.repeat to true will also make it so shaders have no effect on the sprite).

What do you guys think?

**Comment by MasterEric** [comment]
> I think this is due to the fact that `beginShaderFill` doesn't have an option to repeat the texture that its filling with, like how `beginBitmapFill` does. I guess we can add an if check before choosing whether to use `beginShaderFill` or `beginBitmapFill`.
> I think adding a boolean field called `repeat` to `FlxDrawTrianglesItem` and then doing something like this can work:
> ```haxe
> if (!repeat && shader != null)
> 	camera.canvas.graphics.beginShaderFill(shader);
> else
> 	camera.canvas.graphics.beginBitmapFill(graphics.bitmap, null, repeat, (camera.antialiasing || antialiasing));
> ```
> It only has the downside that only one of `FlxStrip.repeat` and `FlxStrip.shader` can work at a time (aka setting FlxStrip.repeat to true will also make it so shaders have no effect on the sprite).
> 
> What do you guys think?

This would work for fixing the issue but obviously make for inconsistent behavior.

Make sure the change is well-documented, and ideally look into potentially modifying `beginShaderFill` thus making it more versatile
