### ISSUE TITLE
Socket error: Error: read ECONNRESET

### ISSUE THREAD

**Issue by REALHaydenGaming** [HaxeFlixel/flixel#2708]
- **Haxe version:** 4.2.5
- **Flixel version:** 4.11.0
- **OpenFL version:** 9.2.0
- **Lime version:** 7.9.0
- **Affected targets:**
HXCPP Debug Server (W/ VSC On), Windows (DEBUG).
________________________________

**Code snippet reproducing the issue**:

```Unavliable, happens globally, DEBUG was enabled.
```

________________________________

**Observed behavior:**
Socket error: Error: read ECONNRESET
**Expected behavior:**
Not being able to crash.

This error happened after I moved my game project over from my Chromebook (W/ Linux Support) to my new Windows 11.

I've read and researched how, but its no effort, any help?

**Comment by Geokureli** [comment]
I don't think this is a flixel bug, it might be a vshaxe issue or an openfl issue, I would ask in the forum
