### ISSUE TITLE
FlxText.width setter does not update underlying textField.width

### ISSUE THREAD

**Issue by T1mL3arn** [HaxeFlixel/flixel#2729]
- **Haxe version:** 4.2.5
- **Flixel version:** 5.1.0
- **OpenFL version:** 9.2.0
- **Lime version:** 8.0.0

________________________________

**Code snippet reproducing the issue**:

```haxe
var width = 150;
var label = new FlxText(0, 0, width, "hello", 24)
...
label.width = 50;
label.alignment = RIGHT;
```

________________________________

**Observed behavior:**

![image](https://user-images.githubusercontent.com/9349164/218709259-028c4dd7-b8ad-4da4-93e8-72c6474128d0.png)

**Expected behavior:**

If I set textfield width directly `label.textField.width = 50` then it works as expected

![image](https://user-images.githubusercontent.com/9349164/218710412-214479b1-43e9-4180-98bc-838ffb7d4880.png)

**Comment by Geokureli** [comment]
text.width is used for collision bounds, it does not determine the graphic bounds, use `text.fieldWidth` for that
