### ISSUE TITLE
Copying saves with save.mergeDataFrom cannot override

### ISSUE THREAD

**Issue by BendyGaming0** [HaxeFlixel/flixel#2735]
- **Haxe version:** 4.2.5
- **Flixel version:** 5.2.1
- **OpenFL version:** 9.2.0
- **Lime version:** 8.0.0
- **Affected targets:** All (presumably)

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxState;
import flixel.util.FlxSave;
import flixel.FlxG;

class PlayState extends FlxState
{
	override public function create():Void
	{
               var save_1 = new FlxSave();
               save_1.bind('save_1', 'BendyGaming0');
               save_1.data.score = 10000;

               var save_2 = new FlxSave();
               save_2.bind('save_2', 'BendyGaming0');
               save_2.data.score = 5000;

               save_2.mergeDataFrom('save_1', 'BendyGaming0', true, false);
               FlxG.log.add('Score : ${save_2.data.score}');
	}
}
```

________________________________

**Observed behavior:**

The value logged is 5000

**Expected behavior:**

The value logged is 10000

**Comment by Geokureli** [comment]
thanks for pointing this out, expect a fix in the 5.3.0 release
