### ISSUE TITLE
Cannot access a FlxSignal's destroy method

### ISSUE THREAD

**Issue by DigiEggz** [HaxeFlixel/flixel#2743]
I was tracing out the destroy function for a FlxSignal and noticed `destroy()` is not natively called when a FlxSignal is destroyed as part of a FlxState. I then wanted to manually call `destroy()`, but the interface is not set for it.

I can create a PR to allow calling `destroy()` on a FlxSignal called directly. Thoughts on this?

**Comment by Geokureli** [comment]
I would approve that PR. I've just been calling signal.removeAll
