### ISSUE TITLE
FlxColor interprets some colors incorrectly

### ISSUE THREAD

**Issue by EliteMasterEric** [HaxeFlixel/flixel#2769]
```haxe
var color:String = '#FF3F2021';

var hex:FlxColor = FlxColor.fromString(color);

trace(hex.toHexString()); // Prints 0x7FFFFFFF instead of 0xFF3F2021
```

**Comment by Geokureli** [comment]
looks like an int vs uint overflow issue

**Comment by Geokureli** [comment]
Can you test this on various targets, and also test `Std.parseInt("0xFF3F2021")` on those same targets

**Comment by Geokureli** [comment]
can't repro, reopen when there's more info, please

**Comment by EliteMasterEric** [comment]
I ended up just changing the string to `#3F2021` and it works fine. If I encounter this issue again and can reliably repro I will let you know.
