### ISSUE TITLE
flixel/5,2,2/flixel/util/FlxDestroyUtil.hx:3: characters 8-32 : You cannot access the flash package while in a macro (for flash.display.BitmapData)

### ISSUE THREAD

**Issue by JonnycatMeow** [HaxeFlixel/flixel#2780]
- **Haxe version:** 4.3.0
- **Flixel version:** 5.2.2
- **OpenFL version:** 9.2.1
- **Lime version:** 8.0.1
- **Affected targets:mac that I only know of **

I was trying to build psych engine using lime when all of a sudden I get this error 

![Screen Shot 2023-04-22 at 1 18 40 AM](https://user-images.githubusercontent.com/107599365/233772212-4f8abd12-d7d3-4f4f-b502-bab7e993cc97.png)

**Comment by Geokureli** [comment]
In the future you should ask these questions in the psych engine discord or github because it has nothing to do with flixel. But luckily i know the cause

In your project's import.hx you're importing the Paths class. You should wrap everything in this file in

```hx
#if !macro
// Your imports here
#end
```

**Comment by JonnycatMeow** [comment]
sorry about asking about the psych engine thing but I thought it was a flixel issue issue

**Comment by JonnycatMeow** [comment]
but thank you so much
