### ISSUE TITLE
flixel.animation.FlxAnimationController has no field getFrameDuration

### ISSUE THREAD

**Issue by JonnycatMeow** [HaxeFlixel/flixel#2821]
- **Haxe version:** 4.3.1
- **Flixel version:** 5.3.1
- **OpenFL version:** 9.2.1
- **Lime version:** 8.0.1
- **Affected targets:**
Mac 
________________________________

**Code snippet reproducing the issue**:

/usr/local/opt/haxe/haxelib/flixel/5,3,1/flixel/animation/FlxAnimation.hx:231: characters 35-51 : flixel.animation.FlxAnimationController has no field getFrameDuration
![Screen Shot 2023-05-27 at 6 00 50 PM](https://github.com/HaxeFlixel/flixel/assets/107599365/41e8c8a5-c947-4c94-9290-1cceb7420daf)

**Comment by MemeHovy** [comment]
it's a flixel 5.3 feature, add this to FlxAnimationController
```haxe
	#if (flixel >= "5.3.0")
	@:allow(flixel.animation.FlxAnimation)
	function getFrameDuration(index:Int)
	{
		return _sprite.frames.frames[index].duration;
	}
	#end
```

**Comment by JonnycatMeow** [comment]
thank you

**Comment by JonnycatMeow** [comment]
can you make a pull request regarding this issue

**Comment by MemeHovy** [comment]
> thank you

you're welcome, and sure thing

**Comment by JonnycatMeow** [comment]
acutally i got another error

**Comment by JonnycatMeow** [comment]
![Screen Shot 2023-05-27 at 7 10 25 PM](https://github.com/HaxeFlixel/flixel/assets/107599365/0f183db7-de50-454d-ad76-820f66835046)

**Comment by JonnycatMeow** [comment]
nvm i fixed my issue

**Comment by JonnycatMeow** [comment]
but thank you

**Comment by Geokureli** [comment]
@JonnycatMeow please share what the issue was and what fixed it, in case other people are having the same issue

**Comment by JonnycatMeow** [comment]
so there was this fnf mod call tails.exe and i relized they had put the flixel.animation.Flxanimationcontroller in the source code

**Comment by JonnycatMeow** [comment]
and so i replaced it with the origninal Flxanimationcontroller with the moddified one

**Comment by JonnycatMeow** [comment]
and i also had to modified it as well because it needed certain variables

**Comment by JonnycatMeow** [comment]
and it worked

**Comment by JonnycatMeow** [comment]
https://github.com/iamteles/tails.exe-final/pull/1/files the fixed version

**Comment by Geokureli** [comment]
> please run `haxelib list flixel` and paste all the flixel versions you're using, here. this seems like an incompatibility issue between flixel and flixel-ui and/or flixel-addons

@JonnycatMeow can you still share your flixel haxelib versions

**Comment by JonnycatMeow** [comment]
yes my haxelib version is 4.1.0 and my flixel version is 5.3.1

**Comment by Geokureli** [comment]
But specifically what is your flixel-addons and flixel-ui version @JonnycatMeow

**Comment by JonnycatMeow** [comment]
flixel-addons 3.1.1 and 2.5.0 flixel-ui
