### ISSUE TITLE
Add a `NO_INIT_SAVE` define in project.xml.

### ISSUE THREAD

**Issue by TheGaloXx** [HaxeFlixel/flixel#2838]
Project.xml:
```xml
<haxedef name="NO_INIT_SAVE"/>
```

FlxG.hx (line 621):
```haxe
#if FLX_ACCELEROMETER
accelerometer = new FlxAccelerometer();
#end

#if !NO_INIT_SAVE
initSave();
#end

plugins = new PluginFrontEnd();
```

This prevents the first save file from generating in the Roaming folder. I think the `initSave` should be optional because, personally, I don't like to create extra files on the player's pc if not necessary. And the only way to solve this (that I thought of) is to modify the `FlxG` class, but this prevents it from updating.

**Comment by TheGaloXx** [comment]
Nice!

**Comment by Geokureli** [comment]
i removed it because this isn't an issue it's a feature request, and you already explained the feature appropriately

**Comment by Geokureli** [comment]
keep this open until the change is made and merged
