### ISSUE TITLE
add an array of Shaders to a FlxSprite

### ISSUE THREAD

**Issue by ghost** [HaxeFlixel/flixel#2855]
It doesn't really go through my head why FlxCameras can have multiple shaders applied at a time, but sprites don't, I'd be nice to have such a thing built-in (while also still having the `shader` variable to not break compatibility)

**Comment by Geokureli** [comment]
the big challenge here is that [openfl.display.Graphics.beginShaderFill](https://github.com/openfl/openfl/blob/develop/src/openfl/display/Graphics.hx#L387) only takes a single shader which is what [FlxDrawQuadsItem](https://github.com/HaxeFlixel/flixel/blob/dev/flixel/graphics/tile/FlxDrawQuadsItem.hx#L135) uses to draw the shaded sprite to the camera. once openfl can apply multiple shaders then so can FlxDrawQuadsItem, and FlxSprite

**Comment by Cheemsandfriends** [comment]
This feels like spam but I thought it can help this issue
I made a repository for a friend of mine pretty recently that it relatively does what it's suggested, render shaders onto a bitmap and then render that bitmap onto the camera with a pretty good perfomance.
Here's the [link](https://github.com/Cheemsandfriends/FlxFilteredSprite)

**Comment by crowplexus** [comment]
> This feels like spam but I thought it can help this issue I made a repository for a friend of mine pretty recently that it relatively does what it's suggested, render shaders onto a bitmap and then render that bitmap onto the camera with a pretty good perfomance. Here's the [link](https://github.com/Cheemsandfriends/FlxFilteredSprite)

thanks for the heads up, the original issue was made by an account of mine, which I just deleted, that's about it, I can see why it looks like spam

I'd mark this as solved if I could LOL
