### ISSUE TITLE
FlxBitmapText not generating bitmap font, and instead crashing

### ISSUE THREAD

**Issue by CyndaquilDAC** [HaxeFlixel/flixel#2856]
- **Haxe version:** ?.?.?
- **Flixel version:** 5.3.1
- **OpenFL version:** ?.?.?
- **Lime version:** ?.?.?
- **Affected targets:**

________________________________

**Code snippet reproducing the issue**:

```haxe
public static var comicSansBmp:FlxBitmapFont = FlxBitmapFont.fromAngelCode(Paths.image("ComicSansPixel_0"), Paths.xml("ComicSansPixel"));
```

________________________________

**Observed behavior:**
Game crashing on launch.

**Expected behavior:**
Creating a bitmap font from the BMFont generated assets placed in the files for later use.

**Comment by CyndaquilDAC** [comment]
oops i didnt have the settings right 😭

**Comment by Geokureli** [comment]
FYI, there is no `Paths` tool in flixel, thats a util hastily made for FNF, that other projects copied, even though it isn't recommended. If you post an issue here with code that uses this proprietary util, my first reaction will always be "I don't know what your Paths tool is doing, try doing this without using that, or share your Paths method so I can actually help you"
