### ISSUE TITLE
Shader keeps saying it has no fields for the variables

### ISSUE THREAD

**Issue by MemeHovy** [HaxeFlixel/flixel#2874]
- **Haxe version:** 4.2.5
- **Flixel version:** 5.3.1
- **OpenFL version:** 9.2.2
- **Lime version:** 8.0.2
- **Affected targets:** Windows

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.system.FlxAssets.FlxShader;
import flixel.FlxG;

class VignetteShaderEffect extends FlxShader{
    @:glFragmentSource('
        #pragma header

        uniform vec2 uResolution;

        uniform float strength = 1.0;
        uniform float radius = 0.5;

        void main(){
            vec2 v = openfl_TextureCoordv.xy / uResolution;
            float distance = distance(v, vec2(0.5));
            float vignette = smoothstep(radius, radius + strength, distance);

            vec4 color = flixel_texture2D(bitmap, v);
            color.rgb *= vignette;

            gl_fragColor = color;
        }
    ')
}

class VignetteEffect{
    public var shader(default, null):VignetteShaderEffect;

    public var strength(default, set):Float;
    public var radius(default, set):Float;

    inline function set_strength(value:Float){
        strength = value;
        shader.strength.value = [strength];
        return strength;
    }

    inline function set_radius(value:Float){
        radius = value;
        shader.radius.value = [radius];
        return radius;
    }

    inline function setResolution()
        shader.uResolution.value = [FlxG.width, FlxG.height];

    public function new(){
        shader = new VignetteShaderEffect();
        setResolution();
    }
}
```

________________________________

**Observed behavior:**
source/VignetteShader.hx:47: characters 16-27 : VignetteShaderEffect has no field uResolution
source/VignetteShader.hx:36: characters 16-24 : VignetteShaderEffect has no field strength
source/VignetteShader.hx:42: characters 16-22 : VignetteShaderEffect has no field radius

**Expected behavior:**
The game to compile

**Comment by Geokureli** [comment]
Ive had issues where shader fields dont work if the shader doesn't have a constructor defined

**Comment by MemeHovy** [comment]
> Ive had issues where shader fields dont work if the shader doesn't have a constructor defined.
> 
> try starting with my [ShaderToyShader](https://gist.github.com/Geokureli/e00d66f85fd9f937b6b69d87937335a4) and adding onto it
> 
> edit:
> 
> 1. capital F in `gl_FragColor` too.
> 2. can't set default values for uniform vars
> 3. can use `openfl_TextureSize` instead of uResolution
> 4. `openfl_TextureCoordv` is already the the normalized coordinate (goes from 0 to 1)
> 5. `openfl_TextureCoordv.xy` is redundant can just do `openfl_TextureCoordv`

alright, I’ll try this and let you know if it works

**Comment by Geokureli** [comment]
I took [this vignette shader](https://www.shadertoy.com/view/lsKSWR) from shadertoy and made [this example](https://github.com/Geokureli/flixel-tests/blob/main/Source/states/VignetteShaderTestState2874.hx), hope it helps

**Comment by MemeHovy** [comment]
I'm gonna close this now since adding the constructor and fixes you mentioned fixed it
