### ISSUE TITLE
Tilemap graphics not updating (until window resize) after a new map is loaded

### ISSUE THREAD

**Issue by TheJoetube** [HaxeFlixel/flixel#2882]
- **Haxe version:** 4.2.5
- **Flixel version:** 5.3.1
- **OpenFL version:** 9.9.2
- **Lime version:** 8.0.2
- **Affected targets:**
cpp (Windows)
________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxCamera;
import flixel.FlxG;
import flixel.FlxState;
import flixel.tile.FlxTilemap;
import flixel.util.FlxColor;

class PlayState extends FlxState
{
	var mapData:Array<Array<Int>> = [
		[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
		[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
		[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
	];

	var mapCam:FlxCamera;
	var map:FlxTilemap;

	override public function create()
	{
		mapCam = new FlxCamera(0, 0, 1280, 720);
		mapCam.bgColor = FlxColor.TRANSPARENT;
		FlxG.cameras.add(mapCam, false);

		map = new FlxTilemap();
		map.loadMapFrom2DArray(mapData, "assets/images/tiles/testTiles.png", 32, 32, OFF, -1, 0);
		add(map);
		map.cameras = [mapCam];
		super.create();
	}

	override public function update(elapsed:Float)
	{
		if (FlxG.keys.justPressed.L)
		{
			var newMap:Array<Array<Int>> = [
				[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
				[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
				[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
			];
			map.loadMapFrom2DArray(newMap, "assets/images/tiles/testTiles.png", 32, 32, OFF, -1, 0);
		}
		super.update(elapsed);
	}
}
```

________________________________

**Observed behavior:**
the new loaded map should be 1 column bigger than the old one, but the new tiles aren't showing until the window is resized

**Expected behavior:**
the column should show immediatly

**Comment by Geokureli** [comment]
@TheJoetube can you be specific about how you're resizing this what size the window is in the project.xml and the game size in Main.hx?

**Comment by TheJoetube** [comment]
> @TheJoetube can you be specific about how you're resizing this, what size the window is set in project.xml and the game size in Main.hx?

The newMap var is bigger by one column than the original mapData variable. So loading a bigger array should make the map bigger, but until the game window is resized the tiles in the new column aren't shown.
The windo size is 1280x720, same in the main hx

**Comment by TheJoetube** [comment]
> @TheJoetube can you be specific about how you're resizing this, what size the window is set in project.xml and the game size in Main.hx?

if you mean resizing the window, anything will work, fullscreening, windowing, anything that resizes the screen

**Comment by Geokureli** [comment]
can you share the tiles image you're using, or something similar
