### ISSUE TITLE
FlxColor and FlxMath does not work with macros

### ISSUE THREAD

**Issue by Geokureli** [HaxeFlixel/flixel#2893]
FlxColor imports FlxMath which imports FlxG which imports a lot of things, perhaps we should make these more self contained in a macro context, since macros may use these tools, or things that use these tools

**Comment by Cheemsandfriends** [comment]
My guess would be to replace FlxMouse with FlxPointer?
but at the same time, it imports FlxCamera which then it has it fair bit of imports so ¯\_(ツ)_/¯
