### ISSUE TITLE
FlxCamera demo issues

### ISSUE THREAD

**Issue by Geokureli** [HaxeFlixel/flixel#2900]
https://haxeflixel.com/demos/FlxCamera/
putting this here as it seems to highlight issues with the FlxCamera, as well as issues with the demo.
- screen-by-screen behaves weird with zooms other than 1.0. [example vid](https://imgur.com/MP0SY2M)

Most deadzone types don't match the overlay unless zoom is 1.0. not sure if this is by design and the overlay should change, or if deadzones should have effectively different rects at different zooms. probably the former, or whatever isn't a breaking change

**Comment by ninjamuffin99** [comment]
should this be fixed with PR merge #2903 ?

**Comment by Geokureli** [comment]
I assumed this would have been auto closed by #2903, thanks
