### ISSUE TITLE
FlxBitmapText, textColor not applied correctly

### ISSUE THREAD

**Issue by 13rice** [HaxeFlixel/flixel#2916]
- **Haxe version:** 4.0.2
- **Flixel version:** 5.2.2
- **OpenFL version:** 9.1.0
- **Lime version:** 7.9.0
- **Affected targets:** html5

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

package;

import flixel.FlxState;
import flixel.graphics.frames.FlxBitmapFont;
import flixel.text.FlxBitmapText;
import openfl.Assets;

class PlayState extends FlxState
{
	override public function create()
	{
		super.create();

		// Assets from the FlxBitmapText demo
		var textBytes = Assets.getText("assets/NavTitle.fnt");
		var XMLData = Xml.parse(textBytes);
		var fontAngelCode = FlxBitmapFont.fromAngelCode("assets/NavTitle.png", XMLData);

		var tf = new FlxBitmapText(fontAngelCode);
		tf.useTextColor = true;
		tf.textColor = 0xff223344;
		tf.text = "Hello World!\nand this is\nmultiline!!!";
		add(tf);
	}
}
```

________________________________

**Observed behavior:**
Incorrect text color.
The color of the text is full white, instead of a dark blue green.

**Expected behavior:**
Apply the text color correctly (see pictures attached).

I dug in the FlxBitmapText class, the alpha isn't applied correctly when we assign a textColor, see around line 348
```haxe
				tAlpha *= textColor.alpha;
```
With the following attribute it's working correctly for me (html5 target):
```haxe
				tAlpha *= textColor.alphaFloat;
```

Current behavior:
![current behavior](https://github.com/HaxeFlixel/flixel/assets/16978288/a4c66d33-aea7-4c34-b267-5538240b6efe)
Expected behavior:
![expected behavior](https://github.com/HaxeFlixel/flixel/assets/16978288/75401375-7ba0-44e9-9493-ab5f27045fcd)

**Comment by Geokureli** [comment]
> I dug in the FlxBitmapText class, the alpha isn't applied correctly when we assign a textColor, see around line 348
> 
> ```hx
> 				tAlpha *= textColor.alpha;
> ```
> 
> With the following attribute it's working correctly for me (html5 target):
> 
> ```hx
> 				tAlpha *= textColor.alphaFloat;
> ```

Good find!

Feel free to make a pull request to fix this, if you're new to open source development this is a great opportunity to learn. Here is a [guide for first-time contributors](https://github.com/HaxeFlixel/flixel/wiki/Contribution-Guide#submitting-changes), but, if you have any trouble, reach out

**Comment by 13rice** [comment]
Yes ok ! I wanted to submit it first. In the meantime I checked my fix on Windows and Android targets, all fine.
I'll do the PR.
