### ISSUE TITLE
[Feature request] Ability to use multiple plugins of the same type.

### ISSUE THREAD

**Issue by T1mL3arn** [HaxeFlixel/flixel#2917]
Right now `PluginFrontEnd` disallows to use more than one plugin with the same type.

https://github.com/HaxeFlixel/flixel/blob/b8e7bb54ebfb781996e7e22d95df319ab02a5391/flixel/system/frontEnds/PluginFrontEnd.hx#L31-L35

My personal use case: tween managers for different types of objects to separately control what can tween and what cannot. Flixel allows to manage tweens in a separate way with `FlxTweenManager`, but I cannot use such manager twice with a plugin frontend. So I have to use it maybe in a state and add the manager to the state as a usual flixel object. Sometimes it is fine. But for me more preferable way would be like that:

```haxe
// MyGame.hx

menuTweens = FlxG.plugins.add(new FlxTweenManager());
gameTweens = FlxG.plugins.add(new FlxTweenManager());

// any other game state *.hx

MyGame.gameTweens.tween(someSprite, ...);

// game was paused

MyGame.gameTweens.active = false;
```

Workaround to bypass type check

```haxe
class MakeFlixelHappyTweenManager extends FlxTweenManager {}
gameTweens = FlxG.plugins.add(new MakeFlixelHappyTweenManager());

// or 

FlxG.plugins.list.push(gameTweens = new FlxTweenManager());
```

**Comment by Geokureli** [comment]
> ```hx
> // MyGame.hx
> 
> menuTweens = FlxG.plugins.add(new FlxTweenManager());
> gameTweens = FlxG.plugins.add(new FlxTweenManager());
> 
> // any other game state *.hx
> 
> MyGame.gameTweens.tween(someSprite, ...);
> 
> // game was paused
> 
> MyGame.gameTweens.active = false;
> ```

what happens if you try this, is there an error thrown?

**Comment by T1mL3arn** [comment]
>what happens if you try this, is there an error thrown?

No errors. Plugin frontend disallows to use multiple `FlxTweenManager` instances, so newly created tween managers (when they are used with "preferable" way) won't be in `FlxG.plugins` and won't be updated by Flixel thus any tweens added to `menuTweens` or `gameTweens` just do nothing. 

Right now I extend `FlxTweenManager` so I can use more than one manager as a plugin.

**Comment by Geokureli** [comment]
I added a PR that deprecates `add` for `addIfUnique` and adds the transitionary method: `addPlugin` which allows for multiple plugins of the same type. Eventually, `add` will take the place of `addPlugin` but only after enough time has passed where people can react to each step of this change. We may need to remove `add` in the next breaking version, since people are less likely to skip over major versions. later on we can add it back
