### ISSUE TITLE
Fix object visibility tests for cases when camera have zoom less than 1.0

### ISSUE THREAD

**Issue by Beeblerox** [HaxeFlixel/flixel#292]
You can see this issue in FlxCamera Demo ( http://haxeflixel.com/demos/flxcamera )
##

**Comment by Beeblerox** [comment]
i think i'll need to add new property to the camera, something like minZoom

**Comment by GimmickyApps** [comment]
@Beeblerox would minZoom be a non-settable value, preventing the bug by not allowing a zoom level at which it occurs, or would it be settable and attempt a workaround if you it set it to a small enough number?

**Comment by MrClogsworthYT** [comment]
Flash is ded now lol
