### ISSUE TITLE
Is there a way to quickly determine when an `FlxEmitter` spawns a particle?

### ISSUE THREAD

**Issue by CaptainBaldi** [HaxeFlixel/flixel#2941]
I looked through the documentation, and couldn't seem to find anything for this.

If there isn't a way to quickly do this, maybe an `FlxSignal` that dispatches whenever a new particle is loaded could be implemented?
Also, maybe another signal that dispatches when a particle is killed off may be handy?

**Comment by Geokureli** [comment]
I would just extend FlxEmitter and add/dispatch these signals rather than adding them to FlxEmitter, or extend FlxParticle and override onEmit

**Comment by CaptainBaldi** [comment]
Fair enough
