### ISSUE TITLE
Strange OpenFL error

### ISSUE THREAD

**Issue by MemeHovy** [HaxeFlixel/flixel#2954]
- **Haxe version:** 4.3.2
- **Flixel version:** Git (Latest Dev Branch, however 5.4.1 has the same behavior)
- **OpenFL version:** 9.3.1
- **Lime version:** 9.1.0
- **Affected targets:** Windows

________________________________

**Code snippet reproducing the issue**:

See: [Line 15 in FlxGraphic](https://github.com/HaxeFlixel/flixel/blob/dev/flixel/graphics/FlxGraphic.hx#L15)
________________________________

**Observed behavior:**
```
HaxeToolkit/haxe/lib/flixel-ui/git/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID)
HaxeToolkit/haxe/lib/flixel/git/flixel/graphics/FlxGraphic.hx:15: characters 8-32 : Type not found : openfl.display.Tilesheet
HaxeToolkit/haxe/lib/flixel/git/flixel/graphics/tile/FlxDrawBaseItem.hx:9: characters 8-32 : Type not found : openfl.display.Tilesheet
HaxeToolkit/haxe/lib/flixel/git/flixel/graphics/tile/FlxDrawTilesItem.hx:10: characters 8-32 : Type not found : openfl.display.Tilesheet
HaxeToolkit/haxe/lib/flixel/git/flixel/input/actions/FlxActionManager.hx:54: characters 47-96 : Type not found : FlxTypedSignal
HaxeToolkit/haxe/lib/flixel/git/flixel/input/gamepad/FlxGamepadManager.hx:46: characters 44-76 : Type not found : FlxTypedSignal
```

This appears to happen while FLX_DRAW_QUADS [is (or should be) defined](https://github.com/HaxeFlixel/flixel/blob/dev/flixel/system/macros/FlxDefines.hx#L207)
And it should also be worth mentioning that Tilesheets were removed in OpenFL 4.0.

(Also on an unrelated note I had to rewrite this twice after the page reloaded, annoying.)

**Expected behavior:**
The game to compile just fine.

**Comment by Geokureli** [comment]
> This appears to happen while FLX_DRAW_QUADS [is (or should be) defined](https://github.com/HaxeFlixel/flixel/blob/dev/flixel/system/macros/FlxDefines.hx#L207) And it should also be worth mentioning that Tilesheets were removed in OpenFL 4.0.

Not sure what's going on here, but it seems like it's time to remove all references to TileSheets. this might also mean removing FLX_DRAW_QUADS too

> (Also on an unrelated note I had to rewrite this twice after the page reloaded, annoying.)

I've seen this happen when i think I'm typing into the field, but I'm not and I trigger some github hotkey. It's pretty lame, ngl
