### ISSUE TITLE
Haxeflixel doesnt compile with latest openfl

### ISSUE THREAD

**Issue by Vortex2Oblivion** [HaxeFlixel/flixel#2955]
- **Haxe version:** 4.3.0
- **Flixel version:** git (same issue on 5.4.1 too)
- **OpenFL version:** 9.3.2
- **Lime version:** 8.1.1
- **Affected targets:** Windows c++

________________________________

**Code snippet reproducing the issue**:

```haxe
function set_pitch(v:Float):Float
	{
		if (_channel != null)
			#if openfl_legacy
			_channel.pitch = v;
			#else
			@:privateAccess
			if (_channel.__source != null)
				_channel.__source.pitch = v;
			#end

		return _pitch = v;
	}
```

________________________________

**Observed behavior:**
The game doesn't compile and gives the error
```batch
C:/HaxeToolkit/haxe/lib/flixel/git/flixel/sound/FlxSound.hx:752: characters 17-25 : openfl.media.SoundChannel has no field __source
C:/HaxeToolkit/haxe/lib/flixel/git/flixel/sound/FlxSound.hx:753: characters 14-22 : openfl.media.SoundChannel has no field __source
```

**Expected behavior:**
The game should compile fine

**Comment by Geokureli** [comment]
fix is underway, this might not get released tonight, but tomorrow at the latest
