### ISSUE TITLE
make a 6.0.0 branch?

### ISSUE THREAD

**Issue by Geokureli** [HaxeFlixel/flixel#2984]
Im wondering If I should make the 6.0.0 release branch now, that way people can start testing all the breaking changes in 6.0.0 now, via `haxelib git flixel https://github.com/HaxeFlixel/flixel.git release6`. that way we can still work on any number of flixel 5 releases without all of these branches waiting in limbo

Relevant Issues: https://github.com/HaxeFlixel/flixel/milestone/13
Pinging @47rooks for input since you have a flixel 6 branch, too

## The Process
merge all approved breaking changes to the branch "release6", meanwhile on dev, continue business as usually, merging non-breaking changes and releasing 5.6.0, and maybe 5.6.1 or 5.7.0, whatever. whenever something is added to dev we merge dev into release6 and fix the conflicts. once release6 is thoroughly tested and we think enough flixel devs have caught up with the latest deprecation warnings we can release flixel 6.0.0 (there have been a lot of deprecation warnings recently, from haxe, flixel, openfl and lime, and I fear people may not want to update to latest flixel because of it, or if they do they are simply ignoring deprecation warnings)

## Alternatives
Release flixel 6 some time after 5.6 if out and tested

**Comment by 47rooks** [comment]
I don't know how you normally decide but if you have a bunch of stuff - I only see like 4 PRs right now - then it makes sense to me. I would use a 6 branch for at least the current project that needs my PR.

I don't know how long you want to maintain two active branches though.
