### ISSUE TITLE
Possibly make FlxCamera.follow take an FlxRect instead of an FlxObject

### ISSUE THREAD

**Issue by CaptainBaldi** [HaxeFlixel/flixel#2988]
I feel like it would be more logical, as I would rather not generate an FlxObject to make something like following a mouse point

Obviously this is a pretty noticeably breaking change, this would have to come along in 6.0.0 probably

**Comment by Geokureli** [comment]
1. As you said, it's breaking change
2. This is actually less functional, `follow(FlxRect.get(x, y, width, height))` has no real benefit over `follow(new FlxObject(x, y, width, height))` other than it's "lighter" class
3. Most people follow their player sprite, which has physics and moves itself, nearly all projects would adapt by setting a rect's x/y to they're player class every frame, which is more cumbersome

I feel like I may be missing something here, cuz I don't see why this is more logical

**Comment by CaptainBaldi** [comment]
> 1. As you said, it's breaking change
> 2. This is actually less functional, `follow(FlxRect.get(x, y, width, height))` has no real benefit over `follow(new FlxObject(x, y, width, height))` other than it's a "lighter" class
> 3. Most people follow their player sprite, which has physics and moves itself, I assume nearly all projects would adapt by setting a rect's x/y to they're player class every frame, which is more cumbersome
> 
> I feel like I may be missing something here, cuz I don't see why this is more logical

ye, I mostly mentioned this due to `FlxRect` being a "lighter" class as you mentioned, with it mostly just having the basic properties `follow` needs to function, however it is true that it would be quite inconvenient to set it's properties every frame.

This is something that could be taken care of in FlxCamera itself, since `target` is stored and is used outside of the `follow` function.

I think if done correctly the only issue here would be that it's still a breaking change
