### ISSUE TITLE
Wrong doc for FlxPoint overloaded operators

### ISSUE THREAD

**Issue by T1mL3arn** [HaxeFlixel/flixel#2994]
This doc tells it returns NEW point, while actually it isn't - it uses method that returns left hand operator.

https://github.com/HaxeFlixel/flixel/blob/bc6d9a825f49f704d5107d5d0c0a5933df0518e4/flixel/math/FlxPoint.hx#L157-L167

This is relevant to probably all compound assignment operators. I can make PR to fix it but before it should be clear what exactly is wrong - either doc or behavior. I personally like current behavior, though current users might use them according to the doc i.e expecting new point objects.

**Comment by Geokureli** [comment]
the doc is wrong, a PR would be awesome, thank you
