### ISSUE TITLE
Add disabled status to FlxButton

### ISSUE THREAD

**Issue by itulau** [HaxeFlixel/flixel#3083]
A very common feature that is missing from FlxButton which I think would be beneficial to have: A DISABLED state for FlxButton which would make the button ignore inputs and be displayed as being unable to be clicked (greyed out).

**Comment by Vortex2Oblivion** [comment]
Would it be a good idea to add a disabled state to more flixel ui stuff
Like FlxUICheckBox for example?
Would need to make a pr on the flixel addons and ui repositories too ofc.

**Comment by Geokureli** [comment]
> Would it be a good idea to add a disabled state to more flixel ui stuff Like FlxUICheckBox for example? Would need to make a pr on the flixel addons and ui repositories too ofc.

We discuss this in https://github.com/HaxeFlixel/flixel/pull/3087

**Comment by itulau** [comment]
Yes, https://github.com/itulau/flixel-ui/tree/flx-button-disabled contains my latest changes which should probably remove some issues related to adding the new disabled status. What I'm missing now is a demo to test those changes, which is becoming a bit tricky since I don't use flixel-ui's classes that much so I'm not sure where to begin.

**Comment by Geokureli** [comment]
> I don't use flixel-ui's classes that much so I'm not sure where to begin.
Try some of the [demos](https://haxeflixel.com/demos/):
- [Cursor Demo](https://haxeflixel.com/demos/Cursor/)
- [FlxSound Demo](https://haxeflixel.com/demos/FlxSound/)
- [Tooltips Demo](https://haxeflixel.com/demos/Tooltips/)

Also, in your branch, I'm wondering if the [toggle button graphic](https://github.com/itulau/flixel-ui/commit/601bf1fe0c2cacc0bdf0773a4d9606c134f158f7#diff-c9d8a60192532fe0fe26cfc6ee82ab80008700b2b48331572f8a53d421172656) should have 2 disabled states, seeing how it has 2 of every other kind?
