### ISSUE TITLE
Barely any fps on 100000 sprites that are 400x400 pixels

### ISSUE THREAD

**Issue by SomeGuyWhoLovesCoding** [HaxeFlixel/flixel#3104]
- **Haxe version:** 4.2.5
- **Flixel version:** 5.6.2 (Latest)
- **OpenFL version:** 9.3.3 (Latest)
- **Lime version:** 8.1.2 (Latest)
- **Affected targets:** Really, any

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxSprite;
import flixel.FlxState;

class PlayState extends FlxState
{
	var stamp:Float = 0;

	override public function create()
	{
		for (i in 0...100000)
		{
			var spr:FlxSprite = new FlxSprite().loadGraphic('assets/image.png');
			spr.x = (i * 0.01);
			spr.alpha = 0.005;
			add(spr);
		}

		stamp = haxe.Timer.stamp();

		super.create();
	}

	override public function update(elapsed:Float)
	{
		Sys.println(1.0 / (haxe.Timer.stamp() - stamp) + ' fps');
		stamp = haxe.Timer.stamp();
		super.update(elapsed);
	}
}
```
(And yes I'm using ``haxe.Timer.stamp`` for time between frames.

________________________________

**Observed behavior:**
100000 sprites gave between 7.9-9.3 fps on a 60hz monitor
**Expected behavior:**
100000 sprites will not lag the game pretty badly (Don't mind the load times when creating all those sprites, that's not the important part)

**Comment by Geokureli** [comment]
Note to others: this is from our discord discussion

What I said was:
> try drawing 100000 objects and then tell me that the MAIN issue there is the draw items
> I emphasize MAIN because you're likely gonna have more prominent issues in that case

Not one is surprised that 100000 sprites causes slowdown, your job was to determine if your hypothesis of why, is correct. You said:
> I think flixel should have a pooling system with draw calls and update calls.
> Because, it's simply more efficient
> And, it keeps the gc from cleaning up every time 
> Which caused more jitters to happen than normal
> So we need to have the least gc clean ups as possible
> It's especially faster than just doing a for loop and calling draw from there

have you learned that the slowdown is related to memory leaks from draw calls? I'm gonna guess that it isn't

**Comment by SomeGuyWhoLovesCoding** [comment]
The memory only leaks a bit for 400x400 pixel images but for 1024x2048 images, yes.
So, I've thought of a pooling system that'll use the same function, and when you set active to false, it basically removes that function from the update pool. Otherwise, it adds back that function.

**Comment by Geokureli** [comment]
the system you talk about [here](https://github.com/SomeGuyWhoLovesCoding/100000SpriteDrawxTest/commit/728c5915627e746fcee948c8301daad7f437866b) would have no effect on memory or GC rate
