### ISSUE TITLE
[FIXEL BUG] Sound starts over when focus gain event triggers (after triggering the focus lost event)

### ISSUE THREAD

**Issue by SomeGuyWhoLovesCoding** [HaxeFlixel/flixel#3117]
Observed on HashLink btw.

To reproduce:
Just play the sound in ``create()`` via ``FlxG.sound.playMusic('assets/music.ogg', 1);``

Here's a video to show proof:

https://github.com/HaxeFlixel/flixel-ui/assets/99929173/50ec0569-eb72-4c89-9a74-dcbce053b6b7

**Comment by Geokureli** [comment]
> It happens with every ogg file, by putting just a string in the first argument of `FlxG.sound.playMusic`

here's what I tried
```hx
package states;

import flixel.FlxG;

class MusicRestartTestState extends flixel.FlxState
{
    override function create()
    {
        super.create();
        
        FlxG.sound.playMusic("assets/sounds/flixel-mono.ogg");
    }
}
```
it worked totally fine, can you share an ogg that causes this for you

**Comment by SomeGuyWhoLovesCoding** [comment]
> > It happens with every ogg file, by putting just a string in the first argument of `FlxG.sound.playMusic`
> 
> here's what I tried
> 
> ```hx
> package states;
> 
> import flixel.FlxG;
> 
> class MusicRestartTestState extends flixel.FlxState
> {
>     override function create()
>     {
>         super.create();
>         
>         FlxG.sound.playMusic("assets/sounds/flixel-mono.ogg");
>     }
> }
> ```
> 
> it worked totally fine, can you share an ogg that causes this for you

It happens on the breakfast music in hashlink

**Comment by Geokureli** [comment]
I don't know what the breakfast music is can you attach or link it to this thread

**Comment by SomeGuyWhoLovesCoding** [comment]
> I don't know what the breakfast music is can you attach or link it to this thread

The current fnf pause music

**Comment by Geokureli** [comment]
> The current fnf pause music

can you just link it or attach it, dude. I've asked like 5 times

**Comment by SomeGuyWhoLovesCoding** [comment]
> > The current fnf pause music
> 
> can you just link it or attach it, dude. I've asked like 5 times

Sure, hold on

**Comment by SomeGuyWhoLovesCoding** [comment]
> > > The current fnf pause music
> > 
> > 
> > can you just link it or attach it, dude. I've asked like 5 times
> 
> Sure, hold on

I can't send an ogg to github so here's a drive link: https://drive.google.com/file/d/1sNjPbnhEXvpTogwcTxHr3S-TK1_N4t8H/view?usp=sharing

**Comment by Geokureli** [comment]
thanks for the file, but it still doesn't reproduce the issue for me

https://github.com/HaxeFlixel/flixel/assets/2609513/d8759a45-3586-4751-bcb4-194d268c00d5

There's not much I can do without a solid repro. I recommend trying this with openfl Sounds too and se if it's a openfl issue

**Comment by SomeGuyWhoLovesCoding** [comment]
> thanks for the file, but it still doesn't reproduce the issue for me
> 
>  Screen.Recording.2024-04-17.at.2.52.22.PM.mov 
> There's not much I can do without a solid repro. I recommend trying this with openfl Sounds too and se if it's a openfl issue



> thanks for the file, but it still doesn't reproduce the issue for me
> 
>  Screen.Recording.2024-04-17.at.2.52.22.PM.mov 
> There's not much I can do without a solid repro. I recommend trying this with openfl Sounds too and se if it's a openfl issue

You're on hl, right?

**Comment by Geokureli** [comment]
> You're on hl, right?

Yes I mention using HL in my initial reply

**Comment by SomeGuyWhoLovesCoding** [comment]
> > You're on hl, right?
> 
> Yes I mention using HL in my initial reply

Okay, that bug does happen to me though

**Comment by Geokureli** [comment]
I'm never said it's not happening to you, I'm saying there's not much I can do without reproducing it myself and I recommend things you should try

**Comment by ACrazyTown** [comment]
Could you be running a Lime fork by chance? I noticed you were making an audio related pull request to Lime so maybe you're using that fork instead of stable?

**Comment by SomeGuyWhoLovesCoding** [comment]
> Could you be running a Lime fork by chance? I noticed you were making an audio related pull request to Lime so maybe you're using that fork instead of stable?

I am running a lime fork - and the bug still persists on the latest stable release (8.1.2)

**Comment by Geokureli** [comment]
> I recommend trying this with openfl Sounds too and se if it's a openfl issue

did you try this?

**Comment by ACrazyTown** [comment]
> > Could you be running a Lime fork by chance? I noticed you were making an audio related pull request to Lime so maybe you're using that fork instead of stable?
> 
> I am running a lime fork - and the bug still persists on the latest stable release (8.1.2)

I tried your fork and I could reproduce the issue (The sound resets when focus is gained):

https://github.com/HaxeFlixel/flixel/assets/47027981/0c2b5fb1-6c3c-410c-9e3f-0cfb747cdaca

However I can't get it to happen on haxelib Lime 8.1.2 (The sound time progresses as expected):

https://github.com/HaxeFlixel/flixel/assets/47027981/9b9108e5-5d8e-4638-886b-7455bd47fd29

Maybe you're not switching between the fork and haxelib properly?

**Comment by SomeGuyWhoLovesCoding** [comment]
> > > Could you be running a Lime fork by chance? I noticed you were making an audio related pull request to Lime so maybe you're using that fork instead of stable?
> > 
> > 
> > I am running a lime fork - and the bug still persists on the latest stable release (8.1.2)
> 
> I tried your fork and I could reproduce the issue (The sound resets when focus is gained):
> 
>  2024-04-18.16-34-56.mp4 
> However I can't get it to happen on haxelib Lime 8.1.2 (The sound time progresses as expected):
> 
>  2024-04-18.16-35-27.mp4 
> Maybe you're not switching between the fork and haxelib properly?

How does the sound even reset in the first place?

**Comment by ACrazyTown** [comment]
> How does the sound even reset in the first place?
>

It's your code, I don't know what changes you made

**Comment by glintfishGH** [comment]
check the stable lime repo you're using, knowing you, you probably changed something in there aswell.

This is what happens when you change code when you have no idea what it does by the way, this is why we tell you _not_ to do shit like this.

**Comment by YanniZ06** [comment]
> > > > Could you be running a Lime fork by chance? I noticed you were making an audio related pull request to Lime so maybe you're using that fork instead of stable?
> > > 
> > > 
> > > I am running a lime fork - and the bug still persists on the latest stable release (8.1.2)
> > 
> > 
> > I tried your fork and I could reproduce the issue (The sound resets when focus is gained):
> > 2024-04-18.16-34-56.mp4
> > However I can't get it to happen on haxelib Lime 8.1.2 (The sound time progresses as expected):
> > 2024-04-18.16-35-27.mp4
> > Maybe you're not switching between the fork and haxelib properly?
> 
> How does the sound even reset in the first place?

Stop asking that, you know the issue is with you so stop requesting us to fix your mess. If you're gonna make your own "better" changes, do them right, otherwise stop complaining and ESPECIALLY don't expect us to be able to fix what is very clearly a mistake 100% on you.

By the way it should generally be common sense to not make an issue for something on the original when you're using a MODIFIED VERSION of it, I mean you wouldn't report any bugs you get while playing a game modded to the original devs of the game, right? I hope this helps you solve your problem(s),

Cheers

**Comment by Geokureli** [comment]
If anyone can reproduce this on the standard lime repo, I'll reopen, but for now, I'm filing this under "not a flixel issue"
