### ISSUE TITLE
Typo in FlxMouseEventManager??

### ISSUE THREAD

**Issue by TheGaloXx** [HaxeFlixel/flixel#3126]
https://github.com/HaxeFlixel/flixel/blob/7e7eb5cfe31e2ccbdc49561ca90b7d9108d3d2c3/flixel/input/mouse/FlxMouseEventManager.hx#L274C47-L274C48

I don't know how this works but I'm pretty sure there's a typo on that line.

"Callback when mouse is this object."

Shouldn't it be something like "Callback when mouse is over this object."?

**Comment by Geokureli** [comment]
You're welcome to make a change and fix it. Just click the edit button, here:
https://github.com/HaxeFlixel/flixel/blob/dev/flixel/input/mouse/FlxMouseEventManager.hx#L274

**Comment by TheGaloXx** [comment]
Alright, thanks!

**Comment by TheGaloXx** [comment]
I think it's done.
https://github.com/HaxeFlixel/flixel/pull/3127
