### ISSUE TITLE
FlxState.destroy() causes FlxG.resetState() to throw an error

### ISSUE THREAD

**Issue by BendyGaming0** [HaxeFlixel/flixel#3146]
- **Haxe version:** 4.2.5
- **Flixel version:** 5.8.0
- **OpenFL version:** 9.3.3
- **Lime version:** 8.1.2
- **Affected targets:** All, to my knowledge

Because the `state.destroy()` function is always called on the current state by `FlxGame` when switching or resetting states, it always throws an error when using a maker function for `NextState` as it calls the overwritten `state._constructor` field in `NextState.createInstance()`
________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxState;
import flixel.ui.FlxButton;

class PlayState extends FlxState
{
	override public function create():Void
	{
		var resetButton = new FlxButton(0, 0, "Reset", () -> FlxG.resetState());
		resetButton.screenCenter();
		add(resetButton);
	}
}
```

________________________________

**Observed behavior:**
FlxState throws an error saying that the state has been destroyed while attempting to use resetState

**Expected behavior:**
The current state (`PlayState`) would be restarted using the previously passed in `NextState` maker function by `FlxG.switchState()` somewhere else

**Comment by Geokureli** [comment]
The provided code snippet does not reproduce the issue, when tested.

Perhaps you're actual failing program is calling resetState in `create` rather on an event, if so, then I would expect there to be issues, regardless?
