### ISSUE TITLE
FlxTween: Unsupported recursive type

### ISSUE THREAD

**Issue by Vortex2Oblivion** [HaxeFlixel/flixel#3149]
Getting a compiler error when targeting for hashlink in FlxTween on line 938 which is 
```hx
typedef TweenCallback = FlxTween->Void;
```

**Comment by Vortex2Oblivion** [comment]
changing it to```hx
typedef TweenCallback = #if hl Dynamic #else FlxTween #end->Void;
```
fixes it??

**Comment by Vortex2Oblivion** [comment]
@CobaltBar
pinging you since you're having the same issue

**Comment by ThePlank** [comment]
@CobaltBar @Vortex2Oblivion, can both of you try building the FlxTween demo? (without the fix vortex found) just to verify that this isn't a project related issue since i've not been able to reproduce the same error

**Comment by DigiEggz** [comment]
@CobaltBar @Vortex2Oblivion What host platform are you compiling on?

**Comment by Vortex2Oblivion** [comment]
> @CobaltBar @Vortex2Oblivion Which host platform are you compiling on?

Windows 11 me and (I think) cobaltbar is on Linux

**Comment by DigiEggz** [comment]
Sample project that reproduces the error
[Demo.zip](https://github.com/user-attachments/files/15596819/Demo.zip)

**Comment by 47rooks** [comment]
You don't list steps or versions but I was able to build it with`lime build hl` on 

haxe 4.3.3
flixel 5.6.2
flixel-addons 3.2.3
Hashlink 1.14
Win 10

Tried turning off dce as transition is not used anywhere. Still didn't repro.

**Comment by DigiEggz** [comment]
> You don't list steps or versions but I was able to build it with`lime build hl` on
> 
> haxe 4.3.3 flixel 5.6.2 flixel-addons 3.2.3 Hashlink 1.14 Win 10
> 
> Tried turning off dce as transition is not used anywhere. Still didn't repro.

Sorry for the lack of details. You'll need to test using flixel 5.7.0 or later. It occurs due to a typedef introduced by FlxTween's flicker.

**Comment by 47rooks** [comment]
Ok, now I can repro it - just updating to flixel 5.7.0 was enough. Next question is why ?
