### ISSUE TITLE
FlxCamera.fill() uses blend mode of the last drawn item on camera

### ISSUE THREAD

**Issue by richTrash21** [HaxeFlixel/flixel#3203]
- **Haxe version:** 4.3.4
- **Flixel version:** 5.8.0
- **OpenFL version:** 9.3.3
- **Lime version:** 8.1.2
- **Affected targets:** all non blitting targets

________________________________

While messing around with blend modes I noticed the following bug: if the last drawn item on camera had any blend mode, it will also apply to the camera's fill function.
Here's an example of this bug from a little [test project](https://github.com/richTrash21/fade-bug-test) I made, that replicates an environment where I encountered the bug:

https://github.com/HaxeFlixel/flixel/assets/87835336/9ed630a9-b62b-46d8-93f9-fe9bf9204ed7

As it was seen in the video the fade effect (which uses the fill function) have an ADD blend mode applied to it which was caused by the last drawn item on camera - a sprite with an ADD blend mode.

This is how it suppose to behave:

https://github.com/HaxeFlixel/flixel/assets/87835336/90f66dba-5638-4b08-ab8b-dc6a7adeb5e4

I ran this test project on Windows, Neko, HashLink, HTML5 and Flash and only non blitting targets were affected by this bug (blend modes just doesn't work on Flash so there's nothing to break I suppose). I also found a solution for this issue but it needs further testing before I can make a PR with a proper implementation of the fix. Might also wait a bit since from what I've read in #2966 blend modes are not implemented but also partially are?

________________________________

**Observed behavior:**
Last rendered item blend mode affects the fill function, applying blend to the resulting fill.

**Expected behavior:**
Last rendered item blend mode should not affect fill function at all.

**Comment by Geokureli** [comment]
Can i get a more simplified way to reproduce this issue, I'm not entirely following the problem and the fix

**Comment by richTrash21** [comment]
> Can i get a more simplified way to reproduce this issue, I'm not entirely following the problem and the fix

Yeah sure, sorry for the inconvenience 
https://github.com/richTrash21/fade-bug-test/tree/simple
