### ISSUE TITLE
FlxAnimationController.callback should be an FlxSignal

### ISSUE THREAD

**Issue by EliteMasterEric** [HaxeFlixel/flixel#3204]
https://github.com/HaxeFlixel/flixel/blob/5ee97353cfca85a25bd835588c879fc005a95871/flixel/animation/FlxAnimationController.hx#L61

Since this (and the finishCallback just below it) are Functions rather than FlxSignals, you can only assign one per sprite, and assigning a second one silently removes the first, causing unexpected issues.

`callback` and `finishCallback` should be deprecated and replaced with appropriate FlxTypedSignals.

The only related issue I found is #2816 which proposes a separate thing.

(Just writing this down before I forget, it should be extremely easy to implement in practice but I'm busy with something else at the moment).

**Comment by richTrash21** [comment]
I was thinking about making this a pr lately, will try to work on it today/tomorrow

**Comment by DetectiveBaldi** [comment]
mentioned this a few days ago in the Haxe discord, totally agree

**Comment by Geokureli** [comment]
piggybacking related issue: https://github.com/HaxeFlixel/flixel/issues/3212

I'd like to address this now while we are adding new fields
