### ISSUE TITLE
FlxCamera.color is not functional

### ISSUE THREAD

**Issue by DetectiveBaldi** [HaxeFlixel/flixel#3207]
Using the following sample results in a untinted white graphic, the expected output is for it to be tinted red:

```haxe
package;

import flixel.FlxG;
import flixel.FlxSprite;
import flixel.FlxState;

import flixel.util.FlxColor;

class PlayState extends FlxState
{
    override function create():Void
    {
        super.create();

        add(new FlxSprite().makeGraphic(640, 480, FlxColor.WHITE));

        FlxG.camera.color = FlxColor.RED;
    }
}
```

![image-11.png](https://github.com/HaxeFlixel/flixel/assets/86160807/1dbc90eb-ee0a-41f0-a9ec-58e3b73ac933)

**Comment by Geokureli** [comment]
Thanks I'll take a look!

**Comment by Geokureli** [comment]
Sorry for the late reply, this is an issue with openfl's colorTransform on non-flash targets: https://github.com/HaxeFlixel/flixel/issues/3207

I'll escalate this issue, but we should consider adding documentation informing that `camera.color` doesn't work on those targets, fixing the openfl issue, or making a workaround. I don't have any ideas at the moment, will report back in a bit

**Comment by Geokureli** [comment]
Adding link again for linkage https://github.com/openfl/openfl/issues/2071
