### ISSUE TITLE
Rendering artifacts are shown when an flxsprite's angle is not 0 or 180

### ISSUE THREAD

**Issue by SomeGuyWhoLovesCoding** [HaxeFlixel/flixel#3224]
- **Haxe version:** 4.3.4
- **Flixel version:** 5.8.0
- **OpenFL version:** 9.3.3
- **Lime version:** 8.1.2
- **Affected targets:**

________________________________

**Repository that you can compile reproducing the issue**: https://github.com/SomeGuyWhoLovesCoding/shader_bitmap_wrap_REPEAT_rendering_artifact_reproduction

________________________________

So, I was coding in a class that:
1. extends flxsprite
2. has a flxsprite variable inside being drawn below the main flxsprite
Now, I did shadow the FlxDrawQuadsItem class and added the ``shader.bitmap.wrap = REPEAT;`` (which I expected that there would be no artifacts) just to experiment with tiling using draw quads instead of draw triangles, which caused a rendering bug that an observed artifact appears when a flxsprite's angle is not equal to 0 or 180. However, the artifact doesn't happen if ``shader.bitmap.wrap`` is CLAMP or REPEAT_U_CLAMP_V.
Here's proof of what I'm talking about:
![Image is edited btw](https://github.com/user-attachments/assets/3694f734-7e41-4670-a488-97c6d6a11628)
(I'm using the latest stable release build)

**Comment by EyeDaleHim** [comment]
You've shadowed a class, so this makes your issue hard to fix. Can you remove the shadowed class?

**Comment by SomeGuyWhoLovesCoding** [comment]
> You've shadowed a class, so this makes your issue hard to fix. Can you remove the shadowed class?

No. I've shadowed it because I've added a new line between lines 121 and 123, which makes the sprite actually repeat texture if you change the frame's y or height.

**Comment by EyeDaleHim** [comment]
The issue with shadowing classes and then posting it to this repository's Issues tab.

Since what I'm looking at here is a bug, this might be irrelevant at all.

**Comment by SomeGuyWhoLovesCoding** [comment]
It's not even an issue with shadowing classes. It's a rendering artifact that you also see with flxstrip or flxtiledsprite.

**Comment by EyeDaleHim** [comment]
> It's not even an issue with shadowing classes. It's a rendering artifact that you also see with flxstrip or flxtiledsprite.

Can you prove it's truly a rendering artifact that we definitely see with those two classes? Not some unexpected behavior of shadowing classes?

**Comment by Geokureli** [comment]
start a new project and recreate the issue without shadowed classes, and if it still happens let us know

**Comment by Geokureli** [comment]
Reopen this issue, if it can be reproduced in vanilla Flixel

**Comment by SomeGuyWhoLovesCoding** [comment]
> start a new project and recreate the issue without shadowed classes, and if it still happens let us know

The issue still happens even without shadowing the class

**Comment by Geokureli** [comment]
then share a simple test case reproducing this

**Comment by SomeGuyWhoLovesCoding** [comment]
The rendering artifact appears if the sprite'd angle is not 9 or 180 and if you add ``graphic.shader.bitmap.wrap = REPEAT``

**Comment by Geokureli** [comment]
create a small, complete TestState.hx that we can copy and test

**Comment by SomeGuyWhoLovesCoding** [comment]
The issue was solved and it was texture bleeding.

**Comment by Geokureli** [comment]
feel free to link the solution for others who have a similar issue
