### ISSUE TITLE
general problems with shaders

### ISSUE THREAD

**Issue by Slushi-Github** [HaxeFlixel/flixel#3240]
- **Haxe version:** 4.3.4
- **Flixel version:** 5.9.0
- **OpenFL version:** 9.3.4
- **Lime version:**  8.1.3
- **Affected targets:** Windows (?)
________________________________

**Code snippet reproducing the issue**:
```haxe
package;

import flixel.FlxState;
import flixel.util.FlxColor;
import flixel.FlxCamera;
import flixel.FlxG;
import flixel.FlxSprite;

class PlayState extends FlxState
{
	var shaderTest:ShaderExample;

	override public function create():Void
	{
		shaderTest = new ShaderExample();

		var sprite = new FlxSprite().makeGraphic(100, 100, FlxColor.WHITE);
		add(sprite);

		sprite.shader = shaderTest.shader; // Null object reference, in graphics.tile.FlxDrawQuadsItem, line 123

		FlxG.camera.shader = shaderTest.shader; // whatever is in this camera becomes invisible (or disappears), but does not crash.
	}
}
```
________________________________

This is an error that has been happening to me for a few days, no shader, or very few work, I can not provide the shader code as I do not know if it is the fault of the shader or Flixel/OpenFL, I do not know if this issue should go to the OpenFL repository, as it is an error apparently coming from ``openfl.display.GraphicsShader``, or is it ok to leave it here.
There is a chance that I have not explained well, an apology.

**Comment by moxie-coder** [comment]
you need to show the error for what is happening and also show what the shader code is, because there isn’t much help that can be done otherwise

**Comment by Slushi-Github** [comment]
> you need to show the error for what is happening and also show what the shader code is, because there isn’t much help that can be done otherwise

Error:
```
Called from flixel.graphics.tile.FlxDrawQuadsItem.render (flixel/graphics/tile/FlxDrawQuadsItem.hx line 123)
Called from flixel.FlxCamera.render (flixel/FlxCamera.hx line 816)
Called from flixel.FlxGame.draw (flixel/FlxGame.hx line 886)
Called from flixel.FlxGame.onEnterFrame (flixel/FlxGame.hx line 566)
Null Object Reference
Called from flixel.FlxGame::onEnterFrame flixel/FlxGame.hx line 566
Called from flixel.FlxGame::draw flixel/FlxGame.hx line 886
Called from flixel.FlxCamera::render flixel/FlxCamera.hx line 816
Called from flixel.graphics.tile.FlxDrawQuadsItem::render flixel/graphics/tile/FlxDrawQuadsItem.hx line 123
```

And this is the shader I've been using previously, which worked without problems:
```haxe
class ThreeDShader extends FlxShader
{
  @:glFragmentSource('
  #pragmaheader 

  #definePI 3.14159265 uniform float xrot = 0.0;
  uniform float yrot = 0.0;
  uniform float zrot = 0.0;
  uniform float depth = 0.0;
  float plane( in vec3 norm, in vec3 po, in vec3 ro, in vec3 rd)
  {
    float
    de = dot(norm, rd);
    de = sign(de) * max(abs(de), 0.001);
    return dot(norm, po - ro) / de;
  }
  vec2 raytraceTexturedQuad( in vec3 rayOrigin, in vec3 rayDirection, in vec3 quadCenter, in vec3 quadRotation, in vec2 quadDimensions)
  {
    // Rotations ------------------
    float
    a = sin(quadRotation.x);
    float
    b = cos(quadRotation.x);
    float
    c = sin(quadRotation.y);
    float
    d = cos(quadRotation.y);
    float
    e = sin(quadRotation.z);
    float
    f = cos(quadRotation.z);
    float
    ac = a * c;
    float
    bc = b * c;
    mat3
    RotationMatrix = mat3(d * f, d * e, -c, ac * f - b * e, ac * e + b * f, a * d, bc * f + a * e, bc * e - a * f, b * d);
    //--------------------------------------
    vec3
    right = RotationMatrix * vec3(quadDimensions.x, 0.0, 0.0);
    vec3
    up = RotationMatrix * vec3(0, quadDimensions.y, 0);
    vec3
    normal = cross(right, up);
    normal /= length(normal);
    // Find the plane hit point in space
    vec3
    pos = (rayDirection * plane(normal, quadCenter, rayOrigin, rayDirection)) - quadCenter;
    // Find the texture UV by projecting the hit point along the plane dirs
    return vec2(dot(pos, right) / dot(right, right), dot(pos, up) / dot(up, up)) + 0.5;
  }
  void main()
  {
    vec4
    texColor = texture2D(bitmap, openfl_TextureCoordv);
    // Screen UV goes from 0 - 1 along each axis
    vec2
    screenUV = openfl_TextureCoordv;
    vec2
    p = (2.0 * screenUV) - 1.0;
    float
    screenAspect = 1280 / 720;
    p.x *= screenAspect;
    // Normalized Ray Dir
    vec3
    dir = vec3(p.x, p.y, 1.0);
    dir /= length(dir);
    // Define the plane
    vec3
    planePosition = vec3(0.0, 0.0, depth + 0.5);
    vec3
    planeRotation = vec3(xrot, PI + yrot, zrot); // this the shit you needa change
    vec2
    planeDimension = vec2(-screenAspect, 1.0);
    vec2
    uv = raytraceTexturedQuad(vec3(0), dir, planePosition, planeRotation, planeDimension);
    // If we hit the rectangle, sample the texture
    if (abs(uv.x - 0.5) < 0.5 && abs(uv.y - 0.5) < 0.5)
    {
      gl_FragColor = vec4(flixel_texture2D(bitmap, uv));
    }
  }
')
  public function new()
  {
    super();
  }
}
```

**Comment by Slushi-Github** [comment]
what I understand about the error is that ``shader.bitmap`` is null, and hence the problem, what I do not understand is, why it is null with shaders that used to work and there are a few shaders that still work.

**Comment by Geokureli** [comment]
shader.bitmap being null may be a case of simply trying to draw a destroyed sprite. Let's focus on the example you gave, does that reproduce this issue? Could you provide the code in ShaderExample.hx?

**Comment by Slushi-Github** [comment]
does not reproduce the error, it is an example code, sorry, with it the ``ShaderExample.hx`` does not exist.
the sprite and shader, it exists, but it returns this error.
I have to admit that I use a fork of Flixel, but neither the one who made the fork or I understand the error that occurs, since the fork has a recent flixel, I accept the inconvenience of not having mentioned that from the beginning or the stupidity that it may be my fault and the one who made that fork that the shaders do not work, only that the way in which the shaders are loaded has not been changed, so we do not understand the problem or when it started.

**Comment by Geokureli** [comment]
unless you can make a simple test that reproduces some error, there's really nothing I can do. in cases like this usually ends up being either your code or the fork

What I tend to do is copy all relevant code over to a new project, if it fails, try removing some code and see if it still breaks, do this until you've removed all unrelated code, once you get there it should be easy to test whether it's the fork or flixel

Can you link the fork?

**Comment by Slushi-Github** [comment]
> What I tend to do is copy all relevant code over to a new project, if it fails, try removing some code and see if it still breaks, do this until you've removed all unrelated code, once you get there it should be easy to test whether it's the fork or flixel

I did that, and it keeps crashing

> Can you link the fork?

Here: https://github.com/glowsoony/flixel

**Comment by Geokureli** [comment]
> > What I tend to do is copy all relevant code over to a new project, if it fails, try removing some code and see if it still breaks, do this until you've removed all unrelated code, once you get there it should be easy to test whether it's the fork or flixel
> 
> I did that, and it keeps crashing

If you "did that", you would have an easily shared test case that reproduces the issue without the fork, but you never supplied one, so I'm assuming you misread what I said or you're holding something back

**Comment by Slushi-Github** [comment]
in both the fork and the original version of flixel, the error occurs, eh, I don't know how to demonstrate the problem anymore, here's the [project folder](https://github.com/user-attachments/files/16680254/Project.zip) where I've been testing for a while now

based on those libraries that I have, whether I use the fork or not, the error occurs

**Comment by Geokureli** [comment]
@Slushi-Github change `#pragmaheader` to `#pragma header` (two words)

**Comment by Geokureli** [comment]
apart from the pragma header issue, openFL uses a specific glsl version which lacks certain features that would work on, say shadertoy (where I tend to make my shaders)
```hx
class ThreeDShader extends FlxShader
{
  @:glFragmentSource('
  #pragma header

  const float PI = 3.14159265; // was "#definePI 3.14159265"  which is nonsense
  uniform float xrot; // uniforms can't have default values, assign in the constructor
  uniform float yrot; // uniforms can't have default values, assign in the constructor
  uniform float zrot; // uniforms can't have default values, assign in the constructor
  uniform float depth; // uniforms can't have default values, assign in the constructor
  float plane( in vec3 norm, in vec3 po, in vec3 ro, in vec3 rd)
  {
    float
    de = dot(norm, rd);
    de = sign(de) * max(abs(de), 0.001);
    return dot(norm, po - ro) / de;
  }
  vec2 raytraceTexturedQuad( in vec3 rayOrigin, in vec3 rayDirection, in vec3 quadCenter, in vec3 quadRotation, in vec2 quadDimensions)
  {
    // Rotations ------------------
    float
    a = sin(quadRotation.x);
    float
    b = cos(quadRotation.x);
    float
    c = sin(quadRotation.y);
    float
    d = cos(quadRotation.y);
    float
    e = sin(quadRotation.z);
    float
    f = cos(quadRotation.z);
    float
    ac = a * c;
    float
    bc = b * c;
    mat3
    RotationMatrix = mat3(d * f, d * e, -c, ac * f - b * e, ac * e + b * f, a * d, bc * f + a * e, bc * e - a * f, b * d);
    //--------------------------------------
    vec3
    right = RotationMatrix * vec3(quadDimensions.x, 0.0, 0.0);
    vec3
    up = RotationMatrix * vec3(0.0, quadDimensions.y, 0.0); // prev version had 0, which is treated as an int
    vec3
    normal = cross(right, up);
    normal /= length(normal);
    // Find the plane hit point in space
    vec3
    pos = (rayDirection * plane(normal, quadCenter, rayOrigin, rayDirection)) - quadCenter;
    // Find the texture UV by projecting the hit point along the plane dirs
    return vec2(dot(pos, right) / dot(right, right), dot(pos, up) / dot(up, up)) + 0.5;
  }
  void main()
  {
    vec4
    texColor = texture2D(bitmap, openfl_TextureCoordv);
    // Screen UV goes from 0 - 1 along each axis
    vec2
    screenUV = openfl_TextureCoordv;
    vec2
    p = (2.0 * screenUV) - 1.0;
    float
    screenAspect = 1280.0 / 720.0; // added .0
    p.x *= screenAspect;
    // Normalized Ray Dir
    vec3
    dir = vec3(p.x, p.y, 1.0);
    dir /= length(dir);
    // Define the plane
    vec3
    planePosition = vec3(0.0, 0.0, depth + 0.5);
    vec3
    planeRotation = vec3(xrot, PI + yrot, zrot); // this the shit you needa change
    vec2
    planeDimension = vec2(-screenAspect, 1.0);
    vec2
    uv = raytraceTexturedQuad(vec3(0), dir, planePosition, planeRotation, planeDimension);
    // If we hit the rectangle, sample the texture
    if (abs(uv.x - 0.5) < 0.5 && abs(uv.y - 0.5) < 0.5)
    {
      gl_FragColor = vec4(flixel_texture2D(bitmap, uv));
    }
  }
')
  public function new()
  {
    super();
    // set drfault values of uniforms
    yrot.value = [0.0];
    zrot.value = [0.0];
    xrot.value = [0.0];
    depth.value = [0.0];
  }
}

**Comment by glowsoony** [comment]
Hey, Coder of repo of my own flixel! @Slushi-Github Is my friend who asked about the shaders because we both seem to have not found a way for them to work after we used later libs and we were looking for solutions, Thank you so much for helping! the error was #pragmaheader not having a space, the shaders are old that's why they have errors, they still work well.

**Comment by glowsoony** [comment]
The errors that were present were shader.bitmap being null when applied to sprites and black screen when applied to shaders which I thought might be errors of something other then the shader. That's all I wanted to say. Thank you so so so much for helping!!!
