### ISSUE TITLE
sprite.color is not honored when using a shader with the default glFragmentSource

### ISSUE THREAD

**Issue by Geokureli** [HaxeFlixel/flixel#3246]
In the following code, a magenta square is the result, but if `@glFragmentSource` is uncommented it becomes a white square, not sure why using a custom fragment shader causes this when FlxGraphicsShader uses color in the [Fragment Header](https://github.com/HaxeFlixel/flixel/blob/dev/flixel/graphics/tile/FlxGraphicsShader.hx#L51)
```hx
package states;

class ShaderColorTestState extends flixel.FlxState
{
	override public function create()
	{
		super.create();
		
		final sprite = new flixel.FlxSprite().makeGraphic(100, 100);
		sprite.shader = new SimpleShader();
		sprite.color = 0xFFff00ff;
		add(sprite);
	}
}

class SimpleShader extends flixel.system.FlxAssets.FlxShader
{
	// Uncommenting this tag will cause the error
	// @:glFragmentSource('
	// 	#pragma header
	// 	
	// 	void main()
	// 	{
	// 		gl_FragColor = texture2D(bitmap, openfl_TextureCoordv);
	// 	}
	// ')
	public function new()
	{
		super();
	}
}
```

**Comment by NeeEoo** [comment]
you need to use flixel_texture2D

**Comment by NeeEoo** [comment]
if you use texture2D instead of flixel_texture2D then it wont honor colorTransform/color or alpha

**Comment by Geokureli** [comment]
Ha, that fixes it, thanks!
