### ISSUE TITLE
FlxInputText - fieldBorderThickness isn't working

### ISSUE THREAD

**Issue by Geokureli** [HaxeFlixel/flixel#3258]
@Starmapo was this working last you tried it? The default `fieldBorderThickness` is 1 and the default color is black

Example:
```hx
override function create()
{
    super.create();
    
    final text = new flixel.text.FlxInputText(10, 10, FlxG.width - 20, "Enter Username... (Max 40 Characters)", 32);
    text.font = "Arial";
    add(text);
}
```
Result:

<img width="799" alt="Screenshot 2024-09-26 at 3 50 07 PM" src="https://github.com/user-attachments/assets/82638367-2827-4d9c-9525-4e1178f021d5">

**Comment by Starmapo** [comment]
That's weird, it definitely was working last time I tested it... I'll look into it once I have the time

**Comment by Starmapo** [comment]
Turns out to have been from an issue in the clipping system, which seems like I did not test out at all 😅

PR #3259 should fix it
