### ISSUE TITLE
Trouble will Compile Android Game in Source Code

### ISSUE THREAD

**Issue by megalives717** [HaxeFlixel/flixel#3274]
![error](https://github.com/user-attachments/assets/9843e022-6c70-4967-b9c6-5a315579ddae)
i use command `lime build android` but shows error

**Comment by megalives717** [comment]
i use command `lime build android` but shows error

**Comment by ACrazyTown** [comment]
Post a screenshot of what command you run and the full output you get

For more info about compiling to Android, read Lime's documentation: https://lime.openfl.org/docs/advanced-setup/android/

**Comment by megalives717** [comment]
yes

**Comment by Vortex2Oblivion** [comment]
*what*
