### ISSUE TITLE
haxelib git flixel https://github.com/HaxeFlixel/flixel not installing

### ISSUE THREAD

**Issue by megalives717** [HaxeFlixel/flixel#3288]

**Comment by ACrazyTown** [comment]
Can you send a screenshot of what appears in the terminal after you type the command?

**Comment by Geokureli** [comment]
My initial guess is that there were some network issues, or maybe the haxelib server was down, briefly. I would try again and copy the error message, here

**Comment by megalives717** [comment]
work

**Comment by Vortex2Oblivion** [comment]
> work

Can you share the solution
