### ISSUE TITLE
How To Port Flash Game to HaxeFlixel?

### ISSUE THREAD

**Issue by megalives717** [HaxeFlixel/flixel#3291]
Port SWF To HaxeFlixel How?

**Comment by megalives717** [comment]
HaxeFlixel Needed?

**Comment by moxie-coder** [comment]
no, this isn’t even flixel related

**Comment by moxie-coder** [comment]
also, you can't port flash games to flixel directly, ActionScript and HaxeFlixel are two different things, there is the Flixel made for Flash which is what this is based on, but that's all you're gonna get really
