### ISSUE TITLE
Port Flash to HaxeFlixel?

### ISSUE THREAD

**Issue by megalives717** [HaxeFlixel/flixel#3292]

**Comment by ACrazyTown** [comment]
What exactly are you trying to accomplish? Could you elaborate a bit more?

**Comment by moxie-coder** [comment]
I already said before that you can't do that, only the Actionscript library

**Comment by Geokureli** [comment]
Please do not:
- Make duplicate issues
- Make issues where you're asking how to do things, use [Discussions](https://github.com/HaxeFlixel/flixel/discussions) for that, and be specific, this is could not be any more vague

**Comment by moxie-coder** [comment]
> Please do not:
> 
> * Make duplicate issues
> * Make issues where you're asking how to do things, use [Discussions](https://github.com/HaxeFlixel/flixel/discussions) for that, and be specific, this is could not be any more vague

They’ve made many other issues like this before on other repos, it’s annoying to be honest

**Comment by megalives717** [comment]
Why?

**Comment by Geokureli** [comment]
Locking this as it does not seem constructive
