### ISSUE TITLE
How I Do Make Sonic In HaxeFlixel?

### ISSUE THREAD

**Issue by megalives717** [HaxeFlixel/flixel#3301]
- **Haxe version:** 4.3.6
- **Flixel version:** 5.8.0
- **OpenFL version:** 9.4.0
- **Lime version:** 8.2.1

Making Sonic In HaxeFlixel?

**Comment by Geokureli** [comment]
As i said in your last Issue.
- These are not issues, make a discussion instead or join the discord that I linked
- These questions are too vague, start with the [tutorial](https://haxeflixel.com/documentation/tutorial/), then look at the [demos](https://haxeflixel.com/demos/) and then ask specific questions like "how do i add curved slopes"

If you ignore this again then we will simply delete all the issues you create, on sight
