### ISSUE TITLE
[Feature request] Wayland support

### ISSUE THREAD

**Issue by Twig6943** [HaxeFlixel/flixel#3302]
![image](https://github.com/user-attachments/assets/41e111b4-11d5-47b1-977a-4c59a62b0052)

This can't be a duplicate, anyways I think a wayland backend would be a great addition cuz X is on its deathbed and should be avoided if possible

**Comment by Geokureli** [comment]
I'm unfamiliar with Wayland, can you link it?

**Comment by Twig6943** [comment]
https://wayland.freedesktop.org/

**Comment by ACrazyTown** [comment]
This should probably be moved to the [Lime](https://github.com/openfl/lime) repository as Lime is the part that handles windowing on native thru SDL2

**Comment by Geokureli** [comment]
Closing this for now, if Lime makes changes that should be reflected in flixel, feel free to reopen this issue

**Comment by Twig6943** [comment]
> Closing this for now. Once Lime makes changes that should be reflected in Flixel, feel free to reopen this issue

@Geokureli is there an issue tracker for this?
