### ISSUE TITLE
windows 10 64bit - Demos display black screen

### ISSUE THREAD

**Issue by non-npc** [HaxeFlixel/flixel#3317]
- **Haxe version:** latest
- **Flixel version:** latest
- **OpenFL version:** latest
- **Lime version:** latest
- **Affected targets:** windows 10 64bit

________________________________

**Code snippet reproducing the issue**:
Hello world example 
https://haxeflixel.com/documentation/hello-world/#add-the-%22hello-world%22-flxtext
________________________________

**Observed behavior:**
In html5 we see Haxe logo then a cursor on a black screen.
In neko we see a black screen.
In flashplayer we see a black screen.

**Expected behavior:**
text "Hello World" should be displayed

**Comment by Vortex2Oblivion** [comment]
> In html5 we see Haxe logo then a cursor on a black screen.
> 
> In neko we see a black screen.
> 
> In flashplayer we see a black screen.

What about hashlink and c++?

**Comment by non-npc** [comment]
> > In html5 we see Haxe logo then a cursor on a black screen.
> > In neko we see a black screen.
> > In flashplayer we see a black screen.
> 
> What about hashlink and c++?

No idea, I just followed the stop by step guide to install, reboot and run the demo.
Never used this before and was expecting to be able to get the demo working by following the very simple and clear steps.

**Comment by Vortex2Oblivion** [comment]
Try running 
```lime test hl```
```lime test cpp```

**Comment by non-npc** [comment]
> Try running `lime test hl` `lime test cpp`

lime test hl produces a window with the logo, a sound effect and a black screen with custom cursor.

lime test cpp produces a very long list of cpp files and then it compiles it after a few minutes and it also produces a window with the logo, a sound effect and then a black screen with custom cursor.

are we supposed to see the "Hello world" text ?

**Comment by ACrazyTown** [comment]
Can you show your code?

**Comment by non-npc** [comment]
> Can you show your code?

I copied line for every step here 
https://haxeflixel.com/documentation/hello-world/#add-the-%22hello-world%22-flxtext

**Comment by Geokureli** [comment]
I followed the hello world code and I see "hello world" on all targets.

please share your actual code.

**Comment by Geokureli** [comment]
If this is fixed, please let us know what the issue was?
