### ISSUE TITLE
"Failed to download https://lib.haxe.org:443/files/3.0/lime-8,2,2.zip."

### ISSUE THREAD

**Issue by Saunter-Official** [HaxeFlixel/flixel#3320]
- **Haxe version:** ?.?.?
- **Flixel version:** 8.2.2
- **OpenFL version:** ?.?.?
- **Lime version:** ?.?.?
- **Affected targets:**

________________________________

I try to install Lime 8.2.2 with the latest version of Haxe (4.3.6) but it keeps erroring me with this message
![image](https://github.com/user-attachments/assets/eaabf2e2-f273-402b-a458-09ede02268cd)

________________________________

**Observed behavior:**

**Expected behavior:**

**Comment by Geokureli** [comment]
Ask lime questions in [lime](https://github.com/openfl/lime), please.

also try again in a bit, could be network issues
