### ISSUE TITLE
Add x, y and alpha properties to FlxGroup

### ISSUE THREAD

**Issue by Gama11** [HaxeFlixel/flixel#360]
I already suggested this over at the [flixel-community fork](https://github.com/FlixelCommunity/flixel/issues/124?source=cc), but the contributors didn't like my approach too much. What do you guys think? 

In my opinion, the `x`, `y` and `alpha` properties for `FlxGroup` should _at least_ be available via an addon called `FlxGroupPlus` or `FlxGroupXY`, if not included in the original class. This was a thing in earlier versions of flixel, and I don't see why they took it out, it's extremely useful.

**Comment by nightblade9** [comment]
Thanks for leaving this paper-trail. When I google how to move a `FlxGroup`, I came upon this thread, which pointed me to `FlxSpriteGroup`. Even though I'm mixing sprites and text, it works perfectly. Thanks!
