### ISSUE TITLE
Improve spritesheet handling

### ISSUE THREAD

**Issue by Beeblerox** [HaxeFlixel/flixel#434]
avoid creation of new bitmapDatas. this will be usefull for native targets

**Comment by MintPaw** [comment]
How do you do this padding stuff now? CachedGraphics and TextureRegion are gone.

**Comment by Gama11** [comment]
Not gone, just replaced by something else. I think you're supposed to use `FlxTileFrames.fromBitmapAddSpacesAndBorders()` now, but @Beeblerox is the expert.

**Comment by Beeblerox** [comment]
now you have to use `FlxTileFrames` class:
```
// top left corner of the first tile
var startX:Int = 2;
var startY:Int = 2;
// tile size
var tileSize:FlxPoint = new FlxPoint(10, 10);
// tile spacing
var tileSpacing:FlxPoint = new FlxPoint(2, 2);
// region of image to use for tiles (optional)
var region:FlxRect = new FlxRect(startX, startY);
var tiles:FlxTileFrames = FlxTileFrames.fromRectangle("assets/colortiles.png", tileSize, region, tileSpacing);
add(level.loadMap(Assets.getText("assets/slopemap.txt"), tiles));
```

**Comment by Beeblerox** [comment]
`FlxTileFrames.fromBitmapAddSpacesAndBorders()` takes spritesheet without spaces between tile images, then adds provided spaces between them and adds borders around tile images (just copies their border pixels). this method could help avoid tile tearing problem on native targets

**Comment by vnavarro** [comment]
Hi, 

I can't get any of this samples working. The current docs don't mention FlxTileFrames and I don't now what kind of object level is so I can't figure what loadMap expects. Furthermore the previous example isn't too much helpful either, I'm kind of lost here :sob: 
Could anyone provide a more complete example?

Thanks :smile:

**Comment by sruloart** [comment]
@vnavarro If you're not using the dev (git clone) version of HaxeFlixel you can't use FlxTileFrames, and if you aren't (i.e you use HaxeFlixel 3.3.9) you need to specify what exactly are you trying to achieve (preferably in the Google group: http://haxeflixel.com/forum/). 

If you're trying to add "borders" to your spritesheet (i.e "padding") then search the issues / forum, the solution is out there :)

**Comment by BrandonRaggett** [comment]
@vnavarro Most of the solutions are outdated now.
