### ISSUE TITLE
Improve the perf window of the debugger

### ISSUE THREAD

**Issue by Gama11** [HaxeFlixel/flixel#508]
The [Hi-ReS! Stats](https://github.com/mrdoob/Hi-ReS-Stats) repo seems to offer stats that are a little more advanced than those of the flixel debugger - specifically the MAX stat ("maxmium memory the application reached") and graphs that illustrate all the stas nicely. I'm thinking it would be beneficial to add these two things to the perf window.

Screenshot of the Hi-ReS! Stats window:

![](https://github.com/mrdoob/Hi-ReS-Stats/raw/master/assets/hires_stats.png)

**Comment by tbrosman** [comment]
I know this thread is probably pretty stale at this point, but out of curiosity why did @Beeblerox's version use FlxTextFormat instead of TextField.htmlText? I've been playing around with both and have been having mixed results with the htmlText in Flixel: <br> tags seem to work, but font color doesn't. Does it just not work in (Haxe) Flixel yet?

**Comment by Gama11** [comment]
@tbrosman What do you mean, `FlxTextFormat`? There are no flixel text classes involved here, this is all flash display list API.

`htmlText` has issues on certain targets, I never got it to work properly on HTML5 IIRC (ironically). Where have you been trying to use it? With a flash `TextField`? A `FlxText`?

**Comment by tbrosman** [comment]
Ah, yeah you're correct, it's just TextFormat. My eyes just put Flx* in front of everything when I read Flixel code ;)

I get some odd results when I try using htmlText depending on whether I use FlxText or a TextField directly:

```haxe
        bgColor = 0xFF888888;
        
        var test = "<font color='#FF0000'>t<u>e</u><i>s</i>t</font>ing<br><br>asdf";
        
        var flxText = new FlxText();
        flxText.textField.htmlText = test;
        add(flxText);
        
        var flashText = new TextField();
        flashText.htmlText = test;
        flashText.y = 40;
        Lib.current.stage.addChild(flashText);
```

![html text test](https://cloud.githubusercontent.com/assets/3754050/7580365/d9341ea4-f828-11e4-9a45-131afec8380f.PNG)

Somehow linebreaks don't show up properly in the OpenFL Textfield (not sure what I'm missing) and colors don't show up in the FlxText. Is this some quirk of the render to bitmap logic?

**Comment by Tiago-Ling** [comment]
Hey guys, one question about the debugger windows: 

Even tough i'm down to just 4 `FlxAtlasFrames` the field `drawTiles` appears with numbers as high as 20-30. Is the overhead of the debugger window so much that you cannot safely rely on the drawTiles value? 

I know that each normal `FlxText` (using .ttf fonts) uses one draw call right? I think this could maybe be changed for `FlxBitmapText`. 

Another thing that could be made is for the `drawTiles` field to not count the debugger window own draw calls - this way the user can have a better idea of how much he/she needs to optmize.

What do you think - is this desirable and / or feasible?

**Comment by Gama11** [comment]
The debugger does not affect any rendering stats, as it doesn't use flixel but flash sprites for rendering.

**Comment by Tiago-Ling** [comment]
So this means that using an `FlxAtlasFrames` does not guarantee only one `drawTiles` call. I wonder what causes additional draw calls when using atlases - surely it is not one per FlxSprite, my game has a lot more than the number displayed on screen at anytime. Could it be one per different frame used? Sorry for the off-topic btw.

**Comment by Beeblerox** [comment]
@Tiago-Ling different sprite's blending or sprite's tinting/no-tinting causes additional drawcalls

**Comment by Tiago-Ling** [comment]
@Beeblerox So in theory, using 4 atlases with no blending or tinting should make only 4 draw calls?

**Comment by Beeblerox** [comment]
@Tiago-Ling if you draw frames for each atlas in series (say, frames from the first atlas, then from the third one, then from the second, and then from the fourth) then there will be four draw calls, but in more general case you "mix" frames from different atlases, so the number of draw calls will be equal to the number of texture switches

**Comment by sruloart** [comment]
You can always create a new tinted/blended FlxAtlas from the tinted/mixed frames of the FlxAtlases in use. UbiArt engine saves (a lot of) atlases for different textures (color presets) as well.
