### ISSUE TITLE
Suggestion: Improved support for ColorTransform interaction on FlxSprites

### ISSUE THREAD

**Issue by VictorGrunn** [HaxeFlixel/flixel#616]
One thing I'd like to be able to do in HaxeFlixel is make sprites smoothly flash - not just tint, but fully flash - one color or another, including white. I know about the color variable for tinting anything but white, but being able to directly manipulate offsets or RGB multipliers more easily than now would be great.

I've been messing around with the framePixels.colorTransform to try and accomplish this, but it's awkward - there doesn't seem to be a way to directly see what the current transform values are, and changing the values as it stands results in some funky results. (Increasing the offset values by 1 each update results in the whole sprite turning solid white way too fast - say at around 30ish, even for a solid red makeGraphic square. Switching offsets to 0 after this doesn't restore the original sprite appearance - in fact the only way to do so seems to be to set the sprite as dirty.)

**Comment by OpmSaitama** [comment]
Any update on this function for windows/neko ?

**Comment by Beeblerox** [comment]
It will be possible with custom Tilesheet shader. But this feature isn't available yet (as far as I know)
