### ISSUE TITLE
FlxTimer array manipulation bug

### ISSUE THREAD

**Issue by sinnus** [HaxeFlixel/flixel#679]
The issue is like #665 but now for timers. FlxTimer has complete callback https://github.com/HaxeFlixel/flixel/blob/dev/flixel/util/FlxTimer.hx#L167 where we can start new timer (add new timer into timers array), for example. Callback is invoked in TimerManager#update function https://github.com/HaxeFlixel/flixel/blob/dev/flixel/plugin/TimerManager.hx#L53. As you can see we can change array inside array iteration.

**Comment by Beeblerox** [comment]
i think that my old commit should fix this issue

**Comment by Gama11** [comment]
That pull request caused a unit test to hang if I remember correctly.

**Comment by Beeblerox** [comment]
i'll try one more time then
