### ISSUE TITLE
FlxCamera FollowStyle class / typedef

### ISSUE THREAD

**Issue by Gama11** [HaxeFlixel/flixel#739]
This idea seems worth investigating: 

https://github.com/FlixelCommunity/flixel/issues/190

Could be implemented as a class or as a typedef I guess. It would probably break compatibility.

**Comment by Gama11** [comment]
I don't see this happening any time soon, we want to keep breaking changes to a minimum after 4.0.0.

**Comment by MSGhero** [comment]
Does it need to be closed or just pushed back? It's not like there will never again be a breaking change after 4.0.

**Comment by larsiusprime** [comment]
After 4.0 we'll save more breaking changes for 5.0. We can of course discuss speeding up the rate of point releases once we've gotten to 4.0 :)

**Comment by MSGhero** [comment]
I meant, why close it if it's a potential 5.0 change?
