### ISSUE TITLE
FlxGame#new should implicitly calculate zoom or size

### ISSUE THREAD

**Issue by jorgenpt** [HaxeFlixel/flixel#759]
Currently, when you call FlxGame#new, it takes both a gameSizeX/gameSizeY and a zoom, but it would make more sense to calculate one from the other (based on the window size).

It seems like there are two ways you want FlxGame to behave:

1. You want to specify a fixed resolution at which you'll be rendering your viewport, and flixel should scale the zoom level when the window is resized
2. You want to specify a fixed zoom level at which you want your assets to be shown, and flixel should grow the viewport when the window is resized

Currently number 2 is supported by using FlxG.autoResize. In either case, passing a gameSizeX / gameSizeY that isn't your window dimensions divided by the zoom makes things behave a little strange.

**Comment by Gama11** [comment]
I think this is now covered by scale modes.
