### ISSUE TITLE
Centre aligned text with word-wrap enabled is buggy.

### ISSUE THREAD

**Issue by PaulGene** [HaxeFlixel/flixel#778]
Center aligned with word-wrap on:
![capture](https://f.cloud.github.com/assets/175800/1894514/b0295786-7aed-11e3-90f6-0b1196085121.PNG)

Center aligned with word-wrap off:
![capture2](https://f.cloud.github.com/assets/175800/1894515/bd042fc6-7aed-11e3-9e13-cc0a0bb6765f.PNG)

**Comment by Gama11** [comment]
The workaround for multiline centered text on flash changed (see #1728), so I assume this is not an issue anymore.
