### ISSUE TITLE
Merge flixel-ui's 9-slice functionality into the core

### ISSUE THREAD

**Issue by Gama11** [HaxeFlixel/flixel#808]
It seems like this feature is too useful to hide away in flixel-ui. It would be especially useful for buttons, because the size of the default button graphic is fixed, so you can't have a label that's longer than like 15 chars without it looking horrible.

Ideally, we could put the functionality for loading a bitmap as a 9-slice into `FlxSpriteUtil` / `FlxBitmapUtil` without touching the core `FlxSprite` at all. Not entirely sure though, I have to take a closer look at how this feature works.
`FlxTypedButton` will probably need updates though because of the way it implements the button states. 

cc @larsiusprime

**Comment by Mixerman123** [comment]
^

**Comment by Tembac** [comment]
If I need a flxSprite using a slice 9 graphic the only solution is to import Flixel UI and use FlxUI9SliceSprite?

**Comment by larsiusprime** [comment]
For now, yes.

**Comment by SARFEX** [comment]
+1 for idea. 9-slice sprite is must-have thing in nearly all projects. Unlike flixel-ui (which does not work in the latest haxe 3.2.1)

**Comment by MSGhero** [comment]
I don't like how many parameters the 9 slice constructor has, and I feel like the corner array would be better suited as a FlxRect or two points. I don't particularly care about the resizing, that could be ui-specific. I can port it to something more general for flixel.

**Comment by MSGhero** [comment]
Got the basic algo working: https://gist.github.com/MSGhero/5f64e8d09beb4e4766a9b87721fb0b94

It's unclear what should be added to this (plus it needs more testing!) based off the several 9-slice issues we have around HaxeFlixel.

**Comment by larsiusprime** [comment]
If you don't want to commit to resizing, the use case becomes a lot simpler. The real question is rendering -- if you could find a way to make this work with the tilesheet renderer, it'd be a lot more efficient use of memory.

The other thing is even if you don't want flixel-ui's parameter bloat, you almost certainly need to support user-definable tiling or stretching as the scale mechanism for the middle slices, as neither method alone covers the majority of use cases.

**Comment by MSGhero** [comment]
I've never directly used Tilesheet, so I'd have to look into that.

**Comment by Tembac** [comment]
Is there any progress on this?

I need to do a 9 slice scaling for the background of a scrolling level selector that we are designing on flash but slice 9 is also broken on the SWF library :(

https://github.com/openfl/swf/issues/94

**Comment by Beeblerox** [comment]
There is https://github.com/HaxeFlixel/flixel-addons/blob/dev/flixel/addons/display/FlxSliceSprite.hx for this

**Comment by bendmorris** [comment]
Unfortunately drawTriangles has generally had pretty poor support from OpenFL. Right now color and alpha don't work for example.

Alternatively, here's a gist of a version I created which simply creates and moves/scales 9 FlxSprites for each of the segments: https://gist.github.com/bendmorris/7a6e66f8e1a17659fd50338fbc445366 Would there be any interest in cleaning up and merging this?

**Comment by Beeblerox** [comment]
That's interesting. But currently i'm working on hardware renderer which supports both color and alpha and works on openfl 4. There are plenty things to fix, but these features are working now. Hope to make pull request in a week

**Comment by MSGhero** [comment]
@IBwWG has a complete solution, but not hardware. The logic can probably be used, however.

**Comment by IBwWG** [comment]
Sorry, I hope nobody had to duplicate work, I'd assumed people would check MSGhero's work and see that I forked it.  Fixed a few issues at https://gist.github.com/IBwWG/9ffe25a059983e7e4eeb7640d6645a37

**Comment by Tembac** [comment]
@Beeblerox, I found some problems with FlxSliceSprite. 

Flash target: http://puu.sh/r2lJE/8abc086f95.jpg
Windows target: http://puu.sh/r2lMp/e926ae6727.png (It includes the debug view of the segments)

Source image: https://dl.dropboxusercontent.com/u/24695185/fondoSelector.png

Code:
`		var slice9spr:FlxSliceSprite = new FlxSliceSprite("assets/images/fondoSelector.jpg", new FlxRect(80, 84, 100, 360), 1024, 768);
		add(slice9spr);`

**Comment by bendmorris** [comment]
I assume you're using drawTriangles for this new hardware renderer? Does antialiasing work? Using it on my own or with FlxSpine, the output seems jaggy even with antialiasing = true.

**Comment by Beeblerox** [comment]
@bendmorris i'm using custom solution based. Haven't experimented with antialiasing yet, but i'll look into it

**Comment by Gama11** [comment]
Moved @Tembac's issue to flixel-addons: #272
