### ISSUE TITLE
Do some benchmarking / comparison with flixel AS3

### ISSUE THREAD

**Issue by Gama11** [HaxeFlixel/flixel#852]
Hasn't been tested in a while I think, gotta make sure there aren't any performance regressions.

FlxBunnyMark: [Haxe](https://github.com/HaxeFlixel/flixel-demos/tree/dev/Performance/FlxBunnyMark) / [AS3](https://github.com/impaler/AS3-FLX-BunnyMark)
NeonVector: [Haxe](https://github.com/Masadow/NeonVector) / [AS3](https://github.com/SestrenExsis/ShapeBlasterTutorial)

**Comment by nazywam** [comment]
Would a website with 2 embedded swf files per each demo be ok?
![Bunny](https://cloud.githubusercontent.com/assets/2192416/9133215/22742058-3cfa-11e5-95cc-04d08f913491.png)
