### ISSUE TITLE
Feature suggestion: FlxCamera zoom with static camera width/height

### ISSUE THREAD

**Issue by VictorGrunn** [HaxeFlixel/flixel#861]
I thought FlxCamera had this previously, but either I was mistaken or I can't find how to do it. I think it'd be great if there was a way to zoom with a camera while maintaining the width/height of the camera itself. Rather like zooming in on a window in the desktop - the graphic can get bigger, but the window stays the same.

I tried replicating this with a 400w 300h camera using...

``` haxe
var tween:FlxTween = FlxTween.multiVar(gameCamera, { zoom: 2, width: 200, height: 150 }, 2, { type: FlxTween.PINGPONG } );
```

...But that's less intuitive than having a single variable to change/tween, plus the ratios don't stay synchronized anyway throughout the transition.
##

**Comment by GimmickyApps** [comment]
@VictorGrunn are you still using this code?  I'm trying to achieve exactly the same thing (but not even with tweening), but in my case, setting the width/height did not do the trick, and trying to set `camera.scroll` only fixed things in two special cases and definitely not the general case.  Any hints?

(This is using the HaxeFlixel dev branch, on Win7, flash/debug target.)

**Comment by GimmickyApps** [comment]
In dev branch's FlxCamera.hx, if I make updateInternalSpritePositions() just do 
```haxe
	_flashBitmap.x = _flashBitmap.y = 0;
```
then this *almost* works perfectly.  (With a flash target, anyway.  I'm sure html5 would need a similar modification.)  Where it doesn't work is as soon as zoom goes < 1, at which point the width and height values are made too small for some reason.  I guess #1718 comes into play at that point.

Nice to know it'd be easy to implement this feature, though (assuming 1718 is reasonably fixable)...can I just make a public Bool (default false) that would allow for this mode?

**Comment by VictorGrunn** [comment]
I'll poke around at it again, but it's been a while since I played with it.
Shouldn't be too hard to replicate either way, barring major revisions
since last time.

On Tue, Feb 9, 2016 at 11:40 AM, GimmickyApps <notifications@github.com>
wrote:

> In dev branch's FlxCamera.hx, if I make updateInternalSpritePositions()
> just do
>
>     _flashBitmap.x = _flashBitmap.y = 0;
>
> then this *almost* works perfectly. (With a flash target, anyway. I'm
> sure html5 would need a similar modification.) Where it doesn't work is as
> soon as zoom goes < 1, at which point the width and height values are made
> too small for some reason. I guess #1718
> <https://github.com/HaxeFlixel/flixel/issues/1718> comes into play at
> that point.
>
> Nice to know it'd be easy to implement this feature, though (assuming 1718
> is reasonably fixable)...can I just make a public Bool (default false) that
> would allow for this mode?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HaxeFlixel/flixel/issues/861#issuecomment-181949010>.
>



-- 
Victor Grunn (Joseph Antolick)
Reviews Editor, Gaming Trend
grunn@gamingtrend.com
@VictorGrunn

**Comment by GimmickyApps** [comment]
Thanks @VictorGrunn and BTW do you use StageSizeScaleMode?

**Comment by Geokureli** [comment]
closing out old issues, seems like this suggestion is how camera's work, now. If I'm misunderstanding, feel free to reopen this
