### ISSUE TITLE
Add default pause functionality via FlxSubState

### ISSUE THREAD

**Issue by gamedevsam** [HaxeFlixel/flixel#883]
We should restore ```FlxG.paused``` as a property and bring up an ```FlxSubState``` if it's set to true. Perhaps the class of the state could be another variable to allow users to customize the pause screen: ```FlxG.pausedSubState```

**Comment by Gama11** [comment]
I don't think this is really all that useful. Opening a new substate already acts as a pause, and you'd need custom logic for it anyway to implement a means of unpausing (which has to happen in the substate).
