### ISSUE TITLE
Add Post Process shader support on cpp targets

### ISSUE THREAD

**Issue by gamedevsam** [HaxeFlixel/flixel#897]
Preliminary work by [MrCdk](https://github.com/mrcdk) resulted in new (and currently broken) [post-process](https://github.com/HaxeFlixel/flixel/tree/post-process) branch. There is currently a positioning issue, and an issue with areas outside of any FlxCamera with a shader not currently rendering. You can see this issue on the [SplitScreen demo on post-process branch](https://github.com/HaxeFlixel/flixel-demos/tree/post-process/Flixel%20Features/SplitScreen).

We need professional help on this one @jgranick, @MattTuttle.

**Comment by AGulev** [comment]
Hi, 
Are you planning to resume work with this feature?

**Comment by Matej244** [comment]
Nice, cant wait for more shader features

**Comment by alminde** [comment]
+1
