### ISSUE TITLE
TextureAtlas not automatically sizing hitboxes properly

### ISSUE THREAD

**Issue by VictorGrunn** [HaxeFlixel/flixel#910]
Use an atlas with multiple sizes of sprite in it (say, h/w 10/10 and 100/100) and it typically defaults to the largest size, even for a 10/10 sprite, when drawing the hitbox. (ie, a 10/10 sprite will have a box of 100/100, but the sprite will be situated in the upper left.)

setOriginToCenter() ends up centering the origin where it should be too.

Can supply pastes of code if needed here.

**Comment by Gama11** [comment]
The referenced files (`mainbase.png`, `mainbase.json`) aren't part of the .zip.
