### ISSUE TITLE
Proper transform/rotation/scaling of children inside FlxSpriteGroup

### ISSUE THREAD

**Issue by AndreiRegiani** [HaxeFlixel/flixel#975]
The objective is to achieve something similar to MovieClip (Flash), where it's possible to add sprites inside a sprite (FlxSpriteGroup) and the matrix for rotation/scaling being properly computed.

*Proposed code (@mrcdk): *https://github.com/mrcdk/flixel/commit/ba6ae5a4fccd9ee4a722b59878eff17e16c4ad73
*It stills a draft / hack, but demonstrates the idea.*

Compiled with current version: https://dl.dropboxusercontent.com/u/21553459/BAD.swf
Compiled with proposed change: https://dl.dropboxusercontent.com/u/21553459/GOOD.swf
Demo source code: https://dl.dropboxusercontent.com/u/21553459/FlxSpriteGroup.zip

E.g.
Top-down tank game, the tank is composed with two sprites, the base sprite and the cannon sprite, without this feature, the cannon will not follow its position when the base is rotating.

**Comment by yanargyr** [comment]
Maybe this is related to a similar flixel-addons FlxNestedSprite issue? 
https://github.com/HaxeFlixel/flixel-addons/issues/156

**Comment by Gama11** [comment]
`FlxSpriteGroup` is already a huge hack, putting more hacks on top of it to make it behave somewhat  more like you'd expect sounds like a nightmare to maintain. `FlxNestedSprite` from flixel-addons is probably a saner approach.
